### ISSUE TITLE
libcppunit issue

### ISSUE THREAD

**Issue by DeNeDeM** [rakshasa/rtorrent#1001]
Ive recently updated from debian buster to debian bullseye and rtorrent doesnt work anymore.
It says it cant find shared libraries: libcppunit-1.14.so.0 and that is true because my version is 1.15 after the upgrade
 ldconfig -p | grep libcppunit
        libcppunit_subunit.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcppunit_subunit.so.0
        libcppunit_subunit.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcppunit_subunit.so
        libcppunit-1.15.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcppunit-1.15.so.1
        libcppunit-1.15.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcppunit-1.15.so

any workarounds?

**Comment by rakshasa** [comment]
Yes, recompile rtorrent or update the rtorrent package. This is a distro issue.

**Comment by DeNeDeM** [comment]
Perfect. Works great.
