### ISSUE TITLE
Does rTorrent have a /rtorrent/data/Temp directory?

### ISSUE THREAD

**Issue by 07416** [rakshasa/rtorrent#1002]
This folder has appeared recently. I'm asking if this is ever created by rTorrent or if it was some third-party program. Only really ruTorrent and pycore have access to the rTorrent data folder on my system and hasn't now been edited in a month despite adding torrents daily.

`/rtorrent/data/Temp`

**Comment by rakshasa** [comment]
Most likely ruTorrent.
