### ISSUE TITLE
Session issue, rtorrent crash "random_device"

### ISSUE THREAD

**Issue by PulsedMedia-Aleksi** [rakshasa/rtorrent#1003]
User had issues launching rtorrent, everyone else on the server fine.

rTorrent immediately dies with error message:
rtorrent: random_device::random_device(const std::string&)

No other pointers. Clearing session "fixed" the issue, so looks like session corruption issue.

It originates from corrupt .torrent file - user had them in his watch directory and those got reloaded -> rtorrent started crashing again. Is there no way to even trace which .torrent it was?

rTorrent version release 0.9.8
rtorrent.rc:

```
#DHT and PEX configuration - If you use private trackers the torrents have private flag, so you can safely leave these enabled in most cases
dht.mode.set = auto
schedule2 = dht_node, 3, 0, "dht.add_node=dht.libtorrent.org:25401"
schedule2 = dht_node, 3, 0, "dht.add_node=dht.transmissionbt.com"
schedule2 = dht_node, 3, 0, "dht.add_node=router.utorrent.com"
schedule2 = watch_directory,15,1,"load.start_verbose=~/watch/*.torrent"
#schedule2 = untied_directory,10,10,stop_untied=
schedule2 = rss,0,1800,"execute={sh,-c,php ~/www/rutorrent/plugins/rss/update.php& exit 0}"
#schedule2 = last_scrape_s, 0, 1800, "d.multicall2=main,d.tracker.send_scrape=0"
schedule2 = scgi_permission,0,0,"execute.nothrow=chmod,770,~/.rtorrent.socket"

protocol.pex.set = yes
try_import = .rtorrent.rc.custom

## Following user should not change in any case - basic config & performance options etc.
pieces.memory.max.set = 1000M
pieces.preload.type.set = 0
pieces.hash.on_completion.set = no
directory.default.set = ~/data
session.path.set = ~/session
system.file.max_size.set = 1000G
system.file.allocate = 1
network.scgi.open_local = ~/.rtorrent.socket
network.send_buffer.size.set = 16M
network.receive_buffer.size.set = 16M
network.max_open_sockets.set = 2000
network.http.max_open.set = 500
network.max_open_files.set = 2000
network.http.dns_cache_timeout.set = 3
network.xmlrpc.size_limit.set = 16M
network.port_range.set = 20000-60000
network.port_random.set = yes
trackers.use_udp.set = yes
trackers.numwant.set = 112

# Increasing these values does not normally increase speed but can negatively impact the server -- please be careful
throttle.min_peers.normal.set = 4
throttle.max_peers.normal.set = 112
throttle.min_peers.seed.set = 4
throttle.max_peers.seed.set = 112
throttle.max_uploads.global.set = 72


protocol.encryption.set = allow_incoming,try_outgoing,enable_retry
encoding.add = utf8
method.insert = system.startup_time, value|const, (system.time)
```

**Comment by PulsedMedia** [comment]
There's been now second case of this happening.

**Comment by kannibalox** [comment]
Is it possible the process is running out of file handles? If I'm reading things correctly, that exception can only show up when rtorrent fails to open `/dev/urandom`, and there are precious little scenarios where that can happen.

**Comment by PulsedMedia-Aleksi** [comment]
> Is it possible the process is running out of file handles? If I'm reading things correctly, that exception only shows up when rtorrent fails to open `/dev/urandom`, and there are precious little scenarios where that can happen. To check for it, you can try starting up rtorrent with `strace`, and if you see something like `openat(AT_FDCWD, "/dev/urandom", O_RDONLY) = -1 EMFILE (Too many open files)`, you have your culprit.

Somehow missed notification of your reply.
looks like this was the case, and somehow previous config for setting these limits were not being applied. Something changed along the line, and we managed to miss it.

If this fixes also #1019 we will grant you @kannibalox the 100€ bounty we set forward.

**Comment by pyroscope** [comment]
Many people do not know: systemd ignores system limits, and uses its own settings!

**Comment by PulsedMedia-Aleksi** [comment]
> Many people do not know: systemd ignores system limits, and uses its own settings!

systemd seems to have caused a bit of fuss for many indeed. Just noticed we had a typo on backend routines which updates systemd settings as well, sometimes replacing config with empty file :)

Lets hope this same thing fixes #1019 as well and we can grant Kannibalox the bounty. Albeit this raises the question why rTorrent does not handle such situation more gracefully, at the very least with comprehensible error message or even some sort of error handling.

**Comment by kannibalox** [comment]
>  Albeit this raises the question why rTorrent does not handle such situation more gracefully, at the very least with comprehensible error message or even some sort of error handling.

 It's hard, because this exception comes bubbled up from gnu's libcpp verbatim and without any context. Newer versions throw things with a little more detail, but ultimately rtorrent would have to fall back on sheer brittle string checking. It might be better to monitor for failed fopen's with EMFILE, but that could introduce overhead depending upon implementation. Ignoring it would probably be an actual problem given that dupe peer IDs has been a thing (see https://github.com/rakshasa/libtorrent/pull/185)

**Comment by PulsedMedia-Aleksi** [comment]
> > Albeit this raises the question why rTorrent does not handle such situation more gracefully, at the very least with comprehensible error message or even some sort of error handling.
> 
> It's hard, because this exception comes bubbled up from gnu's libcpp verbatim and without any context. Newer versions throw things with a little more detail, but ultimately rtorrent would have to fall back on sheer brittle string checking. It might be better to monitor for failed fopen's with EMFILE, but that could introduce overhead depending upon implementation. Ignoring it would probably be an actual problem given that dupe peer IDs has been a thing (see [rakshasa/libtorrent#185](https://github.com/rakshasa/libtorrent/pull/185))

More verbose errors alone would help tremendously, and would be a excellent start.

**Comment by pyroscope** [comment]
> More verbose errors alone would help tremendously, and would be a excellent start.
That won't happen unless someone writes the PRs. I guesstimate 80% or more of generated messages lack readily available context information.

**Comment by PulsedMedia-Aleksi** [comment]
Considering this solved as per @kannibalox suggestion. Payment is pending as soon as he contacts us.

**Comment by doodlebro** [comment]
Unfortunately, I think this issue still exists in rare cases. My install has been running fine for some time, but after a routine reboot I received the "random_device" exception and could not get the session to recover. Restoring from a backup was the temporary fix.
