### ISSUE TITLE
Sometimes FM_EXCLUDE_ITEMS is not defined

### ISSUE THREAD

**Issue by PulsedMedia-Aleksi** [rakshasa/rtorrent#1026]
PHP V5.6, FM_EXCLUDE_ITEMS will not be defined as it needs to be scalar value for PHP 5.6
Hence for function fm_is_exclude_items($file) throws a warning from line ~2380 for the if (!in_array line.

Prepend that function with this to avoid the issue:
`    if (!defined('FM_EXCLUDE_ITEMS') or !is_array(FM_EXCLUDE_ITEMS)) return true;`

You still get warning:
`PHP Warning:  Constants may only evaluate to scalar values in ****** on line 380`

however, so needs another check for PHP Version. But atleast adding that defined check removes warning for:
`PHP Notice:  Use of undefined constant FM_EXCLUDE_ITEMS - assumed 'FM_EXCLUDE_ITEMS'`

**Comment by pyroscope** [comment]
Wrong project.

**Comment by PulsedMedia-Aleksi** [comment]
Oops mistakes were made!
