### ISSUE TITLE
stack dump not enabled

### ISSUE THREAD

**Issue by bpetrov** [rakshasa/rtorrent#104]
after starting rtorrent in a screen, it quits almost immediately with this output:
"Caught Segmentation fault, dumping stack:B
Stack dump not enabled.
Abort trap: 6 (core dumped)"

It happens to me frequently,I keep hope to be reduced with every new version,but it happens again and again ... @#$%
The system is freebsd 9.0 rTorrent 0.9.2/0.13.2 with zfs system, 2GB physical memory and memory limit for rtorrent at .rtorrent.rc file "max_memory_usage = 1280M" . 
If you need more information,contact me, I will be glad to participate in debugging this so much useful application...
Thanks!

**Comment by trane77** [comment]
Install `screen` package
Then run `screen rtorrent`
