### ISSUE TITLE
rtorrent segfault on start

### ISSUE THREAD

**Issue by chrcoluk** [rakshasa/rtorrent#1042]
0.9.6 ran solid for years, updated os and rtorrent.  now this happens on startup with 0.9.8, I found another issue reported where it was found newer curl was the cause, however this already has 7.64 curl in place, so the fix must be different in this case.

Caught Segmentation fault, dumping stack:B] [Port: 20930] [Local x.x.x.x] [Bind x.x.x.x] [U 0/0] [D 0/0] [H 0/48] [S 0/1/
./rtorrent(+0x3a896) [0x557bb813d896]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730) [0x7f5031f59730]
/usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x34923) [0x7f5032b2a923]
/usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x356ea) [0x7f5032b2b6ea]
/usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x38eaa) [0x7f5032b2eeaa]
/usr/lib/x86_64-linux-gnu/libcurl.so.4(curl_multi_socket_action+0x25) [0x7f5032b2eff5]
./rtorrent(+0x138849) [0x557bb823b849]
/usr/local/libtorrent/lib/libtorrent.so.21(_ZN7torrent9PollEPoll7performEv+0xca) [0x7f5032a161fa]
/usr/local/libtorrent/lib/libtorrent.so.21(_ZN7torrent9PollEPoll7do_pollEli+0x70) [0x7f5032a16430]
/usr/local/libtorrent/lib/libtorrent.so.21(_ZN7torrent11thread_base10event_loopEPS0_+0x110) [0x7f5032a4f3e0]
./rtorrent(+0x39925) [0x557bb813c925]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f5031a8709b]
./rtorrent(+0x3a1ba) [0x557bb813d1ba]
Aborted

**Comment by chrcoluk** [comment]
Closing this, I manually compiled a lower version of curl and linked rtorrent to it, and problem solves, however given the multiple reports, I suggest the issue is looked into as to why rtorrent is so sensitive to specific curl versions.  Or maybe the issue is not the version but if its precompiled on a distro vs manually from source package.

**Comment by pyroscope** [comment]
You did not provide the failed / working curl versions, so how would anybody work on this?

**Comment by chrcoluk** [comment]
7.64 from pkg repo broken
7.63 compiled from source tarball, on default flags working

however on another issue on here 0.76.4 was broken.

OS devuan beowulf . (akin to debian 10)

**Comment by jrabensc** [comment]
Same problem here running 0.9.7 on latest debian buster.

```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
```


```rtorrent(+0x1cee2) [0x55911dcbbee2]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730) [0x7ff65cd87730]
/usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x34923) [0x7ff65de54923]
/usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x356ea) [0x7ff65de556ea]
/usr/lib/x86_64-linux-gnu/libcurl.so.4(+0x38eaa) [0x7ff65de58eaa]
/usr/lib/x86_64-linux-gnu/libcurl.so.4(curl_multi_socket_action+0x25) [0x7ff65de58ff5]
rtorrent(+0xe13f9) [0x55911dd803f9]
rtorrent(+0xe1942) [0x55911dd80942]
rtorrent(+0x1e333) [0x55911dcbd333]
/usr/lib/x86_64-linux-gnu/libtorrent.so.20(_ZN7torrent11thread_base10event_loopEPS0_+0x18f) [0x7ff65db82b7f]
rtorrent(+0x1bbe8) [0x55911dcbabe8]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7ff65cbd809b]
rtorrent(+0x1c6ca) [0x55911dcbb6ca]
Aborted
```
