### ISSUE TITLE
Need information on saving sessions

### ISSUE THREAD

**Issue by j03bj03** [rakshasa/rtorrent#1045]
Hello,

I understand this may not be the correct place to post this, but I did not find any forum where to ask questions about rtorrent. Please redirect me in the right direction if I missed such a forum. I also searched all the help files and I did not find anything.

I need to understand properly what the following ".rtorrent.rc" line means and how to modify it myself to my needs. I copy-pasted it directly from the examples in the documentation to increase the auto-save time of sessions, but I am not sure what all the options mean and how to tune it to my needs:

> schedule2 = session_save, 1200, 43200, ((session.save))

I can vaguely understand that 1200 must be related to the 12 hours auto-save interval, because it was written in the documentation, but apart from that, I have no idea what all the other things mean.

Also, let's say I need to reboot rtorrent or the server, is there a command to manually trigger a session save. Right now, the interval is 12 hours, but if I need to suddenly reboot, I have no idea how long ago was the last save and how to trigger a save.

Thanks!

**Comment by kannibalox** [comment]
As per [schedule2](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-schedule2), the 2nd parameter is the delay before the schedule starts running in seconds, and the other parameters are explained as well. If rtorrent is shutdown nicely (i.e. it exits on its own), that includes a full session save by default. However, if you still need to manually trigger one, [session.save](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-session-save), the same method that scheduled line is calling, is what you want.

**Comment by j03bj03** [comment]
Awesome, thank you, much appreciated :-D
