### ISSUE TITLE
Using rtorrent.throttle.global_up.max_rate.set_kb to set upload rate returns error

### ISSUE THREAD

**Issue by evilbulgarian** [rakshasa/rtorrent#1056]
Trying to set upload rate via: rtorrent.throttle.global_up.max_rate.set_kb but getting 'Unsupported target type found' when i pass it a 1500k or 1500 strings what am I doing wrong thanks.

**Comment by pyroscope** [comment]
Read https://rtorrent-docs.readthedocs.io/en/latest/scripting.html#using-xmlrpc-for-remote-control

Also, use Reddit for support, not issues.

**Comment by darena67** [comment]
hahah ok figured it out
looked at the code on github "CMD2_REDIRECT_GENERIC("upload_rate",   "throttle.global_up.max_rate.set_kb");"
so using upload_rate works instead of that throttle.global..

**Comment by pyroscope** [comment]
That is an alias, and they WILL disappear (and already have for some groups). Also close this to reduce the clutter.

**Comment by evilbulgarian** [comment]
looked at the code on github "CMD2_REDIRECT_GENERIC("upload_rate", "throttle.global_up.max_rate.set_kb");"
so using upload_rate works instead of that throttle.global..
