### ISSUE TITLE
Enable the new Discussions feature

### ISSUE THREAD

**Issue by pyroscope** [rakshasa/rtorrent#1058]
… so Issues gets more focussed on code again, and support stuff can be moved over.

Only project owners can do that, so ping @rakshasa

**Comment by NoSubstitute** [comment]
This sounds like a great idea, @rakshasa 
Where's the upvote button? :-)

**Comment by PulsedMedia-Aleksi** [comment]
Agree. But i bet @rakshasa won't be around to do that for a while. Is it now a year since he has last been active?

**Comment by rakshasa** [comment]
Enabled.

You haven't seen any activity here as I've been working on https://github.com/rakshasa/rtorrent-docker instead, though it has been slow.
