### ISSUE TITLE
How to use the d.multicall.filtered command

### ISSUE THREAD

**Issue by averri** [rakshasa/rtorrent#1059]
I have tried to run the `d.multicall.filtered` command by following the documentation presented here:  https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html

... but the command did not work.

Could you please provide an example about how to use the `d.multicall.filtered` command?

**Comment by pyroscope** [comment]
"did not work" does not work as a basis for diagnostics. Also "*See elapsed.greater for an example.*"

**Comment by averri** [comment]
Apologies for not adding more information, I agree with that.

I'm invoking the backend via xmlrpc, with a JS client api, ref: https://github.com/baalexander/node-xmlrpc.
All invocations work fine, except the `d.multicall.filtered`.

This is one example of the arguments for the call to `d.multicall.filtered`:
```json
["", "started", "string.equals=(d.is_private),1", "d.name=", "d.hash="]
```
The above command returns an empty array.

This is another example for a `d.multicall2` arguments that works fine, returning all started downloads:
```json
["", "started", "d.name=", "d.hash=" ]
```

**Comment by pyroscope** [comment]
`equal=d.is_private=,value=1`

**Comment by averri** [comment]
Hello @pyroscope, thank you so much, the command  `["", "started", "equal=d.is_private=,value=1", "d.name=", "d.hash=" ]` worked perfectly.  

Could you please let us know where this syntax `equal=d.is_private=,value=1` is documented?

**Comment by pyroscope** [comment]
Read all of rtorrent-docs, that besides the source is the best you get. And study the examples (config templates) in my projects.
