### ISSUE TITLE
XmlRpc | get Key 

### ISSUE THREAD

**Issue by whoo** [rakshasa/rtorrent#1062]
Hi Guys,
I can't retrieve the key via xmlrpc.

(key value pushed to the tracker )
```C
"&key=" << std::hex << std::setw(8) << std::setfill('0') << m_parent->key() 
```
Key is also present in the torrent.rtorrent file.

I'm fine with it:
- d.local_id_html=
- d.name=
(...) 

Thanks.

**Comment by pyroscope** [comment]
Assuming you mean the infohash, you need the infohash to retrieve that. So just calculate it.

Also, close this to clean up.
