### ISSUE TITLE
Concern about ambigous rtorrent fork

### ISSUE THREAD

**Issue by zawapete** [rakshasa/rtorrent#1082]
At https://github.com/jesec/rtorrent you can find a kind of fork, with no clear statement about its nature and relation with the original project, aiming on the paper to improve RPC interfaces and other optimistation.

I'm rather concerned since the maintainer proofed on other project to be uncaring about community and to be rather following its own development agenda.

He's also the maintainer of Flood, that started as a rtorrent web front-end (an alternative to rutorrent), and now is going to shift to support the JSON-RPC he added to his fork, loosing compatibility with original rtorrent.

What's the stance on the situation by rtorrent's original developer?

**Comment by pyroscope** [comment]
This should be in Discussions.

**Comment by aspacca** [comment]
you're right @pyroscope , sorry, missed that :)

**Comment by jesec** [comment]
My reply:

https://github.com/rakshasa/rtorrent/discussions/1083#discussioncomment-734933
