### ISSUE TITLE
Get tracker details when executing a script

### ISSUE THREAD

**Issue by darnir** [rakshasa/rtorrent#1096]
I'm trying to configure my rtorrent such that it executes a script on `event.download.finished`. However, I can't get it to pass along the list of trackers to my script. My real intention is to execute the script only if the torrent was associated with a given whitelist of trackers.

My current approach is:

```
method.set_key = event.download.finished,test_notify,"execute.capture_nothrow=/usr/local/bin/test.sh,$d.base_path=,$d.name=,$d.tracker_alias"
```

However, this causes the event to not be fired at all. It works if I remove the `$d.tracker_alias` parameter. But then how do I run this script only on certain torrents? For example, the intended `test.sh` looks like:

```
case $3 in
tracker.example.com|tracker.example2.com)
    run_tasks
    ;;
*)
    exit
    ;;
esac
```

**Comment by rakshasa** [comment]
Why is the tracker_alias missing the `=`?

Also, tracker_alias is not part of the mainline rtorrent client
