### ISSUE TITLE
Is the download site down? 

### ISSUE THREAD

**Issue by jerryhou85** [rakshasa/rtorrent#1099]
Title, in particular: https://rtorrent.net/downloads is not accessible. 

The download site changed or server is down for now?

Thanks.

**Comment by rakshasa** [comment]
I rebooted the server in order to change the instance type, so it should have been temporary.

It's up for me now.

**Comment by jerryhou85** [comment]
![image](https://user-images.githubusercontent.com/6203876/126971059-0a63c7c4-e7a0-4605-afd3-5ebac70f483d.png)

I think somehow it is offline again...

**Comment by rakshasa** [comment]
Works for me, might be an issue with an expired certificate.

Can you access if from a browser?

**Comment by Micdu70** [comment]
Hello,

I also have issues to access "rtorrent.net":

Via Wi-Fi (French provider: Free) => No problem to access it.
Via mobile network LTE/4G (French provider: Orange) => Connection timeout...

**Comment by jerryhou85** [comment]
> Works for me, might be an issue with an expired certificate.
> 
> Can you access if from a browser?

I tried with my VPS, Norway, US, and HK. none is working... I tried with Chrome, Edge, Firefox, and Safari on iOS, none is working...

**Comment by Micdu70** [comment]
> Post the IPs just to make sure the DNS record is correct, I'll update the certificates tomorrow.

It seems your webserver is not listening on its IPv4 address, only on its IPv6.

rtorrent.net - IPv4: 18.237.96.92 | IPv6: [2600:1f14:439:6601:1065:6643:3e58:5a09]

**Comment by amlopin** [comment]
It´s still down :(


Fremont-CA - US
Unable to connect to https://rtorrent.net/downloads.
Toronto - CA
Unable to connect to https://rtorrent.net/downloads.
Amsterdam - NL
Unable to connect to https://rtorrent.net/downloads.
Melbourne - AUS
Unable to connect to https://rtorrent.net/downloads.
Singapore - SG
Unable to connect to https://rtorrent.net/downloads.

**Comment by amlopin** [comment]
Do u have any eta when download site will be back?
Thanks

**Comment by rakshasa** [comment]
Updated DNS, should be fixed when it propagates.

**Comment by amlopin** [comment]
Thanks it works now

**Comment by rakshasa** [comment]
Due to this issue I looked closer at the current expenses and atm it costs me $30-50 a month to run this server.

I wouldn’t mind, except pretty much no one donates to this project, having only a single donation one in the past couple months and a few bucks through patreon.

If there’s not enough to cover even the server cost I’ll be shutting it down and/or remove the downloads directory.
