### ISSUE TITLE
rtorrent installation error (no access to xmlrpc-c)

### ISSUE THREAD

**Issue by csgithubgamer** [rakshasa/rtorrent#1103]
Linux Debian 7
sudo apt-get install rtorrent

I can't install rtorrent client, because is no access to this file:
Failed to get http://ftp.fr.debian.org/debian/pool/main/x/xmlrpc-c/libxmlrpc-core-c3_1.16.33-3.2_amd64.deb  404  Not Found [IP: 212.27.32.66 80

and URL http://libtorrent.rakshasa.no

403 Forbidden
You don't have permission to access / on this server.

**Comment by rakshasa** [comment]
Distribution issues, make an issue with debian.

**Comment by csgithubgamer** [comment]
> Distribution issues, make an issue with debian.

How to solve this problem? 
Do you have a script for manual installation rtorrent?
