### ISSUE TITLE
random_device failed to open /dev/urandom: Too many open files

### ISSUE THREAD

**Issue by ma3252788** [rakshasa/rtorrent#1111]
This prompt suddenly appeared after the computer rebooted, and I couldn't open the rtorrent.
![](https://ypyssl.machunjie.com/machunjie/20210831092143.png)

**Comment by rakshasa** [comment]
If a reboot caused it, try to fix it with a reboot.

Looks most likely to be an issue with your system.

**Comment by ma3252788** [comment]
> If a reboot caused it, try to fix it with a reboot.
> 
> Looks most likely to be an issue with your system.

Thank you for your reply. Finally, I found out the reason, which is the problem of permission. I got better after I added sudo.

https://www.machunjie.com/trouble/code_error/1042.html
