### ISSUE TITLE
Copy files on completion

### ISSUE THREAD

**Issue by phibster** [rakshasa/rtorrent#1113]
Hopefully someone has come across this before.  I am running 0.9.8 and have a download directory and an extract directory.  What I would like to happen is when a torrent completes its data gets copied to the extract directory where I can then pull the data into my server, thus deleting the extract copy but leaving the original download to keep seeding.

I had this working once before but my server crashed and I lost all my config files and google is only finding ways to move the data not copy it.

As an added bonus I have a watch directory where torrent files are placed, and I originally had it moving the .torrent file into a subdirectory called imported so that I knew it had loaded without even opening an interface.

Any help appreciated :)

**Comment by pyroscope** [comment]
Is replacing `mv -u` by `cp -rpl` that unobvious?

**Comment by phibster** [comment]
Apparently it was, I had modified one of the move commands but must have messed up somewhere else.  Retried again and got it all working.  For reference I have put the relevant config below in case anyone comes across this and needs.  Thanks for the prompt on looking in the right direction pryo.

#moves .torrent to imported folder after loaded into rtorrent
method.set_key = event.download.inserted_new, move_torrent, "execute={mv,--,\"$cat=$d.tied_to_file=\",/watch/imported/}"

#copy files from /downloads/ folder to /ssd/ extract folder when complete leaving original in place
method.insert = d.get_finished_dir, simple, "cat=/downloads/,$d.custom1="
method.insert = d.get_data_full_path, simple, "branch=((d.is_multi_file)),((cat,(d.directory))),((cat,(d.directory),/,(d.nam
method.insert = d.move_to_complete, simple, "execute=cp,-rp,$argument.0=,$argument.1=;"
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.get_data_full_path=,/ssd/"
