### ISSUE TITLE
stop recheck and just check hash

### ISSUE THREAD

**Issue by Cardboard2** [rakshasa/rtorrent#1118]
Sorry, I didn't know how to phrase that. I disconnected my harddrive, and now all my files are 0%. I just need to make rtorrent check hashes (which should all be complete), which it seems to not be doing when I restart it.

Is there a simple way to do this. I have no idea what im doing btw.

**Comment by Cardboard2** [comment]
I've tried `check_hash = yes`.

`pieces.hash.on_completion`.set wont work as they 'aren't complete'

**Comment by Cardboard2** [comment]
Unless `pieces.hash.on_completion.set` works so that if i start and then stop all my torrents it will check the hash and see they are all complete???

**Comment by Cardboard2** [comment]
Hi I just decided to check. This is gonna take a while :(

**Comment by Nirzak** [comment]
Hi have you solved that problem? I am also going through the same problem here
