### ISSUE TITLE
event.download.finished Bad return code

### ISSUE THREAD

**Issue by JohnTM2411** [rakshasa/rtorrent#1124]
.rtorrent.rc line
`method.set_key = event.download.finished, unrar, "execute2={/media/sdt1/name/bin/aiov2.sh,$d.name=}"`
Error Code
`Event 'event.download.finished' failed: Bad return code.`
I just want it to start my bash script with the Torrent Name as an argument when the download is finished.
I already went through so many possible solutions, but nothing helped. I am desperate now. Still got my 50+ tabs open with StackOverflow, github, rtorrent-docs, reddit, ... I don't know what to search for
Could somebody also please tell me how to let it create a log file?

**Comment by kannibalox** [comment]
That means that the command being executed exited with a non-zero code, the event itself is firing just fine. You can try calling it manually to see if anything goes obviously wrong, or you can create a log file with the [log.execute](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-log-execute) command to see what's happening better.

I'd also recommend using the [execute.*.bg](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-execute-throw-bg) variants once you have things sort, to avoid locking up the main thread
