### ISSUE TITLE
Feature Request: Export list of torrent and Import list of torrents

### ISSUE THREAD

**Issue by fckwan** [rakshasa/rtorrent#1127]
i would like to propose a feature request where user can export the list of torrents to a file and re-import the list of torrents to another instance of rtorrent.
I have a list of torrents where each file is stored in a different directories. i want to be able to export the lists of torrent to a file and then import to a different computer running another copy of rtorrent.
Otherwise I need to re-enter thousands of torrents again.

**Comment by kannibalox** [comment]
You can simply copy the entire session directory, changing the .torrent files manually if desired with a bencode editor.

**Comment by fckwan** [comment]
Thanks for your clarification.

**Comment by rakshasa** [comment]
Use the XMLRPC api, or create your own custom function that you call on a download list, or use bencode editor as said above.
