### ISSUE TITLE
Method.insert Invalid key

### ISSUE THREAD

**Issue by DorianHawkmoon** [rakshasa/rtorrent#1136]
Installed rtorrent in ArchLinux, version 0.9.8 and using latest template I found in this repo.

Currently I left only this line (also with basedir2 just in case)
`method.insert = cfg.basedir,  private|const|string, (cat,"/home/torrent/rtorrent/")`

and this is the response
`/usr/bin/rtorrent -o import=/home/torrent/.rtorrent.rc
rtorrent: Error in option file: ~/.rtorrent.rc:1: Invalid key.`

What am I missing?

**Comment by stickz** [comment]
rTorrent is reading `.rtorrent.rc` twice because you added the import command. It already does this automatically. Launch with this instead: `/usr/bin/rtorrent` or alternatively you may want to use a screen: `/usr/bin/screen -d -m -S rtorrent /usr/bin/rtorrent`.

**Comment by DorianHawkmoon** [comment]
That seems to solve it, thanks!
