### ISSUE TITLE
Unable to communicate with rTorrent (https://xxx.xxx.com/rutorrent/plugins/httprpc/action.php). Response from server does not contain valid XML.

### ISSUE THREAD

**Issue by bleugray** [rakshasa/rtorrent#1146]
I am receiving this message in Sonarr, Radarr and Lidarr appears to have started on Jan 17, 2022

When you navigate to https://xxx.xxx.com/rutorrent/plugins/httprpc/action.php you are presented with a blank page that says "false"

What other info would be helpful?  rtorrent/rutorrent are hosted on a seedbox while Sonarr, Radarr and Lidarr are hosted locally.

**Comment by rakshasa** [comment]
Ask rutorrent.
