### ISSUE TITLE
onereqsnubfailed

### ISSUE THREAD

**Issue by morbificagent** [rakshasa/rtorrent#1147]
Hi together,

At the moment some of my torrents won't start and rtorrent only displays "onereqsnubfailed"

Any idea what this means?

![Screenshot_20220122-074039_Termius.jpg](https://user-images.githubusercontent.com/50199132/150629293-6b602b5f-e037-4c70-b107-a35700db9a35.jpg)

**Comment by morbificagent** [comment]
On others I get a different message I don't understand:

![Screenshot_20220122-092706_Termius.jpg](https://user-images.githubusercontent.com/50199132/150630996-3d50367d-5ab0-41bf-b27c-9a8c8b1f7ff8.jpg)

**Comment by kannibalox** [comment]
Those are the regular column headers getting wrapped around to the next line because your terminal is too small. For that particular torrent, it's not active, so there are no peers.
