### ISSUE TITLE
Ratio groups incorrect documentation, confusing options

### ISSUE THREAD

**Issue by orangecleric** [rakshasa/rtorrent#1158]
Using: Rakshasa's BitTorrent client version 0.9.8.

Ratio groups seems to be very confusing. I can't figure it out and the docs don't seem to be correct.

For example, the docs show "view_add" as a command. When I try that, I get: Command "view_add" does not exist.

I have also seen different ways to set the group options but I can't get them to work. Like "group.group_1.ratio.enable" as in the docs gives me an error that the command doesn't exist.

At this point, I don't know what to do. None of the information seems to work or make sense.

I want two groups. A default that is unlimited and one that has a ratio.

**Comment by kannibalox** [comment]
`view_add` is deprecated, `view.add` should be used instead, and the rest of the commands require the group to exist first. I've updated https://github.com/rakshasa/rtorrent/wiki/RTorrentRatioHandling to match, but didn't test it extensively.

Also, the default should be unlimited already, no need to create a dedicated group for that.

**Comment by orangecleric** [comment]
okay. thanks
