### ISSUE TITLE
Labels with slashes and spaces are URL-encoded

### ISSUE THREAD

**Issue by Jolly-Pirate** [rakshasa/rtorrent#1174]
Here's a little test to demonstrate the problem in rtorrent 0.9.8:
Added this to the rtorrent.rc, to send the label (`$d.custom1=`) to a shell script to log it in a text file, after rehashing a torrent
`method.set_key = event.download.hash_done,whatever,"execute2={/myscript.sh,$d.custom1=}"`

If the label contains a path, i.e. label with sublabels, or if it contains white spaces, those characters are URL encoded!

For example,
- Label in rutorrent: `Label1/Sublabel2 with spaces/Label3`

![ruTorrent v3-10 7-31-2022 7-22-46 PM](https://user-images.githubusercontent.com/4613678/182049529-1d4b1626-abf8-41a1-8cd1-cc97c7b07ca1.png)

- Problematic output in the bash shell script and within the `$d.custom1=` variable: `Label1%2Sublabel2%20with%20spaces%2Sublabel3`

This is a big problem because I'm configuring the .rc file to move folders based on the label and sublabels, but the resulting folders contain the URL-encoded strings and do not respect the proper path creation with subfolders.

**Comment by kannibalox** [comment]
This is not an issue with rTorrent, it's simply how ruTorrent stores the fields. Here's some more info from a previous issue: https://github.com/rakshasa/rtorrent/issues/1050#issuecomment-1140436216

**Comment by Jolly-Pirate** [comment]
Thanks for input @kannibalox it helped me figure a way to fix it. Here it is https://github.com/Jolly-Pirate/rtorrent-snippets/tree/master/fix-urlencoded-label
