### ISSUE TITLE
`d.directory.set` and `d.directory_base.set` stops an active/seeding torrent.

### ISSUE THREAD

**Issue by sktt** [rakshasa/rtorrent#1203]
I've made a script to move a download to a new directory, and it's using xmlrpc to update the directory for rtorrent. Essentially this:

```python
server.d.directory.set(INFO_HASH, DEST)
os.rename(FROM, full_path)
```

While it seems to work, the torrent is no longer active after `d.directory.set`. Trying to start it again using d.start does not do anything. To restart it, I first do a hash recheck. While this works, I would rather not do it, because I want to move several files and it runs on a slow raspberry pi. 

Any idea how to force start a torrent after `d.directory.set`? Is this a bug?

**Comment by kannibalox** [comment]
Make sure you stop and close it first:
```
server.d.stop(INFO_HASH)
server.d.close(INFO_HASH)
```
Then you can change the directory and move the data, and then start it with a regular `d.start`

**Comment by sktt** [comment]
Thank you @kannibalox , this fixes the issue! By the way,  this is `Rakshasa's BitTorrent client version 0.9.8.` on ARM v7, and the xmlrpc client is [rtorrent_xmlrpc](https://github.com/dbowring/rtorrent_xmlrpc). The only slight difference is that I issued these two *after* moving instead.

```python
        server.d.stop(INFO_HASH)
        server.d.start(INFO_HASH)
```
