### ISSUE TITLE
Change the path of certain files from a torrent ?

### ISSUE THREAD

**Issue by Kalytis** [rakshasa/rtorrent#1228]
Hi, I'm using Rtorrent/Rutorrent, and I'm looking for a way to change the location of some files within a same torrent ? ie. one episode of a show season I've already downloaded.

Thanks !

**Comment by Gosokan** [comment]
Use symbolic link.

**Comment by Kalytis** [comment]
Good idea ! Thanks a lot, it worked perfectly.
