### ISSUE TITLE
Curl 8.9.0 causes 100% cpu use

### ISSUE THREAD

**Issue by CountMurphy** [rakshasa/rtorrent#1289]
Running rtorrent on Arch. After updating curl to 8.9.0, rtorrent uses 100% cpu. Downgrading back to 8.8.0 fixes the issue.

**Comment by CountMurphy** [comment]
Might be related to https://github.com/curl/curl/issues/14280 as the symptoms sound similar.

**Comment by mackal** [comment]
I noticed this too, running `lsof -i` I noticed the tracker connection is stuck in CLOSE_WAIT. This isn't happening with all trackers, but it's happening with ubuntu ones. https://releases.ubuntu.com/22.04/ubuntu-22.04.4-desktop-amd64.iso.torrent this torrent specifically I can re-create the issue with. Looking at Tracker list, the "https://torrent.ubuntu.com/announce" one is bolded.

**Comment by mackal** [comment]
The patch to resolve https://github.com/curl/curl/issues/14280 appears to resolve my issue. (It doesn't apply completely cleanly to 8.9.0, but fuzzing seems to get it to)

**Comment by Ketchup901** [comment]
Fixed in 8.9.1.

**Comment by mackal** [comment]
> Fixed in 8.9.1.

Can confirm as well.

**Comment by CountMurphy** [comment]
8.9.1 hasn't made it to the arch repos yet, but I'll close the ticket as fixed.
