### ISSUE TITLE
Who is the 3rd party sponsoring the project and why is their company info not in the readme?

### ISSUE THREAD

**Issue by Pentaphon** [rakshasa/rtorrent#1301]
I think many people would like to know, and I've never seen a sponsored project not mention the sponsor somewhere on the project page for its benefit and transparency.

**Comment by GH0STDATA** [comment]
There seems to be some information that was left out of rakshasa's release notes. He essentially merged changes from this repo that were added as pull requests here 3 weeks ago: https://github.com/stickz/rtorrent

The credit should mainly go to stickz for this update. They also released an update yesterday with some additional crash fixes. If I'm not mistaken (please correct me if I'm wrong here), stickz received donations from a seedbox provider or providers to continue updating rtorrent since it was unstable and experienced frequent crashes. In the past few months, stickz has done an excellent job at fixing those problems, and rtorrent is way more stable and reliable than it was before these updates.

Rakshasa, at least currently, had absolutely nothing to do with this new update that was pushed out today.

**Comment by anthonyryan1** [comment]
I suspect our team at @whatbox is the sponsor mentioned in this release.

We reached out earlier this year and offered to sponsor rtorrent maintenance and development for a minimum of 12 months (and hopefully indefinitely) to get community development rolling again.

Software doesn't exist in isolation. Even the best will bitrot after enough time.

@rakshasa is still in control of all decisions regarding the project. We do not want to use our sponsorship to steer development in any direction other than "active" and "better for all users on all platforms."

It doesn't have to be anonymous, but we only care about rtorrent's development and users. Not every action needs to be a marketing opportunity.

**Comment by Pentaphon** [comment]
@anthonyryan1 even if you didn't see this as a marketing opportunity, which nobody would hold against your team, it is always important to be as transparent as possible when it comes to funding. Many people across many discussion forums are wondering who is funding the project and why the developer didn't just say who the sponsor was. Plus it is simple common courtesy to tell users that the project is currently being sponsored alongside the regular donation section in the readme. 

Hopefully @rakshasa himself can respond to this thread and disclose the sponsor in the readme.

**Comment by GH0STDATA** [comment]
> Software doesn't exist in isolation. Even the best will bitrot after enough time.
> 
> @rakshasa is still in control of all decisions regarding the project. We do not want to use our sponsorship to steer development in any direction other than "active" and "better for all users on all platforms."
> 

I agree, 100%. Without rakshasa, this client probably wouldn't have existed in the first place. His contribution to this software is huge, but sometimes life gets in the way and you have to put stuff like this to the side to focus on more important things. 

That's good to know that it was Whatbox who sponsored these updates. Thank you for helping to get the ball rolling on this, these fixes and updates were long overdue!

**Comment by Pentaphon** [comment]
> That's good to know that it was Whatbox who sponsored these updates.

We don't know since the rakshasa didn't confirm it nor did anthonyryan1 give a direct confirmation. We can't assume anything until rakshasa himself discloses the sponsor. 

But yes, these updates were long overdue and hopefully all of the fixes from stickz and novick get merged into rakshasa's repos.

**Comment by GH0STDATA** [comment]
> > That's good to know that it was Whatbox who sponsored these updates.
> 
> We don't know since the rakshasa didn't confirm it nor did anthonyryan1 give a direct confirmation. We can't assume anything until rakshasa himself discloses the sponsor.
> 
> But yes, these updates were long overdue and hopefully all of the fixes from stickz and novick get merged into rakshasa's repos.

@Pentaphon I already described in my initial comment what happened. The latest changes are coming from @stickz fork of this repo. Please see this comment from @stickz which describes where this latest update came from and when the sponsorship was mentioned: https://github.com/crazy-max/docker-rtorrent-rutorrent/pull/347#issuecomment-2132259835

You can also look at the pull requests here and see that all of the most recent pull requests that were merged, were from @stickz: https://github.com/rakshasa/rtorrent/pulls?q=is%3Apr+is%3Aclosed

Everything adds up based on the evidence provided. Unless something else has occurred that I am not aware of, I believe this is the same sponsorship that is being mentioned here.

**Comment by rakshasa** [comment]
The sponsor did not specify if they wanted to be mentioned, so I didn't.

In the past I've done paid work both for people who asked to be mentioned/advertised, and those who didn't. Don't know the current sponsor that well so I'm treating it as donations towards work on the client, not advertisement.

They request PR's to be merged, I'll review them on technical merit and considering the backlog it should take a while just to get through the obvious fixes and improvements.

**Comment by stickz** [comment]
> 
> Everything adds up based on the evidence provided. Unless something else has occurred that I am not aware of, I believe this is the same sponsorship that is being mentioned here.

Yes, ruTorrent development is being sponsored by @anthonyryan1 at @whatbox as well. I'm also using this funding to contribute to the @rakshasa rtorrent project. I have a fork of rtorrent to test these changes before they get sent to upstream. I told the sponsor on day one: the front end is only as good as the back end.

**Comment by stickz** [comment]
> 
> They request PR's to be merged, I'll review them on technical merit and considering the backlog it should take a while just to get through the obvious fixes and improvements.

I'm advising the sponsor which PR's are most crucial to merge. I'd rather just communicate directly on GitHub with @rakshasa. We need a review for #1296 , #1297 and #1298. The reason these PRs are urgent is they impact the deployment of rtorrent to multiple platforms. Gentoo Linux, Homebrew and Hosting Providers.

**Comment by RubenTeixeira** [comment]
As long as there is no people being hurt, I'm super glad this project is back on track. Thanks to everybody involved, being it for, or not for profit. I want my paycheck at the end of the month so why shouldn't everybody else :)

**Comment by rakshasa** [comment]
> I'm advising the sponsor which PR's are most crucial to merge. I'd rather just communicate directly on GitHub with @rakshasa. We need a review for #1296 , #1297 and #1298. The reason these PRs are urgent is they impact the deployment of rtorrent to multiple platforms. Gentoo Linux, Homebrew and Hosting Providers.

Merged.
