### ISSUE TITLE
Turn off allocation for "off" files

### ISSUE THREAD

**Issue by chaseadam** [rakshasa/rtorrent#132]
Scenario:
A large torrent 30G+
Free space of 20G
Need only one file (~5G)
Load the torrent, turn off all files except the one
Start torrent
rTorrent/LibTorrent fills up the disk

Is there any way to prevent rtorrent from allocating the files I don't want?

I already have the following in my ~/.rtorrent.rc:
system.file_allocate.set = no

My filesystem is simfs (OpenVZ container)

**Comment by YamashitaRen** [comment]
I bet that you have to rebuild rtorrent 
https://wiki.archlinux.org/index.php/RTorrent#Pre-allocation
http://relict.blogspot.fr/2013/06/rtorrent-new-file-size.html
