### ISSUE TITLE
ruTorrent: Faults with tinyxml2

### ISSUE THREAD

**Issue by stickz** [rakshasa/rtorrent#1346]
@kannibalox Do you know why tinyxml2 is faulting on ruTorrent? Here is my rpc log.

```
[2024-12-24 15:25:41] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>to_kb</methodName><params>
<param><value><i8>1024</i8></value></param>
</params></methodCall>
[2024-12-24 15:25:41] Status: 200 OK
Content-Type: text/xml
Content-Length: 269

<?xml version="1.0"?><methodResponse><fault><struct><member><name>faultCode</name><value><i4>-500</i4></value></member><member><name>faultString</name><value><string>invalid parameters: target must be a string</string></value></member></struct></fault></methodResponse>
```

**Comment by kannibalox** [comment]
It looks like the old alias `to_kb` doesn't take a target, while it's newer version `convert.kb` does, and tinyxml2 expects a target for all commands with the sole exception of `system.multicall`. That same situation looks to be true for any command using [CMD2_REDIRECT_GENERIC](https://github.com/search?q=repo%3Arakshasa%2Frtorrent%20CMD2_REDIRECT_GENERIC&type=code), so it should be pretty easy to check for `rpc::CommandMap::flag_no_target`.

**Comment by rakshasa** [comment]
Rutorrent and other webui's should convert to the versions with targets as I want to deprecate the old ones.
