### ISSUE TITLE
Error compiling version 0.9.8: `bind2nd` is not a member of `rak`

### ISSUE THREAD

**Issue by 8dcc** [rakshasa/rtorrent#1359]
I downloaded the `.tar.gz` file from https://github.com/rakshasa/rtorrent-archive/raw/master/rtorrent-0.9.8.tar.gz, then ran:

```
./configure --with-xmlrpc-c=yes
make
```

I got the following error when compiling `download_factory.cc`:

```
download_factory.cc: In member function ‘void core::DownloadFactory::receive_success()’:
download_factory.cc:319:24: error: ‘bind2nd’ is not a member of ‘rak’; did you mean ‘std::bind2nd’?
  319 |                   rak::bind2nd(std::ptr_fun(&rpc::parse_command_multiple_std), rpc::make_target(download)));
      |                        ^~~~~~~
```

This also seems to happen with version 0.9.7.

**Comment by stickz** [comment]
This is due to anther version of libtorrent on your system. It's linking rTorrent to the wrong version. It's recommended to cleanup libtorrent before you build. If you can't due to a shared service, the next best option is to link libtorrent statically.

**Comment by 8dcc** [comment]
I see, thank you for the quick response. I was trying to build it manually because I was modifying the [`rtorrent` guix package](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/bittorrent.scm#n232) so it could be built with XMLRPC support. In the guix environment, it seems to be building with the right `libtorrent` version, so this ended up not being a problem.

If anyone uses Guix and ended up here for some reason, here is my updated recipe: [Link](https://github.com/8dcc/guix-channel/blob/bbf2f550c167e3f3a5bebdd26786f31da61947ab/x8dcc-channel/packages/bittorrent.scm#L19-L47).
