### ISSUE TITLE
Unable to seed

### ISSUE THREAD

**Issue by kaihendry** [rakshasa/rtorrent#138]
Created the torrent file using mktorrent like so:
http://s.natalian.org/2013-06-20/1371741926_1366x768.png

Trying to seed it from uk.webconverger.com http://s.natalian.org/2013-06-21/1371775160_1366x768.png results in "Couldn't connect to server". This VPS is absolutely unrestricted and not firewalled.

I tried `Ctrl-B or send it the command "d.set_connection_seed=initial_seed"` from http://libtorrent.rakshasa.no/wiki/RTorrentInitialSeeding and rtorrent 0.9.2 does not seem to understand that with `( 2:59:13) Input failed: Command "d.set_connection_seed" does not exist.`.

**Comment by JamesTheAwesomeDude** [comment]
Try this

1. `^K` to stop the torrent
2. `6` and navigate to the torrent
3. `^B`, THEN `^S`

You have to set the intial seeding on the torrent while it's stopped

This worked for me on `0.9.2/0.13.2`
