### ISSUE TITLE
Inability to add default DHT bootstrap nodes in .rtorrent.rc

### ISSUE THREAD

**Issue by anthonyryan1** [rakshasa/rtorrent#158]
It appears as though rtorrent is unable to add DHT bootstrap nodes within the configuration file. 

The following settings lines:

```
dht.mode.set = on
dht.add_node = router.utorrent.com
dht.add_node = dht.transmissionbt.com
```

generates the following error when starting rtorrent:

```
rtorrent: Error in option file: ~/.rtorrent.rc:86: DHT not enabled.
```

Line 86 in my case is the first `dht.add_node` instruction.

The workaround seems to be to add these bootstrap nodes manually within rtorrent each time it is started.

**Comment by anthonyettinger** [comment]
how do i actually add a dht node?

**Comment by hellgiver** [comment]
You can view an example of how this is done with schedule command in issue #383
