### ISSUE TITLE
rTorrent via  Cygwin

### ISSUE THREAD

**Issue by shaybracha** [rakshasa/rtorrent#163]
Hi
i'm new with rTorrent and would like to know if there is user guide step by step installing and use rTorrent.
some user manual from http://rtwi.jmk.hu/wiki/rTorrentOnWindows#libsigc 
got compile error
Thanks

**Comment by Drake008** [comment]
So I changed the itr but then I do not know where this (ofc strlen requires including cstring) is.
Maybe someone can clear that out for me.

**Comment by JoeyNJ** [comment]
Add this line on top of directory.cc
#include `<string.h>`

**Comment by ghudiczius** [comment]
Hi,

Give a try to my fork of [libTorrent](https://github.com/ghudiczius/libtorrent) and [rTorrent](https://github.com/ghudiczius/rtorrent) and see the updated compilation manual on how to install [rTorrent on Windows](http://rtwi.jmk.hu/wiki/rTorrentOnWindows)

Regards,
Gabor
