### ISSUE TITLE
Stats reset when Save To used

### ISSUE THREAD

**Issue by quadcom** [rakshasa/rtorrent#186]
In order to keep myself organized on my ssedbox running rTorrent, I move completed seeds that I haven't downloaded into a folder to create a big archive. I then mark those seeds in rTorrent with a DL label.

The problem is when the Save To command is used, the original 'Added Date', 'Uploaded', 'Downloaded' and 'Ratio' stats are reset back to zero. This makes determining how long a seed has been active for or whether the proper ratio has been met impossible.

**Comment by Jolar** [comment]
I too am very curious about why stats are reset when moving files? I can't see any advantages with that behavior whatsoever, only the opposite. Maybe some other clients are doing this - I've never seen it though, and I've tried many different clients - but that's not an argument for rtorrent to also do stupid things.

Or - " rakshasa commented on 5 Apr 2014

This makes no sense... I assume you are using a frontend." - have rtorrent _nothing_ to do with this...? But... rutorrent, in my case?

**Comment by quadcom** [comment]
Interestingly enough, disabling the fast resume option retains all existing seeding stats.

**Comment by rakshasa** [comment]
Fast resume is from what I'm guessing creating a new torrent file with the fast resume info added, but does not include the total_up/downloaded values needed for rtorrent to load the torrent with the latest totals to send to the tracker.

Check the torrent file, and perhaps ask the upstream frontend guys.
