### ISSUE TITLE
Error writing to NTFS drive

### ISSUE THREAD

**Issue by ConradBailey** [rakshasa/rtorrent#194]
I have a 2TB external (USB) drive formatted to NTFS that I like to store my media on. This way I can share it between my linux and windows machines. However, rtorrent doesn't like writing to it, at least for large files (>500MB). rtorrent will freeze after 10%-50% downloaded and ultimately crash with the error message: 

Error: Success
Signal code '2': Non-existent physical address.
Fault address: 0x7f658c5eeb27.

The fault address is not part of any chunk.

I'm not sure how it handles seeding from the drive, I'm still experimenting. I would seriously appreciate a fix though! Here's my fstab mounting line for reference:

UUID=(insert UUID here)   /media/seagate ntfs-3g uid=(insert uid),gid=users,dmask=022,fmask=133 0 0

**Comment by aksr** [comment]
Same issue here. Also downloading to ntfs partition freezes rtorrent.
I found others experiencing the similar issues with rtorrent + ntfs:
https://bbs.archlinux.org/viewtopic.php?id=192811
http://askubuntu.com/questions/399775/constant-freezes-when-downloading-torrent-to-ntfs-partition
Not sure if it's ntfs-3g's issue or rtorrent's.

(https://www.google.com/search?q=rtorrent+ntfs+freezes&ie=utf-8&oe=utf-8)

**Comment by rakshasa** [comment]
NTFS and friends are not supported. Without proper mmap rtorrent can't function.

**Comment by skyway22** [comment]
also on ext4 doesn't work. Still too much wasted data for a torrent of ~8Gb..
[http://s6.postimg.org/i2q3s1wsh/screenshot_2016_09_18_at_17_21_28.jpg](url)

**Comment by kannibalox** [comment]
Someone can correct me if I'm wrong, but that 'wasted data' never hits the disk, only the network interface and RAM.

**Comment by rakshasa** [comment]
Wasted, which I assume is the 'skipped' counter is for data for pieces that is discarded as it doesn't pass the hash check. This is most likely either due to some peers in the swarm sending bad data or buggy mmap implementation for a particular filesystem.

**Comment by skyway22** [comment]
buggy mmap implementation. the same torrent file downloaded with transmission got no wasted data...

**Comment by skyway22** [comment]
closed? was there a solution? i've checked again this week, and still, the problem exists

**Comment by pyroscope** [comment]
mmap and fuse simply don't mix.

**Comment by skyway22** [comment]
so there's no solving for this issue you say ?

**Comment by Foxtrod89** [comment]
so..... you saying there's no solution for external drives?

**Comment by rakshasa** [comment]
It's all designed around mmap, so any solution would require proper support for that.

The ball is in fuse's court, go pressure them.

**Comment by chros73** [comment]
> so..... you saying there's no solution for external drives?

There is: format them to an fs that is a friend of rtorrent (e.g. ext4 fs).

**Comment by Foxtrod89** [comment]
> There is: format them to an fs that is a friend of rtorrent (e.g. ext4 fs).

I have 500 GB 2'5 ntfs drive(with ntfs-3g) So far works like charm
