### ISSUE TITLE
Delete torrent data when deleting from interface

### ISSUE THREAD

**Issue by flaggz** [rakshasa/rtorrent#201]
Since 0.9.4 I can no longer delete torrent data file when i press ctrl+d from the interface

All the files remains in the completed folder

The lines in the rtorrent.rc are these
First part is working but second part works only for incomplete torrents and not for completed that I want to completely remove
# Move completed files

system.method.set_key = event.download.finished,move_complete,"execute=mv,-n,$d.get_base_path=,/my/custom/path"
# Erase data files when a download is removed

system.method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.get_base_path="

**Comment by Ser4ph4** [comment]
> method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.base_path="

Thanks for this.
