### ISSUE TITLE
Files still occupy space despite being set to priority 'off' 

### ISSUE THREAD

**Issue by pierz** [rakshasa/rtorrent#202]
It would be good if files that are set to priority 'off' did not occupy any space (i.e. stayed at zero length), as the storage requirements for some multi-file torrents can be a problem. Another option might be to provide sparse storage of the files if they have to exist.

I have seen this issue on the current git version of rtorrent (e42ec54920bf27b0f0ec3fcd02e79f34ac8fcbb0).

**Comment by spoon0042** [comment]
I also noticed this with 0.9.6 / 0.13.6. It seems that fallocate() is always called now, resulting in a mostly empty file taking up the full space where before a priority 'off' file would be sparse aside from the partial block(s) shared with active files.

This is mentioned in the last couple comments on #132. Doing like the page linked there - [http://relict.blogspot.fr/2013/06/rtorrent-new-file-size.html](url) - mentions - zeroing out flags in libtorrent-0.13.6/src/torrent/data/file.cc:resize_file() - indeed creates a sparse file.

It would be nice if allocating like this was really optional (if selectively doing so for disabled files is impractical, which it may be).

**Comment by chros73** [comment]
I've created a fix for this in libtorrent: https://github.com/rakshasa/libtorrent/pull/108
