### ISSUE TITLE
rtorrent 0.9.4-1: XMLRPC stopped working

### ISSUE THREAD

**Issue by Sergeanter** [rakshasa/rtorrent#205]
Package: rtorrent 0.9.4-1 , libtorrent 0.13.4-1
Architecture: ARM5
Device: Pogoplug V4

What it isn't doing: RPC access via fscgi / XMLRPC stopped working after upgrade from 0.9.3 to 0.9.4, xmlrpc utility on client machine with properly configured lighttpd does not list any available methods

What it should be doing: report "The SCGI socket is bound to a specific network device yet may still pose a security risk, consider using 'scgi_local'." at start up of rtorrent , it does not

Steps to reproduce:
Configure rtorrent on server side and lighttpd on client side according to the guide here:
https://wiki.archlinux.org/index.php/Rutorrent_with_lighttpd#Test 
Start rtorrent on server side. SCGI socket opening message does not show up.
Run the test on the client side as following:
$ xmlrpc ServerAddressHere system.listMethods
Instead of returning the list of methods , http error 500 is reported.
Roll back to rtorrent-0.9.3-2 and libtorrent-0.13.3-2.1-arm.pkg.tar.xz fixes the issue.

**Comment by Sergeanter** [comment]
Still does not work for me. Log files above come empty, there is not response to xmlrpc utility and one of the 1st lines in the interactive window is  "Closed XMLRPC log."
Is it possible that it got compiled without XMLRPC support on this particular platform? It is arm5 under arch linux.

**Comment by mmarquezs** [comment]
Same problem, my rcp_dump :
```
<value><i4>0</i4></value>
</data></array></value>
<value><array><data>
<value><i4>0</i4></value>
</data></array></value>
</data></array></value></param>
</params>
</methodResponse>

---END---
```

The rpc.log was empty.

**Comment by gregf** [comment]
Having the same issue on ubuntu.

```
xmlrpc localhost:5000 system.listMethods
Failed.  Call failed.  libcurl failed to execute the HTTP POST transaction, explaining:  Empty reply from server.  (XML-RPC fault code -504)
```
```
netstat -tulnp | grep rtorrent
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:12990           0.0.0.0:*               LISTEN      25959/rtorrent
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      25959/rtorrent
```

**Comment by rakshasa** [comment]
Closing as this is an ancient issue, if you have the same issue with an up-to-date client create a new issue.
