### ISSUE TITLE
XMLRPC-C... failed in configuration of rtorrent-0.9.4 (Raspberry Pi)

### ISSUE THREAD

**Issue by koper89** [rakshasa/rtorrent#207]
Hi, I have a problem with compiling rtorrent 0.9.4, I want it on my raspberry Pi - OS: Xbian (based on debian wheezy, kernel 3.12.20+), I'm sure that xmlrpc-c is properly compiled because i made the same steps like on my seedbox using debian 7.5 and it worked without problem, i tried using ./configure --with-xmlrpc-c=/usr/local/bin/xmlrpc-c-config
when i use /usr/local/bin/xmlrpc-c-config --version
i got the same value as on my seedbox: 1.33.12
( I already got 0.9.3 on both my seedbox and raspberry Pi and compiled it without any problems )
I got an error during configuration:
checking for XMLRPC-C... failed
Log:
http://pastebin.com/Y9EXMNZC

Followed guide in:
http://forums.rutorrent.org/index.php?topic=4665.0

Would really appreciate any help.

Best wishes

**Comment by Ardakilic** [comment]
For future reference, @koper89 suggested a solution [here](http://forums.rutorrent.org/index.php?topic=4665.0#msg14324), based on the issue https://github.com/rakshasa/rtorrent/issues/156:

Quoting from him directly:

> TO solve this just configure and compile libtorrent with `./configure --disable-instrumentation`

Thanks!
