### ISSUE TITLE
change listen port using XMLRPC interface

### ISSUE THREAD

**Issue by fluver** [rakshasa/rtorrent#211]
Im trying to change the port rtorrent listens on for incomming connections using the xmlrpc interface because my forwarded port is changing every few hours.

```
user@host:~$ python xmlrpc2scgi.py -p scgi://127.0.0.1:5000 set_port_range 34754-34754
```

returns:

```
34754-34754
```

```
user@host:~$ python xmlrpc2scgi.py -p scgi://127.0.0.1:5000 get_port_range
```

returns:

```
34754-34754
```

this change is also reflected in rutorrent gui but rtorrent is still using the "old" port, XMLRPC log isnt showing anything about the set_port_range. Whats wrong?
rtorrent: 0.9.4
libtorrent-0.13.4

**Comment by dominikh** [comment]
Is there any update on this? Being able to change the port on the fly is quite crucial for running rtorrent behind a VPN that allows short-lived, dynamic port forwards, such as PIA. 

The workflow with PIA and torrent clients that support is:

- Get a random, forwarded port from PIA's API
- Change the listening port in the torrent client via an RPC call
- Wait an hour
- Repeat

Right now, as far as I can tell, the only option is to update rtorrent's config, then restart rtorrent.

**Comment by mattberther** [comment]
Agreed. Looking forward to being able to adjust the listen.port on the fly.

**Comment by rakshasa** [comment]
It's not a priority for me, so if you're looking forward to it I hope you can convince someone to implement it.

Shouldn't be that difficult, the code that handles that is rather straight-forward.

**Comment by chros73** [comment]
Isn't ssh tunneling an option?

**Comment by Elegant996** [comment]
I looked at the code; would this not have to apply to each peer? It doesn't seem like there's an update function for the peers once they're established on the initial listening port. I'm still trying to determine how to affect that list if it's even possible as is.

It's not as straight-forward as one would think.

**Comment by rakshasa** [comment]
This will be added in the feature-bind branch.

**Comment by binhex** [comment]
@rakshasa do you know if this got implemented in the feature branch?, ive taken a look at your commits but im not 100% sure whether it made it in yet or not.

**Comment by Elegant996** [comment]
This would be why issues have a closed and open status.

**Comment by jcharaoui** [comment]
As a workaround, I found that if you send the `set_bind` command after changing the port range, `network.listen.port` will be updated. This works on version 0.9.2.

**Comment by tofurky** [comment]
it looks like support was merged just yesterday: https://github.com/rakshasa/rtorrent/commit/e96f2f961e6dff3e68bee2c14ef1f3344fefc420
i will test it out in a bit. thanks for adding that feature!

**Comment by tofurky** [comment]
hi @rakshasa,
i was running into an odd crash (gcc stack smashing triggered) on my amd64 debian 9 system when `network.bind_address.set` was being parsed. after probably way too much time looking into it, i traced it down to the sscanf() used in network_port_range_set():
```
diff --git a/src/command_network.cc b/src/command_network.cc
index 2b6874c..4050141 100644
--- a/src/command_network.cc
+++ b/src/command_network.cc
@@ -304,7 +304,7 @@ network_port_range_set(const std::string& arg) {
   uint16_t port_first;
   uint16_t port_last;
 
-  if (std::sscanf(arg.c_str(), "%" PRIu16 "-%" PRIu16, &port_first, &port_last) != 2)
+  if (std::sscanf(arg.c_str(), "%" SCNu16 "-%" SCNu16, &port_first, &port_last) != 2)
     throw torrent::input_error("Invalid port_range argument.");
 
   torrent::bind()->set_listen_port_range(port_first, port_last, 0);

```

`PRIu16` was being used but that's defined as just "u" in inttypes.h. `SCNu16` is defined as "hu" which is the right size for uint16_t. i found this by compiling with -fsanitize=address btw.

will let you know if i run into anything else.

**Comment by rakshasa** [comment]
Closing as the bug report is no longer relevant.

The PRI-to-SCN thing needs to be done in a separate issue.
