### ISSUE TITLE
Apparently rtorrent does not know how to send metadata for magnet links

### ISSUE THREAD

**Issue by Ayms** [rakshasa/rtorrent#215]
Is this correct?

While seeding a file with rtorrent only and using a magnet link to download it,it appears that the metadata can never be retrieved, using other torrent clients the metadata will be retrieved from them and the download will start from the different seeders, including rtorrent.

**Comment by Drezzler** [comment]
Damn , what a pitty this is , i love rtorrent and dont really want to move away from it .
