### ISSUE TITLE
gcc 4.8.2 compile failure

### ISSUE THREAD

**Issue by nelgin** [rakshasa/rtorrent#223]
I have no idea if this is a gcc bug or an rtorrent bug.

/usr/include/c++/4.8.2/functional:1391:40:   required by substitution of ‘template<class _CVArg, class ... _Args, long unsigned int ..._Indexes> decltype (__arg((declval<_Args>)()...)) std::_Mu<_Arg, true, false>::__call(_CVArg&, std::tuple<_Args2 ...>&, const std::_Index_tuple<_Indexes ...>&) const volatile [with _CVArg = _CVArg; _Args = {_Args ...}; long unsigned int ..._Indexes = {_Indexes ...}; _Arg = std::_Bind<std::_Mem_fn<const torrent::HashString& (torrent::DownloadInfo::*)()const>(std::_Bind<std::_Mem_fn<const torrent::DownloadInfo* (core::Download::*)()const>(std::_Placeholder<1>)>)>] [with _CVArg = std::_Bind<std::_Mem_fn<const torrent::HashString& (torrent::DownloadInfo::*)()const>(std::_Bind<std::_Mem_fn<const torrent::DownloadInfo* (core::Download::*)()const>(std::_Placeholder<1>)>)>; _Args = {core::Download_&&, const torrent::Object&}; long unsigned int ..._Indexes = {0ul, 1ul}]’
/usr/include/c++/4.8.2/functional:1143:50:   template instantiation depth exceeds maximum of 900 (use -ftemplate-depth= to increase the maximum) substituting ‘template<class _Tp> typename std::add_rvalue_reference< <template-parameter-1-1> >::type std::declval() [with _Tp = core::Download_&&]’
g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See http://bugzilla.redhat.com/bugzilla for instructions.
make[3]: **\* [command_download.o] Error 4
make[3]: Leaving directory `/root/rtorrent/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/root/rtorrent/src'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/root/rtorrent'
make: **\* [all] Error 2

**Comment by TCSFrank** [comment]
same issue on gcc 4.8.2 with latest rtorrent. Causes an indefinite loop. Error with libstdc++ or just bad rtorrent coding?
