### ISSUE TITLE
Feature request: search by torrent name

### ISSUE THREAD

**Issue by mkroman** [rakshasa/rtorrent#23]
Hello,

I'd like to request a feature that allows users to search for a specific torrent, e.g. using the widely known / key for searching, I imagine it would be rather easy to implement. Not sure, though.

I seed on thousands of general public torrents, and I can _never_ find the one I'm looking for. For example, I would love if I could hit the / key, type a few letters and it searches the torrents in the current buffer for a torrent with that name.

Sincerely hoping that this request wont be in vein.
Thanks in advance.

**Comment by ilf** [comment]
I would also love to have this natively.

**Comment by chros73** [comment]
[Add a temporary name filter to the current view](https://github.com/rakshasa/rtorrent/pull/519) : pull request by @toff .

You can try it out with [rtorrent-ps-ch](https://github.com/chros73/rtorrent-ps#fork-notes) .
