### ISSUE TITLE
Look in $XDG_CONFIG_HOME for rtorrent.rc

### ISSUE THREAD

**Issue by jleclanche** [rakshasa/rtorrent#251]
This is a feature request to support the [basedir spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) in rtorrent, which would look in $XDG_CONFIG_HOME/rtorrent/ (defaulting to ~/.config/rtorrent/) for the rtorrent.rc file.

**Comment by anthonyryan1** [comment]
This would be very nice to have.

**Comment by gulafaran** [comment]
il just consider this torrent client dead for now until this and #180 is fixed.

**Comment by zabbal** [comment]
any plans to get pull request merged?
