### ISSUE TITLE
XMLRPC Error: Found a file exceeding max file size. [removewithdata]

### ISSUE THREAD

**Issue by elixir1349** [rakshasa/rtorrent#257]
I try to download a torrent (look attachment) with 249 gb file size (single file no folder) but rtorrent don't process it. I try also to delete it but rutorrent have problems:
XMLRPC Error: Found a file exceeding max file size. [removewithdata]

I edited rtorrent.rc adding this line at the end but nothing changed

max_file_size = 300G

How Can I add file size limit to 300 gb?
Look torrent file and try to download it, please.

**Comment by 07416** [comment]
> 
> 
> Yeap this torrent doesn't work with the default rtorrent conf, reason explained here : http://www.sysbiosis.com/blog/increase-rtorrent-max-file-size

https://web.archive.org/web/20130214043927/http://www.sysbiosis.com/blog/increase-rtorrent-max-file-size

**Comment by kannibalox** [comment]
That command is deprecated and not supported in newer versions. See https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-d-max-file-size and https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-system-file-max-size

**Comment by rakshasa** [comment]
See above.
