### ISSUE TITLE
rTorrent hash checking even when option set to no

### ISSUE THREAD

**Issue by xxxxxxxxxxxx** [rakshasa/rtorrent#26]
This doesn't happen in 0.8.6. 

Upgraded to 0.9.0 with the option check_hash = no in .rtorrent.rc . However, it still checks the torrents whenever the client is restarted. 

Would be nice if rtorrent would only check upon the user's request to do so.

**Comment by castanley** [comment]
This is still happening to me. I already downloaded before turning the checking off, now it's still checking 600GB and it is taking forever on an ARM processor. Is there something we can do to stop the checking, and continue seeding?

**Comment by PsySc0rpi0n** [comment]
I'm getting the same here. Please, let us know if is there anything wrong about this that is known to developers.
Thanks
Psy

**Comment by 2knarf** [comment]
Same problem here

**Comment by h8uthemost** [comment]
This is happening to me and I'm on rtorrent 10.0/14.0.

Any help to why this is happening or how to stop it?

**Comment by rakshasa** [comment]
Make a new issue, describe in detail the issue and your environment.
