### ISSUE TITLE
example rtorrent.rc file?

### ISSUE THREAD

**Issue by Ncage1974** [rakshasa/rtorrent#270]
I've been trying to google around for an well documented basic rtorrent.rc file that i can start from and i've been unable to find one. Most of them were too old (2011). I found a youtube video where apparently the wiki on arch used to have a link to one but its no longer there.

I installed rtorrent through the ubuntu repositories (whatever the latest version is there). Can someone link a well documented basic rtorrent.rc file to start from?

**Comment by drmike** [comment]
There's one included with the install I believe:

https://github.com/rakshasa/rtorrent/blob/master/doc/rtorrent.rc

**Comment by rakshasa** [comment]
There is no up-to-date .rc file or docs, as I am not able to allocate the time to write those.
