### ISSUE TITLE
Unable to close file descriptors used by rtorrent logging facilities 

### ISSUE THREAD

**Issue by ab1197590** [rakshasa/rtorrent#286]
There appears to be a way to close or stop logging to the execute log (via command_logging.cc) and the XMLRPC log (via thread_worker.cc), however how do we do the same with the other log files?

The documentation [1] to create logs currently do not describe any way to close the log files created while rtorrent is still running. This leads me to believe this issue is more of a feature request than an issue, but I am not intimate enough with how logging facilities were added to the project to affirmatively say for sure.

Could someone please explain how to close log files in rtorrent (while it's still running). I'd be happy to amend the documents it if this is already possible. If for example a log.close_file command existed (which it doesn't as per system.methodExist), there would be no confusion on how to close log files.

[1] https://github.com/rakshasa/rtorrent/blob/7537a3c2a91d0915f1c4c89b01cd583629dc5fd4/doc/manual/logging.md

**Comment by rakshasa** [comment]
Implemented.
