### ISSUE TITLE
 Command "system.method.insert" does not exist. / Command "system.method.set_key" does not exist.

### ISSUE THREAD

**Issue by tuplink** [rakshasa/rtorrent#292]
this worked in 0.9.2 guessing syntex changed 
alll i want to do i move compleated downloads to /media/torrent/Compleated/LABEL 
i found somewhere d.set_directory needs to be changed to d.directory.set
Command "system.method.insert" does not exist.
     in rc file system.method.insert = d.get_finished_dir,simple,"cat=/media/torrent/Completed/,$d.get_custom1="

Command "system.method.set_key" does not exist.
    in rc file    system.method.set_key = event.download.finished,move_complete,"d.set_directory=$d.get_finished_dir=;execute=mkdir,-p,$d.get_finished_dir=;execute=mv,-u,$d.get_base_path=,$d.get_finished_dir="

any help would be great

**Comment by rakshasa** [comment]
Just grep src/command_*.cc for the key words and you'll find the new ones. Also in src/main.cc you'll find redirects from the old commands to the new ones that can be enabled, so just use those to find the new command names.

**Comment by johanclaesson** [comment]
The following seem to work in 0.9.4:

method.set_key = event.download.finished,move_complete,"d.directory.set=./done/;execute=mv,-u,$d.base_path=,./done/"

Note that the destination directory is here hardcoded to ./done/ (get_finished_dir is not used like above).

**Comment by JulyIGHOR** [comment]
How do I make d.get_finished_dir works again? Can't find any similar command in source code.

**Comment by kannibalox** [comment]
That's a custom command that you would have had defined in your rtorrent.rc, e.g. as seen [here](https://github.com/rakshasa/rtorrent/issues/625#issue-242254329). Merely upgrading versions would not have broken that, unless you were using methods that have been deprecated since many versions ago. See [this script](https://github.com/rakshasa/rtorrent/blob/master/doc/scripts/update_commands_0.9.sed) for updating commands if that's the case.

**Comment by JulyIGHOR** [comment]
Thanks for the answer. Any help with command to apply .sed file?

**Comment by JulyIGHOR** [comment]
I think I have apply .sed script, but now It not works, and log file content is:
`1536511960 W Ignoring rtorrent.rc.
1536511960 N rtorrent main: Starting thread.
1536511960 N rtorrent scgi: Starting thread.
1536512896 N rtorrent scgi: Shutting down thread.
1536512896 N rtorrent main: Shutting down thread.
1536512896 N rtorrent disk: Shutting down thread.`
