### ISSUE TITLE
Rakshasa.no down ?

### ISSUE THREAD

**Issue by Kerwood** [rakshasa/rtorrent#295]
Hi. It appears that Rakshasa.no is down, and has been for some time. Is it coming up again or is there an alternative to downloading stables versions of rtorrent and libtorrent.

**Comment by bhavicp** [comment]
Why not download it from Github? https://github.com/rakshasa/rtorrent/releases

**Comment by Kerwood** [comment]
Thanks man. 

But for curiosity sake, why is Rakshasa.no down ?

**Comment by rakshasa** [comment]
Weird, seems there's been some issues with the server. Currently looking into it.

**Comment by pyroscope** [comment]
Fedora has cached release tarballs.

**Comment by Ardakilic** [comment]
Site is still down for me.

Can anyone confirm these packages are identical to older versions?

http://pkgs.fedoraproject.org/repo/pkgs/libtorrent/
http://pkgs.fedoraproject.org/repo/pkgs/rtorrent/

I specifically install 0.9.3 / 0.13.3 to Raspberry Pi, and it's not on GitHub.

**Comment by rejeep** [comment]
All downloads of rtorrent via Homebrew are currently broken. Would be awesome if you could get this up and running again. Thanks!

**Comment by spanglier** [comment]
any news on the server yet @rakshasa :)

**Comment by rakshasa** [comment]
Just got back to work from a prolonged sick leave, so haven't had the time/energy to fix this.

Seems the server got owned and ended up as a spam bot, thus I'll have to set up something from scratch. Unless I'm too lazy it'll be done in over the weekend.

**Comment by rejeep** [comment]
Thanks! :+1:

**Comment by Ardakilic** [comment]
@rakshasa thanks for the heads-up and godspeed :+1:

**Comment by spanglier** [comment]
great news

**Comment by Ardakilic** [comment]
Any updates on this?

@rakshasa Can you please upload the older versions (<= 0.9.3/0.13.3) to somewhere? I couldn't trust fedora's mirrors.

**Comment by rakshasa** [comment]
Yes... in addition to having to rebuild the server my domain name needs to be moved from a (no longer existing) one-man company to me personally... Looking for alternatives, however if you have no issue with running autogen.sh, use the github autogenerated releases.

**Comment by rakshasa** [comment]
This issue seems to have gone on too long due to various issues getting my server back up... so another solution had to be found:

https://github.com/rakshasa/libtorrent/releases/tag/0.13.5
https://github.com/rakshasa/rtorrent/releases/tag/0.9.5

This is a new release with just minor fixes cherrypicked and using tags and a special release-0.X branch to keep the auto* files.

I haven't been able to test them properly since my mac is set up to compile the old branch.

**Comment by rakshasa** [comment]
I apologize for the long delay, the last few months have been a string of events ending up in a clusterfuck.

**Comment by rakshasa** [comment]
Regarding older releases, I can recover the files, however I can't host them on github as that is built from tags.

**Comment by Ardakilic** [comment]
@rakshasa no worries, take your time man, godspeed!

It would be awesome if you could upload the older releases e.g to mega.co.nz, mediafire.com or some other file sharing server, I'm sure some good people will be more than glad to upload and host them on CDNs.

**Comment by rakshasa** [comment]
Sorry, I don't have... for rather re... err.. stupid reasons... access to the disk images where they are located.

If someone has those and want to upload them, there's plenty of distros with the hashes that can validate them as the real thing.

**Comment by Ardakilic** [comment]
@rakshasa Shit happens, I hope everything on your side gets in order in ease.

I've checked rtorrent-0.9.3.tar.gz from fedora repository, its info hash is 0bf2f262faa8c8c8d3b11ce286ea2bf2 and I can see various results on Google with that, and I can see matches,

I've also come across [this](https://github.com/openembedded/meta-oe/blob/master/meta-oe/recipes-connectivity/rtorrent/rtorrent_0.9.3.bb) script, which I think validates with checksum from the original URL, and the hashes match. Also same with libtorrent 0.9.3.

I've not tried yet, but as of this result I can assume for now fedora repos are identical with the original download.

I'd appreciate if someone else could validate, too.

**Comment by tool-maker** [comment]
[archive.org](http://archive.org/web/)  took a back up on May 12, 2015:

http://web.archive.org/web/*/http://libtorrent.rakshasa.no/
http://web.archive.org/web/20150512121357/http://libtorrent.rakshasa.no/

The whole "downloads" folder is there:

http://web.archive.org/web/20140826221757/http://libtorrent.rakshasa.no/downloads/

**Comment by ghudiczius** [comment]
Jari, would you mind terribly, if I created a mirror for the old libtorrent.rakshasa.no site based on the archives from the wayback machine?

**Comment by tool-maker** [comment]
After my first comment, I grabbed the contents of "downloads" from archive.org, just to be sure the files are all there. It is a bit awkward to mirror.

One file, `xmlrpc2scgi.py`, was not available.

**Comment by maiofalmo** [comment]
Compiling from these links doesn't work:

https://github.com/rakshasa/libtorrent/releases/tag/0.13.5
https://github.com/rakshasa/rtorrent/releases/tag/0.9.5

configure: error: Package requirements (libtorrent >= 0.13.5) were not met:
Requested 'libtorrent >= 0.13.5' but version of libtorrent is 0.13.4

0.13.5.tar.gz gives me the folder name libtorrent-0.13.5 but when configuring rtorrent (./configure --with-xmlrpc-c) it says it needs libtorrent >= 0.13.5 - did you give us the wrong version?

**Comment by Micdu70** [comment]
@maiofalmo Yes there is a problem... reported 10 days ago here => https://github.com/rakshasa/libtorrent/issues/82

To fix this : Update the "configure.ac" file from libtorrent 0.13.5 with these modifications => https://github.com/rakshasa/libtorrent/commit/a7857b2a9d047499707d3cd97eaed7e59599d5a2

Then recompile / reinstall libtorrent 0.13.5 and you will success to configure rtorrent 0.9.5. ;)

**Comment by maiofalmo** [comment]
Thanks for the quick response.

**Comment by rakshasa** [comment]
http://rtorrent.net/downloads/

Use the above for older releases. 0.9.5 was removed.

**Comment by ghudiczius** [comment]
mirror for the old libtorrent.rakshasa.no site based on the archives from the wayback machine: http://rtwi.jmk.hu/wiki/archive/rakshasa.libtorrent.no/WikiStart

**Comment by rakshasa** [comment]
Thanks.

**Comment by antonioantunes** [comment]
Why 0.9.5 was removed?

**Comment by rakshasa** [comment]
http://rtorrent.net/downloads/

0.9.6 has been released.

**Comment by bStyler** [comment]
Hi @rakshasa , thank you for the download link!
Where can we find the changelog of rTorrent 0.9.6?

**Comment by rakshasa** [comment]
Except for the git logs, no.

At some point I'll rebuild a website where the changelogs and such can be posted.

**Comment by hilalafridi** [comment]
I have been getting compilations errors with 0.9.6. 0.9.4 works just fine. Need help platform Ubuntu 12.4 GCC 4.8

**Comment by rakshasa** [comment]
0.9.6+ is a stable branch and won't include fixes for modern C++. For that use the master branch.
