### ISSUE TITLE
rtorrent configure fails with xmlrpc

### ISSUE THREAD

**Issue by Spardz** [rakshasa/rtorrent#300]
When running configure, script fails when testing xmlrpc saying that the xmlrpc could not be compiled.

./configure --prefix=/usr --with-xmlrpc-c

**Could not compile XMLRPC-C test.**

I compiled XMLRPC before running configure. The versions I am using are:

$ xmlrpc-c-config --version
1.39.4
libtorrent-0.13.4
rtorrent-0.9.4

**Comment by Ardakilic** [comment]
Possible Dupe of #283 , please check it @Spardz

**Comment by Spardz** [comment]
Thanks, that solves the issue!
