### ISSUE TITLE
rtorrentInit.sh link

### ISSUE THREAD

**Issue by barchan** [rakshasa/rtorrent#301]
Please share official link to rtorrentInit.sh file on GitHub. Thank you!

**Comment by chros73** [comment]
The official init files was posted on Trac. Although it's gone, you can still get those pages with the help of webarchive.org (the whole wiki is working):
http://web.archive.org/web/20131104120054/http://libtorrent.rakshasa.no/wiki/RTorrentCommonTasks

They are on the bottom of that page (cached on 2013.11.04).

**Comment by barchan** [comment]
thank you *chros73*
