### ISSUE TITLE
Thanks for breaking it

### ISSUE THREAD

**Issue by doublezeta** [rakshasa/rtorrent#304]
I didn't like having a working torrent client, so thanks for trying so hard to fuck it up. Love the new config option names!

**Comment by masterkorp** [comment]
@doublezeta while I agree that config options shouldn't break without advice. your issue isn't very helpful on solving the problem.

Could you point what did brake for you ?

**Comment by pyroscope** [comment]
The new verbs were introduced with 0.8.7, you had several years to adapt.
