### ISSUE TITLE
Fails to compile on Gentoo without cppunit

### ISSUE THREAD

**Issue by mohamadissawi** [rakshasa/rtorrent#307]
From /var/tmp/portage/net-p2p/rtorrent-0.9.4-r1/temp/autoconf.out
    configure.ac:7: error: possibly undefined macro: AM_PATH_CPPUNIT

Emerging dev-util/cppunit solved the issue. Can we make this a dependency please?

System info:
    portage 2.2.20
    rtorrent 0.9.4-r1
    x86_64

**Comment by KyleSanderson** [comment]
This is a gentoo ebuild bug.

**Comment by Feandil** [comment]
There is already a bug open: https://bugs.gentoo.org/show_bug.cgi?id=548998

**Comment by mohamadissawi** [comment]
woops, didn't notice that. Thanks @KyleSanderson @Feandil. I'll go ahead and close this.
