### ISSUE TITLE
How to define additional torrent directories

### ISSUE THREAD

**Issue by xbtowbw** [rakshasa/rtorrent#311]
I define in .rtorrent.rc a incoming folder where rtorrent would place per default new contents of torrents:
# Default directory to save the downloaded torrents.

directory = /media/somepath/rtorrent/incoming

When some torrent download has finished I want to MANUALLY move folders to other directories (to better organize stuff). Is it possible to define additional (non default) directories where rtorrent would also find contents so it would also seed from there?

I am looking for something like

additonal_directory = /media/somepath/rtorrent/incoming_non_default

Is that possible?

**Comment by chros73** [comment]
Yes, it is. More than that there are multiple approaches to reach the same goal, e.g like:
- https://github.com/xombiemp/ultimate-torrent-setup/wiki  (just found it 2 weeks ago), it uses ruTorrent and hardlinks
- in pyroscope utils https://code.google.com/p/pyroscope/wiki/QueueManager (I don't know what it uses)

And here is my solution, which is exactly what you want to accomplish: http://logout.hu/bejegyzes/chros/egyszeru_letoltesi_sor_kezelo_rtorrent_ala_simple.html See part B. in it. (There's hungarian explanation in it, but the comments inside the config are in English.)
I wanted to do this without any other external utilities (except for the built-in shell commands). The result is far from simple, but it's working well, even with 100% dropped data (to seed an already downloaded torrent in rtorrent), I have been using it for half a year now.

If you have any question about it, feel free to ask :)
