### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by mkools** [rakshasa/rtorrent#312]
Trying to compile libtorrent and rtorrent, both give similar errors (Freebsd 10.1)

checking for zlib.h... yes
./configure: 18897: Syntax error: word unexpected (expecting ")")

That line says: 

      PKG_CHECK_MODULES(OPENSSL, libcrypto,

Any idea how to fix this?

Thanks.

**Comment by rakshasa** [comment]
You don't have openssl dev installed.
