### ISSUE TITLE
increase/adjust throttle steps

### ISSUE THREAD

**Issue by ilf** [rakshasa/rtorrent#316]
The steps to adjust upload/download throttle speeds is currently 1/5/50 KB. That seems rather outdated and I would love to see them increased.

Personally, I think 10/100/1000 KB are reasonable steps.

If you really want 1 KB steps in 2015, how about adding a 4th option on f/F/v/V?

**Comment by pyroscope** [comment]
Apply https://github.com/pyroscope/rtorrent-ps/commit/a62f8987154ff6615faa8b552441f82133f4744d and recompile.

**Comment by ilf** [comment]
Thanks, pyroscope!
But that's 5/50/500 instead of 10/100/1000.
And more importantly: I would love to see this changed upstream instead of having to patch and recompile.

**Comment by xbtowbw** [comment]
Yeah. Me too!

**Comment by chros73** [comment]
Then just use `rtorrent-ps` by pyroscope. It already includes this and lots of other enhancement.
Honestly, I don't understand why those patches weren't merged to this original project. I can't live without them and they are so awesome that I don't need any gui/web interface for rtorrent anymore.
Thanks for them (one more time), pyroscope!

**Comment by ilf** [comment]
Any chance to get an answer to this? :)

**Comment by chros73** [comment]
Implemented: #614
