### ISSUE TITLE
http_capath seemingly gets ignored

### ISSUE THREAD

**Issue by haasn** [rakshasa/rtorrent#321]
In my rtorrent.rc I have ```http_capath = ~/.rtorrent```, but this setting seems to get ignored. rtorrent still (unsuccessfully) tries reading from ```/etc/ssl/certs```.

**Comment by haasn** [comment]
I've found a work-around:

```network.http.cacert.set = /home/nand/.rtsession/ca-certificates.crt```

This undocumented setting makes it work.

**Comment by rakshasa** [comment]
It is not a workaround, it is one of many commands that are part of the list of deprecated aliases. (since 0.7.0)
