### ISSUE TITLE
Alternative default trackers

### ISSUE THREAD

**Issue by Bystroushaak** [rakshasa/rtorrent#326]
Hi.

Every time when I add a new torrent from magnet link, the `rtorrent` does nothing (Could not connect to trackers).

When I add new tracker manually (`ctrl+x` and `d.tracker.insert="10","udp://9.rarbg.com:2710/announce"`), it works.

Here is my config:

```
session=/home/bystrousak/.rtorrentsession
directory = /home/bystrousak/torrents
encryption = allow_incoming,try_outgoing,enable_retry
use_udp_trackers = yes
dht = auto
dht_port = 6881
peer_exchange = yes
port_range = 49164-49164
```

Is it possible to somehow specify, that `rtorrent` should add this tracker to every new item automatically?

**Comment by pyroscope** [comment]
All the load commands take additional commands for the new item, i.e. add it to your watch schedule(s).

**Comment by Bystroushaak** [comment]
I weren't able to figure how to do that.

**Comment by chros73** [comment]
Using pyroscope idea, you can do something like this (I haven't tried it out it should work):
```
method.insert = d.add_tracker, simple|private, "d.tracker.insert=\"10\",\"udp://9.rarbg.com:2710/announce\""
schedule = watch_dir_1,  5, 10, "load.start=/home/bystrousak/watchdir,\"d.tracker.insert\""
```
You can create an independent watch dir for only the magnet links.

**Comment by hellgiver** [comment]
Resurrecting an ancient thread but I figured this out so I am sharing.  Every time a new torrent is added this will add the following tracker to it.  

`method.set_key=event.download.inserted_new,add_all_trackers001,"d.tracker.insert=\"32\",\"udp://9.rarbg.com:2710/announce\""`

You can add more than one too...

`method.set_key=event.download.inserted_new,add_all_trackers015,"d.tracker.insert=\"32\",\"http://thetracker.org:80/announce\""
method.set_key=event.download.inserted_new,add_all_trackers016,"d.tracker.insert=\"32\",\"http://torrentsmd.com:8080/announce\""
method.set_key=event.download.inserted_new,add_all_trackers017,"d.tracker.insert=\"32\",\"http://tracker.bittor.pw:1337/announce\""`
