### ISSUE TITLE
Update libncursesw.so.5 to version 6

### ISSUE THREAD

**Issue by panteg** [rakshasa/rtorrent#329]
ncurses 6.0 was released August 8, 2015 (see official website: https://www.gnu.org/software/ncurses/ncurses.html). libncursesw.so.5 has been updated to libncursesw.so.6

Currently when I try to open rtorrent, it fails to start and I see this:
`rtorrent: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory`

**Comment by panteg** [comment]
Or better yet, load the shared library libncursesw.so which is symlinked to the version on the person's system.

**Comment by skydrome** [comment]
i think you just need to recompile

**Comment by panteg** [comment]
Geez, sorry, I fixed it. Thanks.
