### ISSUE TITLE
Have to sync(8) before I can rsync(1) the file on OpenBSD

### ISSUE THREAD

**Issue by hboetes** [rakshasa/rtorrent#331]
I run rtorrent on an OpenBSD host. I noticed that if I rsync(1) a freshly downloaded torrent to another host   the file is often corrupt. I figured out that I have to run sync(2) and then rsync again and the file gets correctly transfered. This may be a bug in OpenBSD, if so I'll report it there. Please consider adding a sync(2) syscall after a succesfull download so the file is really on the disc.

**Comment by pyroscope** [comment]
DIY:

    method.set_key = event.download.finished,sync,"execute.nothrow=sync"

**Comment by hboetes** [comment]
uh, that's nifty indeed.
