### ISSUE TITLE
No manual in the release

### ISSUE THREAD

**Issue by alezost** [rakshasa/rtorrent#332]
Hello, README says:

    The man page "doc/rtorrent.1" must be generated with
    "docbook2man rtorrent.1.xml" if it is missing.

I see these files at https://github.com/rakshasa/rtorrent/tree/master/doc/old but they are missing in the releases (http://rtorrent.net/downloads/).  Could you please include the manual in the release?

**Comment by rakshasa** [comment]
Man is no more. Use wiki or what ever, since I don't have the bandwidth to update.

**Comment by alezost** [comment]
OK, thanks for answering.
