### ISSUE TITLE
Different shortcut for stopping the download and deleting torrent actions 

### ISSUE THREAD

**Issue by CyberMuz** [rakshasa/rtorrent#334]
Hi!
Is it possible to change/split the shortcuts for stopping the download and removing the download from rtorrent?
The problem with current setup where both actions are mapped to ^d is that sometimes I accidentally press  ^d two times which results in removing the download and deleting the torrent. The only way to resume the download is to somehow find the torrent file and re-download it.

The proposed solution is to have two shortcuts, one for stopping the download and another one for deleting the download.
Or keep the same shortcut ^d for both actions but put some confirmation dialog before deleting the download.

**Comment by colinhd8** [comment]
you can stop download by ^k.

**Comment by CyberMuz** [comment]
What is the difference between ^d and ^k ? The description in the wiki is not clear to me.

**Comment by rakshasa** [comment]
^k both stops and closes all files, while ^d only stops the download.

So ^k^d is what you want.
