### ISSUE TITLE
how to log the human readable time.

### ISSUE THREAD

**Issue by colinhd8** [rakshasa/rtorrent#339]
with the follow setting,
log.open_file = "peer", (cat,logs/peer.log)
log.add_output = "peer_info", "peer"
it will get the result like this:
1444484541 I Download unchoked slots adjust; currently:0 adjust:0
1444484541 I Download unchoked slots adjust; currently:0 adjust:0

problem is how to set the time to human readable time.

**Comment by rakshasa** [comment]
Not going to make it human readable atm... Unless patch is provided.

Pipe the logs through a script or something if you need the human friendly dates.
