### ISSUE TITLE
[Closed] Keep torrents in seeding list, when restarting

### ISSUE THREAD

**Issue by boolean-is-null** [rakshasa/rtorrent#341]
It feels like I'm doing something wrong here, but I can't seem to get my current list of torrents in rtorrent. When I restart rtorrent, they're gone and I have to recalculate all hashes of the torrents I'm seeding..

How can I have rtorrent keep the seeding torrents permanently..
rTorrent 0.9.2/0.13.2

**Comment by chros73** [comment]
Probably you don't use a session directory in your config.
`session.path.set = "/your/path/to/session/dir"`

**Comment by boolean-is-null** [comment]
that's it, sorry for bothering
