### ISSUE TITLE
f.priority.set - Wrong object type

### ISSUE THREAD

**Issue by wolandmaster** [rakshasa/rtorrent#342]
The `f.priority.set` xmlrpc call is not working since 0.9.4.
Is something changed in parameters?
(previously the parameters was: `hash`, `file index` and `priority`)

eg.: if I try to change the first file priority to high of a torrent then I got this:
**command:**
```
<methodCall>
  <methodName>f.priority.set</methodName>
    <params>
      <param><value><string>12E34F5E26455274AE60B82D973A3BD8C4FB89DF</string></value></param>
      <param><value><int>0</int></value></param>
      <param><value><int>2</int></value></param>
    </params>
</methodCall>
```
**response:**
```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Wrong object type.</string></value></member>
</struct></value>
</fault>
</methodResponse>
```

**Comment by wolandmaster** [comment]
If I start rtorrent with "-D" option (deprecated mode) than the "f.set_priority" command is working with the above parameters.

**Comment by rakshasa** [comment]
https://github.com/rakshasa/rtorrent/wiki/RPC-Utility-XMLRPC2SCGI#s00112233445566778899aabbccddeeff00112233f123

```
00112233445566778899AABBCCDDEEFF00112233:f123
```

The object is now a single parameter, so you need to use the hash plus :f123, :p333 or :t21 and such.
