### ISSUE TITLE
Some directives in my config doesn't work since 0.9.6

### ISSUE THREAD

**Issue by adaigre** [rakshasa/rtorrent#344]
Hi !

I've just upgrade to rtorrent 0.9.6 and libtorrent 0.13.6 but some directives in my config doesn't work anymore (rtorrent doesn't recognize them and fail to start) :

    use_udp_trackers = yes
    peer_exchange = yes
    system.method.set_key=event.download.finished,filebot_amc,"execute={/path/to/my/script}"

Any idea ?

**Comment by pyroscope** [comment]
https://github.com/rakshasa/rtorrent/blob/master/doc/scripts/update_commands_0.9.sed

**Comment by adaigre** [comment]
Thanks !
It would be nice to publish depreciations and a changelog at every release ;)
