### ISSUE TITLE
Event 'event.download.finished' failed: Could not find '='.

### ISSUE THREAD

**Issue by jackusm** [rakshasa/rtorrent#346]
method.set_key=event.download.finished,filebot_amc,"execute2={$HOME/filebot/filebot,$d.base_path=,$d.name=,$d.custom1=}"

What am I doing wrong? This worked before but stopped for some reason. I updated my config to (I think) support the new stuff but still the same error

**Comment by chros73** [comment]
I don't know how it worked before but the '$HOME' is the problem. Specify full path instead.

**Comment by jackusm** [comment]
Thanks that seems to have worked!
