### ISSUE TITLE
The downloaded field doesn't show accurate information

### ISSUE THREAD

**Issue by jantjo** [rakshasa/rtorrent#349]
I've noticed that the downloaded field doesn't show the accurate amount of data actually download and seems to be more of a bit representation of the percentage complete download.

The scenario is if you download a file from tracker A and it's 200Kb, it should show 200Kb and 100% complete. If you add the same file from tracker B, it does a check on the file and it finds that you either have 100% of the original or maybe missing 2%, once the check is done and download is complete it will still show that you downloaded 200Kb which is false.

**Comment by pyroscope** [comment]
What exactly is the "downloaded field"? (provide a screenshot)

**Comment by jantjo** [comment]
https://whatimg.com/i/elYnty.png
Granted this is via ruTorrent but im assuming it's pulling the info directly from rtorrent and not manipulating the data. The SS is of the same data set stored in the same location. premise is the first file is added and fully downloaded so it should show 8.81GB downloaded. once that is complete the additional torrents are added and checked. if 100% is a match or if there is a bit of difference (99% complete) it still shows that the full 8.81GB is downloaded when that's not true. almost a reverse cheating as on the tracker log it will show that you have downloaded say 21Kb of the 8.81GB file and your seeding 100%. If you check your stats you cannot show the 21Kb, only the full size of the download.

**Comment by pyroscope** [comment]
rtorrewnt can hardly do anything about badly labelled columns in rutorrent (or pulling the wrong value for the advertised semantics).

**Comment by jantjo** [comment]
No worries, 100% my fault as I assumed that it was pulling from the correct field, I'll send a note with to them.

Confirmed within rtorrent.
Prime -  Download:           0.0 KB /   8.8 GB
Prime+X (Delta files or 100% match)
Download:           0.0 KB /   2.2 MB
Download:           0.0 KB /   2.3 MB
Download:           0.0 KB /   0.0 KB
