### ISSUE TITLE
How to move completed files?

### ISSUE THREAD

**Issue by gregf** [rakshasa/rtorrent#358]
I have two scheduled dirs I watch.

```
schedule = watch_directory1,5,5,"load_start=~/watch/tv/*.torrent,d.set_directory=~/files/tv/downloading/"
schedule = watch_directory2,5,5,"load_start=~/watch/movies/*.torrent,d.set_directory=~/files/movies/downloading/"
```

How would I go about moving finished tv shows to ~/files/tv/finished and finished movies to ~/files/movies/finished?

**Comment by chros73** [comment]
Well, there are multiple solution for this:
1. https://wiki.archlinux.org/index.php/RTorrent#Manage_completed_files
- only data is handled here (not torrent files)
2. https://github.com/chros73/rtorrent-ps/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc#L76
I modified the idea of archlinux: handling torrent (meta) files as well (dropped-in datafiles for hash checking are also supported) (and lot's of other ideas are implemented in it)
3. https://github.com/pyroscope/pyrocore
- it uses symlinks (I think) to manage finished data files only
4. https://github.com/xombiemp/ultimate-torrent-setup/wiki
- It uses hard links

I'm using 2nd now (mine) 'cause I can autorotate torrents with it (with the help of the moved torrent (meta) files), but maybe it can be achievable with the other setups as well.
Enjoy reading! :)

**Comment by gregf** [comment]
Thanks this looks like what I needed!
