### ISSUE TITLE
How to make a copy of a torrent file when removing a torrent from rtorrent

### ISSUE THREAD

**Issue by methanols** [rakshasa/rtorrent#359]
When I remove a torrent from rtorrent, I also move the data with this method:
```
method.set_key = event.download.erased, move_data, "execute={mv,-n,--,$d.base_path=,/mnt/a/removed/}"
```
That works great but I'd also like to copy the torrent file from the session directory. I have tried to play with the variables but seems like I don't know the proper way to use them. This is a mockup of the line I'm trying to create:
```
method.set_key = event.download.erased, copy_torrent, "execute={cp,-n,--,$session.path=$d.hash=.torrent,/mnt/a/removed/$d.base_filename=}"
```
My rtorrent-PS 0.9.6 reacts to the above with "Event 'event.download.erased' failed: Bad return code."

Is there a way to do this?

**Comment by pyroscope** [comment]
Your syntax is all wrong, you have to use cat= and escapes orgies to build up those dynamic paths, or better yet pass all input values to bash and build up your command there.

**Comment by chros73** [comment]
Pyroscope is right, try out this one (I haven't tested it although):
`method.set_key = event.download.erased, copy_torrent, "execute={cp,-n,--,\"$cat=$session.path=,$d.hash=,.torrent\",\"$cat=/mnt/a/removed/,$d.base_filename=\"}"`

**Comment by methanols** [comment]
I found out that chros73's command would have worked if rtorrent didn't remove session files before running the event commands. That's why I made another command to copy the torrent file at the addition of a new torrent:
```
method.set_key = event.download.inserted_new, copy_torrent2, "execute={cp,--,\"$cat=$session.path=,$d.hash=,.torrent\",~/session_copy/}"
```
Looks like everything works neatly after I repathed the chros73's command. Thanks a lot you both!

**Comment by chros73** [comment]
You're welcome! Perfect solution.
