### ISSUE TITLE
provide a headless rtorrentd

### ISSUE THREAD

**Issue by infinity0** [rakshasa/rtorrent#36]
Would it be possible to provide a daemon version of rtorrent that doesn't have a UI and just sits there waiting for XML RPC requests? At the moment, I need to mess around with screen - if i just do rtorrent & disown, XML RPCs hang for some reason.

It doesn't even need to background itself, since start-stop-daemon can handle this pretty easily. (Actually, if you did make it background itself by using fork(), you would also need to create a pidfile somewhere so start-stop-daemon can get at the new pid).

It would be really useful for scripting things with torrents. transmission-daemon is the only other client that comes close in this regard, but their RPC client doesn't output machine-parseable data, and for some reason it's not connecting properly for my setup (but rtorrent does). Also they don't support the http_cacert options which is pretty important for what I want to do (encrypted backup over bittorrent).

**Comment by awh-tokyo** [comment]
Is there any reason this pull request was never accepted?  What I'm doing now (with screen) just seems clunky.

**Comment by rolfyone** [comment]
I'm pretty keen on this enhancement also... I might fork and import it myself...

**Comment by munnerz** [comment]
Looks like a PR has been merged for this, just awaiting it landing in a release: https://github.com/rakshasa/rtorrent/pull/446

**Comment by rraallvv** [comment]
Is headless mode supported in 0.9.6 ?

**Comment by chros73** [comment]
No, only in 0.9.7.

**Comment by rraallvv** [comment]
@chros73 Thanks. Nevertheless, I was able to use screen with 0.9.6 for a "sort of" headless mode.

**Comment by chros73** [comment]
Yes, or tmux. That's how the majority of people use rtorrent.

**Comment by rraallvv** [comment]
@chros73 Awesome! I'll check out tmux too then. Thanks.

**Comment by phxn** [comment]
tmux gets my vote too, it’s extremely useful.
