### ISSUE TITLE
Adding torrents by SCGI or by backspace stops working after a day

### ISSUE THREAD

**Issue by janeCMD** [rakshasa/rtorrent#363]
I changed from 0.9.4 to 0.9.6. due to this issue, but it keeps happening.

Usually after day, rtorrent stops adding new torrents, it behaves same way as when torrents are added succesfully, they just dont appear in list and nothing is downloading. Restarting client fixes this issue temporarily (for a day or so).

SCGI commands to change overal download speed, get torrent details and other are working.

When broken, adding torrent by SCGI call (rtgui) or by backspace doesnt add anything, neither does work uploading .torrent file. HOWEVER, if i copy torrent file into watch folder, it will get added and starts downloading normally.

Is this a bug or do you have any advice what i could attempt ? I am a programmer, i am very adept in resolving issues.

**Comment by janeCMD** [comment]
I just want to add, that this issue started to appear just maybe 10 days ago, previously same client version didnt cause this issue. I also have rtorrent 0.9.4 installed on another machine, where this issue didnt happen. I am afraid, problem is not in client directly, but rtorrent behaviour is making it hard to find the source of the problem, because no error is reported but torrents do not add.

**Comment by rakshasa** [comment]
Closing since this is old and likely rtgui related.
