### ISSUE TITLE
rtorrent fails to build with xmlrpc

### ISSUE THREAD

**Issue by ballsystemlord** [rakshasa/rtorrent#365]
I found on my gentoo system that rtorrent fails to build when try to use xmlrpc
The details are in the files, thanks.

[build-rtorrent.txt](https://github.com/rakshasa/rtorrent/files/67222/build-rtorrent.txt)
[emergepqv-rtorrent.txt](https://github.com/rakshasa/rtorrent/files/67223/emergepqv-rtorrent.txt)

**Comment by Micdu70** [comment]
Hello, have you downloaded rtorrent from git master? If yes, it's why it doesn't work because the actual git master is broken here...

INFO: The latest tagged rtorrent version is 0.9.6 (you wrote 0.9.3???).

Solutions:
Download the latest official release here => https://github.com/rakshasa/rtorrent/releases
-OR-
You can try to download, and compile, via my rtorrent repository => https://github.com/Micdu70/rtorrent

**Comment by ainstushar** [comment]
Using the latest release, ran ``sh autogen.sh`` ``./configure --prefix=/usr/local/Cellar/rtorrent/0.9.6 --with-xmlrpc-c`` and ``make``.

I get:
````
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in doc
make[2]: Nothing to be done for `all'.
Making all in src
Making all in core
g++ -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -g -O2 -g -DDEBUG -D_THREAD_SAFE    -I/usr/local/Cellar/libtorrent/0.13.6/include -I/usr/local/Cellar/xmlrpc-c/1.39.07/include  -MT curl_get.o -MD -MP -MF .deps/curl_get.Tpo -c -o curl_get.o curl_get.cc
In file included from curl_get.cc:44:
In file included from ./../globals.h:41:
../../rak/priority_queue_default.h:40:10: fatal error: 'tr1/functional' file not found
#include <tr1/functional>
         ^
1 error generated.
make[3]: *** [curl_get.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
````
I encountered an issue with homebrew version too, more info here: https://github.com/Homebrew/homebrew/issues/46957

**Comment by ZEDGR** [comment]
Also using the latest release and ran 
```
./autogen.sh
./configure --with-xmlrpc-c
make
```

I get this error:
```
...
g++ -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -g -O2 -g -DDEBUG -pthread   -I/usr/local/include  -I/usr/local/include  -MT xmlrpc.o -MD -MP -MF .deps/xmlrpc.Tpo -c -o xmlrpc.o xmlrpc.cc
xmlrpc.cc: In member function 'bool rpc::XmlRpc::process(const char*, uint32_t, rpc::XmlRpc::slot_write)':
xmlrpc.cc:539:74: error: 'xmlrpc_mem_block_contents' was not declared in this scope
   bool result = slotWrite((const char*)xmlrpc_mem_block_contents(memblock),
                                                                          ^
xmlrpc.cc:540:57: error: 'xmlrpc_mem_block_size' was not declared in this scope
                           xmlrpc_mem_block_size(memblock));
                                                         ^
xmlrpc.cc:542:33: error: 'xmlrpc_mem_block_free' was not declared in this scope
   xmlrpc_mem_block_free(memblock);
                                 ^
Makefile:424: recipe for target 'xmlrpc.o' failed
make[3]: *** [xmlrpc.o] Error 1
make[3]: Leaving directory '/root/rtorrent-0.9.6/src/rpc'
Makefile:602: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/rtorrent-0.9.6/src'
Makefile:438: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/rtorrent-0.9.6'
Makefile:369: recipe for target 'all' failed
make: *** [all] Error 2
```
My system is Debian 8.

**Comment by Micdu70** [comment]
@ZEDGR Hi, this issue comes from the last "advanced" version of XMLRPC-C ( because of renamed functions in the "Release 1.44" => http://xmlrpc-c.sourceforge.net/change.html ).

So to solve this issue, you can install the "stable" version of XMLRPC-C instead, or try to modify the source code of rtorrent. (or wait that someone else do that ^^)

**Comment by ZEDGR** [comment]
@Micdu70 Thanks a lot I compiled the stable xmlrpc-c and then libtorrent, rotorrent and everything is working fine.

**Comment by ballsystemlord** [comment]
Sorry for not replying sooner. Bother 0.9.4 and 0.9.6 build fine.
