### ISSUE TITLE
Feature Request: Sequential download

### ISSUE THREAD

**Issue by gabo77** [rakshasa/rtorrent#371]
Add the option to download pieces in sequential order. This would be pretty useful for multimedia download with a multimedia server. This is possible with libtorrent piece picker. Would that be a lot of work to implement?

Edit: Just realised that I confused libtorrent (Rakshasa) with libtorrent (Rasterbar). I would still like to request this feature.

**Comment by arthur4ires** [comment]
Hey @gbdoin ,

Any update here?

**Comment by gbdoin** [comment]
I don't use rtorrent anymore.
