### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by zabbal** [rakshasa/rtorrent#372]
There are several 3rd party .service files out there which uses screen and other ugly hacks to run rtorrent.

Would be nice if rtorrent could be started by systemd directly. Ideally, using socket activation to simplify dependency management and improve user experience.

**Comment by Rhialto** [comment]
On Thu 14 Jan 2016 at 15:16:26 -0800, zabbal wrote:
> Would be nice if rtorrent could be started by systemd directly
> Ideally, using socket activation to simplify dependency management and
> improve user experience

Systemd is an evil abomination and anything that gets tainted by it gets
horribly useless.

Thankfully, systemd is Linux-only and therefore I'm not using it.

-Olaf.
-- 
___ Olaf 'Rhialto' Seibert  -- The Doctor: No, 'eureka' is Greek for
\X/ rhialto/at/xs4all.nl    -- 'this bath is too hot.'

**Comment by rakshasa** [comment]
The evil... don't worry, I got too many things on my todo list for anyone to worry about me going that direction.

**Comment by ballsystemlord** [comment]
> There are several 3rd party .service files out there which uses screen and other
> ugly hacks to run rtorrent.
Even if screen is used to dameonize an app it is not an ulgy hack, that is what screen is for.

**Comment by zabbal** [comment]
> I got too many things on my todo list

Zealous idiots aside, will you accept the patch implementing systemd support for rtorrent?

**Comment by rakshasa** [comment]
If the implementation is decent and modular, then yes.

**Comment by Elegant996** [comment]
T[his should solve the socket part of systemd](http://0pointer.de/blog/projects/socket-activation.html). Looks pretty simple to implement as well.

**Comment by rakshasa** [comment]
Daemon mode is now supported.
