### ISSUE TITLE
make fails with "download_store.cc:143:60: error: ‘const class torrent::DownloadInfo’ has no member named ‘dl_rate’"

### ISSUE THREAD

**Issue by krichter722** [rakshasa/rtorrent#380]
$ make
    CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /mnt/main/sources/rtorrent/missing aclocal-1.15 -I scripts
    CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /mnt/main/sources/rtorrent/missing autoconf
     cd . && /bin/bash /mnt/main/sources/rtorrent/missing automake-1.15 --gnu
    /bin/bash ./config.status --recheck
    running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create --no-recursion
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking for cppunit-config... /usr/bin/cppunit-config
    checking for Cppunit - version >= 1.9.6... 1.13.2
    checking for g++... g++
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking for style of include used by make... GNU
    checking dependency style of g++... gcc3
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking how to print strings... printf
    checking for gcc... gcc
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking how to run the C++ preprocessor... g++ -E
    checking for ld used by g++... /usr/bin/ld -m elf_x86_64
    checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
    checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking for g++ option to produce PIC... -fPIC -DPIC
    checking if g++ PIC flag -fPIC -DPIC works... yes
    checking if g++ static flag -static works... yes
    checking if g++ supports -c -o file.o... yes
    checking if g++ supports -c -o file.o... (cached) yes
    checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking dynamic linker characteristics... (cached) GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether g++ supports C++11 features by default... no
    checking whether g++ supports C++11 features with -std=c++11... yes
    checking should use TR1 headers... no
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for execinfo.h... yes
    checking for sysroot... no
    checking sys/vfs.h usability... yes
    checking sys/vfs.h presence... yes
    checking for sys/vfs.h... yes
    checking sys/statvfs.h usability... yes
    checking sys/statvfs.h presence... yes
    checking for sys/statvfs.h... yes
    checking sys/statfs.h usability... yes
    checking sys/statfs.h presence... yes
    checking for sys/statfs.h... yes
    checking for statvfs... ok
    checking whether pthreads work without any flags... no
    checking for the pthreads library -lpthreads... no
    checking whether pthreads work with -Kthread... no
    checking whether pthreads work with -kthread... no
    checking for the pthreads library -llthread... no
    checking whether pthreads work with -pthread... yes
    checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
    checking if more special flags are required for pthreads... no
    checking for PTHREAD_PRIO_INHERIT... yes
    checking for NcursesW wide-character library... yes
    checking for working ncursesw/curses.h... yes
    checking for working ncursesw.h... no
    checking for working ncurses.h... no
    checking if curses tinfo library is linked properly... yes
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for libcurl... yes
    checking for libtorrent... yes
    checking for XMLRPC-C... ignored
    checking for posix_memalign... yes
    checking for cacheline... using default 128 bytes
    checking for __builtin_popcount... yes
    checking if compiler supports __attribute__((unused))... yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
     /bin/bash ./config.status
    config.status: creating Makefile
    config.status: creating doc/Makefile
    config.status: creating src/Makefile
    config.status: creating src/core/Makefile
    config.status: creating src/display/Makefile
    config.status: creating src/input/Makefile
    config.status: creating src/rpc/Makefile
    config.status: creating src/ui/Makefile
    config.status: creating src/utils/Makefile
    config.status: creating test/Makefile
    config.status: creating config.h
    config.status: config.h is unchanged
    config.status: executing depfiles commands
    config.status: executing libtool commands
    (CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /mnt/main/sources/rtorrent/missing autoheader)
    rm -f stamp-h1
    touch config.h.in
    cd . && /bin/bash ./config.status config.h
    config.status: creating config.h
    config.status: config.h is unchanged
    make  all-recursive
    make[1]: Entering directory '/mnt/main/sources/rtorrent'
    Making all in doc
    make[2]: Entering directory '/mnt/main/sources/rtorrent/doc'
    make[2]: Nothing to be done for 'all'.
    make[2]: Leaving directory '/mnt/main/sources/rtorrent/doc'
    Making all in src
    make[2]: Entering directory '/mnt/main/sources/rtorrent/src'
    Making all in core
    make[3]: Entering directory '/mnt/main/sources/rtorrent/src/core'
    g++ -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -MT download_factory.o -MD -MP -MF .deps/download_factory.Tpo -c -o download_factory.o download_factory.cc
    g++ -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -MT download_store.o -MD -MP -MF .deps/download_store.Tpo -c -o download_store.o download_store.cc
    g++ -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -MT view_manager.o -MD -MP -MF .deps/view_manager.Tpo -c -o view_manager.o view_manager.cc
    download_store.cc: In member function ‘bool core::DownloadStore::save(core::Download*, int)’:
    download_store.cc:143:60: error: ‘const class torrent::DownloadInfo’ has no member named ‘dl_rate’
       rtorrent_base->insert_key("total_downloaded", d->info()->dl_rate()->total());
                                                                ^
    In file included from ./../rpc/command_map.h:45:0,
                     from ./../rpc/parse_commands.h:43,
                     from view_manager.cc:46:
    ./../rpc/command.h: In instantiation of ‘tmpl& rpc::command_base::_pod() [with tmpl = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const torrent::Object&)>]’:
    ./../rpc/command.h:163:46:   required from here
    ./../rpc/command.h:193:79: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       template <typename tmpl> tmpl& _pod() { return reinterpret_cast<tmpl&>(t_pod); }
                                                                                   ^
    ./../rpc/command.h: In instantiation of ‘const tmpl& rpc::command_base::_pod() const [with tmpl = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const torrent::Object&)>]’:
    ./../rpc/command.h:164:110:   required from here
    ./../rpc/command.h:194:97: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       template <typename tmpl> const tmpl& _pod() const { return reinterpret_cast<const tmpl&>(t_pod); }
                                                                                                     ^
    download_factory.cc: In member function ‘void core::DownloadFactory::initialize_rtorrent(core::Download*, torrent::Object*)’:
    download_factory.cc:422:23: error: ‘const class torrent::DownloadInfo’ has no member named ‘mutable_dl_rate’
         download->info()->mutable_dl_rate()->set_total(rtorrent->get_key_value("total_downloaded"));
                           ^
    In file included from ./../rpc/command_map.h:45:0,
                     from ./../rpc/parse_commands.h:43,
                     from download_factory.cc:53:
    ./../rpc/command.h: In instantiation of ‘tmpl& rpc::command_base::_pod() [with tmpl = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const torrent::Object&)>]’:
    ./../rpc/command.h:163:46:   required from here
    ./../rpc/command.h:193:79: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       template <typename tmpl> tmpl& _pod() { return reinterpret_cast<tmpl&>(t_pod); }
                                                                                   ^
    ./../rpc/command.h: In instantiation of ‘const tmpl& rpc::command_base::_pod() const [with tmpl = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const torrent::Object&)>]’:
    ./../rpc/command.h:164:110:   required from here
    ./../rpc/command.h:194:97: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       template <typename tmpl> const tmpl& _pod() const { return reinterpret_cast<const tmpl&>(t_pod); }
                                                                                                     ^
    Makefile:443: recipe for target 'download_store.o' failed
    make[3]: *** [download_store.o] Error 1
    make[3]: *** Auf noch nicht beendete Prozesse wird gewartet …
    Makefile:443: recipe for target 'download_factory.o' failed
    make[3]: *** [download_factory.o] Error 1
    mv -f .deps/view_manager.Tpo .deps/view_manager.Po
    make[3]: Leaving directory '/mnt/main/sources/rtorrent/src/core'
    Makefile:615: recipe for target 'all-recursive' failed
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory '/mnt/main/sources/rtorrent/src'
    Makefile:451: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/mnt/main/sources/rtorrent'
    Makefile:383: recipe for target 'all' failed
    make: *** [all] Error 2

experienced with 0.9.4-93-g9647749

**Comment by pyroscope** [comment]
Solved by #366
