### ISSUE TITLE
Explain how to support the project

### ISSUE THREAD

**Issue by krichter722** [rakshasa/rtorrent#381]
Add a hint to `CONTRIBUTING` or `README` about wanted support for the project (code, printed paper with defined value, coffee, beer, pizza).

**Comment by pyroscope** [comment]
See https://github.com/rakshasa/rtorrent/wiki#rtorrent-and-libtorrent-wiki (docs)
and https://github.com/rakshasa/rtorrent/pull/405#issuecomment-193988249 (code)

**Comment by krichter722** [comment]
> See https://github.com/rakshasa/rtorrent/wiki#rtorrent-and-libtorrent-wiki (docs)
and #405 (comment) (code)

That not a sufficiently clear statement how to support the project.

**Comment by pyroscope** [comment]
It's a start, and better than nothing. There's plenty to do as far as docs are concerned.

**Comment by rakshasa** [comment]
Anyone able to make a decent and libressl'esque HTML file I can put up as the index.html?

Kind of overwhelmed by my current RL work project, put do enjoy some good pull request.

**Comment by krichter722** [comment]
This has been closed without solving the task opened by this issue.

**Comment by rakshasa** [comment]
I've updated with a new README.md, and I'll add more to it later.
