### ISSUE TITLE
Update logging documentation

### ISSUE THREAD

**Issue by krichter722** [rakshasa/rtorrent#390]
Currently there's https://github.com/rakshasa/rtorrent/wiki/LOG-Logging only which is outdated as stated in the article itself and there's no way to figure out how logging is supposed to be set up. Following the outdated guide makes `rtorrent` fail with `rtorrent: Error in option file: ~/.rtorrent.rc:15: Log name not found.`.

experienced with 0.9.2

**Comment by maxkoryukov** [comment]
**0.9.6** - but the same thing. Following documentation could break down the rtorrent...

**Comment by pyroscope** [comment]
:pencil: The wiki is editable, i.e. you can update the wrong information.

**Comment by maxkoryukov** [comment]
:+1:

**Comment by rakshasa** [comment]
Old build.

**Comment by pyroscope** [comment]
Also see the end of https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template, which works with 0.9.6.
