### ISSUE TITLE
rTorrent creates its own local.socket file

### ISSUE THREAD

**Issue by maxkoryukov** [rakshasa/rtorrent#394]
Hello.

First, my environment:

+ rTorrent 0.9.6 (GIT, tag 0.9.6)
+ libtorrent 0.13.6 (GIT, tag 0.13.6)
+ xmlrpc (from [SVN, stable, rev 2810](http://svn.code.sf.net/p/xmlrpc-c/code/stable))
+ lighttpd
+ debian lenny

I've configured the rTorrent like described in [wiki](../wiki/RPC-Setup-XMLRPC) :

```ini
scgi_local = /home/user/rtorrent/rpc.socket
```
_(100% copypaste from wiki)_

Here is my lighttpd.conf ( `rtorrent.conf` -related part ):
```ini
lighttpd.conf:
server.modules += ( "mod_scgi" )
scgi.server = (
                "/RPC2" =>
                  ( "127.0.0.1" =>
                    (
                      "socket" => "/home/user/rtorrent/rpc.socket",
                      "check-local" => "disable",
                      "disable-time" => 0,
                    )
                  )
              )
```
_(100% copypaste from wiki)_

But when I am trying to check the state of rTorrent-RPC, I got an error:
```shell
user@host:/opt/rtorrent$ xmlrpc localhost system.listMethods
>> Failed.  Call failed.  HTTP POST to URL 'http://localhost/RPC2' failed.  HTTP response code is 500, not 200.  (XML-RPC fault code -504)
```

Output in lighttpd.log:
```log
2016-02-11 15:18:03: (mod_scgi.c.1393) connect failed: 8 Permission denied 13 0 /home/user/rtorrent/rpc.socket
2016-02-11 15:18:03: (mod_scgi.c.2410) fcgi-server disabled:  0 /home/user/rtorrent/rpc.socket
2016-02-11 15:18:03: (mod_scgi.c.2790) all handlers for  /RPC2 on /RPC2 are down. 
2016-02-11 15:18:04: (mod_scgi.c.2108) fcgi-server re-enabled:  0 /home/user/rtorrent/rpc.socket
```

I've done a small investigation _(lol, almost entire day =), because I couldn't configure the logger of the rtorrent, so a lot of time I've spent determining whether the rtorrent has enabled XMLRPC)_, and now, I know what is the reason: after starting rTorrent **recreates** socket file, with default permissions: default for **rtorrrent** -- it could read from socket, it could write to socket, but no one else could do the same... For example lighttpd couldn't read/write socket file. And it is sad..

My ~~solution~~ crutch:
```shell
chmod 777 /home/user/rtorrent/rpc.socket
```
fixes the problem (**need to run after rTorrent started!!**)... Of course - to next rtorrent restart. And of course my solution is just a crutch..

**Comment by pyroscope** [comment]
https://github.com/pyroscope/pimp-my-box/blob/master/roles/rtorrent-ps/templates/rtorrent/rtorrent.rc#L61-L62

**Comment by maxkoryukov** [comment]
Cool, but I have bare rTorrent...

**Comment by ghudiczius** [comment]
the highlighted execute.nothrow command should work with vanilla rTorrent

**Comment by maxkoryukov** [comment]
Sorry, guys, didn't understand, that it was part of the `.rtorrent.rc`
Solution works, with small modifications (groups and rights)

Thanks!

**Comment by maxkoryukov** [comment]
I've updated [wiki page](../wiki/RPC-Setup-XMLRPC)

Thanks, @ghudiczius and @pyroscope
