### ISSUE TITLE
rtorrent appends a "?" to updated download folders

### ISSUE THREAD

**Issue by beffy** [rakshasa/rtorrent#395]
I'm trying to get rtorrent to download into "filename/filename.mkv" if a torrent only contains an .mkv.

I created a bash script remmkv.sh with the code
`#!bin/bash
echo "/home/beffy/downloads/$1" | sed 's/\.mkv//'`

which I used in .rtorrent.rc in the following way:
`system.method.insert = changedir,simple,"d.directory.set=\"$execute_capture_nothrow=bash,remmkv.sh,$d.name=\""`

However, when I start the torrent, it starts downloading into a folder named "filename?", that is, it appends a ?. 

This is the same if I try to make the directory within .rtorrent.rc:
`system.method.insert = makedir,simple,"execute_capture_nothrow=mkdir,~/,$d.directory="`

Any idea how to get rid of that question mark? It's not present if I run 'bash remmkv.sh "filename.mkv"' manually.

**Comment by pyroscope** [comment]
You *do* realize you emit a \n with that echo in there?

**Comment by beffy** [comment]
Sorry, I was actually not aware of this. I'll try and change this to 'echo -n' to get rid of the \n.

**Comment by beffy** [comment]
This was indeed the problem. Thanks for the help.
