### ISSUE TITLE
Cant resolve hostname

### ISSUE THREAD

**Issue by jdlovins** [rakshasa/rtorrent#399]
I get this very odd issue where if i do a clean reboot of my server, rtorrent cant resolve any hostnames of trackers, but if I do /etc/init./rtorrent restart, it suddenly can. I haven't found a way to debug it in a way that would get me more information. Has anyone else come across this? It's slightly annoying but not a huge deal i guess.

**Comment by pyroscope** [comment]
The init script you use likely sucks (many of them do), esp. wrt Required-Start init info.

**Comment by jdlovins** [comment]
That is likely. It seems any of them using the start-stop-daemon cause issues. I've found one that just uses su to start rtorrent as a certain user and it seems to have fixed the issue. Deleting the .session folder fixes it for 1 reboot, then causes it the next time, it's bizarre. Anyways ill close this out!

**Comment by chros73** [comment]
Then probably it's a permission problem. You can take a look at mine that I'm using with rtorrent-ps on Ubuntu (along with other config files): https://github.com/chros73/rtorrent-ps/tree/master/ubuntu-14.04/etc/init.d

**Comment by chrcoluk** [comment]
Same issue here, I cannot see the fixed init.d as it seems chros73 didnt feel the need to let others use it.

The box hosting rtorrent has working dns but all torrents showing unable to resolve tracker.

**Comment by chros73** [comment]
> didnt feel the need to let others use it

:) I hope you were kidding. What about the link above or pick your choice from [Common Tasks](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#starting-rtorrent-on-system-startup) wiki page.

**Comment by pyroscope** [comment]
As reported in other tickets, curl and its configure options often play a role in DNS trouble, too.
