### ISSUE TITLE
between objects (custom) G-code

### ISSUE THREAD

**Issue by mrvn** [rakshasa/rtorrent#404]
When printing objects sequentially slic3r sets the first layer temperature for every objects first layer. But it does not wait for the temperature to be reached. It would be nice if slic3r would move the head to somewhere between objects but keep it at least 5mm above the bed, then set and wait for the first layer temperature and last print a (mini) skirt around the next object or extrude some extra material to refill the melt chamber after the pause.

On a more generic front the Print Settings->Custom G-code page should have a box for custom G-code between objects, which would get triggered somewhere in the empty space between objects and before lowering the head.

**Comment by pyroscope** [comment]
You might want to check what project you're in next time. Please close these, and add them to whatever project you actually meant.

**Comment by mrvn** [comment]
sorry, must have hit the wrong tab.
