### ISSUE TITLE
Newly merged "cmd_ui_current_view" function breaks compilation.

### ISSUE THREAD

**Issue by TwoLeaves** [rakshasa/rtorrent#410]
Commit https://github.com/rakshasa/rtorrent/commit/30d8379391ad4cb3097d57aa56a488d061e68662 merges the "cmd_ui_current_view" from rtorrent-pryo's codebase. However since the function is still defined in rtorrent-pyro, compiling rtorrent-pyro fails with this error complaining about multiple definitions:

    libsub_root.a(command_pyroscope.o): In function `cmd_ui_current_view()':
    command_pyroscope.cc:(.text+0x190): multiple definition of `cmd_ui_current_view()'
    libsub_root.a(command_ui.o):command_ui.cc:(.text+0x3b0): first defined here
    collect2: error: ld returned 1 exit status
    Makefile:548: recipe for target 'rtorrent' failed
    make[3]: *** [rtorrent] Error 1

Is this a bug in rtorrent or rtorrent-pyro?

**Comment by TwoLeaves** [comment]
Looks like the function should be removed from rtorrent-ps, now that pyroscope's request to merge the "cmd_ui_current_view" function into rtorrent has been accepted.

**Comment by pyroscope** [comment]
Wrong project, except that the version in configure.in should be bumped *directly after* release (git head is not the 0.9.6 version, it's 0.9.7).
