### ISSUE TITLE
Command "d.save_session" does not exist

### ISSUE THREAD

**Issue by heroclix** [rakshasa/rtorrent#429]
I recently compiled rtorrent-ps with xmlrpc on OSX 10.11.4
And I have been seeing those error

Download event action failed: Command "d.save_session" does not exist.
Event 'event.download.resumed' failed: Command "d.save_session" does not exist.
Event 'event.download.paused' failed: Command "d.save_session" does not exist.
Event 'event.download.finished' failed: Command "d.save_session" does not exist.

I have check the output of `~/bin/rtxmlrpc system.listMethods | grep session`

`d.save_full_session
event.download.inserted_session
get_session
get_session_lock
get_session_on_completion
session
session.name
session.name.set
session.on_completion
session.on_completion.set
session.path
session.path.set
session.save
session.use_lock
session.use_lock.set
session_save
set_session
set_session_lock
set_session_on_completion`

**Comment by chros73** [comment]
Which version have you compiled?
Couple of command had been replaced with new ones, as you can see the correct one for this is: `d.save_full_session`

**Comment by heroclix** [comment]
Ok I found out the problem (btw rtorrent version is 0.9.6). The reason for the errors were from pyroscope rtorrent-0.8.9.rc.default file --> I replaced all the `d.save_session` to `d.save_full_session`, no more issues.

**Comment by chros73** [comment]
This can be closed.

**Comment by pyroscope** [comment]
Then you did not apply ``migrate_rtorrent_rc.sh`` which is the real problem. Since this usually happens automatically, there might be underlying issues, or you're in need of an ``pyrocore`` update.
