### ISSUE TITLE
Question on XMLRPC

### ISSUE THREAD

**Issue by romainhild** [rakshasa/rtorrent#432]
Hi,
I would like to know the difference between the `load` function which can take an URL or a file, and the `load_raw` function, which can only take a file.

My goal is to know if there is a way to pass the torrent file as data in a param of type `base64`  instead of having to copy the file locally.

**Comment by ghudiczius** [comment]
IIRC both `load_raw` and `load_raw_start` does exactly what you need, you just need to send the base64 encoded data in a `<base64></base64>` tag as the method parameter

**Comment by romainhild** [comment]
Thanks indeed it works!

Another question, I used to use `load_start` with `schedule`, which allowed me to set the directory in the same request: `load_start=URL,d.set_directory=DIR`
Is there a way to do it with `load_raw_start` ?
