### ISSUE TITLE
Send and receive buffer sizes

### ISSUE THREAD

**Issue by chros73** [rakshasa/rtorrent#435]
I came across this post about `network.send_buffer.size` and `network.receive_buffer.size` : http://www.torrent-invites.com/showthread.php?t=192492&p=1289478&viewfull=1#post1289478
It states that we should use really small receive buffer size.

Since my networking knowledge is pretty limited, can somebody shed some light on these settings?
Thanks

**Comment by Wymaxep2011** [comment]
If you are using UDP or any other datagram protocol without delivery check - if your packet will be lost you will loose 1M of data or 50k of data that must be sent again? It's better to loose less.
Opposite, any packet has a header, in this case it's UDP header included into IP header, then the network frame etc so less packets you send more useful data you will able to sent in a time. I.e. bigger packet size is better. If you have such kind of fork you must try some tests to select optimal result

**Comment by chros73** [comment]
Thanks for your input. I'm using only TCP (no UDP).
What kind of tests are you referring?
If I understand it correctly the bigger buffer size will result bigger memory footprint (not visible in rtorrent process, but in kernel process).
Right now I set those to these, what do you prefer:

```
network.receive_buffer.size.set = 4M
network.send_buffer.size.set    = 12M
```

Thanks

**Comment by rakshasa** [comment]
If you have a large number of peers and high bandwidth, use high buffer sizes as that reduces the disk seeking / connection polling.

In low-memory, high-bandwidth case you still want decent buffer sizes. It is however the number of upload/downloading peers you want to reduce.
