### ISSUE TITLE
Last chunks download / check error

### ISSUE THREAD

**Issue by nerthazrim** [rakshasa/rtorrent#438]
Hi,

It makes a couple months now that I have a very annoying issue with > 1 GB torrents. Actually, several issues but probably having the same root cause.

I have a custom NAS, running on OpenMediaVault stable (Debian 7-based with Linux 3.2.0-4-amd64) and a virtualized server. Two separate machines. I have a fiber optic WAN connection, 100/100M.
rTorrent (with ruTorrent) is running on the NAS, in a "screen". The download folder is in a Samba share.
rTorrent config file : http://pastebin.com/ga9Xqg89
/media/raid is a symlink to /media/RAID5_UNIQUE_ID
/media/raid/torrents is a shared Samba folder
/home is on a SSD, used only for the NAS OS.
link.sh is a script creating a symlink into the right folder depending on the type of torrent downloaded.

I always have the hash check at completion enabled.
When I leech, sometimes (I don’t manage to get a pattern), after the final hash check, the torrent is reported as 99.8-9% completed, with an error: "Hash check on download completion found bad chunks, consider using "safe_sync".
Naturally, I enabled the safe_sync option but it doesn't change anything.
If I stop & start the torrent, it will download the 0.1-2% missing (usually 1 or 2 chunks) without trouble, hash_check again and validate the download.

After a couple weeks, some leechers of torrent I created and uploaded on the tracker noticed that they, sometimes, were stuck at 99.8-9% download on my torrents. No error message, warning or anything, it just stops at 99.8-9%. Note that the hash checks when I add the torrent to be seeded *PASSES*.
In this case, when I run a hash check, sometimes it passes, in which case the leecher stop&start and everything finishes …
Or it doesn't pass, with an error "Download registered as completed, but hash check returned unfinished chunks" in which case I have to run multiple hash checks to validate the torrent...
I found several posts and threads on Google giving the same issue but none got me the answer. I tried to limit the open files to < 64, enable safe_sync, upgrade to the version of the repo (instead of using the tarballs), downgrade to 0.9.4 and 0.9.2, nothing works.
I even tried to create a virtual machine (Debian 8 with Linux 3.16.0-4-amd64) on my server, running r+ruTorrent into it and downloading on the Samba share folder on the NAS. Still the same errors and bugs.

Another weird example: I download a big torrent, around 20 GB. At 100%, hash check -> error. I stop, start, torrent at 99.9% but no peer connects... Weird. I refresh the tracker, stop, start, nothing.
I manually start a hash check and boom: 100% completed, all lights to green, no further download.
Wtf?!

Please also note another test: I create a torrent, hash_check it, start seeding. The leecher stops at 99.9% without error. I run another hash_check that fails. If I open µTorrent on my laptop and start seeding from the laptop with *the same data on the Samba share on the NAS*, the hash check passes and the upload finishes.

Obviously, I ran all sort of tests on my NAS: disks, memory, CPU, everything looks fine...

I’m lost … If somebody has any idea, it would be great!

**Comment by SR-G** [comment]
Same problem here.

Running rtorrent 0.9.2 in a docker container on ubuntu with a 3.14.48-1-lts kernel.
Happens only on big torrents.

The "safe_sync" configuration parameter is not regognized by my rtorrent version...

**Comment by nerthazrim** [comment]
Nobody has any idea?

I noticed that; since I reduced the max number of open files to 64, the problem doesn't appear as often as before.
I'm a bit lost here ...

**Comment by rakshasa** [comment]
First of all you are running an old version of rtorrent.

Also, reducing the max open files is one of the ways to deal with the limitations on the kind of hardware you're running rtorrent on. There's also the address space size options, etc, that you can try to tweak.
