### ISSUE TITLE
 Could not create download: Bad torrent file, "name" is an invalid path name.

### ISSUE THREAD

**Issue by slamanna212** [rakshasa/rtorrent#458]
I am trying to add a torrent file to Rutorrent and it said added but the torrent never showed up. So i tried adding it using rtorrent and when i add the torrent file, i get this error:

(20:57:32) Could not create download: Bad torrent file, "name" is an invalid path name.

**Comment by pyroscope** [comment]
Use `lstor --raw` to show the contents, else this cannot be diagnosed.

http://pyrocore.readthedocs.io/en/latest/usage.html#lstor

**Comment by rakshasa** [comment]
Closing as it is not clearly an issue with rtorrent.
