### ISSUE TITLE
Magnet Link File exceedes the configured max file size

### ISSUE THREAD

**Issue by Pingblue** [rakshasa/rtorrent#463]
Rtorrent has been crashing after adding certain magnet links.

( 9:17:53) 07B73C37460061143A0F5AB6FDD6AF6A8EEA4532->file_list: Failed to prepare file '/07B73C37460061143A0F5AB6FDD6AF6A8EEA4532.meta': File exceedes the configured max file size

Is there anything I can add to the .rtorrent.rc to solve this issue or is it just a bad magnet link ?

**Comment by chros73** [comment]
What's the size of the torrent?

**Comment by rakshasa** [comment]
The meta file exceeded the max file size? That means the metadata downloaded for that magnet file is corrupted in some way, either in rtorrent or the source.
