### ISSUE TITLE
Wiki-Howto: Performance Tuning

### ISSUE THREAD

**Issue by chros73** [rakshasa/rtorrent#466]
[Performance Tuning](https://github.com/rakshasa/rtorrent/wiki/Performance-Tuning)

I've put together an initial content for this. I tried to gather up every useful info that I encountered during the last years.
Feel free to modify, add more stuff to it. :)

Note: if you'll edit that page, please comment this closed issue (e.g. with your commit message), so others will be notified about your change. Thanks

**Comment by pyroscope** [comment]
Wiki changes are notified. Just watch this project.

**Comment by chros73** [comment]
> Wiki changes are notified. Just watch this project.

Interesting, it doesn't work for me (that's why I created this issue).

On https://github.com/settings/notifications page everything is checked, except for "Include your own updates" under ""Notification email - Settings". With these set, I only receive email about new or commented issues, including pull-requests (since github treats them as issues), but nothing else (not commits into master, no new/updated wiki pages, etc.).

How does it work for you? :)

**Comment by rakshasa** [comment]
Someone please also add something to the main wiki page for these new pages.

I'm planning on starting work on the IPv6 code again in the near future, so it would be helpful if others did the wiki part as I'd rather not put myself in a position where working on this project becomes overwhelming again.

**Comment by chros73** [comment]
> Someone please also add something to the main wiki page for these new pages.

Done.
@rakshasa please check the [last paragraph](https://github.com/rakshasa/rtorrent/wiki#stuff). Cheers
