### ISSUE TITLE
Wiki-Howto: Favoring one group of torrents over the rest of them

### ISSUE THREAD

**Issue by chros73** [rakshasa/rtorrent#467]
[Favoring one group of torrents over the rest of them](https://github.com/rakshasa/rtorrent/wiki/Favoring-group-of-torrents)

This is one of the most frequently asked questions regarding to the usage of `rTorrent`. This feature is so powerful that it will change the way you used to work with `rTorrent`. 

Note: if you'll edit that page, please comment this closed issue (e.g. with your commit message), so others will be notified about your change. Thanks

**Comment by pyroscope** [comment]
Nobody will do this. There is update info in both the global news feed (if you watch the project), and also in the wiki update feed. Besides this…

```sh
rtorrent.wiki$ git log --pretty=format:"%h - %an, %ar : %s" --name-status -3
bc0d7e7 - chros73, 2 hours ago : Adding Favoring group of torrents link
M       Config-Guide.md

eedaf53 - chros73, 3 hours ago : Fixing spelling
M       Favoring-group-of-torrents.md

a8415b7 - chros73, 3 hours ago : Finalizing initial content
M       Favoring-group-of-torrents.md
```

**Comment by chros73** [comment]
> Nobody will do this. 

Probably you meant "Note: if you'll edit that page, please comment this closed issue ".

> Besides this…

Thanks, I know about that.

> There is update info in both the global news feed (if you watch the project), and also in the wiki update feed.

Hhmm... What does this mean?
As I mentioned [here](https://github.com/rakshasa/rtorrent/issues/466#issuecomment-234926167), I don't get any email notification about wiki pages, and I'm a watcher of the main `rtorrent` project.

Can somebody else confirm this? Or enlighten me how to set this?

Cheers

**Comment by pyroscope** [comment]
https://github.com/rakshasa/rtorrent/wiki.atom

**Comment by chros73** [comment]
Cheers, I haven't known about this.
The problem still remains for the regular user about those updates though.

**Comment by rakshasa** [comment]
I think you guys should check out 'rtorrent/src/command_groups.cc', it's somewhat old code that was written on contract with the understanding that it would be made public at some point.

Well, it's been quite a almost a decade so when I did some spring-cleaning it was properly added in.

https://github.com/rakshasa/rtorrent/blob/master/doc/manual/choke_groups.md

**Comment by chros73** [comment]
Cheers, I'll take a look if I'll have more time, though I don't understand a word of it now :)

If it's for the same purpose, then we have at least 2 solution now. :)
