### ISSUE TITLE
Unclear how to use multiple SSL certs

### ISSUE THREAD

**Issue by DavidGriffith** [rakshasa/rtorrent#468]
I see that I can use `network.http.cacert.set` to specify a single SSL certificate.  There doesn't seem to be a way to use more than one.  If I use `network.http.cacert.set` more than once, only the last instance is honored.  `network.http.capath.set` doesn't seem to do anything useful.

**Comment by chros73** [comment]
How do you test it whether it works or not?

**Comment by DavidGriffith** [comment]
You test it by doing something with a torrent with trackers that only use SSL.

**Comment by chros73** [comment]
I have this in my config on Ubuntu, but as I recall it was working fine with https trackers without the 2 additional ssl_verify settings.

```
# Adding support to SSL trackers and peers (http_capath)
network.http.capath.set = /etc/ssl/certs

# CURL options to add support for nonofficial SSL trackers and peers
network.http.ssl_verify_host.set = 0
network.http.ssl_verify_peer.set = 0
```

**Comment by DavidGriffith** [comment]
I was fiddling `network.http.capath.set = /etc/ssl/certs` before, but it seems that adding `network.http.ssl_verify_peer.set = 0` was the magic touch.  rTorrent complained that the `network.http.ssl_verify_host.set` setting doesn't exist, at least in 0.9.2.

**Comment by chros73** [comment]
``network.http.ssl_verify_host.set`` I think it was added in 0.9.6. But ``rTorrent-PS`` definitely has it.

**Comment by ne0ark** [comment]
I am running 0.9.6 and its saying http.ssl_verify_host.set is invalid. Anyone have clue what's going on?

**Comment by kannibalox** [comment]
Like @chros73 mentioned, it's only a part of rtorrent-ps: https://github.com/pyroscope/rtorrent-ps/blob/master/patches/ps-ssl_verify_host_all.patch
