### ISSUE TITLE
^O option to change destination directory is not very useful

### ISSUE THREAD

**Issue by DavidGriffith** [rakshasa/rtorrent#469]
Now and then I get a torrent with a terrible destination directory.  The solution is simple: change the destination directory.  Suppose the destination is `foobar`.  I want it to be in `zorkmid` instead.  When I close that torrent and hit ^O and give it a new path, I'm then told that my new download directory is `/home/dave/rtorrent/download/zorkmid/foobar`.  This does not seem very useful.

**Comment by DavidGriffith** [comment]
pyrocore seems nice and rtmv seems to be the correct utility according to all the examples I found, but it doesn't work.  It complains "WARNING  No download item found for "foo", skipping!"

**Comment by chros73** [comment]
Create an issue there and close this one :)
