### ISSUE TITLE
No Man Included In 0.9.6?

### ISSUE THREAD

**Issue by Geyup** [rakshasa/rtorrent#470]
Looking through the src of 0.9.6 I don't see that any man page was included.

0.9.4 src /doc has quite a few files listed, should any of these been included with 0.9.6?

Also under the 0.9.4 /doc/old I see rtorrent.1 & rtorrent.xml

**Comment by rakshasa** [comment]
If you update the man page for the new version it will be included.

**Comment by Geyup** [comment]
ok thanks
