### ISSUE TITLE
When I add a torrent with content over 160GB, no task is started.

### ISSUE THREAD

**Issue by stevenjtx** [rakshasa/rtorrent#472]
I am using rutorrent as webui, may I know if there is a limitation on file size ? thanks

**Comment by chros73** [comment]
There is: https://github.com/rakshasa/rtorrent/blob/efc9097d62cd93e2d139d6d321b5a71d1b169502/src/command_local.cc#L245
`system.file.max_size` , it's 128 GiB.
But it only applies to a single file. I use to use way bigger torrents (multi-files) than this without a problem (I'm not using `rutorrent`, though).

**Comment by rakshasa** [comment]
The current file size restriction was added a decade ago when 128 GiB was more likely to be a bug than a real torrent.

World has changed, so a new default limit should probably be used. Any ideas? Or better yet, a pull request that changes it to that new default.

**Comment by rakshasa** [comment]
Also use 'system.file.max_size = 512G' or such to set it higher.

**Comment by pyroscope** [comment]
Load those torrents via a watch dir, and they'll likely work. ruT has ZERO error reporting on metafile loads.

**Comment by rakshasa** [comment]
There is an issue with metafile's if you only allow encrypted handshake and data.

It's been annoying me for a while, however it will get fixed when it does.

**Comment by rakshasa** [comment]
New max file size is now 512GB.

BTW, remember that you can also partition large files using the 'system.file.split_*' setting.
