### ISSUE TITLE
Script doesn't execute. Torrents never get labeled as "Finished".

### ISSUE THREAD

**Issue by nicissimo97** [rakshasa/rtorrent#473]
Hi,

I'm trying to run a script whenever a torrent finishes, the problem is that the torrents never get labeled as "finished" so the event "event.download.finished" never occurs.
`system.method.set_key = event.download.finished,fileprocessing,"execute=/media/sdah1/nicissimo97/private/rtorrent/file_processing.sh,$d.get_base_path=,$d.get_name="`

![cattura_censored](https://cloud.githubusercontent.com/assets/6663349/17312079/591309fe-5850-11e6-8216-b2472d07c377.jpg)

Running: 0.9.6
What am i doing wrong?

**Comment by rakshasa** [comment]
Some command aliases have been deprecated for a long time, so check src/main.cc and src/command_*.cc for the correct command names for "$d.get_base_path=,$d.get_name=".

There's also a wiki page for deprecated command names.

**Comment by rakshasa** [comment]
https://github.com/rakshasa/rtorrent/wiki/RPC-Migration-0.9

**Comment by nicissimo97** [comment]
Thanks for your reply, rakshasa.
If i understood everything correctly, it becomes:
`method.set_key = event.download.finished,fileprocessing,"execute=/media/sdah1/nicissimo97/private/rtorrent/file_processing.sh,$d.base_path=,$d.base_filename="`

Still. the script never gets executed because the torrents never get labeled as "finished", at least that is what i think, correct me if i'm wrong.

Thanks.
-Nico-

**Comment by chros73** [comment]
Well, the syntax looks good, but (because there's always a but :) ) :

A. `$d.base_path=,$d.base_filename=` these can be empty sometimes, see: #48 
- you need this method in your config and pass that to the script: https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc#L39

B. you can check if the `finished` event triggered by:
- `method.set_key = event.download.finished, finished_try, "print=finished-triggered!"`
- you should see `finished-triggered!` message in rtorrent when it happens

**Comment by nicissimo97** [comment]
I added the 2 methods to my configuration file, and now it seems to work just fine!

Thank you very much, chros73!

**Comment by nicissimo97** [comment]
Ok, it worked for 35 minutes :)

Now i get: `Event 'event.download.finished' failed: Bad return code.`

**Comment by chros73** [comment]
That error probably is a syntax error, that suggest it never worked.
What do you want to achieve?
What is the relevant part of the config?

**Comment by nicissimo97** [comment]
It worked for a while, as you can see:
![cattura_censored 1](https://cloud.githubusercontent.com/assets/6663349/17364257/76cc598e-597f-11e6-9067-5417f9f594dc.jpg)



The script is currently a work in progress, it just create a text file with the two variable (i'm using it for testing)

Here's the config:

`method.insert = d.get_data_full_path, simple, "branch=((d.is_multi_file)),((cat,(d.directory))),((cat,(d.directory),/,(d.name)))"`

`method.set_key = event.download.finished,fileprocessing,"execute=/media/sdah1/nicissimo97/private/rtorrent/ridotti/file_processing.sh,$d.base_path=,$d.base_filename="`

`method.set_key = event.download.finished, finished_try, "print=finished-triggered!"`

**Comment by chros73** [comment]
> you need this method in your config and pass that to the script:

You missed the 2nd part of that. :)
So, the correct way would be (after modifying the script as well):
```
method.set_key = event.download.finished,fileprocessing,"execute=/media/sdah1/nicissimo97/private/rtorrent/ridotti/file_processing.sh,$d.get_data_full_path="
```
Once it works then you can remove the `finished_try` trigger line.

**Comment by nicissimo97** [comment]
It seems to work now, thanks 👍 

Even if with my luck in a couple of days it will stop working

**Comment by nicissimo97** [comment]
Ok, the "finished" event works fine, but the script doesn't run.
Which is weird, cause it worked before.

Script: 

```
#!/bin/bash

file_path="$1"

echo "$file_path" >> test.txt
```

**Comment by rakshasa** [comment]
https://github.com/rakshasa/rtorrent/wiki/LOG-Logging

There's a logging option that lets you see both the command executed and the raw binary output. When dealing with scripts not working that is what you should look at first, before making tickets and such.

**Comment by rakshasa** [comment]
Which someone really should write up in the wiki or something.
