### ISSUE TITLE
Add support for basic arithmetic operators

### ISSUE THREAD

**Issue by chros73** [rakshasa/rtorrent#476]
I'd be nice that somebody add support for basic arithmetic operators (`+`, `-`, `*`, `/`, maybe `%`) in e.g. [src/command_ui.cc](https://github.com/rakshasa/rtorrent/blob/63c2b7aef5d4dc46e914fecbca278b75c8858f89/src/command_ui.cc), if it's not hard to implement (if it is then this idea can be ditched).

Cheers

**Comment by rakshasa** [comment]
It is actually

**Comment by rakshasa** [comment]
It is easy to add zero-cost aliases for command names, so make them as descriptive as is appropriate. The shorthand name can be figured out later.

**Comment by chros73** [comment]
I also finished this one, I'll create a pull request for it soon.

**I. Summary**
Add support for basic arithmetic operators (`+`, `-`, `*`, `/`, `%`) and `min`, `max` functions.
All commands:
- support multiple arguments
- support list type as well
- restricted to integer arithmetic (as in `bash`), even `/`
  - rtorrent (and libtorrent) currently handles only integer variables
  - `/` always round down

**II. New commands in rtorrent**
- `math.add`
- `math.subtract`
- `math.multiply`
- `math.divide`
- `math.modulo`
- `math.min`
- `math.max`

**II. Arithmetic operators in action** 
```ini
# Subtract 3 numbers: -4
print=(math.subtract,5,2,7)
# Divide 3 numbers: 2 !
print=(math.divide,80,9,4)

# Calculate size of a download using its size of files (example using list type)
print=(f.multicall,,f.size_bytes=)

# Get average size in Bytes of downloads in main view
print=(math.divide,(math.add,(d.multicall2,main,d.size_bytes=)),(view.size,main))
```

`math.min` and `math.max` can be used as variable assignment based on intervals as well:
```ini
# Assign 0 if value smaller than 0, or assign value otherwise ( x >= 0 ? x : 0 )
print=(math.max,0,(math.subtract,2,7))
# Assign 0 if value smaller than 0, 100 if value is bigger than 100, or assign value otherwise ( x < 0 ? 0 : (x > 100 ? 100 : x) )
print=(math.max,0,(math.min,100,(math.divide,500,2)))
```

**Comment by rakshasa** [comment]
Looks good.

BTW, might as well add a minmax operator while you're on it.

**Comment by pyroscope** [comment]
Also ``avg`` and ``med`` (median) for lists.

**Comment by chros73** [comment]
> And using sub, mul, div and mod might be better in terms of readability.

Good idea, thanks, I modified it (and my above comment as well).

> might as well add a minmax operator while you're on it.
> Also avg and med (median) for lists

Sorry guys, I already finished it and - as you can see - I can't modify it easily :)
You can create a different issue for it, so this can be closed, and maybe later somebody (even me :) ) will pick it up. But I have couple of other things in my queue (and so little spare time nowdays).

**Comment by chros73** [comment]
On second thought:

1. How can we get/create list in config apart from using `*.multicall*` commands?

2. `avg` will be added soon:
- a) I see the point having it (e.g. when a list is filtered, e.g. using `f.multicall`)
- b) it should use `apply_math_basic` internally

3. What about having a new command that returns back the number (size) of arguments?
- see 2.a. why
- what shall we call it? count, size, etc?
- what shall be the name of the command?

4. `med` is way more problematic, I'll skip this one for now.

5. `minmax`
- I don't have the slightest clue about this one :)
- should it return back list or map?
- how can we access to the returned elements of it? (with the current state of rtorrent)
- can we create this kind of variables in config now?

Anyway, this suppose to add simple commands (to allow not to call external scripts for simple things). 
The proper solution would be if LUA would be integrated (as it was mentioned in one of the issues) but it won't be that easy.

**Comment by chros73** [comment]
2 new commands have been added to pull request:
- `math.cnt`  (count)
- `math.avg`

**Comment by chros73** [comment]
I've been thinking about `median`, it can be easily done using `nth_element` and `max_element` (see [here](http://stackoverflow.com/questions/1719070/what-is-the-right-approach-when-using-stl-container-for-median-calculation/34077478#34077478)) with the following modification:
- create another private method that will create (copy!) a new list of the supplied arguments, reason for this:
  - `nth_element` will modify the original order of list
  - to be able to use this approach with multiple arguments

If duplicating data isn't a problem then I'll create it in this way.
What do you think?

**Comment by pyroscope** [comment]
Was just an idea to have all the standard statistical stuff, not that important to have it really.

BTW, math.random or system.random?

**Comment by chros73** [comment]
> Was just an idea to have all the standard statistical stuff, not that important to have it really.

I couldn't resist your wish :) , so I added `math.med` as well in the above mentioned way.
I consider this pull request finished.

> `system.random` coming up soon

Good idea!
