### ISSUE TITLE
XML-RPC api not working, can't do anything

### ISSUE THREAD

**Issue by rHermes** [rakshasa/rtorrent#483]
I try to call this after seting up with nginx and rtorrent:

```
[rhermes@oldhorse whatman]$ xmlrpc localhost:8008 set_upload_rate "" i/100000
Failed.  Invalid specification of parameter 0 (starting at zero).  Expected value type specifier such as 'i/' or 'array/' but found ''
[rhermes@oldhorse whatman]$ xmlrpc localhost:8008 throttle.global_up.max_rate.set s/ i/100
Result:

Integer: 0
[rhermes@oldhorse whatman]$
```

But even though I get a result the second time, the throttling has not changed at all. Why is this and is it possible to get a overview of the call syntax for all the other functions, since system.methodSignature doesn't work?

**Comment by pyroscope** [comment]
Use `*.set_kb`, or a properly scaled value.

**Comment by rHermes** [comment]
Using kb doesn't produce exact results:

```
[rhermes@oldhorse rtorrent]$ xmlrpc localhost:8008 throttle.global_up.max_rate.set_kb s/ i/10000
Result:

Integer: 0
[rhermes@oldhorse rtorrent]$ xmlrpc localhost:8008 throttle.global_up.max_rate s/
Result:

64-bit integer: 9216
```

The UI says ```[Throttle   9/off KB]```. Why is the count not exact?

**Comment by rHermes** [comment]
It seems that set_kb and set are the same command and that both require an integer which is a multiple of 1024, that is to say a whole KiB.
