### ISSUE TITLE
Limit Issues

### ISSUE THREAD

**Issue by bjay1404** [rakshasa/rtorrent#491]
Hello,

Long time user here. I'm using the 0.9.6/0.13.6 release. I noticed something strange today. I have a 50 MBs connection and the client would never max out the connection even though the provider is totally able to do so. I had a limit set to 5120 and I would never even get near it! I thought for the longest time it was a connection issue, but when I removed the limit and set it to unlimited, the speed went even higher than the original limit - I didn't even think that was possible. I'm using rutorrent. Could you think of a reason why that could be happening? 

![2016-08-19](https://cloud.githubusercontent.com/assets/11383735/17828670/11c4327e-6667-11e6-94f4-1c00af33e77b.png)

**Comment by pyroscope** [comment]
Add config snippets instead of a verbal description. Also tell us what we see here, is the drop when you have the limit set (and how did you set it)? 

Any throttles? Throttles are deactivated when you set no global limit.

**Comment by bjay1404** [comment]
Exactly - the drop is when I set the limit to 5 MB/s. The limit was set to
5MB, when you say throttle?


Once I removed the limit below and changed it to 0 - my speeds went from
2.5 to 6 MB which doesn't seem to make sense to me.
# Global upload and download rate in KiB. "0" for unlimited.
download_rate = 5120
upload_rate = 5120

On Sat, Aug 20, 2016 at 2:56 AM, PyroScope Project <notifications@github.com

**Comment by bjay1404** [comment]
Also, no Channel is set to limit upload speed.

**Comment by pyroscope** [comment]
throttle.global_down.max_rate.set = 5M
throttle.global_up.max_rate.set = 5M

**Comment by bjay1404** [comment]
I think that worked. I will let you know once I restart rtorrent. Thank you!

**Comment by bjay1404** [comment]
That worked great, thank you!
