### ISSUE TITLE
statistics (feature request)

### ISSUE THREAD

**Issue by nikoss** [rakshasa/rtorrent#508]
For each torrent you have...
>Peer list
>Info
>File list
>Tracker list
>Chunks seen
>Transfer list

It would be nice to also have...
>Statistics

Personally, I would be interested to know how much data was uploaded, or downloaded, per torrent, the last...
> 24h
> 7days
> 30days
> 365days
> 3x365days
> Total

-
some brainstorming:
+ Use 24h, 7days, etc instead of day, week, etc.
Because, for example, if you said month, what would you mean?
The last 30 days, or since the 1st day of the current month?

+ Some people would be interested to know the number of connected peers per torrent,
and such stuff. It might be an indication of the torrent's popularity.

+ Some people would rather have statistics disabled by default, for sure. There ought to be such an option in the rtorrent.rc.

-
Ok, not the most important feature. Just my 2cents.

**Comment by rakshasa** [comment]
Rtorrent already supports extensive logging of stats, and quite a few examples usable with e.g. gnuplot are available in rtorrent/doc.
