### ISSUE TITLE
systemd service issue

### ISSUE THREAD

**Issue by Angristan** [rakshasa/rtorrent#516]
I'm using this service for rtorrent on Debian 8 : 

```
[Unit]
Description=rTorrent
After=network.target

[Service]
User=rtorrent
Type=forking
KillMode=none
ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/local/bin/rtorrent
ExecStop=/usr/bin/killall -w -s 2 /usr/local/bin/rtorrent
WorkingDirectory=%h

[Install]
WantedBy=default.target
```

and sometime when downloading, rtorrent crashes : 
![screenshot_25-10-2016_b 3uvjouaw](https://cloud.githubusercontent.com/assets/11699655/19704209/233128a8-9b07-11e6-9f31-d6e470aa5cbd.png)

Any idea why ? 🤔

**Comment by rakshasa** [comment]
This issue tracker isn't for user issues or 3rd party stuff.

**Comment by Angristan** [comment]
Du you provide any "official" init script ?

**Comment by rakshasa** [comment]
No.

**Comment by chros73** [comment]
Take a look at the Starting rTorrent on System Startup section of the [Common tasks](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#starting-rtorrent-on-system-startup) WIKI page.

**Comment by Angristan** [comment]
Thanks ! (I don't understand rakshasa's answer)
