### ISSUE TITLE
Fast resume for multi files torrent fails

### ISSUE THREAD

**Issue by enigmaxia** [rakshasa/rtorrent#518]
I use rtorrent_fast_resume.pl to create both single file torrent and  multi files torrent.
single file torrent works fine but multi files torrent can not be loaded, the error msg appeals

```
Could not create download: Bad torrent file, "path" has zero entries or a zero length entry
```

I am using git version of rtorrent, nothing is wired to me when I check the modified torrent with Bencode Editor,  have no ideal why this happening.

**Comment by chros73** [comment]
Does this [section](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#adding-fast-resume-data-to-torrent-files) of WIKI helps?

**Comment by enigmaxia** [comment]
I'm not sure, not all multi files torrents are failed. I have tested more torrents, the fails are torrents of BluRay disk which has a extremely complex file structure, hundreds of files. I can't tell where the problem goes. However, the scripts works fine with most torrents. I'll close this issue.

**Comment by xiayyu** [comment]
I have figured out the problem: if a path part is a pure number, the fast_resume perl script will encode it as a number type into the torrent file. here is a python report of the original torrent file and the one modified by perl fast_resume scrtipt
```
#print index,item
#for original torrent
28 {'path': ['BDMV', 'JAR', '89011', 'TickerPopInComposite1.png'], 'length': 584348}
#for modified torrent
28 {'path': ['BDMV', 'JAR', 89011, 'TickerPopInComposite1.png'], 'length': 584348}
```
I am not familiar with perl, but I think this bug is easy to fix.
