### ISSUE TITLE
Vim like keybindings

### ISSUE THREAD

**Issue by linuxenko** [rakshasa/rtorrent#522]
Is it possible change keybings to change `arrows` navigation to `h,j,k,l` ? Maybe someone can share such config file?

**Comment by Hund** [comment]
It's pretty stupid that this feature has not been included yet. I'm rather confident that 99.99% of the user base here uses a Vi bases editor here. Every other 'power user's application includes Vi-like keybindings, except for rTorrent who's stuck with the arrow keys.

**Comment by pyroscope** [comment]
It's pretty stupid to start such statements with "It's pretty stupid". Also, these days, many vi(m) users are VERY likely using the arrow keys in their modern vi build as a default way of moving around.
If someone feels inclined, the `keys.layout` command shows how to do this – actually it could be used for this, e.g. as `keys.layout=qwertz,vi`.

**Comment by Hund** [comment]
> It's pretty stupid to start such statements with "It's pretty stupid".

I have never claimed to not be stupid so. :) I'm just frustrated that something that the community has been wanting more than a decade, has years later not been added.

>Also, these days, many vi(m) users are VERY likely using the arrow keys in their modern vi build as a default way of moving around.

I highly doubt this, but I don't have any data for it, so I have no idea what most users use. It just sound weird to me.

I don't have any physical arrow keys as I don't need them. I try my best to stay away from applications that requires less ergonomic keybindings.

> If someone feels inclined, the `keys.layout` command shows how to do this – actually it could be used for this, e.g. as `keys.layout=qwertz,vi`.

I don't know what this means. Does rTorrent have Vi-like keybindings built in already?

**Comment by pyroscope** [comment]
No, it means if the community wants the community can deliver. You just have to find a person both interested in the feature, and capable of writing the code (which in this case is not very complicated, but still work taking time).

**Comment by bartenbach** [comment]
> Also, these days, many vi(m) users are VERY likely using the arrow keys in their modern vi build as a default way of moving around.

https://youtu.be/D4Ha_XjCuA8
