### ISSUE TITLE
make fails due to "error: ‘LOG_DHT_MANAGER’ is not a member of ‘torrent’"

### ISSUE THREAD

**Issue by krichter722** [rakshasa/rtorrent#523]
`./autogen.sh && ./configure && make` fails due to

    dht_manager.cc: In member function ‘void core::DhtManager::load_dht_cache()’:
    dht_manager.cc:58:26: error: ‘LOG_DHT_MANAGER’ is not a member of ‘torrent’
       lt_log_print_subsystem(torrent::LOG_DHT_MANAGER, "dht_manager", log_fmt, __VA_ARGS__);

experienced with 0.9.4-185-g10ce686 on Ubuntu 16.10

**Comment by rakshasa** [comment]
Update libtorrent.
