### ISSUE TITLE
Unable to compile current git (2016-12-02)

### ISSUE THREAD

**Issue by CryptoSiD** [rakshasa/rtorrent#527]
rpc/command.h:193:50: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
mv -f .deps/command_download.Tpo .deps/command_download.Po
mv -f .deps/command_groups.Tpo .deps/command_groups.Po
make[3]: Leaving directory '/root/rtorrent/src'
Makefile:615: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/rtorrent/src'
Makefile:451: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/rtorrent'
Makefile:383: recipe for target 'all' failed
make: *** [all] Error 2
Making install in doc
make[1]: Entering directory '/root/rtorrent/doc'
make[2]: Entering directory '/root/rtorrent/doc'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/root/rtorrent/doc'
make[1]: Leaving directory '/root/rtorrent/doc'
Making install in src
make[1]: Entering directory '/root/rtorrent/src'
Making install in core
make[2]: Entering directory '/root/rtorrent/src/core'
make[3]: Entering directory '/root/rtorrent/src/core'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/rtorrent/src/core'
make[2]: Leaving directory '/root/rtorrent/src/core'
Making install in display
make[2]: Entering directory '/root/rtorrent/src/display'
make[3]: Entering directory '/root/rtorrent/src/display'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/rtorrent/src/display'
make[2]: Leaving directory '/root/rtorrent/src/display'
Making install in input
make[2]: Entering directory '/root/rtorrent/src/input'
make[3]: Entering directory '/root/rtorrent/src/input'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/rtorrent/src/input'
make[2]: Leaving directory '/root/rtorrent/src/input'
Making install in rpc
make[2]: Entering directory '/root/rtorrent/src/rpc'
make[3]: Entering directory '/root/rtorrent/src/rpc'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/rtorrent/src/rpc'
make[2]: Leaving directory '/root/rtorrent/src/rpc'
Making install in ui
make[2]: Entering directory '/root/rtorrent/src/ui'
make[3]: Entering directory '/root/rtorrent/src/ui'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/rtorrent/src/ui'
make[2]: Leaving directory '/root/rtorrent/src/ui'
Making install in utils
make[2]: Entering directory '/root/rtorrent/src/utils'
make[3]: Entering directory '/root/rtorrent/src/utils'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/rtorrent/src/utils'
make[2]: Leaving directory '/root/rtorrent/src/utils'
make[2]: Entering directory '/root/rtorrent/src'
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -pthread    -I/usr/local/include  -I/usr/include  -MT command_ip.o -MD -MP -MF .deps/command_ip.Tpo -c -o command_ip.o command_ip.cc
In file included from globals.h:41:0,
                 from command_ip.cc:45:
../rak/priority_queue_default.h: In destructor â€˜rak::priority_item::~priority_item()â€™:
../rak/priority_queue_default.h:56:95: warning: throw will always call terminate() [-Wterminate]
       throw torrent::internal_error("priority_item::~priority_item() called on a queued item.");
                                                                                               ^
../rak/priority_queue_default.h:56:95: note: in C++11 destructors default to noexcept
In file included from command_ip.cc:42:0:
command_ip.cc: In function â€˜void ipv4_filter_parse(const char*, int)â€™:
command_ip.cc:78:16: error: â€˜LOG_CONNECTION_FILTERâ€™ is not a member of â€˜torrentâ€™
   lt_log_print(torrent::LOG_CONNECTION_FILTER, "adding ip filter (%u.%u.%u.%u/%u)",
                ^
command_ip.cc:78:16: error: â€˜LOG_CONNECTION_FILTERâ€™ is not a member of â€˜torrentâ€™
   lt_log_print(torrent::LOG_CONNECTION_FILTER, "adding ip filter (%u.%u.%u.%u/%u)",
                ^
command_ip.cc: In function â€˜torrent::Object apply_ipv4_filter_load(const list_type&)â€™:
command_ip.cc:234:16: error: â€˜LOG_CONNECTION_FILTERâ€™ is not a member of â€˜torrentâ€™
   lt_log_print(torrent::LOG_CONNECTION_FILTER, "loaded %u %s address blocks (%u kb in-memory) from '%s'",
                ^
command_ip.cc:234:16: error: â€˜LOG_CONNECTION_FILTERâ€™ is not a member of â€˜torrentâ€™
   lt_log_print(torrent::LOG_CONNECTION_FILTER, "loaded %u %s address blocks (%u kb in-memory) from '%s'",
                ^
In file included from command_helpers.h:40:0,
                 from command_ip.cc:46:
rpc/command.h: In instantiation of â€˜tmpl& rpc::command_base::_pod() [with tmpl = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const torrent::Object&)>]â€™:
rpc/command.h:163:46:   required from here
rpc/command.h:193:50: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   template <typename tmpl> tmpl& _pod() { return reinterpret_cast<tmpl&>(t_pod); }
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rpc/command.h: In instantiation of â€˜const tmpl& rpc::command_base::_pod() const [with tmpl = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const torrent::Object&)>]â€™:
rpc/command.h:164:110:   required from here
rpc/command.h:194:62: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   template <typename tmpl> const tmpl& _pod() const { return reinterpret_cast<const tmpl&>(t_pod); }
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rpc/command.h: In instantiation of â€˜tmpl& rpc::command_base::_pod() [with tmpl = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const std::__cxx11::basic_string<char>&)>]â€™:
rpc/command.h:181:80:   required from â€˜void rpc::command_base::set_function(T, int) [with T = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const std::__cxx11::basic_string<char>&)>]â€™
rpc/command_map.h:117:5:   required from â€˜void rpc::CommandMap::insert_slot(std::map<const char*, rpc::command_map_data_type, rpc::command_map_comp>::key_type, Slot, rpc::command_base::any_slot, int, const char*, const char*) [with T = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const std::__cxx11::basic_string<char>&)>; Slot = std::_Bind<torrent::Object (*(std::_Placeholder<2>))(const std::__cxx11::basic_string<char>&)>; std::map<const char*, rpc::command_map_data_type, rpc::command_map_comp>::key_type = const char*; rpc::command_base::any_slot = const torrent::Object (*)(rpc::command_base*, rpc::rt_triple<int, void*, void*>, const torrent::Object&); rpc::target_type = rpc::rt_triple<int, void*, void*>]â€™
command_ip.cc:284:3:   required from here
rpc/command.h:193:50: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   template <typename tmpl> tmpl& _pod() { return reinterpret_cast<tmpl&>(t_pod); }
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rpc/command.h: In instantiation of â€˜tmpl& rpc::command_base::_pod() [with tmpl = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const std::vector<torrent::Object>&)>]â€™:
rpc/command.h:181:80:   required from â€˜void rpc::command_base::set_function(T, int) [with T = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const std::vector<torrent::Object>&)>]â€™
rpc/command_map.h:117:5:   required from â€˜void rpc::CommandMap::insert_slot(std::map<const char*, rpc::command_map_data_type, rpc::command_map_comp>::key_type, Slot, rpc::command_base::any_slot, int, const char*, const char*) [with T = std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const std::vector<torrent::Object>&)>; Slot = std::_Bind<torrent::Object (*(std::_Placeholder<2>))(const std::vector<torrent::Object>&)>; std::map<const char*, rpc::command_map_data_type, rpc::command_map_comp>::key_type = const char*; rpc::command_base::any_slot = const torrent::Object (*)(rpc::command_base*, rpc::rt_triple<int, void*, void*>, const torrent::Object&); rpc::target_type = rpc::rt_triple<int, void*, void*>]â€™
command_ip.cc:286:3:   required from here
rpc/command.h:193:50: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
Makefile:582: recipe for target 'command_ip.o' failed
make[2]: *** [command_ip.o] Error 1
make[2]: Leaving directory '/root/rtorrent/src'
Makefile:615: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/root/rtorrent/src'
Makefile:451: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by rakshasa** [comment]
See #525
