### ISSUE TITLE
rtorrent killed when download a lot of torrents at high speed

### ISSUE THREAD

**Issue by colinhd8** [rakshasa/rtorrent#528]
rtorrent version: git 9abcea84c7f7594ef9cc99f151467cf8b718a9c0
libtorrent version: git 0042d93fd3d135bb7cd2bf873341af6e03b6dae4
leeching torrents: 23
speed: DL:15MB/s~  UP:7MB/s~
OS: Fedora 24 installed on esxi 6.0
CPU: E3 1231v3 (4 cores for fedora 24)
mem:8G

problem:
rtorrent was killed after run a while(sometimes a few minutes, sometimes 2 hours) with the message:
bash: row 1: 11369 Killed                  rtorrent -n -o import=/home/public/rtorrent-colin/rtorrent.rc
(11369 is a random num, different for everytime)

rtorrent.rc:

#general
throttle.global_up.max_rate.set_kb = 0
throttle.global_down.max_rate.set_kb = 0
throttle.max_uploads.set = 500
throttle.max_downloads.set = 500
throttle.min_uploads.set = 10
throttle.min_downloads.set = 10
throttle.max_uploads.global.set = 5000
throttle.max_downloads.global.set = 5000
throttle.max_uploads.div.set = 1
#throttle.max_downloads.div.set = 1

trackers.numwant.set = 500
network.http.max_open.set = 60
#should less than system's max open files limits. ulimit -a
#network.max_open_files.set = 65000
network.max_open_files.set = 1024 
#network.max_open_sockets.set = 80
#net.core.somaxconn 
network.listen.backlog.set = 512
network.send_buffer.size.set = 12M
network.receive_buffer.size.set = 12M

#protocol.encryption.set = allow_incoming,require_RC4,enable_retry
protocol.encryption.set = allow_incoming,enable_retry,prefer_plaintext
system.umask.set = 0007
#keys.layout.set = qwertz

pieces.hash.on_completion.set = no

#range for listening port
network.port_range.set = 20207-20207
network.port_random.set = no

#tracker-less torrent support
dht.mode.set = off
protocol.pex.set = yes
trackers.use_udp.set = yes

#peer settings
throttle.min_peers.normal.set = 80
throttle.max_peers.normal.set = 200
throttle.min_peers.seed.set = 50
throttle.max_peers.seed.set = 200

#resource usage
pieces.memory.max.set = 6000M
network.xmlrpc.size_limit.set = 12M

#preload type 0 = Off, 1 = madvise, 2 = direct paging
pieces.preload.type.set = 0 
pieces.preload.min_size.set = 262144
pieces.preload.min_rate.set = 5120

#compiling libtorrent with --with-posix-fallocate to use system.file.allocate
system.file.allocate.set = 0

#
#CORE settings (mostly keep these, but still check them)
#
#network.http.capath.set = /etc/ssl/certs
encoding.add = utf8

directory.default.set = /home/public/rtorrent-colin/downloaded
session.path.set = /home/public/rtorrent-colin/session
network.scgi.open_local = /home/public/rtorrent-colin/rpc.socket
#scgi_local = /tmp/colin.socket
#scgi_local = /var/www/colin.socket
#SCGI_port = 127.0.0.1:5000
#log.execute = /home/public/rtorrent-colin/logs/execute.log

#SCHEDULE: Make SCGI socket group-writable
schedule2 = scgi_permission,0,0,"execute.nothrow=chmod,777,/home/public/rtorrent-colin/rpc.socket"

execute2 = {sh,-c,/usr/local/php/bin/php /var/www/rutorrent/php/initplugins.php colin &}

#SCHEDULE: Watch disk space
schedule2 = low_diskspace,15,40,close_low_diskspace=1000M

#EVENTS: Logging (don't log "opened", or you get swamped at startup)
method.set_key = event.download.inserted_new,log,"print=\"LOADED \",$d.name=,\" [\",$convert.date=$system.time=,\"]\""
method.set_key = event.download.finished,log,"print=\"COMPLETED \",$d.name=,\" [R=\",$d.ratio=,\", \",$convert.date=$system.time=,\"]\""
method.set_key = event.download.closed,log,"print=\"CLOSED \",$d.name=,\" [R=\",$d.ratio=,\", \",$convert.date=$system.time=,\"]\""

#CURL options
network.http.ssl_verify_peer.set=0
network.http.ssl_verify_host.set=0

#
#LOCAL Settings
#

#Add anything of your own here...

#NETWORK: Unwanted peers
##ipv4_filter.add_address = 1.2.3.666, unwanted

system.file.max_size.set = 2048G
#network.local_address.set = 2.22.2.2

#log.open_file = "rpc_dump.log", (cat,$RT_HOME/logs/rpc_dump.log.,(system.pid))
#log.add_output = "rpc_dump", "rpc_dump.log"
#log.open_file = "log name", "file path"

log.open_file = "rtorrent_rpc.log", (cat,logs/rpc.log) 
#log.add_output = "rpc_events", "rtorrent_rpc.log"
log.open_file = "rpc_dump.log", (cat,logs/rpc_dump.log)
#log.add_output = "rpc_dump", "rpc_dump.log"

################ If you need log, uncomment (remove ######) from all lines below
log.open_file = "rtorrent", (cat,logs/rtorrent.log)
log.open_file = "tracker", (cat,logs/tracker.log)
log.open_file = "storage", (cat,logs/storage.log)
log.open_file = "peer", (cat,logs/peer.log)
log.open_file = "connection", (cat,logs/connection.log)
log.open_file = "torrent", (cat,logs/torrent.log)
log.open_file = "socket", (cat,logs/socket.log)

log.add_output = "info", "rtorrent"
log.add_output = "critical", "rtorrent"
log.add_output = "error", "rtorrent"
log.add_output = "warn", "rtorrent"
log.add_output = "notice", "rtorrent"
#log.add_output = "debug", "rtorrent"

#log.add_output = "tracker_debug", "tracker"
log.add_output = "torrent_debug", "torrent"
#log.add_output = "peer_debug", "peer"
#log.add_output = "connection_debug", "connection"
log.add_output = "socket_warn", "socket"

#log.add_output = "dht_debug", "tracker"
#log.add_output = "storage_debug", "storage"
###END rtorrent.rc #########################################################
Does anyone has the same problem?

**Comment by pyroscope** [comment]
network.max_open_files.set = 1024

**Comment by colinhd8** [comment]
@pyroscope Thank you for your reply. But "network.max_open_files.set " was already set to 1024. I will reduce it and retry.

**Comment by pyroscope** [comment]
It should be clearer now. :trollface:
