### ISSUE TITLE
ignores backspace in xfce4-terminal 0.8.1

### ISSUE THREAD

**Issue by konstyab** [rakshasa/rtorrent#530]
rtorrent running inside xfce4-terminal
trying to add torrent, pressing backspace. no effect

going in terminal preferences -> compatibility -> "backspace key generates". changing option from "auto-detect" to "ASCII DEL". then backspace works in rtorrent

using xfce4-terminal 0.8.1

**Comment by rakshasa** [comment]
https://github.com/rakshasa/rtorrent/blob/master/src/ui/download_list.cc#L343-L344

If you find the missing key code then feel free to add it.
