### ISSUE TITLE
[Bug Report] rtorrent_fast_resume.pl handles path improper

### ISSUE THREAD

**Issue by xiayyu** [rakshasa/rtorrent#531]
The problem is discussed here: [Fast resume for multi files torrent fails](https://github.com/rakshasa/rtorrent/issues/518) 

If a path part is a pure number, the fast_resume perl script will encode it as a number type into the torrent file. Here is a python report of the original torrent file and the one modified by perl fast_resume scrtipt
```
#print index,item
#for original torrent
28 {'path': ['BDMV', 'JAR', '89011', 'TickerPopInComposite1.png'], 'length': 584348}
#for modified torrent
28 {'path': ['BDMV', 'JAR', 89011, 'TickerPopInComposite1.png'], 'length': 584348}
```
The non-string `89011` part of path is unrecognizable to rtorrent.

**Comment by rakshasa** [comment]
I'm happy to accept any patches/pull requests.

**Comment by xiayyu** [comment]
As I looking deep into the script, I think it's a limitation of perl and a known issue.
 
The non-string problem can be fix by setting
```
$Convert::Bencode_XS::COERCE = 0;
```
But another problem arised: perl can't handle the large integer properly.
As mentioned in the document of [Convert::Bencode_XS](http://search.cpan.org/dist/Convert-Bencode_XS/lib/Convert/Bencode_XS.pm)  

> Problems may arise if you want to use a arbitrary sequence of integers as a real integer, mainly because it could surpass the maximum allowed by your platform. (At the moment there is no solution for that). 

Maybe a more complex perl script could solve this problem, but I'm not expert to perl. The original Python bencode package could handle this problem well, and an implement of rtorrent_resume is given by [pyroscope/pyrocore](https://github.com/pyroscope/pyrocore)

**Comment by rakshasa** [comment]
Other tools are available for adding this, use them.
