### ISSUE TITLE
XMLRPC attributes for load.raw_verbose

### ISSUE THREAD

**Issue by 0xCCD** [rakshasa/rtorrent#533]
Hi, it is actually not an issue, i would like to use **load.raw_verbose** with ruby, what kind of data does **load.raw_verbose** expects ? 

```
require 'xmlrpc/client'
host = 'myserver.com'
port = 80
path = '/asdasjdlkasjdasd'
file_path = '/tmp/kubuntu-16.10-desktop-amd64.iso.torrent' # dwnloaded from http://cdimage.ubuntu.com/kubuntu/releases/16.10/release/kubuntu-16.10-desktop-amd64.iso.torrent

server = XMLRPC::Client.new(host, path, port)
```

I've tried as byte array
`server.call('load.raw_verbose', '', File.read(path).bytes)`
which raises Wrong object type error.

I've tried it base64 encoded
`server.call('load.raw_verbose', '', Base64.encode64(File.read(file_path)))`
which doesn't throw an exception but rtorrent logs
Could not create download, the input is not a valid torrent.

I've tried to send just the plain content,
`server.call('load.raw_verbose', '', File.read(file_path))`
which ends in an ArgumentError: invalid byte sequence in UTF-8

I'm really thankfull for any suggestion

**Comment by pyroscope** [comment]
You tried 2 things in 3 combinations. There is a 4th.

**Comment by 0xCCD** [comment]
you mean i have to bas64 encode the byte array ?

**Comment by 0xCCD** [comment]
> Besides, why the hell do you use "raw" when the data is in a file anyway.
The UI does not run on the same server

**Comment by pyroscope** [comment]
Well, find out how your xmlrpc encoding works,m the XML has to be right.

**Comment by 0xCCD** [comment]
A few words from you about the correct way to go would be really helpfully !
And do you have an example XML structure, I actually don't really know how the XML should look like ?

Many thanks in advance

**Comment by pyroscope** [comment]
Call

    rtxmlrpc load.raw_verbose '' @foo.torrent --debug

and read the log. See https://pyrocore.readthedocs.io/en/latest/installation.html

**Comment by 0xCCD** [comment]
thx for extending your library :) this helps a lot

**Comment by 0xCCD** [comment]
`server.call('load.raw_verbose', '', XMLRPC::Base64.new(File.read(path)))`
