### ISSUE TITLE
rtorrent and D state

### ISSUE THREAD

**Issue by colinhd8** [rakshasa/rtorrent#537]
Via the top command, it shows that rtorrent is in the D state(top's S column) for 90%+ of the time.
Is this a normal thing? And how can i confirm what's it waiting for?

Thank you.

**Comment by rakshasa** [comment]
We use read/write on mmap'ed files so much of the work is happening as the kernel is copying directly from file pages it loads to the network stack, thus the client is only uninterruptible when the context switches back to user space.
