### ISSUE TITLE
Variable use in rtorrent.rc

### ISSUE THREAD

**Issue by ymvunjq** [rakshasa/rtorrent#540]
The following rtorrent.rc template (mainly taken from https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template)

```
method.insert = cfg.basedir,  private|const|string, (cat,"/home/user/rtorrent/")
method.insert = cfg.watch,    private|const|string, (cat,(cfg.basedir),"watch/")
method.insert = cfg.logs,     private|const|string, (cat,(cfg.basedir),"log/")
method.insert = cfg.logfile,  private|const|string, (cat,(cfg.logs),"rtorrent-",(system.time),".log")
method.insert = cfg.download, private|const|string, (cat,(cfg.basedir),"download/")
method.insert = cfg.session,  private|const|string, (cat,(cfg.basedir),"session/")

session.path.set = (cat,(cfg.session))
directory.default.set = (cat,(cfg.download))

schedule2 = watch_start_music,1,10,"load.start=(cat,(cfg.watch),\"dir1/*.torrent\"),d.directory.set=(cat,(cfg.download),\"/dir1\")"
```

produces 

`Scheduled command failed: watch_start_music: Junk at end of input.`

If the schedule command is changed like that

`schedule2 = watch_start_music,1,10,"load.start=(cat,(cfg.watch),\"dir1/*.torrent\"),d.directory.set=\"/home/user/rtorrent/download/dir1\""`

It works. It seems that it is not possible to use a variable in d.directory.set

**Comment by chros73** [comment]
> Scheduled command failed: watch_start_music: Junk at end of input.
This means that you have syntax error in that line.

What about this instead?
`schedule2 = watch_start_music,1,10,"load.start=(cat,(cfg.watch),\"dir1/*.torrent\"),\"d.directory.set=(cat,(cfg.download),/dir1)\""`

**Comment by ymvunjq** [comment]
Impressive, it works.
This syntax is for me very weird. Can you explain me how do you find it ?

**Comment by chros73** [comment]
:) I "found" it via trail and error approach.
You can can take a look at these 3 config files (and the rest of the color configs) if you are interested in scripting: you can do amazing things with rtorrent.
(.rtorrent.rc)[https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc], (.rtorrent-config.rc)[https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent-config.rc], (rtorrent-ps.rc)[https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc]

**Comment by ymvunjq** [comment]
I'm sure that amazing things can be done with it... the problem is this syntax that is very difficult to handle.

**Comment by chros73** [comment]
Yes, you're right. And more than that: there are 2 different syntaxes that you can use. The old one (using `"`) and the new one (using `(`, `)`).

> This syntax is for me very weird.

Well, not really. As you can see, every command starts and ends with `"` : 
- `"load.start=..."`
- `"d.directory.set=..."`
And you have to escape starting commands inside of a command: `\"`

**Comment by ymvunjq** [comment]
It seems that when I'm using this syntax, my torrents do not start automatically...
It works like if I was using `load` instead of `load_start`. Do you think there can be a linked ?

**Comment by chros73** [comment]
It should be called: `load.start` not load_start , see [here](https://github.com/rakshasa/rtorrent/blob/ce0008510723b6c96c86f8fe944affc84f90cd69/src/command_events.cc#L349).

**Comment by ymvunjq** [comment]
Sorry it was a typo...

I am using this example, that you gave me and that is working.

`schedule2 = watch_start_music,1,10,"load.start=(cat,(cfg.watch),\"dir1/*.torrent\"),\"d.directory.set=(cat,(cfg.download),/dir1)\""`

The only problem is that torrent does not start automatically, I need to use CTRL+S in order to start it.

**Comment by chros73** [comment]
> `schedule2 = watch_start_music,1,10,"load.start=(cat,(cfg.watch),\"dir1/*.torrent\"),\"d.directory.set=(cat,(cfg.download),/dir1)\""`

I just tried out the very same line (only modified the `dir1` and `cfg.*` entries) and it works as it should: it also starts the download.
Are your cfg entries valid?

**Comment by ymvunjq** [comment]
Yes my entries seem valid, it's maybe because I'm using rtorrent-ps with pyroscope (It should be the default configuration). I have to investigate a bit more :)

**Comment by chros73** [comment]
> it's maybe because I'm using rtorrent-ps with pyroscope

I'm using it as well :)

**Comment by ymvunjq** [comment]
Yeah I know, I have read your configuration :)

So I finally solved my problem and it was not really linked with rtorrent as you know :).

It was in fact because of rutorrent... rtorrent was not able to access rutorrent configuration file... (don't ask me why rtorrent needs to read rutorrent configuration file...). I successfully found the solution using the `log.execute` directive of rtorrent.rc file. The log was displaying a permission denied on that file.

Now everything works well, until the next problem :+1:

**Comment by pyroscope** [comment]
@ymvunjq please close this.

BTW, the more readable version of this is…
https://github.com/pyroscope/pyrocore/blob/master/src/pyrocore/data/config/rtorrent.d/categories.rc#L40

(add the d.directory.set command in addition to setting labels)

**Comment by 01100001** [comment]
@pyroscope @chros73  I believe [this is how it's to be done as per the new config](https://github.com/pyroscope/pimp-my-box/blob/master/roles/rtorrent-ps/templates/rtorrent/_rtlocal.rc#L10-L14)?

```
schedule2 = watch_start_music, 10, 10, ((load.start, (cat, (cfg.watch), "dir1/*.torrent")), (d.directory.set, (cat, (cfg.download), "dir1/")))
```

**Comment by chros73** [comment]
Yep, if it works ... :)

>Defining another constant is unnecessary clutter. 

Well, not [necessarily](https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent-config.rc#L69) :)

**Comment by 01100001** [comment]
Just updated my rtorrent instance after a while, and moving over to the new config. So I haven't tested it, yet. 🤔

> Defining another constant is unnecessary clutter.

I meant more like, "Defining another constant _when it's not necessary_ is unnecessary clutter." Was just a thought though, not advising or anything. 😅
