### ISSUE TITLE
How to download with magnet.

### ISSUE THREAD

**Issue by MrSorcus** [rakshasa/rtorrent#541]
I can't find any info about this.

**Comment by Pipfstarrd** [comment]
1. Launch rtorrent
2. Hit <Bcksp>
3. Paste magnet link
4. Hit <Enter>
5. ???
6. PROFIT

**Comment by DebugReport** [comment]
Thanks you. But why i can't find this info in wiki?

**Comment by Pipfstarrd** [comment]
I didn't find this info in wiki either, I've made a conclusion that this is a way of feeding rtorrent with magnets from `rtorrent -h`:

Main view keys:
  backspace         Add a torrent url or path

**Comment by chros73** [comment]
That's one way to do it.
Another way is to use a script that creates a fake torrent file that can be used with watch directories:
- from [ArchWiki](https://wiki.archlinux.org/index.php/RTorrent#Saving_magnet_links_as_torrent_files_in_watch_folder)
- and a [modified version](https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/bin/addMagnetLink.sh) with which you can select from multiple predefined watch directories

**Comment by DebugReport** [comment]
>Main view keys:
backspace Add a torrent url or path

It's not absolutely obviously...
Maybe change it? Like this:

>Main view keys:
backspace Add a torrent url (magnet) or path
