### ISSUE TITLE
Port listening not working with latest git

### ISSUE THREAD

**Issue by Elegant996** [rakshasa/rtorrent#543]
[settings.txt](https://github.com/rakshasa/rtorrent/files/690725/settings.txt)

I've compiled the latest commit from the feature-bind branch but I am not able to specify the port to listen on. rTorrent runs just fine but seems to ignore the setting. See attached (name changed for upload purposes).

The first line has no bearing on whether it works or not as both provide the same result. The port being chosen is in the default range rTorrent uses.

**Comment by xsmile** [comment]
Port listening does work, but it chooses to listen on port 6980 via IPv6 on all interfaces, instead of listening on a specified port on IPv4.

I suspect we have the same issue.

**Comment by TwoLeaves** [comment]
I have avoided upgrading rtorrent on my server because of this bug. For those who use a VPN with rtorrent, binding to a particular port is essential.

**Comment by rakshasa** [comment]
This will all be fixed in the feature-bind branch, however that is still work in progress.

**Comment by TwoLeaves** [comment]
Good to know thanks.

**Comment by chros73** [comment]
> Good to know thanks.

Well, have you tried the master branches? They should shouldn't be affected by this (only feature-bind branch).

**Comment by TwoLeaves** [comment]
I thought I was on master. I will give it a go, thank you.

**Comment by chros73** [comment]
This can be closed.

**Comment by Elegant996** [comment]
No, this issue still exists in feature-bind, it can be closed once feature-bind is released or at least the issue is corrected.

**Comment by sss123next** [comment]
https://github.com/rakshasa/libtorrent/blob/feature-bind/src/torrent/net/bind_manager.cc#L80

hardcoded port ....

**Comment by rakshasa** [comment]
Fixed.
