### ISSUE TITLE
command_ip.cc compile error:LOG_CONNECTION_FILTER is not a member of torrent

### ISSUE THREAD

**Issue by colinhd8** [rakshasa/rtorrent#544]
For the latest rtorrent & libtorrent source, there's a compile error :
command_ip.cc:234:16: error：‘LOG_CONNECTION_FILTER’ is not a member of ‘torrent’

It seems that 'LOG_CONNECTION_FILTER ' was not added to libtorrent\src\torrent\utils\log.h

**Comment by chros73** [comment]
It's a known issue, take a look at the [last comment](https://github.com/rakshasa/rtorrent/issues/525#issuecomment-271105025) of this issue .

**Comment by colinhd8** [comment]
Thank you, and sorry for make the duplicate issue.
