### ISSUE TITLE
Problem with the upload ratio

### ISSUE THREAD

**Issue by wenxhwork** [rakshasa/rtorrent#548]
Version 0.9.6 has ratio problem. The upload traffic and the ratio reported to the tracker are wrong sometimes,especially in some sites powered by NexusPHP.

Anyone has the same problem? And any patch to solve it?

**Comment by ErikZown** [comment]
Any solution for this???
I seem to have the same issue with rtorrent 0.9.6 sending wrong info to the tracker. Its not on every torrent but on the effected ones it usually dont report downloaded data and on a 6-7GB torrent it can say i've uploaded more than 500GB within a day (private tracker too, usually it can be 20-30GB a day with my seedbox). Thanks
