### ISSUE TITLE
check hash always checked/cant disable

### ISSUE THREAD

**Issue by ErikZown** [rakshasa/rtorrent#555]
Hello.

So this is an issue i've never had before.

Have an dedicated server with Ubuntu 16.04 (first time using that version of ubuntu) and have installed rtorrent (with rutorrent) and noticed an issue.
The "Check hash after download" in rutorrent settings is always checked, even if i uncheck it and press OK. 
rtorrent.rc have check_hash = no.

rutorrent can change/do other stuff in the settings except remove check hash option. 
same with rtorrent.rc, it reads everything else except check_hash.

I tried do some research but all i can find is an old issue from 2012 
https://github.com/rakshasa/rtorrent/issues/26

So maybe this issue is back?

Notice the last comment, seems the problem is not only me (know 2 others with same issue on other forum too)

Using the latest (well for now)
rtorrent: 0.9.6
libtorrent: 0.13.6

Thanks

UPDATE: Seems this is just a rutorrent issue where the checkbox in the settings for check hash is always checked. rtorrent.rc works fine with check_hash = no, it starts seeding a torrent directly after hitting 100%.
Thanks to Micdu70 for a better explaining about the issue :)

**Comment by Micdu70** [comment]
Hello @ErikZown 

I don't think that's the same issue. For me "check_hash = no" is properly working in rtorrent but ruTorrent, like you, doesn't seem to "read" the "check_hash" info of rtorrent. So it's a ruTorrent related issue to my mind.

I didn't find any function in ruTorrent source code to check this case...

**Comment by ErikZown** [comment]
Well thats right. I saw this issue from 2 others on another forum so i installed everything myself and noticed the checkbox for check hash is always checked.
But now when i added a torrent and got 100% it started seeding. 

So this issues wasnt as big as i though it was, thanks for the reply Micdu70!

**Comment by Micdu70** [comment]
I fixed this issue for ruTorrent / did a PR.

**Comment by ErikZown** [comment]
> I fixed this issue for ruTorrent / did a PR.

Thanks! The checkbox does no longer stay checked after your fix :)
