### ISSUE TITLE
event.download.finished script won't run, no log output

### ISSUE THREAD

**Issue by junkyhlm** [rakshasa/rtorrent#557]
I've been struggling for some days now with getting my script to run at `event.download.finished` but it won't run.

This code works as intended
```
# move command after finishded download
system.method.set_key = event.download.finished,move_complete,"d.set_directory=$d.get_custom1= ;execute=mv,-u,$d.get_base_path=,$d.get_custom1="
```

This one does not
```
# unrar or move files depending on if they are packed or not
system.method.set_key = event.download.finished,unrar_move_files,"execute={/home/holmen/script/rt_rsync_unrarall.sh,$d.get_base_path=,$d.get_name=,$d.get_custom1=}"
```
The script are working from the command line but not when rtorrent are supposed to run it. rtorrent are run by the same user (me) that created the script.
I can't find anything in the logfiles and don't know which `log.add_output` to use

**Comment by pyroscope** [comment]
It's `log.execute`.

**Comment by junkyhlm** [comment]
Thank you, my bad!
