### ISSUE TITLE
rTorrent 0.9.6/0.13.6 - Enabled debug logs, unable to truncate logs

### ISSUE THREAD

**Issue by deunanknute** [rakshasa/rtorrent#559]
Hello

I enabled debug logs. I tried to truncate the log file but it refreshes and restore back to the size it wasbefore truncation command as if nothing happened.  Tailing the log, while truncating it, it captures a message saying file being truncated, but that didn't happen.

Awesome piece of software engineering and thank you for developing it.

**Comment by rakshasa** [comment]
You can no close and reopen the log files to fix this.
