### ISSUE TITLE
Command "enable_trackers" does not exist

### ISSUE THREAD

**Issue by yermulnik** [rakshasa/rtorrent#570]
```
$> rtorrent
rtorrent: Error in option file: ~/.rtorrent.rc:12: Command "enable_trackers" does not exist.
$> fgrep enable_trackers ~/.rtorrent.rc
enable_trackers = no
$> rtorrent -h | head -1
Rakshasa's BitTorrent client version 0.9.6.
```
Is it something with installed version on my side or option misuse?
I want to find an approach to totally disable rtorrent during some periods of time.

**Comment by yermulnik** [comment]
Googled answer by myself: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=619207#10

**Comment by pyroscope** [comment]
Please close solved tickets.

**Comment by yermulnik** [comment]
Pardon me.

By the way, would be great if documentation is updated mentioning real options names =)
