### ISSUE TITLE
Session warning with relative session path

### ISSUE THREAD

**Issue by DominicMe** [rakshasa/rtorrent#572]
It seems like a relative path doesn't work  in the config file and produces **rutracker_check: Plugin will not work. Webserver user must have execute access to the rtorrent session directory (./.session/).** warning.

What is the **./** relative to? It doesn't seem to be relative to the Default directory path setting. Entering the Default directory path with the /.session appended in the session option works fine. It also appears to create lock and cache files with relative session path but warning is still displayed.

**Comment by pyroscope** [comment]
just use an absolute path, or `system.cwd.set`

**Comment by DominicMe** [comment]
How is this a solution? Clearly I already knew I could use an absolute path. This is a pretty silly bug to have especially since it is implied in the config comments that a relative path should be used.

**Comment by kannibalox** [comment]
Is the session directory working correctly in rtorrent? If so, this isn't a rtorrent bug and should be brought up on rutorrent's help channels. I can tell you that rtorrent's current working directory will not be the same as rutorrent's working directory unless you specifically made changes for it to be so. Using an absolute path as mentioned above will avoid the need for that kind of jankiness.

**Comment by DominicMe** [comment]
If by session directory you mean the default value of ("./" if i'm not mistaken) then no it doesn't work. I had to manually set it to an absolute path. Directory path also  had to be set otherwise torretns would not add properly. Note I am using rtorrent with -n option and setting custom config path in case that matters. Maybe just the comments should be changed, because the way it is  now it seems like it's intentionally misleading.

**Comment by kannibalox** [comment]
> no it doesn't work

According to your first post ("It also appears to create lock and cache files with relative session path but warning is still displayed."), it sounds like rtorrent is working just fine with relative paths, which makes this a rutorrent issue and more appropriate for the rutorrent repository: https://github.com/Novik/ruTorrent. It sounds like the error message was clear enough that you were able to figure out the problem pretty quickly though, it's probably a design limitation of that specific plugin.

> Maybe just the comments should be changed, because the way it is now it seems like it's intentionally misleading.

I highly doubt those comments were added maliciously, but feel free to open a PR.

**Comment by chros73** [comment]
> Note I am using rtorrent with -n option and setting custom config path in case that matters. 

I don't think that matters. But it's always a good practice to use absolute paths.

**Comment by DominicMe** [comment]
It is not ruTorrent issue as the error is from rTorrent itself. I can see it in the logs and not just in the ruTorrent GUI. Maybe it's a false positive since the lock/session files are created but that's till a bug.
