### ISSUE TITLE
Move completed downloads redownloads torrent when rTorrent is restarted

### ISSUE THREAD

**Issue by ratio187** [rakshasa/rtorrent#573]
Here's how I am trying to have rTorrent with ruTorrent setup.

Directory for downloads in progress:
`~/downloads/Downloading/torrent_name`

Directory for completed/seeding downloads:
`~/downloads/Seeding/label_name/torrent_name`

I have AutoTools disabled in ruTorrent so it won't interfere with what I have in `.rtorrent.rc`. Here is what I have in that file for moving completed downloads:

```sh
method.insert = d.get_finished_dir,simple,"cat=/home6/**username**/downloads/Seeding/,$d.get_custom1="

method.set_key = event.download.finished,move_complete,"d.set_directory=$d.get_finished_dir=;execute=mkdir,-p,$d.get_finished_dir=;execute=mv,-u,$d.get_base_path=,$d.get_finished_dir="
```

This correctly gets the label from ruTorrent and moves the torrent data into a directory corresponding to the label inside of the the Seeding directory when the download finishes. All is well until rTorrent is restarted, and then the torrent is redownloaded into `~/downloads/Downloading/` directory.

When I look at the torrent's corresponding `<hash>.torrent.rtrorrent` file after the download is completed and moved, that file still shows `~/downloads/Downloading/` for the directory. So from what I can tell this is why the torrent redownloads on restart. As I am fairly new to rtorrent I don't really understand why `d.set_directory=$d.get_finished_dir=` does not update the `.rtorrent` file but the torrent still seeds/works normally after it's moved.

I did a test and when using AutoTools in ruTorrent the directory in the `torrent.rtorrent` file gets updated after the torrent is completed and moved. So maybe this is a permissions issue where updating the directory from a script in `.rtorrent.rc` is not letting it write the `.torrent.rtorrent` file? 

Any help is greatly appreciated!

**Comment by pyroscope** [comment]
Add ``d.save_full_session`` to the end of your event handler.

**Comment by ratio187** [comment]
@pyroscope thanks for the help!

So should it look like 1 or 2? 2 has equal sign on the end.

1:
`method.set_key = event.download.finished,move_complete,"d.set_directory=$d.get_finished_dir=;execute=mkdir,-p,$d.get_finished_dir=;execute=mv,-u,$d.get_base_path=,$d.get_finished_dir=;d.save_full_session"`


2:
`method.set_key = event.download.finished,move_complete,"d.set_directory=$d.get_finished_dir=;execute=mkdir,-p,$d.get_finished_dir=;execute=mv,-u,$d.get_base_path=,$d.get_finished_dir=;d.save_full_session="`

**Comment by chros73** [comment]
2.
But Maybe it's not so easy, you'll see.

**Comment by ratio187** [comment]
Thanks @pyroscope & @chros73. Adding the `d.save_full_session=` updates the directory in the `.torrent.rtorrent` file and the torrent is not redownloaded.

There is still one abnormal thing that happens that I would like to fix if possible. When rtorrent is restarted the completed torrent will show up as "downloading" again instead of completed. It doesn't actually redownload the torrent though since the `.rtorrent` file is pointed at the correct directory now, so it just does a recheck and moves back to the "completed" downloads. Is there another command I need to add to make it not show up in the downloads section again?

**Comment by ratio187** [comment]
I think it's working properly now. It will eventually not show up in downloading on restart if I let enough time go by before the restart.

**Comment by xxx31fr** [comment]
@ratio187 Hello,
I just came to your issue you get.
I would like to do the same.
Could you, please, detail me how to use the following code
`method.set_key = event.download.finished,move_complete,"d.set_directory=$d.get_finished_dir=;execute=mkdir,-p,$d.get_finished_dir=;execute=mv,-u,$d.get_base_path=,$d.get_finished_dir=;d.save_full_session="`

I don't understand how to use it in my .rtorrent.rc

Thank you for your help

**Comment by ratio187** [comment]
@xxx31fr I just have this at the bottom of my `.rtorrent.rc` file:

```
method.insert = d.get_finished_dir,simple,"cat=~/downloads/Seeding/,$d.get_custom1="
method.insert = d.update_dir,simple,"d.set_directory=$d.get_finished_dir="
method.insert = d.move_torrent_data,simple,"execute=mkdir,-p,$d.get_finished_dir=;execute=mv,-f,$d.get_base_path=,$d.get_finished_dir=;"
method.set_key = event.download.finished,move_complete,"d.update_dir=;d.move_torrent_data=;d.save_full_session=;execute=~/scripts/post_process.sh,$d.get_custom1=,$d.get_finished_dir=,$d.get_name=,$d.directory=,$d.base_filename="
```

You'll have to change the directories in the 2 places I have them in the code above (they start with ~) to match your setup.
