### ISSUE TITLE
make fails due to "command_network.cc:51:38: fatal error: torrent/net/bind_manager.h: No such file or directory"

### ISSUE THREAD

**Issue by krichter722** [rakshasa/rtorrent#577]
After installation of `libtorrent` 0.13.4-176-gc167c5a with `./autogen.sh && ./configure && make && sudo make install` in a clean source root, `./autogen.sh && ./configure && make` for `rtorrent` 0.9.4-195-gb90e27c fails due to `command_network.cc:51:38: fatal error: torrent/net/bind_manager.h: No such file or directory` on Ubuntu 16.10. Find the complete build log at https://richtercloud.de:451/index.php/s/IahcboI9dGmlKxj.

I'm assuming that the issue that only the feature-bind branch compiles is resolved since master builds correctly on travis.ci.org.

**Comment by rakshasa** [comment]
Old version.

**Comment by krichter722** [comment]
Both versions are referring to HEAD of master. Afaik no newer version can exist. Please elaborate.

**Comment by rakshasa** [comment]
226e670decf92e7adaa845a6982aca4f164ea740 is the rtorrent HEAD you should compile against.
