### ISSUE TITLE
Event.download.finished or hash_done not firing on completion

### ISSUE THREAD

**Issue by madcatsu** [rakshasa/rtorrent#579]
My rtorrent.rc (borrowing example from [https://wiki.archlinux.org/index.php/RTorrent#Manage_completed_files](https://wiki.archlinux.org/index.php/RTorrent#Manage_completed_files) )

```
schedule2 = watch_dir_multimedia,5,15,"load_start=/data/watch/multimedia/*.torrent,d.directory.set=/data/incoming/multimedia,d.custom1.set=multimedia,d.custom3.set=/data/complete/multimedia"

########################################### Fixes ###########################################
# Workaround for getting torrent data path
method.insert = d.get_data_full_path,simple,"branch=((d.is_multi_file)),((cat,(d.directory))),((cat,(d.directory),/,(d.name)))"
########################################### Fixes ###########################################

# Function: Check whether torrent is in the completed folder location, returns true if false
method.insert = checkdirs,simple,"not=\"$equal={d.custom3=,d.get_data_full_path=}\""

# Function: Check torrent is complete, not yet moved and has a completion path specified
method.insert = movecheck,simple,"and={checkdirs=,d.complete=,d.custom3=}"

# Function: Move torrent to specified complete folder and reload to update rTorrent with new location
# Sets new path to value of custom3, moves torrent to location specified in custom3 and restarts torrent for seeding
method.insert = movetorrent,simple,"d.directory.set=$d.custom3=;execute=mv,-f,$d.get_data_full_path=,$d.custom3=;d.custom3.set=;d.stop=;d.start="

# Event: On torrent completion, check torrent location and move _if_ not in seeding location
method.set_key = event.download.finished,move_complete,"branch={$movecheck=,movetorrent=}"
```

From rtorrent.log (with debug level set):
```
1489374350 I handshake_manager->176.9.103.37: Handshake success.
1489374350 I Download unchoked slots adjust; currently:0 adjust:1
1489374350 I Download unchoked slots adjust; currently:1 adjust:1
1489374351 I Download unchoked slots adjust; currently:2 adjust:1
1489374351 I Download unchoked slots adjust; currently:3 adjust:1
1489374358 I 49D7FCEDA406793318F7E08820BC77D6FCE521E7->tracker_controller: Start requesting.
1489374398 I Download unchoked slots adjust; currently:4 adjust:-1
1489374398 I Download unchoked slots adjust; currently:3 adjust:-1
1489374398 I Download unchoked slots adjust; currently:2 adjust:-1
1489374398 I Download unchoked slots adjust; currently:1 adjust:-1
1489374398 I 49D7FCEDA406793318F7E08820BC77D6FCE521E7->download_list: Received finished.
1489374398 I 49D7FCEDA406793318F7E08820BC77D6FCE521E7->download_list: Confirming finished.
1489374398 I 49D7FCEDA406793318F7E08820BC77D6FCE521E7->tracker_controller: Sending completed event.
1489374398 I 49D7FCEDA406793318F7E08820BC77D6FCE521E7->tracker_list: Sending 'completed' to group:0 url:'https://_*redacted*_/announce'.
1489374400 I 49D7FCEDA406793318F7E08820BC77D6FCE521E7->tracker_list: Received 0 peers from tracker url:'https://https://_*redacted*_/announce/announce'.
1489374410 I 49D7FCEDA406793318F7E08820BC77D6FCE521E7->tracker_controller: Start requesting.
```

My directory structure is pretty simple for my needs, and eventually I'd like to both move files into the completed folder and then execute an additional shell script to unpack compressed files. Checking my folder tree after the download finishes, I can see files remain in my /data/incoming/multimedia folder

Any ideas why the event isn't firing on completion?

**Comment by madcatsu** [comment]
Environment info:
OS: Alpine Linux x86_64
rtorrent version: 0.9.6 compiled from source with xmlrpc-c
libtorrent version: 0.13.6 compiled from source

**Comment by pyroscope** [comment]
method.set_key = event.download.finished, aaa,\
        "print=\"COMPLETED \",$d.name=,\" - \",$d.custom3=,\" [\",$convert.date=$system.time=,\"]\""

Add that, see what happens.

**Comment by madcatsu** [comment]
Nothing noted in rtorrent.log after updating the rtorrent.rc file

rTorrent is being called by:
```
screen -D -m -S \
	rtorrent s6-setuidgid abc /usr/local/bin/rtorrent \
	-n -o import=/config/rtorrent/rtorrent.rc
```
FWIW, this is inside a Docker container running s6-overlay

**Comment by brendanmeyer** [comment]
Hi, was this ever solved?

**Comment by joshuajbrunner** [comment]
Same here.
Running a modified version of @binhex arch-rtorrentvpn docker image. rTorrent is 0.9.6 from the Arch User Repo. Nothing fires after download.finished or download.hash_done

Did figure anything out yet @madcatsu / @pyroscope ?

**Comment by madcatsu** [comment]
@joshuajbrunner no update sorry, wasn't able to resolve this

**Comment by joshuajbrunner** [comment]
@madcatsu 

I just got it to work somehow... the syntax is very touchy it seems and the documentation on it isn't very good, especially between the new and old conventions. Wish there was a good way to debug this stuff

Here is what I got working. Just something simple. Fire off a script when the download finished, passing the base path, name, and custom1 to the script

`method.set_key=event.download.finished,filebot,"execute.throw.bg={/home/nobody/postdl.sh,$d.base_path=,$d.name=,$d.custom1=}"`

**Comment by pyroscope** [comment]
It's absolutely possible to get to a terminal, see https://rtorrent-ps.readthedocs.io/en/latest/overview.html#launching-a-demo-in-docker

The assumption that events don't fire is just wrong, the handler's code simply fails. Putting stuff into a bash script where you have documented syntax is a good idea.

**Comment by kannibalox** [comment]
> Wish there was a good way to debug this stuff

Try using the log.execute command: http://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-log-execute

**Comment by joshuajbrunner** [comment]
@pyroscope @kannibalox Thank you! I will check both of those out.
