### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by Pingblue** [rakshasa/rtorrent#580]
Having an issue with rtorrent using 100% CPU in Debian 8 fresh install.

Restarting rtorrent resolves the issue for a few hours, can anyone give any pointers as to where the problem might be?

curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP

**Comment by chros73** [comment]
Maybe [this](https://github.com/rakshasa/rtorrent/issues/535) can help (or the linked issues in it).

**Comment by ncla** [comment]
I have same issue, about 100 active torrents, after a minute of them being active the rTorrent shits the CPU to 100% usage and the OS becomes unresponsive. Same setup as yours, Debian 8 and curl is 7.38.0. Used quickbox.io install script to set-up my seedbox.

**Comment by rakshasa** [comment]
The rest of the system should not become unresponsive if there's a bug in rtorrent, so it's likely an issue with the kernel being triggered.

**Comment by Pingblue** [comment]
The 100% usage has appeared with only running 10 torrents and no https trackers, I cannot really see any pattern but at no point does the server become unresponsive.

%Cpu(s):  8.8 us, 12.9 sy,  0.6 ni, 66.0 id, 10.2 wa,  0.0 hi,  1.5 si,  0.0 st
KiB Mem:  26457289+total, 26380195+used,   770936 free,  1668252 buffers
KiB Swap: 48891900 total, 10569928 used, 38321972 free. 24620652+cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2989 ****      20   0 2787652 147212  54720 R 100.2  0.1 406:46.97 rtorrent main
  523 ****      20   0 2783312 114036  40004 R  99.9  0.0 310:52.15 rtorrent main

What's the best way to debug and fine the cause?

**Comment by qwerty2586** [comment]
We had similar issue lately with fresh installation of server. After few hours of reinstalling we figured out that our RAID-5 is still building parity and every access to partition generating huge CPU load.

**Comment by omegadrh** [comment]
I'm sorry for double-posting, but I realized I posted my initial response on #535, which is closed, so I figured it might be beneficial to post on this issue that's still open.

...

I also started encountering this recently on a Debian testing amd64 box. I don't know if it coincided with an update to libcurl, but I know it coincided with an update from kernel 4.11 to 4.12.

Checking strace on rtorrent, during times of spiked CPU use, the system is pounded with `epoll_wait(... {EPOLLOUT, ...}, ...)` calls; the return value (number of available fds) seems to always equal the number of fds in the `struct epoll_events* events`, which appears to correspond to the number of 'handshake' sockets shown in the UI ([S **7**/34/768]). (There have been a few occasions where handshakes is zero, and CPU use also drops.)

I'm not a kernel hacker, but I'm slightly suspicious of work on epoll that went into 4.12, like [epoll: Add busy poll support to epoll with socket fds.](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bf3b9f6372c45b0fbf24d86b8794910d20170017)

I should also note that the `epoll_wait(...)` calls appear to be happening roughly 1-5 times per second, based on the timeout value, e.g.:

```
epoll_wait(7, [{EPOLLOUT, {u32=152, u64=152}}, ..., 1024, 781) = 15
epoll_wait(7, [{EPOLLOUT, {u32=152, u64=152}}, ..., 1024, 780) = 15
epoll_wait(7, [{EPOLLOUT, {u32=152, u64=152}}, ..., 1024, 779) = 15
epoll_wait(7, [{EPOLLOUT, {u32=152, u64=152}}, ..., 1024, 779) = 15
epoll_wait(7, [{EPOLLOUT, {u32=152, u64=152}}, ..., 1024, 779) = 15
epoll_wait(7, [{EPOLLOUT, {u32=152, u64=152}}, ..., 1024, 779) = 15
epoll_wait(7, [{EPOLLOUT, {u32=152, u64=152}}, ..., 1024, 779) = 15
epoll_wait(7, [{EPOLLOUT, {u32=152, u64=152}}, ..., 1024, 778) = 15
epoll_wait(7, [{EPOLLOUT, {u32=152, u64=152}}, ..., 1024, 778) = 15
```

**Comment by rakshasa** [comment]
To have epoll_wait being called 1-5 times per seconds is not a lot, so wouldn't call that the system being 'pounded'.

https://github.com/rakshasa/rtorrent/wiki/LOG-Logging

Set up a single log file, then add event outputs to it. You could perhaps find out where it is happening.

The connection* events would be particularly interesting.

**Comment by omegadrh** [comment]
Hah! Oops. I meant per *mili*second.
```[pid  4832] 12:05:30.060866 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 196) = 2
[pid  4832] 12:05:30.060993 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 195) = 2
[pid  4832] 12:05:30.061121 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 195) = 2
[pid  4832] 12:05:30.061249 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 195) = 2
[pid  4832] 12:05:30.061387 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 195) = 2
[pid  4832] 12:05:30.061515 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 195) = 2
[pid  4832] 12:05:30.061647 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 195) = 2
[pid  4832] 12:05:30.061816 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 195) = 2
[pid  4832] 12:05:30.061942 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 195) = 2
[pid  4832] 12:05:30.062066 epoll_wait(7, [{EPOLLOUT, {u32=150, u64=150}}, {EPOLLOUT, {u32=153, u64=153}}], 1024, 194) = 2
```
In 2.509 seconds of real time, strace logged 8308 `epoll_wait` calls (dwarfing the next highest, 769 calls to `sendto`); this averages 3.32 `epoll_wait` calls per milisecond, consistent with my 1-5 times per [mili]second estimate.

I briefly tried setting up logging, but I'm not entirely sure I'm capturing the desired output. `log.add_output = "connection", "rtorrent.log"` and various other permutations give me "Input failed: Invalid option name.", but I did eventually coax message like this from the logs (probably with `connection_debug`?):
```1503682528 I handshake_manager->{ip address}: Handshake success.
1503682536 I handshake_manager->{ip address}: Handshake success.
1503682537 I handshake_manager->{ip address}: Adding incoming connection: fd:187.
1503682538 I handshake_manager->{ip address}: Handshake success.
1503682550 I handshake_manager->{ip address}: Received error: message:7 network unreachable.
1503682550 I handshake_manager->{ip address}: Received error: message:7 network unreachable.
1503682550 I handshake_manager->{ip address}: Received error: message:7 network unreachable.
1503682550 I handshake_manager->{ip address}: Received error: message:7 network unreachable.
1503682554 I handshake_manager->{ip address}: Received error: message:7 network unreachable.
1503682559 I handshake_manager->{ip address}: Received error: message:7 network unreachable.
1503682559 I handshake_manager->{ip address}: Received error: message:7 network unreachable.
1503682560 I handshake_manager->{ip address}: Adding outcoming connection: encryption:13 message:3.
1503682560 I handshake_manager->{ip address}: Adding outcoming connection: encryption:13 message:3.
1503682560 I handshake_manager->{ip address}: Received error: message:7 network error.
1503682561 I handshake_manager->{ip address}: Received error: message:7 network error.
1503682569 I handshake_manager->{ip address}: Received error: message:7 network unreachable.
1503682574 I handshake_manager->{ip address}: Received error: message:7 network unreachable.
1503682582 I handshake_manager->{ip address}: Adding incoming connection: fd:177.
```
In any event, I'm not seeing any log messages coming through 3000 times per second (somewhat thankfully).

**Comment by rakshasa** [comment]
It sounds like some sockets aren't being fully exhausted before a new poll is done. This sounds suspiciously like the previous curl-related issues.

Could you do logging with 'socket_debug' on?

**Comment by omegadrh** [comment]
Here's some socket_debug log excerpt (more in attachment):
```1504098552 D epoll->curl(162): Open event.
1504098552 D epoll->curl(162): Insert error.
1504098552 D epoll->curl(162): Modify event: op:1 mask:8.
1504098552 D epoll->curl(162): Insert read.
1504098552 D epoll->curl(162): Modify event: op:3 mask:9.
1504098552 D epoll->curl(162): Remove write.
1504098552 D epoll->curl(162): Closed event.
1504098552 D epoll->handshake(162): Open event.
1504098552 D epoll->handshake(162): Insert write.
1504098552 D epoll->handshake(162): Modify event: op:1 mask:4.
1504098552 D epoll->handshake(162): Insert error.
1504098552 D epoll->handshake(162): Modify event: op:3 mask:c.
1504098552 D epoll->handshake(185): Open event.
1504098552 D epoll->handshake(185): Insert write.
1504098552 D epoll->handshake(185): Modify event: op:1 mask:4.
1504098552 D epoll->handshake(185): Insert error.
1504098552 D epoll->handshake(185): Modify event: op:3 mask:c.
1504098552 D epoll->curl(189): Open event.
1504098552 D epoll->curl(189): Insert error.
```

[rtorrent.log.socket_debug.zip](https://github.com/rakshasa/rtorrent/files/1264428/rtorrent.log.socket_debug.zip)

**Comment by omegadrh** [comment]
For what it's worth, here's the top entry from `perf report`:
```-   78.92%     0.00%  rtorrent main  [unknown]             [k] 0xffffffffffffffff
   - 0xffffffffffffffff
      - 78.92% _start
           __libc_start_main
         - main
            - 78.92% torrent::thread_base::event_loop
               - 62.50% torrent::PollEPoll::do_poll
                  - 55.47% torrent::PollEPoll::poll
                     - epoll_wait
                        - 53.12% system_call_fast_compare_end
                           - 50.78% sys_epoll_wait
                              + 16.40% ep_poll
                              + 12.09% nmi_handle
                              + 11.11% finish_task_switch
                              + 4.68% _copy_to_user
                              + 4.13% new_sync_read
                              + 2.35% __sched_text_start
                    2.35% torrent::PollEPoll::perform
                    2.34% pthread_mutex_lock
               + 11.72% std::tr1::_Function_handler<void (), std::tr1::_Bind<void (*())()> >::_M_invoke
                 2.34% 0x29a82
```
(Recorded with `sudo perf record -F 100 --proc-map-timeout 2000 -p $(pidof rtorrent) -g --call-graph dwarf --vmlinux=/usr/lib/debug/vmlinux-4.12.0-1-amd64 -- sleep 30` .)

I can provide a perf data file, or some other diagnostic, if you'd like, or rebuild with some new log message added if you point me to the line(s) you'd like.

**Comment by omegadrh** [comment]
As [pointed to](https://github.com/rakshasa/rtorrent/issues/635#issuecomment-325183445) in issue #635 by @Micdu70, curl/curl@74dac34 _appears_ to have completely resolved the issue for me.

I applied _only_ that patch on top of the current Debian testing curl source (7.55.0-1), built/installed libcurl3 (`DEB_BUILD_OPTIONS="nostrip noopt" fakeroot dpkg-buildpackage -b` ... `sudo dpkg -i ../libcurl3_7.55...`), and restarted rtorrent. CPU use is down in single digits, and the abundant tracker timeouts I'd seen recently are absent. I'll admit to being too lazy so far to verify that reversing the patch, and then rebuilding with the same method reintroduces the problem, though.

**Comment by ayoooooooo** [comment]
I'm having the same issue with 100% CPU usage on Gentoo using curl 7.64 with OpenSSL & c-ares. 

```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.0.2r zlib/1.2.11 c-ares/1.13.0
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy
```

Like omega, I checked strace and I'm getting about 5 epoll_wait events every 200 microseconds. I've seen many people have issues with this that were fixed when recompiling curl with OpenSSL, but that hasn't solved it for me.

**Comment by ayoooooooo** [comment]
Upgrading to Gentoo's (currently unstable) curl 7.64.1 fixed this for me, and CPU usage is now at 0%.

**Comment by jay** [comment]
> Upgrading to Gentoo's (currently unstable) curl 7.64.1 fixed this for me, and CPU usage is now at 0%.

There was a regression and curl/curl@4015fae (in 7.64.1) should have fixed it.

**Comment by omegadrh** [comment]
Thanks @jay! I can confirm that cherry-picking that commit on top of Debian 10 (Buster)'s currently packaged libcurl4 (7.64.0-2) [re-]fixed this issue for me.
