### ISSUE TITLE
Opening the wiki to git access by contributors?

### ISSUE THREAD

**Issue by pyroscope** [rakshasa/rtorrent#581]
It would make refactoring & extending the wiki a lot easier if we could change it via git, but it seems that needs contributor status to the project, even with public editing enabled. Can you imagine to add a few people as contributors for that purpose?

The main **code** branches can be protected against direct pushes in the project settings, so that should be no issue. Not sure though if that protection also affects you as the owner. An alternative would be to put the wiki into its own project, with the option to then publish a static version (with each release) to GH pages.

Anyway, I made a list of people with >= 10 edits:

     13 Author: aksr <aksr@users.noreply.github.com>
     20 Author: Speeddymon <Speeddymon@gmail.com>
     38 Author: Jari Sundell <sundell.software@gmail.com>
     41 Author: chros73 <chros73@gmail.com>
     67 Author: PyroScope Project <pyroscope.project@gmail.com>

**Comment by rakshasa** [comment]
http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

The above seems like a possible solution.
