### ISSUE TITLE
Is there a way to seed via tor or vpn/proxy?

### ISSUE THREAD

**Issue by scriptzteam** [rakshasa/rtorrent#584]
Is there a way to seed via tor or vpn/proxy?

I am on private torrent tracker so any idea how? thx!

**Comment by chros73** [comment]
leycec wrote a [wiki page](https://github.com/rakshasa/rtorrent/wiki/Tor-based-Proxying-Guide) about this.

**Comment by scriptzteam** [comment]
The problem is connection with tor/vpn is all encrypted and dunno if torrent tracker can read the data ;) so asking, does this works for anyone who SEED?

**Comment by chros73** [comment]
Personally I never used this.
What I used just a short amount of time was routing only tracker requests (http) but not peer communication via tor network (my isp screwed up something with only 1 domain) and it worked. (I used a headless setup, that is slightly different than on the wiki page.)
