### ISSUE TITLE
Hash check on download completion found bad chunks, consider using "safe_sync"

### ISSUE THREAD

**Issue by JanSimek** [rakshasa/rtorrent#585]
When I start downloading torrents with rtorrent, I get these messages in journalctl:

```bře 26 12:59:42 simserver kernel: attempt to access beyond end of device
bře 26 12:59:42 localhost kernel: sdc1: rw=1, want=3884075360, limit=3710935453
bře 26 12:59:42 localhost kernel: attempt to access beyond end of device
bře 26 12:59:42 localhost kernel: sdc1: rw=1, want=3884077408, limit=3710935453
bře 26 12:59:42 localhost kernel: attempt to access beyond end of device
bře 26 12:59:42 localhost kernel: sdc1: rw=1, want=3884079104, limit=3710935453
bře 26 12:59:42 localhost kernel: attempt to access beyond end of device
bře 26 12:59:42 localhost kernel: sdc1: rw=1, want=3884083200, limit=3710935453
bře 26 12:59:42 localhost kernel: attempt to access beyond end of device
bře 26 12:59:42 localhost kernel: sdc1: rw=1, want=3884085248, limit=3710935453
bře 26 12:59:42 localhost kernel: attempt to access beyond end of device
bře 26 12:59:46 localhost kernel: btrfs_dev_stat_print_on_error: 18 callbacks suppressed
bře 26 12:59:46 localhost kernel: BTRFS error (device sdc1): bdev /dev/sdc1 errs: wr 1525345, rd 813, flush 0, corrupt 0, gen 0
bře 26 12:59:46 localhost kernel: attempt to access beyond end of device
bře 26 12:59:46 localhost kernel: sdc1: rw=1, want=3861230848, limit=3710935453
bře 26 12:59:46 localhost kernel: BTRFS error (device sdc1): bdev /dev/sdc1 errs: wr 1525346, rd 813, flush 0, corrupt 0, gen 0
bře 26 12:59:46 localhost kernel: attempt to access beyond end of device
bře 26 12:59:46 localhost kernel: sdc1: rw=1, want=3861231744, limit=3710935453
bře 26 12:59:46 localhost kernel: BTRFS error (device sdc1): bdev /dev/sdc1 errs: wr 1525347, rd 813, flush 0, corrupt 0, gen 0
```

Torrent download usually fails with the message:

**Inactive: Hash check on download completion found bad chunks, consider using "safe_sync".**

but when I add```safe_sync = yes``` to rtorrent.rc, rtorrent doesn't start because it doesn't recognize the command.

I ran ```btrfs check --repair /dev/sdc1``` which repaired some errors, but when I start rtorrent, the whole process starts over. Running ```smartctl -t short /dev/sdc``` found no HDD errors.

Arch linux, rtorrent 0.9.6

**Comment by pyroscope** [comment]
Diagnostics w/o a config doesn't work. Plus info about the metafile in question, like the data size.

**Comment by JanSimek** [comment]
This is my [rtorrent.rc configuration](https://gist.github.com/JanSimek/60efb61ced18d198de0fc3d90df83439)

[Here is an example torrent that fails](https://downloads.raspberrypi.org/raspbian_latest.torrent)

**Comment by chros73** [comment]
> but when I add `safe_sync = yes` to rtorrent.rc, rtorrent doesn't start

Name of the command is changed, use: `pieces.sync.always_safe.set=1`
I can't help with the other problems, since I don't have these using ext4 on Ubuntu 14.04.

**Comment by pyroscope** [comment]
Arch linux, rtorrent 0.9.6

**Comment by JanSimek** [comment]
Thank you @chros73. After adding the above setting to rtorrent.rc I don't get the hash check failed error anymore, but torrents just stop at various stages of completion with the status "Inactive:" and no other message. I enabled logging:

```
log.open_file = "rtorrent.log", (cat,/tmp/rtorrent.log.,(system.pid))  

log.add_output = "info", "rtorrent.log"
log.add_output = "warn", "rtorrent.log"
log.add_output = "error", "rtorrent.log"
log.add_output = "critical", "rtorrent.log"
log.add_output = "notice", "rtorrent.log"
log.add_output = "debug", "rtorrent.log"

```
and the log file is full of these messages:

```
1490629551 I handshake_manager->255.255.255.255: Adding incoming connection: fd:15.
1490629551 I handshake_manager->255.255.255.255: Received error: message:6 unknown download.
``` 
(I replaced the real ip address with 255.255.255.255)

**Comment by JanSimek** [comment]
I switched from rtorrent to Transmission and so far not a single issue, so there is definitely something wrong with rtorrent.

**Comment by rakshasa** [comment]
The way rTorrent and Transmission do file and network stuff is very different, and my client has exposed more than a few kernel bugs.

So when there are weird issues that only seem to happen for certain combinations of kernel versions and file systems, etc, I've learned to be a bit skeptic. This smells of a filesystem+mmap issue.

**Comment by johnhamelink** [comment]
I had a very similar issue to this by having a file open in OSX when creating a torrent in transmission, "scp"ing the torrent's contents into a server and then attempting to seed the torrent with rtorrent on said server.

**Comment by runderwo** [comment]
bře 26 12:59:42 localhost kernel: sdc1: rw=1, want=3884075360, limit=3710935453
bře 26 12:59:42 localhost kernel: attempt to access beyond end of device

Are you sure the partition is sized appropriately for the block device containing it?  This "attempt to access beyond end of device" often happens if a partition is cloned from another disk with the same nominal size (in this case, 2 TiB) but a differing (less) total block count.

**Comment by JanSimek** [comment]
It started happening with transmission as well, so this is not an rtorrent issue. I think you are right @runderwo

**Comment by JanSimek** [comment]
Just in case someone stumbles upon this issue, I have reformatted the partition to EXT4 and it works flawlessly.

**Comment by darachm** [comment]
I had this problem with a btrfs file-system. Also happened with transmission. Alternative solution: I was able to make a RAM-disk, torrent into there, then copy the file to hard-disk.

**Comment by oyvindsaether** [comment]
I've been using rtorrent happily for years and years and after installing fedora on a box with it's now default btrfs file system I got this fine message:

Inactive: Hash check on download completion found bad chunks, consider using "safe_sync".

I've never had any such issue before using rtorrent on a box with btrfs file system.

It's probably a btrfs issue and not a rtorrent issue. one could argue that rtorrent is a bit more aggressive (efficient) than the rest of them (which is why it's great) - but that isn't really a valid excuse for btrfs not handling whatever rtorrent does when it works just fine with other file systems that I've used it on over the years (ext4, xfs, probably reiserfs ages ago)

**Comment by adambarta** [comment]
This turned out to be a DRAM issue in my case. Used memtest86+ to identify the bad sodimm then added memmap=4K$0x0BADPAGE to reserve the memory so the kernel wont allocate it. If choosing to use the dimms in a dual configuration be aware of address interleaving etc.
