### ISSUE TITLE
wishlist: new release?

### ISSUE THREAD

**Issue by legrostdg** [rakshasa/rtorrent#586]
rtorrent HEAD contains interesting changes since 0.9.6. It would be great to have a new release!

**Comment by rakshasa** [comment]
New release will happen once feature-bind is merged.

**Comment by chros73** [comment]
> New release will happen once feature-bind is merged

It would be nice if you'd take the time to clean all the pending pull requests first:
- by merging / rejecting them
  - probably it would take another month but I'm sure we can help you with quickly modifing anything in them if something comes up
- it helps You and us, later, who try to make rtorrent even better
- it has to be done once anyway :)

And I only hope that the new release finally will be based on master branches, if there's nothing against it.

Cheers

**Comment by rakshasa** [comment]
The pull requests will also be handled after feature-bind, don't worry I haven't forgotten about them.

**Comment by pyroscope** [comment]
Right now, you're not getting the PRs you could get because of the mounting risk of merge conflicts. Nobody likes to rework their PRs for that.

**Comment by rakshasa** [comment]
If there's merge conflicts or, as sometimes happens, there's details I want to change I have no issue with fixing those myself.
