### ISSUE TITLE
Full IPv6 Support

### ISSUE THREAD

**Issue by ghost** [rakshasa/rtorrent#59]
This ticket has been open for 4 years (!) now, with no progress in the main rtorrent branch: http://libtorrent.rakshasa.no/ticket/1111

IPv6 is very real, and very much in production. Comcast, KDDI, Time Warner Cable, Free Telecom, etc... are all deploying IPv6 for their customers starting now: http://www.worldipv6launch.org/

If rtorrent does not support IPv6, there is a good chance that in the near future peers/seeds from major ISP's will be unreachable due to Carrier Grade NAT: http://iepg.org/2012-03-ietf83/IPv6%20Critical%20Mass%20and%20Avoiding%20CGN.pdf

IPv6 support is now an IETF BCP: http://tools.ietf.org/html/rfc6540

All major server providers support IPv6: OVH, LeaseWeb, SoftLayer, FDCServers, NForce, Swiftway, etc... 
All other major torrent clients support IPv6: uTorrent, Deluge, QBittorrent, and Transmission.

**Comment by rvalles** [comment]
IPv6 with IPv4 NAT in the ISP is very real and crippling.

How's IPv6 support coming along?

**Comment by rakshasa** [comment]
Merged.

**Comment by bernhardschmidt** [comment]
@rakshasa Any chance to make a release with this patch soon? Freeze for Debian Stretch is approaching, a release in early December (or earlier) would help to get it in.

**Comment by colinhd8** [comment]
good news. thanks.:+1:

**Comment by chros73** [comment]
There are some bugs: https://github.com/rakshasa/libtorrent/issues/114
Please try it out as many as we can, so they can be fixed before a new release.

**Comment by telmich** [comment]
Hello,

I would love to test/use rtorrent with IPv6, as our networks are IPv6 only now - is there any progress on this?

**Comment by rakshasa** [comment]
I have various corner cases to deal with before it is done. I hope to have it done over the next couple months.
