### ISSUE TITLE
$d variables in schedule

### ISSUE THREAD

**Issue by vconnat** [rakshasa/rtorrent#590]
Hi,
Is there a way to have access to $d variable in a schedule command ? 
I'm working on a pluggin

**Comment by rakshasa** [comment]
No, there's no schedule that you can set on downloads, you need to use the download list.

**Comment by chros73** [comment]
@vconnat , what do you want to achieve?

**Comment by vconnat** [comment]
@chros73 I periodically want some info about each torrents

**Comment by pyroscope** [comment]
https://pyrocore.readthedocs.io/en/latest/usage.html#using-output-templates

**Comment by vconnat** [comment]
@pyroscope @chros73 Look great, but i'm looking for something more "from rtorrent" 

@rakshasa How can I use the download list ? Did you have some doc ?

**Comment by pyroscope** [comment]
"from rtorrent" is futile, since you'll never achieve anything – creating reports with a limited config language is hardly a sensible goal. Especially when its author tells you so. I'll unsubscribe now…

**Comment by chros73** [comment]
@vconnat As @pyroscope suggested:
- if you want to get statistical info about downloads **outside of rtorrent** then you should use the xml-rpc interface (e.g. with `pyrocore`)
- if you want to process downloads **inside of rtorrent** for whatever reason then you can use the mentioned download lists; here's a small, but perfect example for it: [auto scraping](https://github.com/rakshasa/rtorrent/wiki/Auto-Scraping)
