### ISSUE TITLE
"rpc_*" log group considered invalid option name

### ISSUE THREAD

**Issue by pyed** [rakshasa/rtorrent#593]
running `rTorrent 0.9.6/0.13.6`

``` bash
$ rtorrent
rtorrent: Error in option file: ~/.rtorrent.rc:69: Invalid option name.
```
```
# Logging:
#   Levels = critical error warn notice info debug
#   Groups = connection_* dht_* peer_* rpc_* storage_* thread_* tracker_* torrent_*
print = (cat,"Logging to ",(cfg.logfile))
log.open_file = "log", (cfg.logfile)
log.add_output = "info", "log"
log.add_output = "rpc_debug", "log"         # <-- line 69
```
commenting out the `rpc_debug` line will fix the rc file, same holds true for all `rpc_`levels, I also tried opening a separate file for rpc `log.open_file`, same results.

full .rtorrent.rc file: http://sprunge.us/DXGg

**Comment by pyroscope** [comment]
It's `rpc_events` and `rpc_dump`.

**Comment by pyed** [comment]
well, that ought to be mentioned in the wiki!

Thank you @pyroscope for your contributions to the rtorrent community

**Comment by rakshasa** [comment]
Updated wiki.
