### ISSUE TITLE
Question about installation and repository

### ISSUE THREAD

**Issue by raspdealer** [rakshasa/rtorrent#600]
Hi guys,

Great work here!
I'm coming with a small question for you, if I install your stuff like this:
```
git clone -b feature-bind https://github.com/rakshasa/rtorrent
cd rtorrent
./autogen.sh
./configure --with-xmlrpc-c
make
sudo make install
sudo ldconfig
```
will it be upgraded with an apt-get upgrade? or this will only work with:
`apt-get install rtorrent`

If the answer is yes, it will only work after an apt-get install, are the debian repository packages always up-to-date?

Thanks for your feedback 🥇

**Comment by rakshasa** [comment]
This is not the place for distribution related issues.

**Comment by chros73** [comment]
Since you compile it by yourself: package management doesn't know anything about it.
Btw, you can use @pyroscope's build.sh script of [rotrrent-ps](https://github.com/pyroscope/rtorrent-ps) to "install" it separately from the distrib version on a Debian flavoured system.
