### ISSUE TITLE
WIKI Edit: All directories should end with forward slash?

### ISSUE THREAD

**Issue by 01100001** [rakshasa/rtorrent#601]
Hi, I just edited [this page on the wiki](https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template) to change this:

```
session.path.set = (cat, (cfg.basedir), ".session")
directory.default.set = (cat, (cfg.basedir), "download")
```

To this:

```
session.path.set = (cat, (cfg.basedir), ".session/")
directory.default.set = (cat, (cfg.basedir), "download/")
```

Reason as [stated in the wiki edit](https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template/_history):

> Forward slash for directories as they could be used elsewhere, e.g. `directory.default` could be used in watch directories. So as a general rule, we should have forward slash for directories? E.g.
> 
>     schedule2 = watch_start_music, 10, 10, ((load.start, (cat, (cfg.watch), "dir1/*.torrent")), (d.directory.set, (cat, (directory.default), "dir1/")))

Good or bad?

**Comment by rakshasa** [comment]
Looks good.
