### ISSUE TITLE
rtorrent.service doesn't start properly

### ISSUE THREAD

**Issue by lovewangbo** [rakshasa/rtorrent#605]
After a clean install on debian 8.1 or 7.7, I can login in rutorrent but rutorrent reports that "No connection to rTorrent. Check if it is really running".  Further test shows that rtorrent.service is started improperly. Detail is given in the following:

1.  OS version
\# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.1 (jessie)
Release:        8.1
Codename:       jessie

2.  The abnormal status of rtorrent.service
$ sudo systemctl status rtorrent
● rtorrent.service - rtorrent (in tmux)
   Loaded: loaded (/etc/systemd/system/rtorrent.service; enabled)
   Active: active (exited) since Wed 2017-05-17 07:07:41 EDT; 1h 31min ago
  Process: 29945 ExecStop=/usr/bin/tmux kill-session -t rtorrent (code=exited, status=1/FAILURE)
  Process: 29968 ExecStart=/usr/bin/tmux -2 new-session -d -s rtorrent rtorrent (code=exited, status=0/SUCCESS)
 Main PID: 29968 (code=exited, status=0/SUCCESS)

 May 17 07:07:41 localhost systemd[1]: Started rtorrent (in tmux).
\# ps -ef | grep rtorrent
root     30017 29991  0 09:16 pts/3    00:00:00 grep rtorrent 

After restart the service and reboot,  I got repeated result.

In contrast , the properly started service in another OS ubuntu 15.10 is
$ sudo systemctl status rtorrent
● rtorrent.service - rtorrent (in tmux)
   Loaded: loaded (/etc/systemd/system/rtorrent.service; enabled; vendor preset: enabled)
   Active: active (exited) since Wed 2017-05-17 03:44:30 MSK; 13min ago
  Process: 31111 ExecStart=/usr/bin/tmux -2 new-session -d -s rtorrent rtorrent (code=exited, status=0/SUCCESS)
 Main PID: 31111 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/rtorrent.service
           ├─31113 /usr/bin/tmux -2 new-session -d -s rtorrent rtorrent
           ├─31114 sh -c rtorrent
           └─31117 rtorrent

May 17 03:44:30 localhost systemd[1]: Starting rtorrent (in tmux)...
May 17 03:44:30 localhost systemd[1]: Started rtorrent (in tmux).
$  ps -ef | grep rtorrent
abcd   31113     1  0 03:44 ?        00:00:00 /usr/bin/tmux -2 new-session -d -s rtorrent rtorrent
abcd   31114 31113  0 03:44 pts/1    00:00:00 sh -c rtorrent
abcd   31117 31114  0 03:44 pts/1    00:00:00 rtorrent
abcd   31139  1658  0 03:57 pts/0    00:00:00 grep --color=auto rtorrent

3.  cheking tmux 
$ tmux ls
failed to connect to server: Connection refused
\# tmux ls
failed to connect to server: No such file or directory
\# ps -ef | grep tmux
(empty result)

For the properly started one obtained in ubuntu 15.10, the result is 
$ tmux ls
rtorrent: 1 windows (created Wed May 17 05:41:55 2017) [237x62]
\# ps -ef | grep tmux
abcd    11073     1  0 05:41 ?        00:00:07 /usr/bin/tmux -2 new-session -d -s rtorrent rtorrent
root     11473 11457  0 11:00 pts/0    00:00:00 grep --color=auto tmux

**Comment by rakshasa** [comment]
Not the right place.
