### ISSUE TITLE
Syntax error while configuring with xmlrpc

### ISSUE THREAD

**Issue by Lukyczk** [rakshasa/rtorrent#606]
Hi,
I was trying to resolve this issue for already 2 days, but I couldnt find anything that would have made it work. I have tried building and installing libcurl from source code, installing it through apt, nothing worked. When I try to remove the three lines that check for it, I get the same problem with libtorrent (that I also built from source code). Here is the log: https://pastebin.com/VgiZFMLy . Thanks

**Comment by chros73** [comment]
Which distrib?

**Comment by Lukyczk** [comment]
Xubuntu

**Comment by chros73** [comment]
Build rtorrent-ps with its build.sh script.

**Comment by Lukyczk** [comment]
I have no idea what you just said

**Comment by Lukyczk** [comment]
I didnt find any build.sh script, could you please explain what I should do ?

**Comment by Lukyczk** [comment]
And when trying to install all the dependencies I get this: E: Unable to correct problems, you have held broken packages.

**Comment by chros73** [comment]
Use [rtorrent-ps](https://github.com/pyroscope/rtorrent-ps) by @pyroscope (or its fork [rtorrent-ps-ch](https://github.com/chros73/rtorrent-ps#fork-notes)), it will take care all the dependencies.

**Comment by Lukyczk** [comment]
It´s been compiling for at least 15 minutes and then I get a ncurses.h: No such file or directory... I just dont know what to do

**Comment by chros73** [comment]
Close this issues and create a new one on the specific project.

**Comment by Lukyczk** [comment]
Well, I think that im gonna just pass up and use a more not-broken torrent client. Thanks tho
