### ISSUE TITLE
[Bug] Hash computing for shared folders / partial reseed

### ISSUE THREAD

**Issue by noraj** [rakshasa/rtorrent#609]
I have 146 completed torrents. But 66 at have an error status.

All have the same error message (torrent info > tracker status): `Download registered as completed, but hash check returned unfinished chunks.`.

I think this is because I do re-seed. I always have 3 to 5 trackers for the same torrent, but they are not always the same torrent exactly. Some have only a `.nfo`, some have a `.nfo` + `.sfv`, some have `.nfo` + `.sfv` + a `sample` folder.

rTorrent has no problem for the download, he add the `sample` folder into the previous torrent folder without re-downloading already download files for example.

But for hash computing it seems to has a problem.

**Comment by noraj** [comment]
The reason of the closing?

**Comment by rakshasa** [comment]
Cleaning up old bug reports with no clear indication of what the issue is, and you're messing with the downloaded files and fast resume.

**Comment by noraj** [comment]
Anyway I'm using qbitorrent now because there isn't any reliable Web-UI for rtorrent unfortunatly.
