### ISSUE TITLE
very slow exit

### ISSUE THREAD

**Issue by gthreepw00d** [rakshasa/rtorrent#610]
Sometimes rtorrent is painfully slow to quit after Ctrl-q.

**Comment by Micdu70** [comment]
If I don't say wrong, rtorrent calls a tracker update (and wait for a response) on all actives torrents before quitting. That's why I think it's sometimes slow...

If you double 'Ctrl-q' (Ctrl-q-q), it should quit immediately.

**Comment by rakshasa** [comment]
As said above.

There is the tracker stopped request reason, and for some kernels they don't want to guarantee file pages were scheduled for sync immediately so the process might walk around as a zombie for a while.

**Comment by gthreepw00d** [comment]
> If you double 'Ctrl-q' (Ctrl-q-q), it should quit immediately.
Doesn't work
> process might walk around as a zombie for a while
ps says it's in "interruptible sleep" state

I still think it's a bug.
