### ISSUE TITLE
rtorrent keeps downloading something but none of my torrents have anything else to download

### ISSUE THREAD

**Issue by Achus619** [rakshasa/rtorrent#611]
rtorrent shows a constant download rate of 3-5KB/s even though all my torrents are completed and seeding or they don't have anything else to download. When I stop all torrents then the downloading stops as well.
If I use rutorrent to list all by download speed they all show 0B/s but I know something somewhere must be downloading. I use an old PC as a home server/seedbox and I'm worried about unnecessary writes to my disk.

Also, as I side note, the partial seeding torrents showing as incomplete bothers me as well, it there a way to apply [this patch](https://github.com/rakshasa/rtorrent/pull/575) by chros73 to my installation?

thanks!

**Comment by rakshasa** [comment]
Global rate accounts for all BT protocol messages, not just file data.

**Comment by chros73** [comment]
> I use an old PC as a home server/seedbox and I'm worried about unnecessary writes to my disk.

You don't have to worry about this, we have way bigger [problem](https://github.com/rakshasa/rtorrent/issues/443) :)

> is there a way to apply this patch by chros73 to my installation?

You can try it out by [building](https://github.com/chros73/rtorrent-ps/blob/master/docs/DebianInstallFromSourceTheEasyWay.rst) [rtorrent-ps-ch 1.5.0-0.9.7](https://github.com/chros73/rtorrent-ps#fork-notes) on your old PC.
