### ISSUE TITLE
load.* methods do not work for magnet links

### ISSUE THREAD

**Issue by hjbotha** [rakshasa/rtorrent#617]
When I run a command to load a magnet URL:

$ xmlrpc localhost load.normal "magnet:?xt=urn:btih:59066769B9AD42DA2E508611C33D7C4480B3857B&dn=ubuntu-17.04-desktop-amd64.iso&tr=http%3A%2F%2Ftorrent.ubuntu.com%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.torrent.ubuntu.com%3A6969%2Fannounce"

I get:

Failed.  Call failed.  RPC failed at server.  Could not find info-hash..  (XML-RPC fault code -501)

Adding the exact same link directly in rtorrent using load.normal works perfectly.

rtorrent: 0.9.6
libtorrent: 0.13.6
libxmlrpc-c++8: 1.33.14-0.2 (Debian package)

**Comment by pyroscope** [comment]
rT only loads metafiles, not anything else.

See http://pyrocore.readthedocs.io/en/latest/references.html#mktor

“If passed a magnet URI as the only argument, a metafile is created
in the directory specified via the configuration value 'magnet_watch',
loadable by rTorrent. Which means you can register 'mktor' as a magnet:
URL handler in Firefox.”

**Comment by hjbotha** [comment]
Fair enough. I did figure out that the first parameter should be the target, and the second the URI. It works that way. Apologies.

**Comment by delacroix0815** [comment]
Could you please provide an example ? I'm trying to figure this out myself

**Comment by hjbotha** [comment]
Oof, it's been a while and I'm not using rt anymore but if I remember correctly, using the above link as an example, the correct command was:

xmlrpc localhost load.normal "" "magnet:?xt=urn:btih:59066769B9AD42DA2E508611C33D7C4480B3857B&dn=ubuntu-17.04-desktop-amd64.iso&tr=http%3A%2F%2Ftorrent.ubuntu.com%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.torrent.ubuntu.com%3A6969%2Fannounce"

First argument is an empty string.

**Comment by delacroix0815** [comment]
I already tried that. This is the xmlrpc output :

Failed.  Invalid specification of parameter 0 (starting at zero).  Expected value type specifier such as 'i/' or 'array/' but found ''

**Comment by kannibalox** [comment]
```
xmlrpc localhost load.normal 'array/("")'  "magnet:?xt=urn:btih:59066769B9AD42DA2E508611C33D7C4480B3857B&dn=ubuntu-17.04-desktop-amd64.iso&tr=http%3A%2F%2Ftorrent.ubuntu.com%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.torrent.ubuntu.com%3A6969%2Fannounce"
```

This is due to how the `xmlrpc` command works, nothing to do with rtorrent.

**Comment by delacroix0815** [comment]
Still, same error:

xmlrpc localhost load.normal 'array/("")'  "magnet:?xt=urn:btih:59066769B9AD42DA2E508611C33D7C4480B3857B&dn=ubuntu-17.04-desktop-amd64.iso&tr=http%3A%2F%2Ftorrent.ubuntu.com%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.torrent.ubuntu.com%3A6969%2Fannounce"
Failed.  Invalid specification of parameter 1 (starting at zero).  Junk after parameter specification: ':?xt=urn:btih:59066769B9AD42DA2E508611C33D7C4480B3857B&dn=ubuntu-17.04-desktop-amd64.iso&tr=http%3A%2F%2Ftorrent.ubuntu.com%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.torrent.ubuntu.com%3A6969%2Fannounce'


I'm using xmlrpc-c-1.39.11-r1 on Gentoo Linux.

**Comment by kannibalox** [comment]
File a bug with xmlrpc-c then, or double check the documentation for that version.

**Comment by delacroix0815** [comment]
Ok, solved. I had to escape the colons, so the above command must be : 

xmlrpc localhost load.normal 'array/("")' "magnet\:?xt=urn\:btih\:59066769B9AD42DA2E508611C33D7C4480B3857B&dn=ubuntu-17.04-desktop-amd64.iso&tr=http%3A%2F%2Ftorrent.ubuntu.com%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.torrent.ubuntu.com%3A6969%2Fannounce"
