### ISSUE TITLE
Error with ./configure

### ISSUE THREAD

**Issue by ghstridr** [rakshasa/rtorrent#618]
checking whether pthreads work without any flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for NcursesW wide-character library... no
checking for Ncurses library... yes
checking for working ncurses/curses.h... no
checking for working ncurses.h... yes
./configure: line 18466: syntax error near unexpected token `CPPUNIT,'
./configure: line 18466: `PKG_CHECK_MODULES(CPPUNIT, cppunit,, no_cppunit="yes")'

lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

This is reproducible. Generated by autogen.sh

**Comment by rakshasa** [comment]
You need to install cppunit before running autogen.sh.

**Comment by michael-gracy** [comment]
@rakshasa 
I do have cppunit installed. I show that below along with my default lddconfig.
ghstridr@buddha:~/git/rtorrent⟫ sudo apt-get install libcppunit-1.13-0v5 libcppunit-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcppunit-1.13-0v5 is already the newest version (1.13.2-2.1).
libcppunit-dev is already the newest version (1.13.2-2.1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

ghstridr@buddha:/usr⟫ find ./ -name libcppunit*.so*
./lib/x86_64-linux-gnu/libcppunit-1.13.so.0.0.2
./lib/x86_64-linux-gnu/libcppunit_subunit.so
./lib/x86_64-linux-gnu/libcppunit-1.13.so.0
./lib/x86_64-linux-gnu/libcppunit_subunit.so.0.0.0
./lib/x86_64-linux-gnu/libcppunit_subunit.so.0
./lib/x86_64-linux-gnu/libcppunit.so

ghstridr@buddha:/usr⟫ grep  '/usr/lib' /etc/ld.so.conf.d/*
/etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf:/usr/lib/x86_64-linux-gnu/libfakeroot
/etc/ld.so.conf.d/x86_64-linux-gnu.conf:/usr/lib/x86_64-linux-gnu
/etc/ld.so.conf.d/x86_64-linux-gnu_EGL.conf:/usr/lib/x86_64-linux-gnu/mesa-egl
/etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf:/usr/lib/x86_64-linux-gnu/mesa

**Comment by pyroscope** [comment]
It's pkg-config that is missing, not cppunit.

```sh
apt-get install build-essential pkg-config \
    libssl-dev zlib1g-dev libncurses-dev libncursesw5-dev \
    libcppunit-dev autoconf automake libtool
```

**Comment by ghstridr** [comment]
Thank you @PyroScope, that fixed it.

<https://about.me/michael.gracy?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>
Michael Gracy
about.me/michael.gracy
<https://about.me/michael.gracy?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>

On Tue, Jun 27, 2017 at 4:20 PM, PyroScope Project <notifications@github.com
