### ISSUE TITLE
All torrents turn red when a big maximum number of open files is set

### ISSUE THREAD

**Issue by lovewangbo** [rakshasa/rtorrent#621]
Hi,

My server encounted an issue. When a big maximum number of open files, e.g., 512, is set, all torrents turn red after a while, with tracker status reporting "Tracker: [Timeout was reached]", "Tracker: [SSL connect error]" or "Tracker: [SSL connect error]" . In the bottom right of terminal screen, it appears:
[H 18/32] [S 13/754/768] [F 256/256]
the value 18 is equal to the number of red torrents.

If the maximum number of open files is reduced to the default value, i.e., 128, the red torrents can turn to green after a while.

OS: Debian 8
$ ulimit -n
open files                      (-n) 65535

**Comment by pyroscope** [comment]
If you start via systemd, ulimit is not relevant.
