### ISSUE TITLE
How to make rTorrent resume downloading after reboot?

### ISSUE THREAD

**Issue by frankvw2017** [rakshasa/rtorrent#622]
I'm running rTorrent 0.9.2 on a system that I'm not the admin of. Occasionally this system has to be rebooted. When this happens and I restart rTorrent after the reboot, all my downloads are gone from the queue and I can't seem to get them to resume. So far all I've managed is to start each download again from scratch.

I'm downloading torrents from magnet links (in rTorrents main screen hit Backspace, then past the magnet link into it). I no longer put torrent files into a watch directory these days. (TPB no longer uses them )

After the reboot I'm left with the partial files sitting in the "incoming" directory, with a meta file for each one which rTorrent creates when downloading a magnet link.

Contents of .rTorrent.rc:

```
max_uploads = 5
download_rate = 0
upload_rate = 10
directory = /home/pi/bittorrent/incoming
```

I've searched extensively (including here) but if there's a solution I can't find it. Yet every torrent client I've seen so far simply resumes downloading once restarted, so I assume rTorrent must be able to do that as well. What am I missing?

**Comment by 2600box** [comment]
you need a session directory.
i think for your old version you need the old syntax for your config file:
`session = /home/your_user_name/session`

make the directory (`mkdir`) before starting rtorrent and it will keep track of your torrents after a reboot.

**Comment by frankvw2017** [comment]
That works! Thanks!
