### ISSUE TITLE
Crash after upgrade to Debian 9

### ISSUE THREAD

**Issue by Babybolzer** [rakshasa/rtorrent#623]
After upgrading to Debian 9 and installing rtorrent and libtorrent from apt, rtorrent crashes instantly:

*** Error in `rtorrent': free(): invalid pointer: 0x00007ffcdb4e0798 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bcb)[0x7f324e130bcb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76f96)[0x7f324e136f96]
/lib/x86_64-linux-gnu/libc.so.6(+0x777de)[0x7f324e1377de]
rtorrent(+0x116862)[0x5566ebab3862]
rtorrent(+0x44527)[0x5566eb9e1527]
rtorrent(+0x2b903)[0x5566eb9c8903]
rtorrent(+0x1d1a8)[0x5566eb9ba1a8]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f324e0e02b1]
rtorrent(+0x21f7a)[0x5566eb9bef7a]
======= Memory map: ========
5566eb99d000-5566ebb1f000 r-xp 00000000 08:02 1838038                    /usr/bin/rtorrent
5566ebd1f000-5566ebd25000 r--p 00182000 08:02 1838038                    /usr/bin/rtorrent
5566ebd25000-5566ebd26000 rw-p 00188000 08:02 1838038                    /usr/bin/rtorrent
5566ebd26000-5566ebd29000 rw-p 00000000 00:00 0
5566ec319000-5566ec3cf000 rw-p 00000000 00:00 0                          [heap]
7f323c000000-7f323c021000 rw-p 00000000 00:00 0
7f323c021000-7f3240000000 ---p 00000000 00:00 0
7f3244000000-7f3244021000 rw-p 00000000 00:00 0
7f3244021000-7f3248000000 ---p 00000000 00:00 0
7f3248dc4000-7f3248dc5000 ---p 00000000 00:00 0
7f3248dc5000-7f32495c5000 rw-p 00000000 00:00 0
7f32495c5000-7f32495cc000 r-xp 00000000 08:02 1840166                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f32495cc000-7f32497cc000 ---p 00007000 08:02 1840166                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f32497cc000-7f32497cd000 r--p 00007000 08:02 1840166                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f32497cd000-7f32497ce000 rw-p 00008000 08:02 1840166                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f32497ce000-7f32497e1000 r-xp 00000000 08:02 5898487                    /lib/x86_64-linux-gnu/libgpg-error.so.0.21.0
7f32497e1000-7f32499e0000 ---p 00013000 08:02 5898487                    /lib/x86_64-linux-gnu/libgpg-error.so.0.21.0
7f32499e0000-7f32499e1000 r--p 00012000 08:02 5898487                    /lib/x86_64-linux-gnu/libgpg-error.so.0.21.0
7f32499e1000-7f32499e2000 rw-p 00013000 08:02 5898487                    /lib/x86_64-linux-gnu/libgpg-error.so.0.21.0
7f32499e2000-7f32499f3000 r-xp 00000000 08:02 1840180                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.3
7f32499f3000-7f3249bf3000 ---p 00011000 08:02 1840180                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.3
7f3249bf3000-7f3249bf4000 r--p 00011000 08:02 1840180                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.3
7f3249bf4000-7f3249bf5000 rw-p 00012000 08:02 1840180                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.3
7f3249bf5000-7f3249c27000 r-xp 00000000 08:02 5898510                    /lib/x86_64-linux-gnu/libidn.so.11.6.16
7f3249c27000-7f3249e27000 ---p 00032000 08:02 5898510                    /lib/x86_64-linux-gnu/libidn.so.11.6.16
7f3249e27000-7f3249e28000 r--p 00032000 08:02 5898510                    /lib/x86_64-linux-gnu/libidn.so.11.6.16
7f3249e28000-7f3249e29000 rw-p 00033000 08:02 5898510                    /lib/x86_64-linux-gnu/libidn.so.11.6.16
7f3249e29000-7f3249e83000 r-xp 00000000 08:02 1835133                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.2.0
7f3249e83000-7f324a082000 ---p 0005a000 08:02 1835133                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.2.0
7f324a082000-7f324a08c000 r--p 00059000 08:02 1835133                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.2.0
7f324a08c000-7f324a08e000 rw-p 00063000 08:02 1835133                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.2.0
7f324a08e000-7f324a0a8000 r-xp 00000000 08:02 1841932                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f324a0a8000-7f324a2a7000 ---p 0001a000 08:02 1841932                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f324a2a7000-7f324a2a8000 r--p 00019000 08:02 1841932                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f324a2a8000-7f324a2a9000 rw-p 0001a000 08:02 1841932                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f324a2a9000-7f324a2bd000 r-xp 00000000 08:02 5898340                    /lib/x86_64-linux-gnu/libresolv-2.24.so
7f324a2bd000-7f324a4bc000 ---p 00014000 08:02 5898340                    /lib/x86_64-linux-gnu/libresolv-2.24.so
7f324a4bc000-7f324a4bd000 r--p 00013000 08:02 5898340                    /lib/x86_64-linux-gnu/libresolv-2.24.so
7f324a4bd000-7f324a4be000 rw-p 00014000 08:02 5898340                    /lib/x86_64-linux-gnu/libresolv-2.24.so
7f324a4be000-7f324a4c0000 rw-p 00000000 00:00 0
7f324a4c0000-7f324a4c3000 r-xp 00000000 08:02 5898508                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f324a4c3000-7f324a6c2000 ---p 00003000 08:02 5898508                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f324a6c2000-7f324a6c3000 r--p 00002000 08:02 5898508                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f324a6c3000-7f324a6c4000 rw-p 00003000 08:02 5898508                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f324a6c4000-7f324a6cf000 r-xp 00000000 08:02 1840164                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f324a6cf000-7f324a8ce000 ---p 0000b000 08:02 1840164                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f324a8ce000-7f324a8cf000 r--p 0000a000 08:02 1840164                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f324a8cf000-7f324a8d0000 rw-p 0000b000 08:02 1840164                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f324a8d0000-7f324a9d7000 r-xp 00000000 08:02 5898310                    /lib/x86_64-linux-gnu/libgcrypt.so.20.1.6
7f324a9d7000-7f324abd6000 ---p 00107000 08:02 5898310                    /lib/x86_64-linux-gnu/libgcrypt.so.20.1.6
7f324abd6000-7f324abd8000 r--p 00106000 08:02 5898310                    /lib/x86_64-linux-gnu/libgcrypt.so.20.1.6
7f324abd8000-7f324abdf000 rw-p 00108000 08:02 5898310                    /lib/x86_64-linux-gnu/libgcrypt.so.20.1.6
7f324abdf000-7f324ac60000 r-xp 00000000 08:02 1844149                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
7f324ac60000-7f324ae60000 ---p 00081000 08:02 1844149                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
7f324ae60000-7f324ae61000 r--p 00081000 08:02 1844149                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
7f324ae61000-7f324ae62000 rw-p 00082000 08:02 1844149                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
7f324ae62000-7f324ae97000 r-xp 00000000 08:02 1841887                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.3
7f324ae97000-7f324b096000 ---p 00035000 08:02 1841887                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.3
7f324b096000-7f324b098000 r--p 00034000 08:02 1841887                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.3
7f324b098000-7f324b099000 rw-p 00036000 08:02 1841887                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.3
7f324b099000-7f324b0cc000 r-xp 00000000 08:02 1841901                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.3
7f324b0cc000-7f324b2cc000 ---p 00033000 08:02 1841901                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.3
7f324b2cc000-7f324b2cd000 r--p 00033000 08:02 1841901                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.3
7f324b2cd000-7f324b2ce000 rw-p 00034000 08:02 1841901                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.3
7f324b2ce000-7f324b458000 r-xp 00000000 08:02 1841905                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.13.1
7f324b458000-7f324b658000 ---p 0018a000 08:02 1841905                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.13.1
7f324b658000-7f324b665000 r--p 0018a000 08:02 1841905                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.13.1
7f324b665000-7f324b666000 rw-p 00197000 08:02 1841905                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.13.1
7f324b666000-7f324b667000 rw-p 00000000 00:00 0
7f324b667000-7f324b77a000 r-xp 00000000 08:02 1838597                    /usr/lib/x86_64-linux-gnu/libunistring.so.0.1.2
7f324b77a000-7f324b979000 ---p 00113000 08:02 1838597                    /usr/lib/x86_64-linux-gnu/libunistring.so.0.1.2
7f324b979000-7f324b97c000 r--p 00112000 08:02 1838597                    /usr/lib/x86_64-linux-gnu/libunistring.so.0.1.2
7f324b97c000-7f324b97d000 rw-p 00115000 08:02 1838597                    /usr/lib/x86_64-linux-gnu/libunistring.so.0.1.2
7f324b97d000-7f324b97e000 rw-p 00000000 00:00 0
7f324b97e000-7f324bb4b000 r-xp 00000000 08:02 1838535                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f324bb4b000-7f324bd4a000 ---p 001cd000 08:02 1838535                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f324bd4a000-7f324bd67000 r--p 001cc000 08:02 1838535                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f324bd67000-7f324bd77000 rw-p 001e9000 08:02 1838535                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f324bd77000-7f324bd7a000 rw-p 00000000 00:00 0
7f324bd7a000-7f324bd93000 r-xp 00000000 08:02 5898287                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f324bd93000-7f324bf92000 ---p 00019000 08:02 5898287                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f324bf92000-7f324bf93000 r--p 00018000 08:02 5898287                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f324bf93000-7f324bf94000 rw-p 00019000 08:02 5898287                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f324bf94000-7f324bfe1000 r-xp 00000000 08:02 1841938                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.7
7f324bfe1000-7f324c1e0000 ---p 0004d000 08:02 1841938                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.7
7f324c1e0000-7f324c1e2000 r--p 0004c000 08:02 1841938                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.7
7f324c1e2000-7f324c1e3000 rw-p 0004e000 08:02 1841938                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.7
7f324c1e3000-7f324c1e5000 rw-p 00000000 00:00 0
7f324c1e5000-7f324c1f2000 r-xp 00000000 08:02 1838334                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.7
7f324c1f2000-7f324c3f2000 ---p 0000d000 08:02 1838334                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.7
7f324c3f2000-7f324c3f3000 r--p 0000d000 08:02 1838334                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.7
7f324c3f3000-7f324c3f4000 rw-p 0000e000 08:02 1838334                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.7
7f324c3f4000-7f324c3f7000 r-xp 00000000 08:02 5898324                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f324c3f7000-7f324c5f6000 ---p 00003000 08:02 5898324                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f324c5f6000-7f324c5f7000 r--p 00002000 08:02 5898324                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f324c5f7000-7f324c5f8000 rw-p 00003000 08:02 5898324                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f324c5f8000-7f324c627000 r-xp 00000000 08:02 1840162                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f324c627000-7f324c827000 ---p 0002f000 08:02 1840162                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f324c827000-7f324c829000 r--p 0002f000 08:02 1840162                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f324c829000-7f324c82a000 rw-p 00031000 08:02 1840162                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f324c82a000-7f324c82b000 rw-p 00000000 00:00 0
7f324c82b000-7f324c8f4000 r-xp 00000000 08:02 1839770                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f324c8f4000-7f324caf4000 ---p 000c9000 08:02 1839770                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f324caf4000-7f324cb02000 r--p 000c9000 08:02 1839770                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f324cb02000-7f324cb05000 rw-p 000d7000 08:02 1839770                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f324cb05000-7f324cb4d000 r-xp 00000000 08:02 1839617                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f324cb4d000-7f324cd4c000 ---p 00048000 08:02 1839617                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f324cd4c000-7f324cd4e000 r--p 00047000 08:02 1839617                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f324cd4e000-7f324cd50000 rw-p 00049000 08:02 1839617                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f324cd50000-7f324cf85000 r-xp 00000000 08:02 1841950                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
7f324cf85000-7f324d185000 ---p 00235000 08:02 1841950                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
7f324d185000-7f324d1a1000 r--p 00235000 08:02 1841950                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
7f324d1a1000-7f324d1b0000 rw-p 00251000 08:02 1841950                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
7f324d1b0000-7f324d1b4000 rw-p 00000000 00:00 0
7f324d1b4000-7f324d213000 r-xp 00000000 08:02 1841951                    /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
7f324d213000-7f324d413000 ---p 0005f000 08:02 1841951                    /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
7f324d413000-7f324d417000 r--p 0005f000 08:02 1841951                    /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
7f324d417000-7f324d41d000 rw-p 00063000 08:02 1841951                    /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
7f324d41d000-7f324d429000 r-xp 00000000 08:02 1838623                    /usr/lib/x86_64-linux-gnu/libpsl.so.5.1.1
7f324d429000-7f324d629000 ---p 0000c000 08:02 1838623                    /usr/lib/x86_64-linux-gnu/libpsl.so.5.1.1
7f324d629000-7f324d62a000 r--p 0000c000 08:02 1838623                    /usr/lib/x86_64-linux-gnu/libpsl.so.5.1.1
7f324d62a000-7f324d62b000 rw-p 0000d000 08:02 1838623                    /usr/lib/x86_64-linux-gnu/libpsl.so.5.1.1
7f324d62b000-7f324d656000 r-xp 00000000 08:02 1844469                    /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
7f324d656000-7f324d855000 ---p 0002b000 08:02 1844469                    /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
7f324d855000-7f324d856000 r--p 0002a000 08:02 1844469                    /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
7f324d856000-7f324d857000 rw-p 0002b000 08:02 1844469                    /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
7f324d857000-7f324d872000 r-xp 00000000 08:02 1847274                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f324d872000-7f324da72000 ---p 0001b000 08:02 1847274                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f324da72000-7f324da73000 r--p 0001b000 08:02 1847274                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f324da73000-7f324da74000 rw-p 0001c000 08:02 1847274                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f324da74000-7f324da95000 r-xp 00000000 08:02 1838608                    /usr/lib/x86_64-linux-gnu/libidn2.so.0.1.4
7f324da95000-7f324dc94000 ---p 00021000 08:02 1838608                    /usr/lib/x86_64-linux-gnu/libidn2.so.0.1.4
7f324dc94000-7f324dc95000 r--p 00020000 08:02 1838608                    /usr/lib/x86_64-linux-gnu/libidn2.so.0.1.4
7f324dc95000-7f324dc96000 rw-p 00021000 08:02 1838608                    /usr/lib/x86_64-linux-gnu/libidn2.so.0.1.4
7f324dc96000-7f324dcb9000 r-xp 00000000 08:02 1838341                    /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.12.3
7f324dcb9000-7f324deb8000 ---p 00023000 08:02 1838341                    /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.12.3
7f324deb8000-7f324deb9000 r--p 00022000 08:02 1838341                    /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.12.3
7f324deb9000-7f324debc000 rw-p 00023000 08:02 1838341                    /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.12.3
7f324debc000-7f324debf000 r-xp 00000000 08:02 5898292                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f324debf000-7f324e0be000 ---p 00003000 08:02 5898292                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f324e0be000-7f324e0bf000 r--p 00002000 08:02 5898292                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f324e0bf000-7f324e0c0000 rw-p 00003000 08:02 5898292                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f324e0c0000-7f324e255000 r-xp 00000000 08:02 5898286                    /lib/x86_64-linux-gnu/libc-2.24.so
7f324e255000-7f324e455000 ---p 00195000 08:02 5898286                    /lib/x86_64-linux-gnu/libc-2.24.so
7f324e455000-7f324e459000 r--p 00195000 08:02 5898286                    /lib/x86_64-linux-gnu/libc-2.24.so
7f324e459000-7f324e45b000 rw-p 00199000 08:02 5898286                    /lib/x86_64-linux-gnu/libc-2.24.so
7f324e45b000-7f324e45f000 rw-p 00000000 00:00 0
7f324e45f000-7f324e477000 r-xp 00000000 08:02 5898339                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f324e477000-7f324e676000 ---p 00018000 08:02 5898339                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f324e676000-7f324e677000 r--p 00017000 08:02 5898339                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f324e677000-7f324e678000 rw-p 00018000 08:02 5898339                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f324e678000-7f324e67c000 rw-p 00000000 00:00 0
7f324e67c000-7f324e692000 r-xp 00000000 08:02 5898247                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f324e692000-7f324e891000 ---p 00016000 08:02 5898247                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f324e891000-7f324e892000 r--p 00015000 08:02 5898247                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f324e892000-7f324e893000 rw-p 00016000 08:02 5898247                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f324e893000-7f324e996000 r-xp 00000000 08:02 5898297                    /lib/x86_64-linux-gnu/libm-2.24.so
7f324e996000-7f324eb95000 ---p 00103000 08:02 5898297                    /lib/x86_64-linux-gnu/libm-2.24.so
7f324eb95000-7f324eb96000 r--p 00102000 08:02 5898297                    /lib/x86_64-linux-gnu/libm-2.24.so
7f324eb96000-7f324eb97000 rw-p 00103000 08:02 5898297                    /lib/x86_64-linux-gnu/libm-2.24.so
7f324eb97000-7f324ed09000 r-xp 00000000 08:02 1838977                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f324ed09000-7f324ef09000 ---p 00172000 08:02 1838977                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f324ef09000-7f324ef13000 r--p 00172000 08:02 1838977                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f324ef13000-7f324ef15000 rw-p 0017c000 08:02 1838977                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f324ef15000-7f324ef19000 rw-p 00000000 00:00 0
7f324ef19000-7f324ef1e000 r-xp 00000000 08:02 1971483                    /usr/local/lib/libxmlrpc_util.so.3.43
7f324ef1e000-7f324f11d000 ---p 00005000 08:02 1971483                    /usr/local/lib/libxmlrpc_util.so.3.43
7f324f11d000-7f324f11e000 rw-p 00004000 08:02 1971483                    /usr/local/lib/libxmlrpc_util.so.3.43
7f324f11e000-7f324f137000 r-xp 00000000 08:02 1971513                    /usr/local/lib/libxmlrpc_xmltok.so.3.43
7f324f137000-7f324f337000 ---p 00019000 08:02 1971513                    /usr/local/lib/libxmlrpc_xmltok.so.3.43
7f324f337000-7f324f339000 rw-p 00019000 08:02 1971513                    /usr/local/lib/libxmlrpc_xmltok.so.3.43
7f324f339000-7f324f349000 r-xp 00000000 08:02 1971505                    /usr/local/lib/libxmlrpc_xmlparse.so.3.43
7f324f349000-7f324f548000 ---p 00010000 08:02 1971505                    /usr/local/lib/libxmlrpc_xmlparse.so.3.43
7f324f548000-7f324f549000 rw-p 0000f000 08:02 1971505                    /usr/local/lib/libxmlrpc_xmlparse.so.3.43
7f324f549000-7f324f565000 r-xp 00000000 08:02 1971523                    /usr/local/lib/libxmlrpc.so.3.43
7f324f565000-7f324f765000 ---p 0001c000 08:02 1971523                    /usr/local/lib/libxmlrpc.so.3.43
7f324f765000-7f324f766000 rw-p 0001c000 08:02 1971523                    /usr/local/lib/libxmlrpc.so.3.43
7f324f766000-7f324f76b000 r-xp 00000000 08:02 1971531                    /usr/local/lib/libxmlrpc_server.so.3.43
7f324f76b000-7f324f96b000 ---p 00005000 08:02 1971531                    /usr/local/lib/libxmlrpc_server.so.3.43
7f324f96b000-7f324f96c000 rw-p 00005000 08:02 1971531                    /usr/local/lib/libxmlrpc_server.so.3.43
7f324f96c000-7f324fa74000 r-xp 00000000 08:02 1971735                    /usr/local/lib/libtorrent.so.19.0.0
7f324fa74000-7f324fc74000 ---p 00108000 08:02 1971735                    /usr/local/lib/libtorrent.so.19.0.0
7f324fc74000-7f324fc79000 rw-p 00108000 08:02 1971735                    /usr/local/lib/libtorrent.so.19.0.0
7f324fc79000-7f324fc7b000 rw-p 00000000 00:00 0
7f324fc7b000-7f324fcf8000 r-xp 00000000 08:02 1845561                    /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
7f324fcf8000-7f324fef7000 ---p 0007d000 08:02 1845561                    /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
7f324fef7000-7f324fefa000 r--p 0007c000 08:02 1845561                    /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
7f324fefa000-7f324fefb000 rw-p 0007f000 08:02 1845561                    /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
7f324fefb000-7f324ff20000 r-xp 00000000 08:02 5898441                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f324ff20000-7f3250120000 ---p 00025000 08:02 5898441                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f3250120000-7f3250124000 r--p 00025000 08:02 5898441                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f3250124000-7f3250125000 rw-p 00029000 08:02 5898441                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f3250125000-7f3250153000 r-xp 00000000 08:02 5898344                    /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f3250153000-7f3250353000 ---p 0002e000 08:02 5898344                    /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f3250353000-7f3250354000 r--p 0002e000 08:02 5898344                    /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f3250354000-7f3250355000 rw-p 0002f000 08:02 5898344                    /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f3250355000-7f3250378000 r-xp 00000000 08:02 5898268                    /lib/x86_64-linux-gnu/ld-2.24.so
7f32503ba000-7f3250555000 r--p 00000000 08:02 1845528                    /usr/lib/locale/locale-archive
7f3250555000-7f325056b000 rw-p 00000000 00:00 0
7f3250574000-7f3250578000 rw-p 00000000 00:00 0
7f3250578000-7f3250579000 r--p 00023000 08:02 5898268                    /lib/x86_64-linux-gnu/ld-2.24.so
7f3250579000-7f325057a000 rw-p 00024000 08:02 5898268                    /lib/x86_64-linux-gnu/ld-2.24.so
7f325057a000-7f325057b000 rw-p 00000000 00:00 0
7ffcdb4c2000-7ffcdb4e3000 rw-p 00000000 00:00 0                          [stack]
7ffcdb5d7000-7ffcdb5d9000 r--p 00000000 00:00 0                          [vvar]
7ffcdb5d9000-7ffcdb5db000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted

**Comment by rakshasa** [comment]
Looks like an issue with changes in your ABI or similar. Recompile everything and it should work.

**Comment by Babybolzer** [comment]
I found the problem: Due to this problem: https://github.com/rakshasa/libtorrent/issues/138 ,
libtorrent will not compile correctly. Apt seems to have no problem installing libtorrent, but it won't work.
Recompiling both libtorrent and rtorrent from the feature-bind branch solved the issue.
