### ISSUE TITLE
Tor Devs: "Bittorrent over Tor isn't a good idea"

### ISSUE THREAD

**Issue by automated-response** [rakshasa/rtorrent#624]
The tor core developers advise not using BitTorrent over Tor ( https://blog.torproject.org/blog/bittorrent-over-tor-isnt-good-idea ).

BitTorrent relies heavily on UDP for functionality, goes very slowly over tor, and the protocol is designed to route around connectivity issues. All of which makes trying to stuff it into a TCP proxy problematic if you're not careful.

You can obtain the same or better anonymity and massively better performabce buy renting a $5 VPS with Bitcoin and then just SSHing into it over tor.

But more importantly, torrenting over the tor network is generally frowned upon by the community as it absolutely eats the precious little bandwidth available on the network for activities that, at least in most cases, do not need to be fully torrified.

Just my $0.02. (I have no actually technical bones to pick with this, for what it’s worth.)

**Comment by rakshasa** [comment]
Not sure what the point of posting that here is.

**Comment by chros73** [comment]
Maybe because of this? :)
[Tor based Proxying Guide Wiki Page](https://github.com/rakshasa/rtorrent/wiki/Tor-based-Proxying-Guide)

**Comment by pyroscope** [comment]
Fixed.

**Comment by rakshasa** [comment]
I guess please be a bit more specific about complaints, especially if it is about wiki pages I haven't read. ;/
