### ISSUE TITLE
RFE: use socat instead of screen / tmux

### ISSUE THREAD

**Issue by multun** [rakshasa/rtorrent#629]
How about attaching rtorrent to a new pty instead of running it inside tmux / whatever ?
It would make much easier daemonizing the process with some init scripts.

```sh
socat PTY,link=/run/rtorrent/pty EXEC:rtorrent,pty,nofork
```

Once the daemon is running, you can attach to its pty using `screen /run/rtorrent/pty`.

Here is an example systemd unit:
https://github.com/multun/scaleway-torrents/blob/master/overlay/etc/systemd/system/rtorrent.service

How about referencing this method somewhere in the wiki ?

PS: this method only makes sense for <=0.9.6, as there is a daemon mode available anyway afterwards

**Comment by pyroscope** [comment]
git head already has a daemon mode. This is redundant.

**Comment by rakshasa** [comment]
If you have a howto, add it to the wiki, it should be open for editing.

**Comment by multun** [comment]
added.
