### ISSUE TITLE
Download to the same folder where is .torrent

### ISSUE THREAD

**Issue by impr3ssi0n** [rakshasa/rtorrent#633]
How to download data to different folders, where is .torrent files?

I tried something like this:

```
method.insert = find_torrent, simple, \
        "execute.capture_nothrow = bash, -c, \"find /home/maxim/Downloads -name *.torrent -print -quit\""

method.insert = dir_torrent, simple, \
        "execute.capture_nothrow = bash, -c, (cat, \"dirname \", (find_torrent))"


method.insert = delete_torrent_file, simple, \
        "execute.throw = bash, -c, (cat,\"rm -f \",(find_torrent))"


schedule2 = watch_start, 5, 5, ((load.start, (cat, (dir_torrent), "/*.torrent"), "d.directory.set = (dir_torrent)"))
```

But, this doesn't work
Instead of dir_torrent, in result bad string, i think. Because path: /home/user/Downolads/...*.torrent it work

**Comment by chros73** [comment]
Couple of problems with the script snippet:
- last line: `"d.directory.set = (dir_torrent)"` , you don't need the quotes around this
- `find_torrent` : can return multiple file names! you can use arguments to pass over
  - if the `*` character is the problem, you can try to escape it: `\*`

**Comment by impr3ssi0n** [comment]
1. without quotes: Junk at end of input.

And, 
schedule2 = watch_start, 5, 5, ((load.start, **(cat, (dir_torrent), "/*.torrent")**, "d.directory.set = **(dir_torrent)**"))  - doesn't work

schedule2 = watch_start, 5, 5, ((load.start, /home/user/Downloads/*.torrent, d.directory.set = /home/user/Downloads/))  - work.

i don't understand why(

print = (cat,(dir_torrent)) -
/home/user/Downloads 

But,
print = (cat,(dir_torrent), "/*.torrent")  -
/home/user/Downloads
/torrent.torrent

mayby '\n'? But i delete tr - d '\n', and so too
