### ISSUE TITLE
some ssl trackers timeout with curl 7.55.1

### ISSUE THREAD

**Issue by chargr** [rakshasa/rtorrent#635]
announcing to some ssl trackers appears to timeout (and max a cpu core) with curl 7.55.1
using curl from cli with the same requests did not timeout and got a valid response in < 2 seconds.
downgrading to 7.54.1 fixed the issue for me (this was arch linux)

**Comment by Micdu70** [comment]
Same issue for me with curl version 7.55+, Debian 9.

**Comment by SJ50** [comment]
I have timeout with non-ssl trackers as well.

**Comment by 2600box** [comment]
i also have timeouts on ssl and non-ssl

**Comment by lamarpavel** [comment]
Also had timeouts accompanied by one cpu core maxed out. Downgrading curl to 7.54.1 seems to fix it here as well.

**Comment by soredake** [comment]
Same for me on gentoo with 7.55.0.

**Comment by SJ50** [comment]
updated cur to 7.55.1-2 on arch linux and it seem to fix the issue, at least non-ssl. 
I do not have ssl tracker.

**Comment by Micdu70** [comment]
curl fix: https://github.com/curl/curl/commit/74dac344b2feb2e0f4baddb70532dc8e45d2d817
