### ISSUE TITLE
Support for command parsing to setting bind_address and local_address

### ISSUE THREAD

**Issue by chros73** [rakshasa/rtorrent#636]
@rakshasa , can you do this while you're working on feature_bind?

Add support for command parsing to `network.bind_address.set` and `network.local_address.set`:
- we can call external scripts / internal commands to set them

E.g.:
```ini
# get public IP address without the need of having dynamic DNS service
method.insert = get_public_ip_address, simple, "execute.capture=bash,-c,\"echo -n \$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com)\",getPublicIp"

schedule2 = ip_tick, 0, 1800, network.local_address.set=(get_public_ip_address)
```

**Comment by pyroscope** [comment]
Quote that scheduled command and it'll work (assuming a rebind is actually performed) – nothing needs to be changed in the core.

Right now, you're setting a **CONSTANT** IP resolved during parsing.

**Comment by chros73** [comment]
> Quote that scheduled command and it'll work

Thanks for the quick answer: indeed it works! :)

Although with need a little mod, get rid of the surrounding quotes around the ip address:
```ini
# Get public IP address without the need of having dynamic DNS service
method.insert = get_public_ip_address, simple, "execute.capture=bash,-c,\"public_ip=\$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com); echo -n \${public_ip//\\\\\\\"}\",getPublicIp"

# The ip address reported to the tracker. (ip) This should handle dynamic ip's as well.
schedule2 = ip_tick, 0, 1800, "network.local_address.set=(get_public_ip_address)"
```

The good thing about doing this from inside rtorrent that the external "script" will run in the network namespace of rtorrent (e.g. when using vpn).

Now, it can be put on the Wiki.

> Right now, you're setting a CONSTANT IP resolved during parsing.

I still fail to see why. Can you elaborate it for me a bit more? :) Thanks

**Comment by pyroscope** [comment]
BTW, using this leads to less obscure escaping:

    eval echo -n $(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com)

**Comment by chros73** [comment]
Nice, and `eval` is not evil in this case. :)

And here's the `network.bind_address.set` version (with some funky escaping as well :) ):
```ini
# Set an interface with IPv4 address to bind to: [eth0|tun0]
method.insert = cfg.interface.bind, string|const|private, (cat,"")

# Get IPv4 address of a given interface
method.insert = get_interface_ipv4_address, simple|private, "execute.capture=bash,-c,\"$cat=\\\"echo -n \$(ip -o -4 addr show \\\",$argument.0=,\\\" | grep -Po 'inet \\\\\\\\\\K[\\\\\\\\\\d.]+')\\\"\""

# The ip address the listening socket and outgoing connections is bound to. (bind)
schedule2 = set_bind_address, 0, 0, "branch=((cfg.interface.bind)),((network.bind_address.set,(get_interface_ipv4_address,(cfg.interface.bind))))"
```

**Comment by chros73** [comment]
Corresponding [sections](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#setting-bind-address) are updated on Wiki.
