### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by psycholyzern** [rakshasa/rtorrent#637]
I have been struggle for an hour to run command ```make```.
I was using source from http://rtorrent.net/downloads.

While compiling libtorrent, I had this issue https://github.com/rakshasa/libtorrent/issues/138. So I cloned branch ```feature-bind``` and installed it.

Then to compile rtorrent, I had this error:
```
This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```
I solved it by passing running ```make CXXFLAGS="-std=c++11```.

Also I have errors same like https://github.com/rakshasa/rtorrent/issues/298. I can't solve it even I already ran ```./autogen.sh```. So I switched my source to git. After I cloned, I repeat, I got a new error:
```
curl_get.cc:42:32: fatal error: torrent/exceptions.h: No such file or directory
compilation terminated.
Makefile:437: recipe for target 'curl_get.o' failed
make[3]: *** [curl_get.o] Error 1
make[3]: Leaving directory '/home/xxx/rtorrent/src/core'
Makefile:609: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/xxx/rtorrent/src'
Makefile:445: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/xxx/rtorrent'
Makefile:377: recipe for target 'all' failed
make: *** [all] Error 2
```

I gave up because have no clue what is my real issue is.
Would be great if someone could help to get this work for me.
I am using **Ubuntu 16.04**

**Comment by rakshasa** [comment]
You do not have 'torrent/exceptions.h' installed in any of your include paths.

**Comment by psycholyzern** [comment]
And where should I get that?
I have no clue.

**Comment by psycholyzern** [comment]
Okay, so I reinstalled xmlrpc-c and libtorrent . Then everything went smooth. Havent got any issue mentioned above, thus neither solution stated were needed.
Thanks.
