### ISSUE TITLE
After resuming session most of torrents are missing

### ISSUE THREAD

**Issue by ashe24** [rakshasa/rtorrent#639]
The title says it all. After upgrading to stretch and fixing php for rutorrent to work i restart rtorrent.

First its starts hashing almost everything again for some obscure reason (anyway to avoid that, and to make rtorrent assume every torrent is complete ?)

Second i only habe roughly 333 torrents in rutorrent vs. 2000 before.

In my .session folder i have about 5k files. It doesn't really seem right to me that this only represents 300 torrents.

Anyway to check how many torrents are in the client through the cli ?  *

Anyway to fix the issue ?

Thanks

**Comment by ashe24** [comment]
After recompiling with latest patches seems to work.

Still about 500 torrents lost their path. So i have to manually edit the torrents so that they find their data again...

**Comment by pyroscope** [comment]
https://github.com/JohnDoee/autotorrent
