### ISSUE TITLE
rtorrent triggering script before download finishes

### ISSUE THREAD

**Issue by chienb** [rakshasa/rtorrent#641]
I'm getting corrupted files, especially with large tv packs, where filebot script seems to think (based on duration/file size?) rtorrent has finished a download even though it was just added. 

I'm using this command in my .rc: 
`method.set_key=event.download.finished,filebot,"execute={/home/owner/Downloads/rt-postprocess.sh,$d.base_path=,$d.name=,$d.custom1=}"`

Is there currently a fix for this?

**Comment by kannibalox** [comment]
How do you know rt-postprocess.sh and/or filebot isn't the issue here? Without the source of the script there's no way to tell, and I've never had event.download.finished trigger incorrectly.

**Comment by chros73** [comment]
+1
