### ISSUE TITLE
can't set listening port in git version - also DHT

### ISSUE THREAD

**Issue by d3im** [rakshasa/rtorrent#643]
I have this in .rtorrent.rc:
```
network.port_range.set = 61614-61614
dht.mode.set = auto
dht.port.set = 61615
```
But I can't see any of this port opened. UI writes:
`[Throttle off/off KB] [Rate   0,0/  0,0 KB] [Port: 6980]`

Tried build with and without IPv6 support also.
There is no error.

**Comment by asavah** [comment]
https://github.com/rakshasa/libtorrent/issues/146

**Comment by rakshasa** [comment]
dup
