### ISSUE TITLE
rtorrent symlink causes missing time rutorrent

### ISSUE THREAD

**Issue by jasonafernandez** [rakshasa/rtorrent#646]
I am currently switching away from using rutorrent plugins. I would like to symlink/hardlink new downloads (what is seeding, continue to seed) to a finished folder for download processing. While below works, ruTorrent is left with missing time in the "Finished" column and sometimes the "Created On" is also missing a date/time stamp. 

In my .rtorrent.rc, I have added the following:
method.set_key = event.download.finished,link,"execute2=/home/buzz/link.sh,$d.custom1=,$d.name=,$d.base_path="

![image](https://user-images.githubusercontent.com/26947122/30411698-7270ed90-98c7-11e7-8e90-cee00bdc3dda.png)

I've tried symlink, hardlink, and copy, all result in same issue. 

I believe this has something to do with the hash. In ruTorrent if I force recheck, the missing Finished time shows up. 

Thank you in advance for any assistance.

**Comment by jasonafernandez** [comment]
I was able to partially resolve my own issue. The order of things is important. 

method.insert = d.get_finished_dir,simple,"cat=/home/buzz/finished/"
method.set_key = event.download.finished,move_complete,"execute2=cp,-lr,$d.base_path=,$d.get_finished_dir="

If I wanted to copy only items with specific labels, what would I use? Schedule watch directory settings custom1?

Thank you.

**Comment by pyroscope** [comment]
Use `execute.nothrow` to ensure the handler chain doesn't stop.

And conditonal completion handling is here: https://rtorrent-docs.readthedocs.io/en/latest/use-cases.html#versatile-move
Namely checking the target is not empty.

**Comment by jasonafernandez** [comment]
Your script works well. Except I would like to leave the data seeding in the base_path. What ends up in the target_path my lftp script deletes as soon as downloaded. I try to modify the pieces in .rtorrent.rc, method.insert, from mv to cp, but it seems information regarding the seed is moved there. If I end up deleting what is in target_path, the seed breaks. 

Any advice? 

Thanks for your help.

**Comment by jasonafernandez** [comment]
I was able to get this working with a more simple bash.

Thank you for your help.
