### ISSUE TITLE
Provide an API to determine whether or not a torrent has finished seeding

### ISSUE THREAD

**Issue by blackwind** [rakshasa/rtorrent#647]
When hooking up rTorrent to Sonarr, Sonarr reports the following:

> Sonarr is unable to remove torrents that have finished seeding when using rTorrent

[According to the developer](https://forums.sonarr.tv/t/sonarr-and-rtorrent-seeding/10676), this is because:

> From what we've seen rTorrent doesn't provide a way for Sonarr to know that the torrent actually finished seeding and wasn't manually stopped for another reason. We opted to leave it unavailable than to guess and hope we don't nuke something that was paused/stopped for another reason.

Since one hand doesn't appear to be talking to the other, I'm here on behalf of Sonarr users to request an API for this. I'd love to be using rTorrent full-time, but as a Sonarr user, this issue is a show-stopper.

**Comment by kannibalox** [comment]
rTorrent has API calls for pretty much everything, what does "finished seeding" mean in the context? If it means reaching a certain ratio, ratio groups are native and sound like exactly what Sonarr wants:  https://github.com/rakshasa/rtorrent/wiki/RTorrentRatioHandling

**Comment by pyroscope** [comment]
Just set a custom in a ratio group command, or pretty much any other state that you want to interpret as finished. In the end, simply add a custom `d.is_finished`, let the external app call that, and define it to your liking (it's not as if "finished seeding" has an obvious definition).

The most obvious thing would be a `finished` view.
