### ISSUE TITLE
rtorrent instantly crashing 

### ISSUE THREAD

**Issue by Drastiques** [rakshasa/rtorrent#649]
Hello, i'm trying to configure a seedbox on a vps i recently rented

but as soon as i start rTorrent with systemctl it runs for 10 seconds and crashes instantly
can you help me with this issue ? 

here is the systemctl status log 
just ask if you need any other log or info

thank you by advance 
`
root@Serveur:~# systemctl status rtorrent
● rtorrent.service - rTorrent
Loaded: loaded (/etc/systemd/system/rtorrent.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Fri 2017-10-06 04:26:33 EDT; 1s ago
Process: 2960 ExecStop=/usr/bin/killall -w -s 2 /usr/bin/rtorrent (code=exited, status=1/FAILURE)
Process: 2956 ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/bin/rtorrent (code=exited, status=0/SUCCESS)
Main PID: 2957 (code=exited, status=0/SUCCESS)

oct. 06 04:26:32 Serveursystemd[1]: Starting rTorrent...
oct. 06 04:26:32 Serveur systemd[1]: Started rTorrent.
oct. 06 04:26:32 Serveur systemd[1]: rtorrent.service: Control process exited, code=exited status=1
oct. 06 04:26:33 Serveursystemd[1]: rtorrent.service: Unit entered failed state.
oct. 06 04:26:33 Serveur systemd[1]: rtorrent.service: Failed with result 'exit-code'.
`

**Comment by pyroscope** [comment]
Remove the layers of fog, start it manually, see actual error messages.
