### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by genell** [rakshasa/rtorrent#661]
I just pulled latest sources from github and built on my Ubuntu 16.04 LTS 32-bit machine. Build of both libtorrent and rtorrent went fine, but when trying to run rtorrent I get the following error:
rtorrent: undefined symbol: _ZN7torrent15signal_bitfield10add_signalESt8functionIFvvEE
Please let me know if I need to do something more on my side to narrow things down!
Regards,
/Anders

**Comment by pyroscope** [comment]
On Ubuntu LTS, just use a pre-built DEB.

**Comment by genell** [comment]
Sorry for commenting on a closed issue, but I would just like to mention that it seems the version in the repositories for Ubuntu 16.04 LTS does not support magnet links, which is why I tried to build from source. I 'll try to get around that by converting magnet links into torrents locally for now.
Regards,
/Anders

**Comment by rakshasa** [comment]
Uninstall both rtorrent and libtorrent, build both from source.

**Comment by chros73** [comment]
> Ubuntu 16.04 LTS does not support magnet links

Errr... It should be 0.9.6/0.13.6, right? If so, then it should support magnet links.
Although I haven't used 32bit OS for a long time.

**Comment by genell** [comment]
The repository versions are indeed rTorrent 0.9.6/0.13.6 but does not seem to work with magnet links, though I might be doing something wrong. 

Removing the repo version and building from source was what I did just before stumbling upon the “undefined symbol”. 

As I said, I can use the repo version and convert magnets locally for now. 

Regards,
Anders

**Comment by chros73** [comment]
I think it's your settings (regarding problems with magnet links), take a look at [this issue](https://github.com/rakshasa/rtorrent/issues/645#issuecomment-344895122).

Also, you can try to build [rtorrent-ps-ch](https://github.com/chros73/rtorrent-ps-ch) on Ubuntu 16.x (I built it on 14.x, 17.x and Debian 9), but I suggest to use 64bit OS if you can.
