### ISSUE TITLE
run script on finished download

### ISSUE THREAD

**Issue by valantislevas** [rakshasa/rtorrent#662]
Hello i already put on my .rtorrent.rc

`method.set_key = event.download.finished,rename_srt,"execute2=/home/seeder/scripts/rename-el.sh,$d.get_name="
`
the rename-el.sh script is a simple command for rename like this

```
#!/bin/bash
rename 's/\.srt$/.el.srt/' *.srt
```

is possible to make it work? because now i have error

does anyone know how i can make it work? 
rTorrent 0.9.4

**Comment by chros73** [comment]
There was a similar issue like this: #557 

A. You need to pass the [full path of the download](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#getting-the-full-path-of-data-of-a-torrent) to your script, and not just `$d.get_name=`

B. You don't use the passed parameter in your bash script at all :)
- use logging in your script, e.g. `echo $some_var >> logfile.txt` to see what's going on

C. I'm not sure that rtorrent can seed downloads if you rename their files! :)
