### ISSUE TITLE
Error in option file: ~/.rtorrent.rc:64: Junk at end of input.

### ISSUE THREAD

**Issue by jduckett** [rakshasa/rtorrent#664]
Did a fresh compile and install.  Followed the instructions in the wiki to download a config template.

curl -Ls "https://raw.githubusercontent.com/wiki/rakshasa/rtorrent/CONFIG-Template.md" \
    | grep -A9999 '^######' | grep -B9999 '^### END' \
    | sed -re "s:/home/USERNAME:$HOME:" >~/.rtorrent.rc
mkdir ~/rtorrent

started rtorrent to test if everything was working and get the following error:

Error in option file: ~/.rtorrent.rc:64: Junk at end of input.

here is the offending line.

system.umask.set = 0027 # This is inverted to usual unix permissions, the example provided is for permissions of 750

edited the file and removed the comment.

restarted rtorrent and everything was cool.  seems like the parser doesn't like comments inline with settings, but, it could be something else.  I didn't investigate further.

**Comment by chros73** [comment]
Thanks, indeed.
Do you know that you can edit wiki pages? Try it out and close this issue afterwards.

**Comment by pyroscope** [comment]
well, it's reverted, but the close is still pending.
