### ISSUE TITLE
No issue, just a question about encryption

### ISSUE THREAD

**Issue by milesbenson** [rakshasa/rtorrent#670]
Hi there,

if i set 

encryption = require,require_RC4,allow_incoming,try_outgoing,enable_retry

will all transfer and connections be encrypted? It is not very well documentated what all those possibilities mean and what they do when combined. Thanks in advance for your help.

**Comment by chros73** [comment]
No, they won't.
Take a look at [here](https://github.com/rakshasa/libtorrent/issues/144) for more info.

And note that magnet links [won't work](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#supporting-public-torrents-magnet-links-udp-trackers-dht) this way.

**Comment by milesbenson** [comment]
Well, i alread read this one but it does not make things clear at all. When i use the line above, i only get connections to peers that seem to be encrypted (Flag E in ruTorrent). But what do i need to do to make sure that all traffic is encrypted. What is the difference between required and required_rc4?

**Comment by chros73** [comment]
Well, it can be the case. :)

> What is the difference between required and required_rc4?

I don't know.

> will all transfer and connections be encrypted?

That's an interesting question:
- the above setting only applies to peer-to-peer communication, nothing else
- that means that tracker (http (not https), udp) and dht communication will be still unencrypted

https://security.stackexchange.com/questions/90017/rc4-encryption-of-torrents-safely
https://security.stackexchange.com/questions/149378/what-is-torrent-encryption-and-does-it-make-my-traffic-anonymous

**Comment by milesbenson** [comment]
If you dont know what the difference is, how can you give advices how to user proper encryption? Sorry to be rude, but that does not help at all. I see you are willing to help, but not able to.

https announce is a must, but what do i have to do to get connection to encrypted peers only and using encrypted traffic as well?

**Comment by kannibalox** [comment]
Here's the start of some documentation for the command, a bit of it is just regurgitating what @chros73 said in the earlier ticket. Keep in mind though, bittorrent's encryption is less about data protection and more about avoiding traffic shaping.

> This command takes a comma-separated list of flags, as seen in `strings.encryption`, and uses them to determine how to handle connections to other peers (i.e. tracker and DHT connections are not effected by this setting). The flags are all applied simultaneously, which means that certain applied flags may not take effect (e.g. for ``prefer_plaintext,require_rc4``, plaintext will never used despite the flag being applied). *rTorrent* has support for both plaintext "encryption" (uses no extra CPU cycles, provides only obfuscation of the header) and RC4 encryption (encrypts the entire header and message, at the cost of a few CPU cycles), with flags to control the behavior of both

* ``none`` - The default, don't attempt any encryption
* ``allow_incoming`` - Allow incoming encrypted connections from other peers
* ``try_outgoing`` - Attempt to set up encryption when initiating a connection
* ``require`` - Require encryption, and reject to peers who don't support it
* ``require_RC4`` - Require RC4 encryption specifically
* ``require_rc4`` - Same as above
* ``enable_retry`` - If a peer is rejected for not supporting the encryption we need, retry the handshake
* ``prefer_plaintext`` - Prefer plaintext encryption

So for forcing secure connections, `require,require_rc4` is probably your best bet.

**Comment by milesbenson** [comment]
Thank you for clarifying.

**Comment by chros73** [comment]
> Sorry to be rude

No worries, that's why I wrote that I don't know.

@kannibalox : thanks for the detailed description, you can also put it on the wiki somewhere.

**Comment by wheelerlaw** [comment]
Wouldn't `encryption = require,require_RC4` be the same as `encryption = require_RC4`?

**Comment by kannibalox** [comment]
* `encryption = require,require_RC4` - This means require encryption, and specifically only allow RC4 encryption. No plaintext obfuscation or unencrypted connections allowed
* `encryption = require_RC4` - I haven't tested it, but looking at the code I believe it would only reject plaintext obfuscation; connections would either be entirely unencrypted or use RC4. 
* `encryption = require,require_RC4,enable_retry` - `enable_retry` only kicks in if a connection is dropped while unencrypted, so it doesn't do anything if encryption is required. You can see this in the `connection_info` log level

**Comment by Cubox-** [comment]
Sorry to resurrect this issue, but I wanted a quick confirmation.
If you have set-up `encryption = require,require_RC4`, does `allow_incoming` or `try_outgoing` do anything?

**Comment by chros73** [comment]
I don't understand your question, @kannibalox just answered exactly this right above.

**Comment by wheelerlaw** [comment]
@Cubox- Correct, they are redundant when setting `require` and `require_RC4`.

**Comment by wheelerlaw** [comment]
Which, in the year of our lord two thousand and nineteen, why on earth people are using non-encrypted communications is beyond me.

**Comment by chros73** [comment]
- uses more CPU
- tracker / trackerless communication can be still non-encrypted
- someone may use VPN

**Comment by kannibalox** [comment]
To add on to what @chros73 said, bittorrent's encryption spec is barely more than obfuscation, it provides essentially no security regardless of which client you're using.

**Comment by maisun** [comment]
How can I configure rTorrent to prefer encryption but not force it?
