### ISSUE TITLE
Error "Could not parse address." while starting

### ISSUE THREAD

**Issue by onestay** [rakshasa/rtorrent#676]
rtorrent immediately crashes after I start it with the error "rtorrent: Error in option file: ~/.rtorrent.rc:95: Could not parse address.".

On line 95 in my .rtorrent.rc I have "network.scgi.open_port = 5432". The rest of the config is pretty much the template.

**Comment by pyroscope** [comment]
well, how about adding the missing "localhost:" part?

**Comment by onestay** [comment]
In the docs it just says port.
I'll try that later.

**Comment by onestay** [comment]
Works now. Thanks!
