### ISSUE TITLE
event.download.finished not working

### ISSUE THREAD

**Issue by adammascherin** [rakshasa/rtorrent#684]
I'm trying to create a pushbullet notification when a download completes. I found [this tutorial](https://www.rapidseedbox.com/blog/push-notifications-pushbullet) and [this tutorial](https://www.rapidseedbox.com/blog/beginners-guide-pushbullet#pbh4) and I'm able to manually execute the script from terminal and I receive the notification successfully. But when I setup the event in the rtorrent.rc file, it doesn't work. This is the line I added:

`system.method.set_key = event.download.finished,notify_me5a,"execute=~/push_rtorrent.sh"`

I also tried different variations, like just method.setkey (without "system.") Can anyone help?

**Comment by pyroscope** [comment]
add a `log.execute` command to debug the error you made.

**Comment by adammascherin** [comment]
Can you be a bit more specific? Am I replacing `execute` with `log.execute`?

**Comment by adammascherin** [comment]
I added log.execute but it didn't help -- I couldn't see the command in the log. It doesn't seem to be executing it at all. I did some fooling around and changed event.download.finished to event.download.resumed and as soon as I restart rtorrent, I immediately received 100+ pushbullet notifications at once. This is what the line looks like:

works (when rtorrent restarts, it fires a notification for each torrent in rtorrent):
`system.method.set_key = event.download.resumed,notifyme,"execute.nothrow=push,\"test\",\"some\""`

doesn't work (when a download completes):
`system.method.set_key = event.download.finished,notifyme,"execute.nothrow=push,\"test\",\"some\""`

**Comment by adammascherin** [comment]
This was getting super frustrating. I started commenting out other set_key lines. I finally found that if I comment out the following line in rtorrent.rc, my event.download.finished event was fired:

`system.method.set_key = event.download.finished,filebot,"execute={.filebot/scripts-enabled/rtorrent-postprocess.sh,$d.get_base_path=,$d.get_name=,$d.get_custom1=}"`

I don't know what that line does exactly, but when it's uncommented, no other event.download.finished events work.

Any ideas what this is?

**Comment by chros73** [comment]
Well, me neither, you have to search for the `rtorrent-postprocess.sh` file and go through it to see what its  purpose is. Do you use rutorrent?

What happens if you replace `execute` to `execute.nothrow` in that line?

**Comment by adammascherin** [comment]
After commenting out the filebot line (see [comment above](https://github.com/rakshasa/rtorrent/issues/684#issuecomment-362462041)), my own event.download.finished started firing properly. Closing this issue as resolved.

**Comment by Quickboxfan** [comment]
Sorry guys issue is presume to be closed but idiot understand how exactly you got your issue resolved,can you give bash script I mean corrected bash script so that I can execute once for all,I Google all the pages but no where I got some one getting success except this thread,i would like it You create few steps to know how to correctly install pushbullet to get notifications.

**Comment by luckylittle** [comment]
I ended up having an issue which led me to this page. I believe that some of you may have a problem when kicking off HTTP API calls? I certainly had and found out why - perhaps it will be helpful for someone who will end up here as well ➡ 
* rTorrent uses XML-RPC for communication and when you execute a script via `event.download.finished` it captures the script's output
* If that output isn't valid XML-RPC (which e.g. HTTP responses aren't), it confuses the XML-RPC parser

Solution:
* In your script, use `/usr/bin/curl -s` for silent mode
* Make the call asynchronous so rTorrent doesn't wait for the response (rung in the background via `&`)
