### ISSUE TITLE
rtorrent release or commits to master only

### ISSUE THREAD

**Issue by binhex** [rakshasa/rtorrent#687]
Hi, i would kindly like to ask if rtorrent will produce a github "release" in the future or whether we are looking at commits to master only going forward?. 

It's been a while since the last release (2015) and if that will be the last official release then i will switch to referencing the master branch instead, if on the other hand you simply feel there are too many bugs to create a release at this time then i will just wait for the next release.

Please don't take this issue in the wrong context, i am NOT pushing you to create a release, i simply want to know your thoughts going forward.

**Comment by rakshasa** [comment]
Once the feature-bind branch is ready, it will be merged and a release will be made.

Due to personal issues and the need to create rtorrent-vagrant for testing the going has been slow. Hoping to get it done in a month or two.

**Comment by binhex** [comment]
Ok no problems and thanks for clarifying.
