### ISSUE TITLE
Delete API / Settings?

### ISSUE THREAD

**Issue by opoei** [rakshasa/rtorrent#688]
Kind of curious if there are settings (if not, can someone point me towards an API or the code to do so) to clean up downloaded files based on either of the following:
1) Last active time ( last time the file was used for uploads)
2) "Created On"

**Comment by kannibalox** [comment]
The [pyrocore ](https://pyrocore.readthedocs.io/en/latest/) tools, specifically [rtcontrol](https://pyrocore.readthedocs.io/en/latest/usage.html#rtcontrol) can do it e.g. `rtcontrol -/3 is_complete=yes -s active --dry-run --delete` would delete the 3 oldest completed torrents, according to the last time a peer was connected for them.
