### ISSUE TITLE
Download on fast SSD, on finish move to HDD for long term seeding

### ISSUE THREAD

**Issue by Ondjultomte** [rakshasa/rtorrent#692]
Is it possible to move a finished torrent to a new location and continue to seed?

**Comment by kannibalox** [comment]
Absolutely, see the wiki for examples, e.g. https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#move-completed-torrents-to-a-fixed-location

**Comment by pyroscope** [comment]
Dupe, see #547
