### ISSUE TITLE
Something totally weird happening... Downloading, but not?

### ISSUE THREAD

**Issue by trancephorm** [rakshasa/rtorrent#693]
Leeching section is empty (nothing is downloading, yet I have many seeds), but some constant download of around 24 KB/s is happening. Can't find for the life of mine what is being downloaded. Anyone experienced the same? rtorrent 0.9.6 / librorrent 0.13.6

**Comment by chros73** [comment]
Do you have partially finished downloads? (When you selects files to off in a download.)

**Comment by trancephorm** [comment]
I don't have anything in incomplete section. How do you "select files to off in download"?

**Comment by pyroscope** [comment]
Traffic indicators indicate *any* traffic, not just "upload" or "download". Peer sync causes traffic. Can be closed.

**Comment by trancephorm** [comment]
I'm pretty positive it's not the peer sync because I have another rtorrent machine with the same rtorrent and same tracker running many torrents, and it doesn't behave like that. The problematic one just recently started to have that phantom downloads, before everything was ok.

**Comment by trancephorm** [comment]
Turns out it was some peer sync. But that was some intensive sync with just one IP, I don't really know why.

**Comment by rakshasa** [comment]
Do you know which client the peer used?

**Comment by trancephorm** [comment]
I don't know... Was trying to find out but I didn't know how.
