### ISSUE TITLE
cygwin64 on Win10_64: make fails at dht_manager.cc

### ISSUE THREAD

**Issue by kilves76** [rakshasa/rtorrent#694]
Make fails at dht_manager.cc with a bunch of errors, not a programmer so no idea what all this means.
Doesn't seem to have any relation to previously reported cygwin issues.
My setup should be ok, just compiled mktorrent without issues.

configure messages and log: https://pastebin.com/X9WQireb
make output: https://pastebin.com/r04VXKzg

**Comment by rakshasa** [comment]
Looks like an issue of header files not being included or different versions.

**Comment by pyroscope** [comment]
If you're on W10, use Docker.
