### ISSUE TITLE
Ending rtorrent.rc config to allow content downloading

### ISSUE THREAD

**Issue by nbah07** [rakshasa/rtorrent#698]
Hello,
This rtorrent.rc had some modifications from what I understood would suit my network/enviroment, based on documentation and examples. Unfortunately I am unable to trigger start download of this magnet, which is seen at last line of the following file:
What should fix this?

[rtorrent.txt](https://github.com/rakshasa/rtorrent/files/1778223/rtorrent.txt)

**Comment by kannibalox** [comment]
Your config is currently set to have DHT disabled, see this section of the wiki on how to enable it and set it up: https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#supporting-public-torrents-magnet-links-udp-trackers-dht

**Comment by nbah07** [comment]
this given magnet does not work, but others magnets did, not present on testing before/after procedure though.
Another question: How to priority OFF all files when file list becomes huge, as a collection contained torrent. That way, only require user to switch ON by demand, wanted files.

**Comment by chros73** [comment]
From the [User Guide](https://github.com/rakshasa/rtorrent/wiki/User-Guide#file-list-view-keys): push `*` multiple times on the File List view.
