### ISSUE TITLE
FPE on startup of rtorrent

### ISSUE THREAD

**Issue by rayfun** [rakshasa/rtorrent#703]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
rtorrent Version: 0.9.6-2build1

After having added a torrent using a magnet link rtorrent crashes. Also when trying to start rtorrent again.

How can I fix this?

Caught Floating point exception, dumping stack:
rtorrent() [0x415ca7]
rtorrent() [0x4528ec]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f98d69be4b0]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZNK7torrent8FileList16chunk_index_sizeEj+0x27) [0x7f98d7e823e7]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0x9f152) [0x7f98d7ed2152]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0x9f410) [0x7f98d7ed2410]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0x9f56b) [0x7f98d7ed256b]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xd2c9f) [0x7f98d7f05c9f]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xcf920) [0x7f98d7f02920]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xcfcb0) [0x7f98d7f02cb0]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent9PollEPoll7performEv+0xd1) [0x7f98d7e71d31]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent9PollEPoll7do_pollEli+0x61) [0x7f98d7e71e51]
/usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x124) [0x7f98d7ead374]
rtorrent() [0x412064]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f98d69a9830]
rtorrent() [0x415329]
Aborted

**Comment by rakshasa** [comment]
Old.
