### ISSUE TITLE
rtorrent config question

### ISSUE THREAD

**Issue by CardSnap** [rakshasa/rtorrent#704]
Instead of using `/home/USERNAME/rtorrent` can I use the following in my .rtorrentrc and not have issues?
```
method.insert = cfg.basedir, private|const|string, (cat,"~/rtorrent/")
```
```
method.insert = cfg.basedir, private|const|string, (cat,"$HOME/rtorrent/")
```
I ask because it'd make it easy to backup the config among my dotfiles.

**Comment by pyroscope** [comment]
2nd no, 1st might (try, or follow EVERY usage for ~ working).

Also, https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-system-env
