### ISSUE TITLE
Can't download any torrents

### ISSUE THREAD

**Issue by clidx** [rakshasa/rtorrent#705]
Suddenly, I can't download any torrents. Seeding is fine but anything that needs writing to disk doesn't work.

Before, I was getting errors like these

Failed to prepare file 'xyz' Could not open file: Permission denied
Could not create directory '/storage/torrents': No such file or directory (17:14:50) Could not resume download: Could not create directory '/storage/torrents': No such file or directory  -that's the parent download dir
Failed to save session torrents

Occasionally I would get a "Resource temporarily unavailable" error.

I checked the permissions on all the files/folders (downloads, session dir etc) and they're all correct.

I tried a new session, added a torrent and it would not download. Now I don't get any errors even when reverting to the old session, instead it just says "Hashing:" without a %age and doesn't do anything.

I tried setting the session directory to tmpfs, didn't change anything.

Here's my .rtorrent.rc which has been working fine so far. I'm not using Pyroscope even though the file looks like I am.

```
# general
throttle.global_up.max_rate.set_kb = 1300
throttle.global_down.max_rate.set_kb = 5700 
throttle.max_uploads.set = 100
throttle.max_uploads.global.set = 250
max_downloads_global = 2
trackers.numwant.set = 80
network.http.max_open.set = 100
network.max_open_files.set = 600
network.max_open_sockets.set = 300
protocol.encryption.set = allow_incoming,enable_retry,require_RC4
pieces.hash.on_completion.set = no
system.umask.set = 0755

# range for listening port
network.port_range.set = 23772-23772
network.port_random.set = no

# tracker-less torrent support
dht.mode.set = disable
protocol.pex.set = no
trackers.use_udp.set = no

# peer settings
throttle.min_peers.normal.set = 20
throttle.max_peers.normal.set = 60
throttle.min_peers.seed.set = 30
throttle.max_peers.seed.set = 80

#
# CORE settings (mostly keep these, but still check them)
#
network.http.capath.set = /etc/ssl/certs
encoding.add = utf8

directory.default.set = /storage/torrents
session.path.set = /storage/.rtorrentsession

# SCHEDULE: Watch directories
schedule = watch_directory,5,5,load_start=/storage/torrentfiles
schedule = tied_directory,6,5,start_tied=
schedule = untied_directory,7,5,stop_untied=

# SCHEDULE: Watch disk space
schedule = low_diskspace,15,60,close_low_diskspace=1000M

# EVENTS: Logging (don't log "opened", or you get swamped at startup)
method.set_key = event.download.inserted_new,log,"print=\"LOADED \",$d.name=,\" [\",$convert.date=$system.time=,\"]\""
method.set_key = event.download.finished,log,"print=\"COMPLETED \",$d.name=,\" [\",$convert.date=$system.time=,\"]\""
method.set_key = event.download.closed,log,"print=\"CLOSED \",$d.name=,\" [\",$convert.date=$system.time=,\"]\""

# UI/VIEW: Sort "seeding" by ratio
view.sort_current = seeding,greater=d.ratio=
```

I'm running 0.9.6 on Arch Linux. It's not a hardware problem - no other apps have any issues and ZFS says the pool all this stuff is on is healthy. I updated the kernel (lts) and ZFS around the same time but I can't pin it down.
What could the problem be?

**Comment by kannibalox** [comment]
`system.umask.set = 0755` doesn't do what you think it does. Since umask is a bit mask, the permission the file ends up getting created with is actually the octal XOR of the input. So `0755` means the files are getting created with `022` permissions.

> I checked the permissions on all the files/folders (downloads, session dir etc) and they're all correct.

Define correct: are the user and group from the process vs the file permissions in alignment, and are the permissions set to something that would let the user/group write and read all files? Do all the directories have the executable bit set appropriately?

**Comment by clidx** [comment]
Aha! Commenting that out fixed it. The reason it was getting stuck on Hashing is that an empty file was created but never deleted from when I added a torrent previously while trying to troubleshoot. Strange that line in the config was being ignored all this time until suddenly it wasn't. Thanks.
