### ISSUE TITLE
Is xmlrpc broken on master?

### ISSUE THREAD

**Issue by FallingSnow** [rakshasa/rtorrent#709]
Unable to get xmlrpc to run when built with latest master.
```
$ xmlrpc localhost:5000 system.listMethods
Failed.  Call failed.  HTTP POST to URL 'http://localhost:5000/RPC2' failed.  libcurl failed even to execute the HTTP transaction, explaining:  Empty reply from server.  (XML-RPC fault code -504)
```

**Comment by tashkas1** [comment]
xmlrpc localhost:5001 get_upload_rate ""
Failed.  Call failed.  libcurl failed to execute the HTTP POST transaction, explaining:  Empty reply from server.  (XML-RPC fault code -504)

**Comment by FallingSnow** [comment]
I decided to use deluge instead.

**Comment by tashkas1** [comment]
well my rtorrent stuck sometimes 

ldd /usr/bin/rtorrent |grep curl
        libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f08ca72e000)
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2g zlib/1.2.11 libidn2/2.0.2 libpsl/0.18.0 (+libidn2/2.0.2) librtmp/2.3
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy PSL
