### ISSUE TITLE
ipfilter p2p format proposal

### ISSUE THREAD

**Issue by skydrome** [rakshasa/rtorrent#71]
I propose to change the ipfilter mechanism to support the p2p standard

quick example: http://www.iblocklist.com/list.php?list=bt_level1

<string of who owns this range>:<address start>-<address end>

Detected AP2P on Dadehaye Donyaye Door proxy:2.184.193.227-2.184.193.227
Mediamarket S.p.A:2.228.1.248-2.228.1.251
Fastweb Networks MEDIAMARKET public subnet:2.228.6.72-2.228.6.75
Mediamarket S.p.A:2.228.122.52-2.228.122.55
Mediamarket S.p.A:2.228.124.180-2.228.124.183

this could also introduce the ability to show the <string of who owns this range> in a log file when a block is made.

**Comment by MindTooth** [comment]
Really would like to try rTorrent, but sadly the process of including a filter list includes a custom script.  So I would really love to see this feature as well.  I'm sadden to say that I can't contribute code for this, otherwise I'd submit some.
