### ISSUE TITLE
Is xmlrpc broken on master?

### ISSUE THREAD

**Issue by tashkas1** [rakshasa/rtorrent#710]
xmlrpc localhost:5000 system.listMethods
Failed.  Call failed.  HTTP POST to URL 'http://localhost:5000/RPC2' failed.  libcurl failed even to execute the HTTP transaction, explaining:  Empty reply from server.  (XML-RPC fault code -504)

well my rtorrent stuck sometimes

ldd /usr/bin/rtorrent |grep curl
libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f08ca72e000)

curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2g zlib/1.2.11 libidn2/2.0.2 libpsl/0.18.0 (+libidn2/2.0.2) librtmp/2.3
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy PSL

Using 'epoll' based polling.
Using 'epoll' based polling.
Using 'epoll' based polling.
Closed XMLRPC log.

**Comment by kannibalox** [comment]
I suspect you are pointing the xmlrpc command at the port opened by network.scgi.open_port, which will not work. I'd suggest using a tool like [rtxmlrpc](https://pyrocore.readthedocs.io/en/latest/usage.html#rtxmlrpc) from the pyrocore suite to skip the webserver and test the endpoint directly.

**Comment by tashkas1** [comment]
have no clue how to install rtxmlrpc 

lighttpd.conf
scgi.server = (
     "/RPC2" =>
          ( "127.0.0.1" =>
               (
                "host" => "127.0.0.1",
               "port" => "5000",
                "check-local" => "disable"
                )
         )
)
rtorrent.tc

scgi_port=127.0.0.1:5000

**Comment by kannibalox** [comment]
https://pyrocore.readthedocs.io/en/latest/installation.html from the same site that I linked, if you want to install it.

You need to point `xmlrpc` at the port lighttpd is listening on, not the port rtorrent is listening on.

**Comment by Loader009** [comment]
I had the same issue.
Using scgi_port = 127.0.0.1:5000
instead of scgi_port = localhost:5000
solved it for me.
