### ISSUE TITLE
How to adjust the max_file_size parameter in rtorrent's advanced settings?

### ISSUE THREAD

**Issue by kfen** [rakshasa/rtorrent#713]
How to adjust the max_file_size parameter in rtorrent's advanced settings?

System debian9 rt0.9.6

In torrent.rc tried set_max_file_size = *, after saving restart rt or not start, ask no one know how to call max_file_size rtorrent.rc this parameter?

**Comment by kannibalox** [comment]
That command is deprecated, use `system.file.max_size.set` instead. What error are you seeing when you start it? Also, I'm assuming `*` is a placeholder since the command takes a number (in bytes), what actual value are you using?

**Comment by kfen** [comment]
Thanks for the answer to the problem, I called max_file_size to -1.

There is also a small problem shown in Figure: https://images2.imgbox.com/02/39/XSqXFD6n_o.png

Every time rt is started again, this is turned off by opening the listening port, but I have set the listening port range pointer, see my rtorrent.rc:

### Networking
network.port_range.set = 51333-51333
network.port_random.set = no
dht.mode.set = auto
protocol.pex.set = yes
trackers.use_udp.set = yes

What is the solution to this situation?

**Comment by kannibalox** [comment]
Try `network.port_open.set = yes`

**Comment by gwern** [comment]
If this is deprecated (and also it doesn't work to begin with), why does the man page for `0.9.6-3build1` still say

       File-system related settings.

       max_file_size = size
              Set the maximum size a file can have. Disable by passing -1.

? And the error message for too-large files invokes `max_file_size`?

**Comment by kannibalox** [comment]
It's been deprecated since 0.7.0, but was only actually removed in version 0.9.7. Can you provide a more specific example of an error message? According to https://github.com/rakshasa/libtorrent/blob/master/src/torrent/data/file_list.cc#L443, that message hasn't changed in many years.

**Comment by gwern** [comment]
The error message said exceeds 'max file size', and the man page only mentions `max_file_size`; nothing about it being deprecated or any other replacement. Whatever version it was removed in, it must've been removed in mine, because setting it caused rtorrent to exit on startup, and very puzzled, googling led me here to find what setting I actually needed to set.

**Comment by kannibalox** [comment]
It was removed in 0.9.7, however 0.9.6 probably needs the `-D` flag to enable the deprecated commands. While I do agree an updated man file is needed, rtorrent has no control over the older builds/files that distros might ship. https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html is currently the most complete documentation for commands, for future reference.
