### ISSUE TITLE
Move to Label name folder & Hardlink

### ISSUE THREAD

**Issue by Qwatuz** [rakshasa/rtorrent#714]
Is it possible to have two event.download.finished commands?

My aim is to have files moved to a folder of their Label name on completion and to also hardlink the completed files/folders to a different directory.

My move to label folder name is:

`method.insert = d.get_finished_dir,simple,"cat=/home/user/rtorrent/,$d.get_custom1="
method.set_key = event.download.finished,move_complete,"d.set_directory=$d.get_finished_dir=;execute=mkdir,-p,$d.get_finished_dir=;execute=mv,-u,$d.get_base_path=,$d.get_finished_dir="
`

I stumbled upon a hardlink on completion command:

`method.set_key=event.download.finished,move_complete,"execute=cp,-al,$d.base_path=,/home/user/rtorrent/"`

When I had them both enabled it would only run the move to label name. Is it possible to merge them into one command?

Thanks!

**Comment by chros73** [comment]
You can have multiple `method.set_key` for the the same event (e.g. `event.download.finished`) but with a different "key", you used the same key for both of them: `move_complete`

Or you can use only one that calls an external script that will do everything you want with e.g. [execute.nothrow](https://github.com/rakshasa/rtorrent/blob/master/src/command_local.cc#L324)

**Comment by chros73** [comment]
How does the rtorrent part look like?

**Comment by chros73** [comment]
What OS, fs do you use?

On the most recent OSs you [can't hardlink a directory](https://askubuntu.com/questions/210741/why-are-hard-links-not-allowed-for-directories)!
That can be a problem, since `d.base_path` can point to a file or a directory (if it's a multi-file download).

Lastly, don't use `d.base_path` but this [replacement method](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#getting-the-full-path-of-data-of-a-torrent) instead.

**Comment by chros73** [comment]
> do I simply add the new line method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))" and then replace d.get_base_path for each line with d.data_path?

Yes, that's correct.

> it broke my original move to folder

You have to work in smaller chunk of code and debug what you try to do. If it works then you can add more functionality into a command and start the workflow from the beginning. :)

**Comment by chros73** [comment]
@Qwatuz , did you managed to make it working?

**Comment by Qwatuz** [comment]
@chros73 I did not. I am now using rtorrent 0.9.7 so it has to be reworked from what I can tell.

**Comment by Qwatuz** [comment]
Hey @chros73 I thought id give this another try and have made a bit of progress!

I am using this:

```
method.insert = d.get_finished_dir, simple, "cat=~/Download/,$d.custom1="
method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="
```
Found in this url: https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#move-completed-torrents-to-a-fixed-location


My actual settings are:


```
method.insert = d.get_finished_dir, simple, "cat=/mnt/unionfs/downloads/torrents/completed/,$d.custom1="
method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="
```

```
method.insert = d.get_finished_dir2, simple, "cat=/mnt/unionfs/downloads/torrents/completed/#Hardlinks/,$d.custom1="
method.insert = d.data_path2, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"
method.insert = d.move_to_complete2, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=cp,-al,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete2,"d.move_to_complete2=$d.data_path2=,$d.get_finished_dir2="
```


This works except it will set the Save Path in rtorrent as `/mnt/unionfs/downloads/torrents/completed/#Hardlinks/<label>`.

I'm not sure how I can make sure that the #Hardlinks path is ignored - any ideas?
