### ISSUE TITLE
rtorrent freezes

### ISSUE THREAD

**Issue by tashkas1** [rakshasa/rtorrent#718]
rtorrent freezes when i/o hits 100% is there way to make priorities for rtorrent

**Comment by kannibalox** [comment]
You can use [ionice](https://linux.die.net/man/1/ionice) to set the scheduling class for processes, but if IO requests are blocked, then there's not much rtorrent can do about that. You'll need to either figure out what's causing it to hit 100%, or upgrade your hardware to something that doesn't. You haven't mentioned if it's rtorrent causing the bulk of the IO, but if it is, this page has some tips on tuning rtorrent: https://github.com/rakshasa/rtorrent/wiki/Performance-Tuning#reduce-disk-usage
