### ISSUE TITLE
my torrent disappears for no reason

### ISSUE THREAD

**Issue by lainiwaku** [rakshasa/rtorrent#719]
ok so i have a weird bug, randomly (sometime it happen after hours, sometime after days) all my torrent disappears, but when i say they disappears, they are really deleted, even when i ftp connect to my server, the fils are not in the "downloads" folder.
i tried to create a "test" folder inside the "downloads" folder, and the test folders are never deleted only my torrents are deleted
it's hurt me well since it's very  hard to seed with this bug

**Comment by Micdu70** [comment]
Hello, do you use a front-end (example: ruTorrent web interface)? If yes, did you apply a "ratio" rules on your torrents? If no, do you accept to send, in private message, IP of your rtorrent instance/seedbox? I will check if you have a security breach.

**Comment by lainiwaku** [comment]
hi, didn't found how to send PM on github but it's ok  i can post ip her i didn't have sensitive thing  anyways  my seedbox ip is https://176.31.250.206/
i access rutorrent with this path https://176.31.250.206/rutorrent/

**Comment by pyroscope** [comment]
The most likely reality is you or someone else has configured auto-delete, but you don't realize, making a software bug out of that config feature. Or else you have on-completion auto-move, i.e. the files are simply elsewhere now.

**Comment by Micdu70** [comment]
ruTorrent has no security authentification, SCGI Web access mount point "/RPC2" has no security authentification...

If you want fast & secure seedbox installation, you can use a recent script for that. This one is nice (scroll down to see how-to install it): [](https://quickbox.io/)

**Comment by zxvfxwing** [comment]
Hi, it happened to me multiples times since the recent [update](https://www.archlinux.org/packages/?sort=-last_update&name=rtorrent).

I'm using ruTorrent too, but I set up a basic_auth into my nginx configuration.

**Comment by rakshasa** [comment]
Closing as this is most likely config issue.
