### ISSUE TITLE
Adding torrent prepends '/' to path

### ISSUE THREAD

**Issue by clidx** [rakshasa/rtorrent#720]
Adding a torrent adds a '/' to the beginning of the path. So let's say I hit backspace and type /dir/file.torrent

It errors with 'Reading torrent file failed: "//dir/file.torrent"' and if I do it with dir/file.torrent, it doesn't add a '/'.

It started doing this suddenly, I don't think anything on the system changed. Also adding torrents via xml-rpc doesn't work either but I have never tried this method before so don't know if it's right.

> % xmlrpc localhost:6001 load.start_verbose /dir/file.torrent
> Failed.  Call failed.  RPC failed at server.  Unsupported target type found..  (XML-RPC fault code -501)

Why would it do this?

**Comment by pyroscope** [comment]
Because the PR for the fix doesn't get merged. Just close this dupe, the issues are a mes as it is.
