### ISSUE TITLE
Move completed torrents to different directory depending on watch directory

### ISSUE THREAD

**Issue by jarjarbnks** [rakshasa/rtorrent#721]
Hi guys,
I've been using rtorrent for quite some time though I still consider myself a newbie since rtorrent is "configure and forget" solution. After setting up new hardware I had to configure everything from scratch. I've used the wiki installation guide and it all went smooth up until configuration section.

I'd like to move completed torrents to different directory depending on watch directory. I used this from wiki:

`schedule2 = watch_directory_1,10,10,"load.start=/Download/watch_stuff1/*.torrent,d.custom1.set=~/Download/stuff1/"
method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.custom1="`

But when starting rtorrent with this I get
Error in option file: ~/rtorrent/rtorrent.d/watch-dirs.rc:22: Invalid key.

and line 22 is:
`method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"`

Any idea why?

**Comment by kannibalox** [comment]
That's the error you get when trying to re-define a method. You probably have it defined in a different .rc and can just remove it from watch-dirs.rc.

**Comment by jarjarbnks** [comment]
True that, after commenting this line out, no error shows up. Nevertheless, all downloaded files end up in /work directory (default directory) regardless of watch directories. That is when I put .torrent into /watch/stuff1 or /watch_stuff2 it all ends up /work instead of /stuff1 and /stuff2 respectively.

Anyway, I'll more googling and when I find the solution I will post here for future reference

**Comment by chros73** [comment]
I move stuff with [this](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc#L97). Take a look, maybe you like the setup.

**Comment by pyroscope** [comment]
Or this: https://rtorrent-docs.readthedocs.io/en/latest/use-cases.html#versatile-move

Which doesn't even require multiple watches, depending on your criteria.

**Comment by suburbanafro** [comment]
@jarjarbnks I recently tried to add this to my rtorrent.rc and have been getting similar issues. Did anyone ever find a solution to this problem? If not I'll probably take on @pyroscope 's approach.

**Comment by pyroscope** [comment]
Use log.execute to debug.

**Comment by gh3rann** [comment]
@jarjarbnks -- what worked for me was to check on the .rtorrentrc file, since I had already declared "d.data_path" somewhere above. 
By commenting one of them out, I got it to run with no issues.
