### ISSUE TITLE
Moving Away from Github

### ISSUE THREAD

**Issue by ghost** [rakshasa/rtorrent#725]
For a torrent client as important as rtorrent I think it shouldn't be hosted on Github, which is now owned by Microsoft. Maybe it could be considered to move to Gitlab? Gitlab is itself FOSS which is great. I believe you made rtorrent free software because you believe in the spirit of free software, but continuing to stay on Github would go directly against that spirit and it would be quite ironic.

https://www.bloomberg.com/news/articles/2018-06-03/microsoft-is-said-to-have-agreed-to-acquire-coding-site-github

**Comment by rakshasa** [comment]
If this was 15 years ago I would have agreed, however the world has moved
on and MS is no longer the big enemy of FOSS it used to be.

I'm way more worried about how google, facebook and twitter are
manipulating people's filter bubbles on a massive scale, and the way they
censor and suppress political views they disagree with.

**Comment by chros73** [comment]
> I'm way more worried about how google, facebook and twitter are
manipulating people's filter bubbles on a massive scale, and the way they
censor and suppress political views they disagree with.

Unfortunately this is only the tip of the iceberg ...

**Comment by a7lan** [comment]
> If this was 15 years ago I would have agreed, however the world has moved on and MS is no longer the big enemy of FOSS it used to be.

Skype, Nokia...

**Comment by MindTooth** [comment]
> > If this was 15 years ago I would have agreed, however the world has moved on and MS is no longer the big enemy of FOSS it used to be.

> Skype, Nokia...

[Embrace, extend, and extinguish](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish) comes to mind 👍   Guess we just need to wait and see.  Really bad if the sceptics get it right, but lets not hope so 🍺
