### ISSUE TITLE
Freezes X(needs X restart) when (trying to)run from rtorrent.desktop file in chromium.

### ISSUE THREAD

**Issue by mhertz** [rakshasa/rtorrent#726]
I have an issue with rtorrent when build from feature-bind branch, but isn't an issue on latest stable v0.9.6, and the log is empty so at whits end honestly.

I have made a 'rtorrent.desktop' file in '~/.local/share/applications/', which runs a shell-script i've made whenever clicking on a magnet/torrent in chromium(starts vpn and rtorrent with detach in background, if not running already, and loads magnet/torrent) and this worked fine in latest stable, but now always fails on rtorrent-ps from feature-bind branch, and I thought it was one of pyroscope's additions that did this, but now after building vanilla feature-bind branch there is same issue. I didn't understood why it also happened on regular rtorrent-ps, but found it was because of being run from a 8 color terminal in this way. 

It's not related to my script at all, because i've also changed the rtorrent.desktop file to instead just run 'rtorrent %U', which works on the stable rtorrent, but also fails with feature-bind branch.

If run from a terminal i.e. 'rtorrent(or script) '<magnet_url/torrent-path>', then it works fine, and if changing the rtorrent.desktop to 'urxvtc -e rtorrent %U', then also it works fine. It also works fine, of-course, through "non-X" from a VT with zsh(or bash).

It's just strange, as i've never seen a difference between running directly or from desktop file, with other clients i've used before with shell-scripts i've made for them, e.g. deluged/deluge-console and qbittorrent-nox.

Note, the freezing happens without the magnet/torrent even being added to the queue - it simply fails running from chromium(xdg-open) with a "$1" argument and freezes X on the way down(and empty logs).

Thanks alot in advance for any insight or tips/comments :)

(I'm using %U in desktop file and "$1" in shell-script to load magnet/torrent directly into rtorrent, if not rtorrent running already, or if it is already running I use xmlrpc2scgi.py to load it, and am not using watch folders)

(I'm using fully up2date arch-linux btw.)

EDIT: Hmm, after thinking about it, this sounds like a chromium bug and not rtorrent? But why only happen on feature-branch as opposed to stable v0.9.6??? Damn, I would hate never being able to go any higher than v0.9.6 in the feature because of this "workflow-issue" of mine... I always start torrents by selecting them from a browser and then they are loaded in the background, and then I have a shell-function to attach to rtorrent again to monitor/make-changes, if needed later on. Also, because i've just gotten my feet wet with rtorrent just now, and was thinking to migrate to rtorrent-ps-ch or atleast vanilla feature-bind.

-Martin.

**Comment by chros73** [comment]
Is it the same with master branches as well?

**Comment by mhertz** [comment]
Thank you chros :) Yes, good question, which I should have tried too, but it is the same. I realize that this is a very special scenario, and that it probably isn't a rtorrent issue, since 'rtorrent "$1"' works fine, but just not together with xdg-open. Actually, I have an issue also with the stable release where, maybe once in 10 - 20 runs, it will load and download fine, but after my script closes everything down in background(namespaced-openvpn/rtorrent/detach), then X is also frozen and need restart, but only happens rarely - this issue now is more annoying because happens every-time and never even loads torrent. I don't use any special settings at all, just a few for regular stuff like peer-amount and enabling features etc. Well, as rtorrent works from terminal, and just is an issue through xdg-open, then I'll close this issue down to not "pollute" and try reverting to earlier chromium versions(and whatever package xdg-open is in) and see if anything changes. As last resort, i'll have to use rtorrent like all of you does(without xdg-open). Also, i'm on public trackers, so don't like running to long(despite the vpn, i'm a little paranoid) + hate having too much running in background as it is, and I rarely even download, just wanted it for when needed. Still if anyone has any input, i'll gladly hear it of-course.

Thanks again chros for your help buddy, you're a good guy! :)

CU, Martin.

**Comment by mhertz** [comment]
... Just for others finding this possibly in a google search, then i'll just add to this that I have found a succesful workaround! :)

Note, I edited the previous post with some extra info also, e.g. an error message about polling epoll failed and that it's solely a chromium issue because 'xdg-open magneturl' works fine from terminal.

Anyway, as rtorrent non-stable git branch-builds fails loading direct from chromium, including through dtach, then I found it works succesfully through screen for some reason! :)

I only installed and used dtach, because I normally don't use screen/tmux because my WM(dwm) already provides most of that functionality except the detaching/attaching part which I haden't had a use for until switching from deluge-console to rtorrent. Note if using the rtorrent-ps[-ch], then you need either add 'term screen-256color' to your .screenrc, or add '-T screen-256color' to your screen command. Note, I know tmux is the better term-multiplexer, but as just for this simple job, then there's no difference, and so I preferred screen, as opposed to tmux which adds in 2 extra deps and in total has twice the foot-print.

Lastly, the issue I described about rtorrent sometimes freezing X when being killed from script, even though it's a gracefull "kill"(pkill uses by default sig-15), then feature-bind freezes X every time, but I fixed it by instead using signal 2, so 'pkill -2 rtorrent'.

All good now :)
