### ISSUE TITLE
0.9.7 / 0.13.7 still unstable ?

### ISSUE THREAD

**Issue by crazy-max** [rakshasa/rtorrent#737]
From the wiki [home page](https://github.com/rakshasa/rtorrent/wiki#download-links), 0.9.7 / 0.13.7 are marked unstable but not on [releases page of GitHub](https://github.com/rakshasa/rtorrent/releases).
Who am I to believe? :sweat_smile:

**Comment by chros73** [comment]
:) The Wiki. An example from [Linux kernel version numbering](http://www.linfo.org/kernel_version_numbering.html):
_"... even numbers indicated a stable release, that is, one that was deemed fit for production use ... Likewise, odd numbers, ... have historically represented development releases."_

**Comment by crazy-max** [comment]
Ok so you should change the flag to pre-release on releases page, just to be aware of no?

**Comment by crazy-max** [comment]
I thought you were using the ["semantic versioning"](https://semver.org/)

**Comment by kannibalox** [comment]
Not all projects use the same version convention as the kernel, I'd prefer that @rakshasa weighed in on the distinction (assuming there even is one).

**Comment by rakshasa** [comment]
Github page is just the released versions nothing more, while the wiki distinguishes between stable/unstable depending on if a release has been used for a while without serious issues or not.

I never list new releases as stable.

**Comment by kannibalox** [comment]
Thanks.
