### ISSUE TITLE
Bumped version to 0.6.7.

### ISSUE THREAD

**Issue by mvegetto** [rakshasa/rtorrent#746]
configure.ac	Bumped version to 0.6.7.	10 days ago

It should be 0.9.7.

**Comment by pyroscope** [comment]
How about looking at the actual diff? Then close this.

**Comment by mvegetto** [comment]
It's probably just a typo, currently checking this new version out.

**Comment by mvegetto** [comment]
Confirmed that this is a typo, this will confuse people when using git checkout v0.13.7.

**Comment by pyroscope** [comment]
No it won't.

    $ git tag -ln | tail -n1
    v0.9.7          Release of rtorrent version 0.9.7.

Just stop this useless discussion and close the ticket already, nobody will rewrite git history for a mere commit message typo.
