### ISSUE TITLE
Error opening terminal: unknown for docker daemon mode

### ISSUE THREAD

**Issue by calvintam236** [rakshasa/rtorrent#747]
Hi,

I have build the [docker image for `rtorrent`](https://github.com/calvintam236/docker_rtorrent), but it seems `rtorrent` cannot run without `-it` flag in daemon mode. I get `Error opening terminal: unknown` message. Is there a way to just run it and print out logs on non-interactive screen?

**Comment by rakshasa** [comment]
Yes, check the wiki.

**Comment by rakshasa** [comment]
There are extensive logging options, and an option to disable ncurses.

**Comment by kodsu** [comment]
Just in case someone finds this problem : the solution was to add `system.daemon.set = true` in the `.rtorrent.rc` file.
My rtorrent.service looks like this :

```
[Unit]
Description=rTorrent system daemon
After=network.target

[Service]
Type=simple
User=rtorrent
Group=rtorrent

ExecStartPre=/bin/rm -f /srv/torrent/.session/rtorrent.lock
ExecStart=/usr/bin/rtorrent -n -o import=/srv/torrent/.rtorrent.rc

Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
```
