### ISSUE TITLE
rtorrent-0.9.7 fails to compile if ncurses was built with "-with-termlib" - "SysV or X/Open-compatible Curses header file required"

### ISSUE THREAD

**Issue by ss23** [rakshasa/rtorrent#749]
> --with-termlib: When building the ncurses library, organize this as two parts: the curses library (libncurses) and the low-level terminfo library (libtinfo). [...]

This issue is fairly well documented through the web (see https://github.com/nzbget/nzbget/issues/188 https://moc.daper.net/node/1469 https://github.com/varnishcache/varnish-cache/pull/2331).

I'm not sure on the best way to solve it, but there's a patch in Gentoo which fixes it for now: https://658390.bugs.gentoo.org/attachment.cgi?id=536300

If this is the desired way to fix the issue, I can create a pull request, otherwise it looks simple enough that someone else can solve it the desired way if they prefer.

**Comment by rakshasa** [comment]
Please make a pull request.
