### ISSUE TITLE
Adding magnet via RPC

### ISSUE THREAD

**Issue by mafrosis** [rakshasa/rtorrent#752]
I'd love to be able to add a magnet directly to rtorrent with `load.start`, just like I can do in the UI (as discussed in #541). It's not clear to me why this is possible via the UI, but isn't via RPC. Surely it should work with either method, if it works with one?

I know I can create a `.torrent` file, but that's a pain for my use-case.

I asked this question once before, but can't find it! Might have been on a mailing list.

**Comment by kannibalox** [comment]
load.start works just fine for me, e.g.
```
rtxmlrpc load.start '' 'magnet:?xt=urn:btih:874fc6a6a52372f73b6b0723344ec8124f377a00&dn=archlinux-2018.06.01-x86_64.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce'
```

**Comment by mafrosis** [comment]
`rtxmlrpc` is a part of the pyrocore project - I'm talking directly to rtorrent via XMLRPC in python code

**Comment by pyroscope** [comment]
Then it obviously is a good test whether something working for someone else also works for you. If yes, it's your code that's at fault.

**Comment by mafrosis** [comment]
@pyroscope aside from your snarky tone (as usual), I presume you're suggesting I install pyrocore and use that.

That's not an option. I'm talking about XMLRPC direct to rtorrent. No intermediary spaghetti.

Does anyone know if this is possible?

**Comment by mafrosis** [comment]
It does work! Very good. As you were.

**Comment by delacroix0815** [comment]
Would you be so kind and telling us how ?

**Comment by mafrosis** [comment]
@delacroix0815 try something like:

```
server = SCGIServerProxy('scgi://{}:{}/'.format(host, port))
server.load.start_verbose('', magnet_url)
```
