### ISSUE TITLE
[Q] Is there a XMLRPC command to obtain the tracker (name) associated with a hash?

### ISSUE THREAD

**Issue by SteveMalso** [rakshasa/rtorrent#756]
Thanks

**Comment by pyroscope** [comment]
https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-d-tracker-alias

Or call `rtcontrol --debug -qo tracker // -/1` to see all the gory details, and how to get full URLs.

**Comment by SteveMalso** [comment]
Thanks for replying Pyro. I discovered that command earlier, was hoping for a native rtorrent command.

**Comment by pyroscope** [comment]
The "native" way is in the 2nd paragraph.

**Comment by SteveMalso** [comment]
Are you referring to the 'd.tracker_alias' command which requires rTorrent-PS?

**Comment by kannibalox** [comment]
Torrents can have multiple announce urls, are you looking for `t.url`? e.g.:
```
rtxmlrpc d.multicall2 '' main t.multicall=,t.url=
```

**Comment by SteveMalso** [comment]
@kannibalox 

Cheers. I'm a complete newb at XMLRPC commands, is there a way to extract multiple announce urls from a torrent with its hash? 

Better yet, suppose there's a tracker with the domain name xyz.com which has multiple announce urls, is there a command that can merge the announce urls, returning only the domain name?

**Comment by kannibalox** [comment]
If you're looking to replicate what d.tracker_alias does, the code for it is here: https://github.com/pyroscope/rtorrent-ps/blob/master/patches/command_pyroscope.cc#L199

**Comment by SteveMalso** [comment]
Sweet. Appreciate the help.
