### ISSUE TITLE
munin rtorrent plugin fails on 0.9.7

### ISSUE THREAD

**Issue by sulaweyo** [rakshasa/rtorrent#757]
I recently upgraded to rtorrent 0.9.7 and libtorrent 0.13.7 and it works fine except the munin graphs do not work anymore in this version.

I use these:
https://github.com/munin-monitoring/contrib/tree/master/plugins/rtorrent

RPC calls via nginx work fine but the plugin fails to read anything. I'm not really good on perl to do some deeper debugging but something clearly has changed in the endpoint.

**Comment by pyroscope** [comment]
Why report this here instead of where it has to be fixed?

https://github.com/rakshasa/rtorrent/wiki/RPC-Migration-0.9#migration

**Comment by sulaweyo** [comment]
Well basically because i did not find that page and wanted to ask if the change was intended or not as the version is marked as unstable. As it's intended it obviously has to go there.
Thx

**Comment by sulaweyo** [comment]
Just in case someone runs into this as well, here is the pull request with the needed changes for at least the allsession graphs:
https://github.com/munin-monitoring/contrib/pull/921

**Comment by Sephtex** [comment]
I created https://github.com/munin-monitoring/contrib/pull/1050 to fix the rtrom_ modules with the same changes as done for the allsession
