### ISSUE TITLE
peer_exchange config no longer works

### ISSUE THREAD

**Issue by kroeckx** [rakshasa/rtorrent#761]
In 0.9.6 I was able to set the peer exchange option. But in 0.9.7 it complains if I set that in the .rtorrent.rc file and refuses to start. It is however still documented.

**Comment by kroeckx** [comment]
So if I understand what you're saying, I should change it to protocol.pex.set=, that peer_exchange= has been deprecated since 0.7 (but only added in 0.7.8), but is still the only documented way to enable it.

**Comment by kroeckx** [comment]
It seems that in Debian, the only documentation is some old rtorrent man page

**Comment by kroeckx** [comment]
The README file still says:
```
 Run "./autogen.sh" to generate the configure scripts if
nessesary. The man page "doc/rtorrent.1" must be generated with
"docbook2man rtorrent.1.xml" if it is missing.
```

But it moved to doc/old/

**Comment by pyroscope** [comment]
You're looking at all the wrong places…

https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html?highlight=pex#term-protocol-pex

**Comment by kroeckx** [comment]
Yes, that's a little my point. There is only old documentation
that's shipped with the source, so that is what people find and
read.

**Comment by beadon** [comment]
It also still appears in the man pages for rtorrent (  v0.9.8 )
