### ISSUE TITLE
"Download registered as complete, but hash check returned unfinished chunks": how to resume?

### ISSUE THREAD

**Issue by TheBloke** [rakshasa/rtorrent#762]
I am running https://github.com/chros73/rtorrent-ps-ch (from @chros73) version 1.7.3-0.9.7 on Ubuntu Server 18.04 LTS.

I downloaded a 173GB torrent.  Once it finished, rtorrent moved it to my ```done``` directory and ran the final hash check, but that failed and now the torrent shows the message "Download registered as complete, but has check returned unfinished chunks".  Now I can't find a way to resume the torrent to fix the missing chunks.

Since then I have tried:
* re-running the hash check
* hitting ^e to re-create files
* checking the list of files to find which one was incomplete (it was 98%, all others 100%), then deleting it from the file system, then hitting ^e again and re-running the hash check yet again.  That one bad file is now re-created, but is 0 bytes.

Regardless of what I do, I can't get rtorrent to resume this torrent and finish that one file.  Hitting ^s on it does nothing.  I guess because rtorrent has marked it complete, it won't let me start it (even though it knows not all data is there?)

Is there a way to mark it as not complete, so I can re-download the one file that failed the hash check?  

Or must I delete it from the UI, move all the files back to the active directory, and manually add the torrent/magnet again?     I'm hoping there's a cleaner way than that.

FYI below is what I have in .rtorrent.rc for auto-moving completed torrents.  I don't have multiple category directories, just a single ```active``` and ```done``` directory, so I have hardcoded the latter.

This is the first time I've had this problem - I've downloaded many torrents before without issues using this config.
```
directory.default.set = /data/torrents/rtorrent/vpn1/download/active
method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,/data/torrents/rtorrent/vpn1/download/done"
```

Thanks in advance.

**Comment by kannibalox** [comment]
Have you tried ^k ^e ^r? That's the standard sequence for "resetting" an active torrent with a hash check.

**Comment by TheBloke** [comment]
Ahh, thank you!  I didn't realise ^k made a difference to an already-stopped/inactive download.

That worked great: I just did ^k, ^e and then ^s and it's downloading that missing file.   I didn't bother with ^r as I'd already run it a few times and it takes a long time on this torrent.

The torrent is now showing as complete.

Thanks for the fast reply!
