### ISSUE TITLE
New ports policy in version 0.9.7?

### ISSUE THREAD

**Issue by shamazmazum** [rakshasa/rtorrent#765]
Hello. I am using rtorrent on FreeBSD 11.2-RELEASE. I also use VPN which provides one forwarded port. The previous version of rtorrent used one port for torrent traffic, picked from a range specified in `network.port_range.set` setting, so I had my firewall configured accordingly. The new version, however, does not work with this firewall configuration. I checked my traffic in wireshark and figured out that rtorrent uses almost any other random port for outgoing connections.

Now my ipfw rules for rtorrent look like ($TORRENT and $DHT are ports for torrent and DHT traffic):
~~~~
# Torrents
$IPFW add allow tcp from any to me dst-port $TORRENT in via $IFACE setup keep-state :after-nat
$IPFW add allow tcp from me 15000-65535 to any out via $IFACE setup keep-state :after-nat
$IPFW add allow udp from me $DHT to any out via $IFACE
$IPFW add allow udp from any to me dst-port $DHT in via $IFACE
~~~~

I am not sure if this is correct, but it works for downloading. But, unfortunately, I cannot upload anything. So what ports and when rtorrent uses now? Can I return the old behaviour with the new version?

**Comment by mhertz** [comment]
Rtorrent doesn't have means for defining outgoing port(-range) as not available through POSIX. 

If you have a single port forwarded from your VPN, e.g. port 62820, then use in .rtorrent.rc:

network.port_range.set = 62820-62820
dht.mode.set = auto
dht.port.set = 62820

**Comment by shamazmazum** [comment]
Thanks, @mhertz. Obviously, I forgot some details about TCP connections and wrote wrong firewall rules. I will stick to my new rules.

The strange thing is what it worked before :) The old rules were:
~~~~
$IPFW add allow tcp from any to me dst-port $TORRENT in via $IFACE
$IPFW add allow tcp from me $TORRENT to any out via $IFACE
~~~~
So I just kept open one port on my system and it worked somehow
