### ISSUE TITLE
small problem after upgrade

### ISSUE THREAD

**Issue by flier56** [rakshasa/rtorrent#766]
hello i need a little guidance i am running scars uploader with rtorrent it was working fine in rtorrent 0.9.6 like this

system.method.set_key = event.download.finished,upload_torrent,"execute=/home/username/upload/wrapper,rtorrent,$d.get_chunk_size=,$d.get_base_path="

i upgraded to 0.9.7 it had a error that said system.method.set_key does not exist so i changed the line to this
 
method.set_key = event.download.finished,upload_torrent,"execute2=/home/username/upload/wrapper,rtorrent,d.chunk_size=,d.base_path="

but i can not get it to upload the torrent like it should.
thanks for time

**Comment by pyroscope** [comment]
do an issue search, this is a FAQ. and read the wiki.

**Comment by flier56** [comment]
i may have found the error in the line forgot to add the $ changed the line to this
method.set_key = event.download.finished,upload_torrent,"execute2=/home/username/upload/wrapper,rtorrent,$d.chunk_size=,$d.base_path="
