### ISSUE TITLE
Could not open log file

### ISSUE THREAD

**Issue by dncohen** [rakshasa/rtorrent#770]
I'm trying rtorrent version 0.9.7 with the tempate .rtorrent.rc (very slightly modified).

rtorrent always errors out with:

    rtorrent: Error in option file: ~/.rtorrent.rc:121: Could not open log file './log/rtorrent.log'.

It does create the directory `./log`, but not `.log/rtorrent.log`.  If I create an empty file, I still get the same error.

Any ideas?  Thanks.

**Comment by dncohen** [comment]
Looks like a relative path, starting "./", errors out.

Now, I'm experimenting with `system.cwd` at the top of my .rtorrent.rc and it starts up ok...

```
## Instance layout (base paths)
#method.insert = cfg.basedir,  private|const|string, (cat,"/home/user/rtorrent/")
method.insert = cfg.basedir,  private|const|string, (cat,(system.cwd), "/")
method.insert = cfg.download, private|const|string, (cat,(cfg.basedir),"download/")
method.insert = cfg.logs,     private|const|string, (cat,(cfg.basedir),"log/")
method.insert = cfg.logfile,  private|const|string, (cat,(cfg.logs),"rtorrent-",(system.time),".log")
method.insert = cfg.session,  private|const|string, (cat,(cfg.basedir),".session/")
method.insert = cfg.watch,    private|const|string, (cat,(cfg.basedir),"watch/")

```

**Comment by harduino** [comment]
Solution helped me:
`chown -R rtorrent:rtorrent /downloads/`
