### ISSUE TITLE
Torrent state not persisting

### ISSUE THREAD

**Issue by anstosa** [rakshasa/rtorrent#772]
Installed rtorrent and rutorrent via linuxserver container. The container, UI and daemon boot up great and I understand that I cannot change rtorrent settings in a persistent way via the UI. However the torrent state is also not persisting. The torrents are still there, but if they're paused when I turn off the container, they start again when I restart it and if I've changed the download locations of specific torrents they revert to the default download location. Any ideas?

**Comment by pyroscope** [comment]
Fix your shutdown code.

**Comment by anstosa** [comment]
Yeah I just wasn't waiting long enough. As part of testing this new (to me) client, I wanted to know what I should expect from a power failure (happens a few times a year where I live) so I was testing non-graceful shutdowns. Giving it longer in between solved it. I'm fine with losing 20mins worth of data. Thank you for the detailed response
