### ISSUE TITLE
0.9.7 - files from schedule2 watched directories have a restrictive mask

### ISSUE THREAD

**Issue by IvanTheViking** [rakshasa/rtorrent#773]
When I upgraded to 0.9.7 from 0.9.6 on my server, I noticed the new files rtorrent is saving have a 640 mask.  Previously I had seen a 644 mask which allowed anyone to access the downloads. 
Looked through the wiki, didn't see anything obvious.

Is there a setting I missed, or did something else change?

**Comment by pyroscope** [comment]
```console
$ rtlistmethods mask
system.umask.set
```

**Comment by IvanTheViking** [comment]
Works mint.  Thanks so much.  As typical, damn PEBKAC was the problem and I missed this one in the commands reference when I made the new config file sans legacy stuff.
