### ISSUE TITLE
rtorrent.rc

### ISSUE THREAD

**Issue by DevilStyle** [rakshasa/rtorrent#774]
Hello everyone, congratulations for this fantastic community, I installed with the rtinst rutorrent script and everything that works without problems, I have a question to ask:

I set up RSS feeds so that it automatically downloads the files of each category, but unfortunately as soon as you start a download it immediately creates the folder of the torrent file that downloads and then I never understand when the download is finished (I need to know for example when I want to archive folders with 7zip)

Is it possible to make sure that when I finish a download of a folder set by me, it moves the finished file to another folder? Thank you

**Comment by pyroscope** [comment]
read the wiki on completion handling, and close this.
