### ISSUE TITLE
Start and pause for all

### ISSUE THREAD

**Issue by quaeched** [rakshasa/rtorrent#775]
It would be nice to be able to start/pause all torrents at once (for example I only want to download one torrent -> pause all then add/start this one).

**Comment by pyroscope** [comment]
It would be nice if more people used the wiki.

**Comment by quaeched** [comment]
I'm sorry but search did not return anything. Could You be so kind and point me to the section, please? Thank You very much. :)

**Comment by quaeched** [comment]
is it d.stop?

**Comment by pyroscope** [comment]
common tasks. read the headings.

**Comment by quaeched** [comment]
Oh yes, thank You. Pardon my ignorance.
