### ISSUE TITLE
rTorrent + Ubuntu 18.04.1 LTS?

### ISSUE THREAD

**Issue by AnsuRio** [rakshasa/rtorrent#778]
Yesterday I did an do-release-upgrade from 16.04.X LTS to 18.04.1 LTS on one of my servers. After that rTorrent is broken due to "rtorrent: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by rtorrent)".

When I run the command for installing all the dependencies to just check what's causing the problem and error I get this "The following packages have unmet dependencies.
 libcurl3 : Conflicts: libcurl4 but 7.58.0-2ubuntu3.2 is to be installed
 libcurl4 : Conflicts: libcurl3 but 7.58.0-2ubuntu2 is to be installed"

Is anyone in here able to get rTorrent running on the 18.04.1 LTS installation?

Best
Pontus

**Comment by AnsuRio** [comment]
When checking here, there are others with other apps that are having huge problem with libcurl3 and libcurl4. [https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294]

**Comment by pyroscope** [comment]
Bring your own curl, then there is no prob. ;)

**Comment by gtwy** [comment]
I recompiled libtorrent and it was fine.

```
git clone https://github.com/rakshasa/libtorrent.git
cd libtorrent/
./autogen.sh
./configure
make
make install
```

That being said, I am now having some problems with xml-rpc

**Comment by rakshasa** [comment]
Dependency hell is someone else's problem, have fun.

**Comment by pyroscope** [comment]
BTW, https://bintray.com/pyroscope/rtorrent-ps/download_file?file_path=rtorrent-ps_0.9.6-PS-1.1-25-g1b53ac9%7Ebionic_amd64.deb
