### ISSUE TITLE
rTorrent 0.9.7 Hashing Even When Told Not To

### ISSUE THREAD

**Issue by ghost** [rakshasa/rtorrent#779]
I just recently built out rTorrent 0.9.7 and have specifically set the following directives in my .rtorrent.rc file

`pieces.hash.on_completion.set    = no`
`check_hash                       = no`

When I reboot my server rTorrent still hashes all 5300 or so torrents that are loaded. Are there any other changes I can make to prevent hash checking? I have confirmed in the ruTorrent GUI that "check hash after downloading" is also unchecked.

OS: Ubuntu 16.04 LTS (up to date)
RAM: 8GB
CPU: 8vCPU

Any additional information can be provided. Thank you!

**Comment by pairughdocks** [comment]
I read the Wiki and I am using a proper session directory set in .rtorrent.rc.

**Comment by kannibalox** [comment]
Turn off ruTorrent while troubleshooting, make sure that all necessary mountpoints exist before shutdown and before startup (e.g. no automount stuff), and that your session directory is getting populated with the correct data. You can verify that the directory is where you expect by entering the following command in the Ctrl-x prompt in rTorrent: `print=$session.path=`. That will print the current session directory to the screen.

If you want to manually verify that the session data is correct (and apologies if this gets a bit technical), if you install the [pyrocore tools](https://pyrocore.readthedocs.io/en/latest/installation.html) you can do `lstor -V --raw <infohash>.torrent.libtorrent_resume` and compare the `mtime`s in the `files` list against the real files by correlating it with the `files` list in the `<infohash>.torrent`.
If all else fails, please share your full config.

For posterity, `check_hash` is the same thing as `pieces.hash.on_completion.set`, and they don't effect whether rtorrent needs to re-hash data on startup. See https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-pieces-hash-on-completion for reference.

**Comment by pyroscope** [comment]
Let's hope your ulimits fit your config. 300 slots certainly do not fit 1.5k sockets (waste of cpu cycles *at best*).

**Comment by pairughdocks** [comment]
> 
> 
> Let's hope your ulimits fit your config. 300 slots certainly do not fit 1.5k sockets (waste of cpu cycles _at best_).

Would you be able to help me learn how to better balance out the resources I have? I'm clearly missing something in the documentation.

**Comment by pyroscope** [comment]
Either you provided 6k+ handles in systemd or limits.conf, or you made that instance highly prone to trouble / crashes.

**Comment by pairughdocks** [comment]
> 
> 
> Either you provided 6k+ handles in systemd or limits.conf, or you made that instance highly prone to trouble / crashes.

I haven't touched anything in limits.conf or modified anything with systemd. Can you elaborate? It's a  stock install of Ubuntu Server 16.04. My top/htop usage is all showing very low, that's why I posted my .rtorrent.rc to see if I configured something along the way in regards to hashing.

**Comment by pyroscope** [comment]
the wiki config template page explains why its values are right and why "more is better" is wrong.

**Comment by rakshasa** [comment]
As said, if the mtime doesn't match it rehashes.
