### ISSUE TITLE
Scheduled command failed: watch_directory: Command "load_start" does not exist.

### ISSUE THREAD

**Issue by shelterx** [rakshasa/rtorrent#780]
rTorrent 0.9.7/0.13.7 

`schedule2 = watch_directory,5,5,"load_start=/rtorrent/auto/*.torrent"`

Any ideas, looking at the provided rtorrent.rc it seems like load_start should work?

**Comment by kannibalox** [comment]
Whatever "provided rtorrent.rc" you're using still has deprecated commands, which were removed entirely in 0.9.7. See the repo's [rtorrent.rc](https://github.com/rakshasa/rtorrent/blob/master/doc/rtorrent.rc) or https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template for up-to-date configs, or [update_commands_0.9.sed](https://github.com/rakshasa/rtorrent/blob/master/doc/scripts/update_commands_0.9.sed) for a sed script to update your current config.

**Comment by shelterx** [comment]
Thank you, wasn't that easy to find tbh.
I looked on the files that the distribution installed, I also looked here:
https://github.com/rakshasa/rtorrent/blob/master/doc/rtorrent.rc <- still has the old syntax.

Anyway, I hope someone else find this helpful.
