### ISSUE TITLE
move_to_complete watch dir config corrupts files on completion for torrents added not via watch directories (ruTorrent)

### ISSUE THREAD

**Issue by kinghrothgar** [rakshasa/rtorrent#781]
I have setup rtorrent with the move on complete watch dir example from the Wiki:

```
schedule2 = watch_directory_1,5,5,"load.start=/watch/misc/*.torrent,d.directory.set=/download/misc,d.custom1.set=/media/misc"
schedule2 = watch_directory_2,5,5,"load.start=/watch/music/*.torrent,d.directory.set=/download/music,d.custom1.set=/media/music"

# upon completion, move content to path specified above via custom1
method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.custom1="
```

If you add a torrent via some other method other than a watch directory  (i.e. ruTorrent), on completion rtorrent does something to corrupt the file. The file will still be in the same location, but the hash check fails. I have verified with md5sum that the file is indeed different then a successfully downloaded file. Is there a way to have move on completion features without breaking ruTorrent's add torrent feature?

EDIT: Messed up the watch_directory lines

**Comment by pyroscope** [comment]
There is no "above" that sets custom1. Blindly combining snippets of .rc hell without understanding the parts usually ends in tears. Also, if you run ruT, numbered customs are ALL taken and cannot be used for other stuff.

**Comment by kinghrothgar** [comment]
I messed up the constructing of my example config. When I had it setup I had the d.custom1.set done correctly.

I thought I understood what the snippet was doing and was pretty sure the issue was caused by either $d.custom1= being set to something weird by ruTorrent or because it was missing. I have tried to find examples / guides to wrap my head around the if conditional logic but after spending many hours I still have not grasped it enough to write my own modifications of it.

Is it possible to use a named custom and if logic on the `method.set_key = event.download.finished` line to accomplish what I'm trying to do?

**Comment by pyroscope** [comment]
My recommendation is always to write any logic in a sane and documented language, i.e. delegate to bash or similar. The only thing done in .rc is capture and set the resulting NEW path, which the script produces.

See https://rtorrent-docs.readthedocs.io/en/latest/use-cases.html#versatile-move

**Comment by kinghrothgar** [comment]
Thanks tons! Finally had time to parse through that. Took me a while to wrap my head around using both the new and old format. I got moving downloads working from both watch directories and ruTorrent and have greatly increased my understanding of scripting rtorrent! Being able to call out to an external script is great.

Is there any forum or chat room that's a good place to get rtorrent scripting help? I have a few more random questions and github issues definitely doesn't seem like the correct place.

**Comment by pyroscope** [comment]
##rtorrent channel on irc.freenode.net
