### ISSUE TITLE
Incoming connections broken on FreeBSD

### ISSUE THREAD

**Issue by dbaio** [rakshasa/rtorrent#786]
Hi.

There are some reports of issues on FreeBSD about rtorrent/libtorrent (0.9.7/0.13.7) and incoming connections.

```
$ sockstat -46 -p 50000
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
dbaio    rtorrent   4159  15 tcp46  *:50000
```

When runs telnet to port `50000`, `ipv4` or `ipv6`, the connection is not established.

A user reported that forcing the use of IPPROTO_IPV6 solves the issue. [1,2,3]

After applying the workaround locally, telnet works again as well.

Maybe this is the issue on FreeBSD? https://github.com/rakshasa/rtorrent/blob/master/src/utils/socket_fd.cc#L136-L141

Any hints/idea?

Regards.

[1] - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231274
[2] - https://bugs.freebsd.org/bugzilla/attachment.cgi?id=197598&action=diff
[3] - https://bugs.freebsd.org/bugzilla/attachment.cgi?id=197597&action=diff

**Comment by chros73** [comment]
You can take a look at this [discussion](https://github.com/rakshasa/rtorrent/issues/783#issuecomment-425054611), maybe it helps.
