### ISSUE TITLE
how to save in dated dir?

### ISSUE THREAD

**Issue by tashkas1** [rakshasa/rtorrent#793]
How to save in dated ir?

schedule = watch_directory_1,5,5,"load.start=/home/MP3/*.torrent,d.set_directory=home/MP3/$(date +%Y%m%d)/,d.set_custom1=MP3"

**Comment by pyroscope** [comment]
https://github.com/pyroscope/pimp-my-box/blob/24e9aa5ecf0792aac67a34ffa289938552c9651a/roles/rtorrent-ps/templates/rtorrent/rtorrent.d/15-logging.rc#L23-L24

**Comment by kannibalox** [comment]
> ` method.insert = cfg.download, private|const|string, (cat,(cfg.basedir),"execute.capture_nothrow = bash, -c, "echo -n $(date +%Y%m%d)"")`

The inner quotes need to be escaped, just as shown in the example posted above.

**Comment by pyroscope** [comment]
besides NOT using the helper method as-is, to keep the exec magic separate and, well, working. because the above will not, even with escaping.

**Comment by tashkas1** [comment]
so how it should be can somebody writte it?

**Comment by tashkas1** [comment]
method.insert = cfg.basedir, private|const|string, (cat,"/home/incoming/MP3/")
method.insert = cfg.download, private|const|string, (cat,(cfg.basedir),"execute.capture_nothrow = bash, -c, \"echo -n $(date +%Y%m%d)\"")
schedule2 = watch_directory_1,5,5, ((load.start, home/final/MP3/*.torrent, d.directory.set, (cat,(cfg.download)), d.set_custom1=MP3))

im getting this one 

Command on torrent creation failed: Could not find '='.

**Comment by tashkas1** [comment]
schedule2 = watch_directory,5,3,load.start_verbose=(cat,(cfg.final), "*.torrent'), d.set_directory=(cat,(cfg.download)), d.set_custom1=MP3

Junk at end of input. what that means?

**Comment by chros73** [comment]
It means that you have syntax error somewhere.

**Comment by tashkas1** [comment]
so how to fix it?

**Comment by rakshasa** [comment]
If anyone wonders, there's both a " and ' used to quote *.torrent, only " is supported.

**Comment by j-c-m** [comment]
I fought the syntax demons for this one, hopefully this helps someone.

```
method.insert = cfg.watch, private|const|string, (cat,"/your/watch/directory/")
method.insert = cfg.download_dir, private|const|string, (cat,"/your/download/directory/")

method.insert = download_stamp, private|simple,\
    "execute.capture_nothrow = bash, -c, \"echo -n $(date +%Y-%m-%d)\""

method.insert = cfg.download, private|const|string, (cat,(cfg.download_dir),"/",(download_stamp))

schedule2 = watch_load, 10, 1, ((load.normal, (cat, (cfg.watch), "/*.torrent"), "d.delete_tied=", (cat,"d.directory.set=",(cfg.download)), \
    (cat,"execute.capture_nothrow = bash, -c, \"mkdir -p ",(cfg.download),"\"")))

```

**Comment by j-c-m** [comment]
```
method.insert = dl.stamp, private|simple,\
    "execute.capture_nothrow = bash, -c, \"echo -n $(date +%Y-%m-%d)\""

method.insert = dl.stamp.directory, private|simple,\
    "d.directory.set = (cat, (directory.default),\"/\",(dl.stamp)); execute.throw = mkdir, -p, (d.directory)"

schedule2 = watch_load, 10, 1, ((load.normal, (cat, (cfg.watch), "/*.torrent"), "d.delete_tied=", "dl.stamp.directory="))
```
