### ISSUE TITLE
Is it possibile to move only certain files after download with rtorrent.rc? 

### ISSUE THREAD

**Issue by samsepiol59** [rakshasa/rtorrent#798]
Not an issue per se, I know

Now I'm using this

event.download.finished,move_complete,"execute=cp,-R,-u,$d.get_base_path=,~/uploads/"

I'd like to be able to only move certain files (let's say .mkv and .mp4) to my destination folder!! Is it achievable?! Thanks!

**Comment by 0x20Man** [comment]
Yeah it's possible, but you shouldn't abuse the bug tracking system to post questions.

You are using:
* an ancient rtorrent version
* deprecated commands (execute, d.get_base_path)

Anyway, change the arguments of the "cp" above to something like:

    (cat,$d.base_path=,"/*.(mp4)")

The double quotes probably need to be escaped when put in the line above
