### ISSUE TITLE
Delete torrent with data when seed ratio is achieved

### ISSUE THREAD

**Issue by pmalek** [rakshasa/rtorrent#799]
I'm trying to figure out how to erase torrent with data when seed ratio is achieved but somehow I cannot get it to work.

I'm using rTorrent 0.9.7 and the following config

```
method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"
# Changing the command triggered when the ratio is reached.
# (the default is "d.try_close= ; d.ignore_commands.set=1")
method.set = group.seeding.ratio.command, "d.close= ; d.erase= ; execute=rm,-rf,--,$d.data_path="
```

Which doesn't seem to delete the downloaded data. How can I do that?

BTW Is there a place I can find functions that can be called on `d` (like `erase` here)?

**Comment by pyroscope** [comment]
1 - destroy item; 2 - gimme item's path. err, what item?
https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#d-commands
