### ISSUE TITLE
moving completed torrents to a fixed location based on Wiki?

### ISSUE THREAD

**Issue by bernid** [rakshasa/rtorrent#800]
Hi,
I'm trying to enable moving completed torrents to a fixed location by coping 4 lines 
[from Wiki](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#move-completed-torrents-to-a-fixed-location) to my .rtorrent.rc on fresh Ubuntu 18.10 (with rtorrent 0.9.7/0.13.7).
Unfortunately I receive: ‘ Error in option file: ~/.rtorrent.rc:128: Invalid key.’
Is the wiki up-to-date in this area?
Please have a look on my:
[.rtorrent.rc](http://paste.ubuntu.com/p/PkzRmYn4JV/)
especially on the last lines/rows  and advice what should I change. 
I would like that completed torrents to be move to directory ~/done
Thanks in advance and regards,

**Comment by chros73** [comment]
You already defined `d.data_path` method in line 86, so just remove line 128.

**Comment by bernid** [comment]
Thank you. You're right. I missed it.
