### ISSUE TITLE
screen init script issue

### ISSUE THREAD

**Issue by bernid** [rakshasa/rtorrent#803]
Hi, 
I would like to start/stop rtorrent  at boot with screen on my Ubuntu 18.10. 
So I copied the template from:
https://github.com/rakshasa/rtorrent/blob/master/doc/scripts/init/rtorrentInitScreen.sh
as [Wiki](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#debian) said. Changed user in the init file ( in my case user="rtorrent") but unfortunately rtorrent don't want to start:
```
● rtorrent.service
   Loaded: loaded (/etc/init.d/rtorrent; generated)
   Active: failed (Result: exit-code) since Sun 2018-11-04 09:00:05 CET; 12s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 23422 ExecStart=/etc/init.d/rtorrent start (code=exited, status=3)
 Main PID: 1515 (code=exited, status=0/SUCCESS)

Nov 04 09:00:05 akacja su[23423]: pam_unix(su:session): session closed for user rtorrent
Nov 04 09:00:05 akacja su[23483]: Successful su for rtorrent by root
Nov 04 09:00:05 akacja su[23483]: + ??? root:rtorrent
Nov 04 09:00:05 akacja su[23483]: pam_unix(su:session): session opened for user rtorrent by (uid=0)
Nov 04 09:00:05 akacja su[23483]: pam_systemd(su:session): Failed to create session: Start job for unit user-1001.slice failed with 'canceled'
Nov 04 09:00:05 akacja su[23483]: pam_unix(su:session): session closed for user rtorrent
Nov 04 09:00:05 akacja rtorrent[23422]: cannot find readable session directory  from config /mnt/harddisk/P2P/rtorrent/.rtorrent.rc. check permissions
Nov 04 09:00:05 akacja systemd[1]: rtorrent.service: Control process exited, code=exited status=3
Nov 04 09:00:05 akacja systemd[1]: rtorrent.service: Failed with result 'exit-code'.
Nov 04 09:00:05 akacja systemd[1]: Failed to start rtorrent.service.[/code]
```
User 'rtorrent' and home directory seems to work:
```
ela@akacja:~$ su rtorrent
Password:
rtorrent@akacja:/home/ela$ $HOME
bash: /mnt/harddisk/P2P/rtorrent: Is a directory
rtorrent@akacja:/home/ela$
```
Copy of my /mnt/harddisk/P2P/rtorrent/.rtorrent.rc is 
[HERE](http://paste.ubuntu.com/p/Jb4j49yfWK/)
What should I change to move on?
TIA and regards,

**Comment by pyroscope** [comment]
This works…

https://www.reddit.com/r/seedboxes/comments/9d1ufq/rtorrent_systemd_unit_user_service_with_builtin/

**Comment by chros73** [comment]
At the time of writing of init script the `session` option was hardcoded in rtorrent config, now it's scripted, hence init script [doesn't find](https://github.com/rakshasa/rtorrent/blob/master/doc/scripts/init/rtorrentInitScreen.sh#L78) the session directory.
Solution is to hardcode the full path of the session dir in init script.
(And the same applies to lock file as well.)

**Comment by bernid** [comment]
Thanks guys, 
I would like stay with screen maybe I try tmux some day. 
Currently I use systemd unit service file '/etc/systemd/system/rtorrent.service' to control start/stop rtorrent service based on [ArchLinux documentation](https://wiki.archlinux.org/index.php/RTorrent#With_screen):
```
[Unit]
Description=rTorrent
After=network.target

[Service]
Type=forking
KillMode=none
User=rtorrent
WorkingDirectory=%h
ExecStartPre=/bin/bash -c "if test -e %h/.session/rtorrent.lock && test -z 'pidof rtorrent'; then rm -f %h/.session/rtorrent.lock; fi"
ExecStart=/usr/bin/screen -dmfa -S rtorrent /usr/bin/rtorrent
ExecStop=/bin/bash -c "test 'pidof rtorrent' && killall -w -s 2 /usr/bin/rtorrent"
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
However when I want to reboot (or poweroff) my Ubuntu 18.10  I have to wait 1min30sec to close the rtorrent service. 
When I close service mannually ('sudo systemctl stop rtorrent') the service is closed much faster. 
How could I shorten the service off time?
Thanks,
