### ISSUE TITLE
rtorrent with systemd user service echo mesg: Using 'epoll' based polling when start tmux

### ISSUE THREAD

**Issue by tuyenpm9** [rakshasa/rtorrent#804]
```
( 9:54:10) Using 'epoll' based polling. 
( 9:54:10) Using 'epoll' based polling. 
( 9:54:10) Using 'epoll' based polling. 
```

I'm using archlinux latest and tmux latest, also rtorrent.

I use rtorrent.service as systemd service in userland to start rtorrent. When open tmux I got those cuty mesg and have no clue why it echos those. No log from `journalctl`.

**Comment by chros73** [comment]
This supposed to be the standard message logs on rtorrent interface when rtorrent starts.

**Comment by tuyenpm9** [comment]
@chros73 : What does it suppose to mean?

**Comment by chros73** [comment]
It just states that rtorrent uses "'epoll' based polling" :) The point is that these messages are always (!) displayed during startup.

**Comment by tuyenpm9** [comment]
That's pretty neat or messy at the same time :), I need to stop laziness and make a vote!
