### ISSUE TITLE
branch not branching

### ISSUE THREAD

**Issue by chris400** [rakshasa/rtorrent#809]
I am adding torrents via a watch directory and manually. I would like to move the torrents added via watch directory when they are finished. I am using a custom var to do that. Here is my code:
```
schedule2 = watch_directory_rss,10,10,"load.start=/data/watch/rss/*.torrent,\"d.custom.set=donedirset,1\",\"d.custom.set=donedir,/data/done/torrent/rss/\",print=\"schedload\""

method.set_key = event.download.finished,check_customdir,"branch=d.custom=donedirset,$printJA=,$printNEIN="
```

Both(!) methods (printJA and printNEIN) are started, regardless of whether the torrents are added by watch directory or manually. The second custom var (donedirset) was not there in first place, I tought branch might not working correctly on a string, so I added another var like it is used in the [wiki](https://github.com/rakshasa/rtorrent/wiki/COMMAND-Scheduling).

Is it a bug or am I doing something wrong?

**Comment by chros73** [comment]
It should work, maybe you need `cat` for strings, try this:
```ini
schedule2 = watch_directory_rss, 10, 10 ,"load.start=/data/watch/rss/*.torrent,\"d.custom.set=donedir,$cat=/data/done/torrent/rss/\""

method.set_key = event.download.finished, check_customdir, "branch=d.custom=donedir, print=JA, print=NEIN"
```

**Comment by chris400** [comment]
> It should work, maybe you need `cat` for strings, try this:
> 
> ```ini
> schedule2 = watch_directory_rss, 10, 10 ,"load.start=/data/watch/rss/*.torrent,\"d.custom.set=donedir,$cat=/data/done/torrent/rss/\""
> 
> method.set_key = event.download.finished, check_customdir, "branch=d.custom=donedir, print=JA, print=NEIN"
> ```

thx for your reply - but the behavior is still the same :confounded:

**Comment by chros73** [comment]
I tried out for you what I've posted with `0.9.7` and it's working here (only "JA" is displayed), so there must be other issues in your config.
The `event.donload.finished` line is fine, you can check whether the custom attribute is set by placing the cursor on the download and hit `CTRL+x` and run (you should see "/data/done/torrent/rss/"):
```ini
print=$d.custom=donedir
```

Which rtorrent version do you use?

**Comment by chris400** [comment]
Thank so much for testing it.

The custom attribute is set, I already tested it. I am running Debian stable, rtorrent version is `0.9.6`.

I am using multiple lines with `event.download.finished` - is that a problem?

**Comment by pyroscope** [comment]
Remove the early evaluation that you have in your 1st post, if that is still in there.

**Comment by chris400** [comment]
Still the same result :-(

My current complete .rtorrent.rc: https://gist.github.com/chris400/5e7dcc68fae352d625e0406284b43279

**Comment by pyroscope** [comment]
again, remove the $ evaluation, which causes that problem.
