### ISSUE TITLE
100% CPU and RAM usage on Unraid

### ISSUE THREAD

**Issue by ghost** [rakshasa/rtorrent#811]
I'm no developer so I don't know what is causing this but here are some images:

https://imagez.to/i/f0ESR8VO.png

https://imagez.to/i/sijRAGuF.png

Using version 0.9.7-1-11 because the latest version had a WebUI issue which would refuse to load the WebUI. Seems I can't use any version of rTorrent now.

**Comment by mb720** [comment]
The screenshot of htop you posted, shows that while rTorrent uses 82.3% of memory, it consumes 0.0% CPU.

**Comment by mb720** [comment]
Does limiting rTorrent's memory usage affect the issue?

    pieces.memory.max.set = 1800M
