### ISSUE TITLE
Cannot bind to 0.0.0.0

### ISSUE THREAD

**Issue by psycholyzern** [rakshasa/rtorrent#813]
Hi. I want to bind rtorrent to 0.0.0.0 but it refuses to start.
I tried putting `bind = 0.0.0.0`  also tried `rtorrent -b 0.0.0.0` with no luck.

I got this error:
```
rtorrent: Could not open/bind port for listening: Success
```
and this is from rtorrent log file
```
1543912495 C Caught exception: 'Could not open/bind port for listening: Success'.
```

I am using latest source of libtorrent and rtorrent, pulled using git clone, branch `feature-bind`.

**Comment by cantalupo555** [comment]
`# The ip address the listening socket and outgoing connections is
# bound to.
#bind = 127.0.0.1
#bind = rakshasa.no`

**Comment by psycholyzern** [comment]
@cantalupo555  what that supposed to mean? I want to bind to 0.0.0.0

Currently netstat shows:
```
tcp6       0      0 :::11967                :::*                    LISTEN      16495/rtorrent
```

**Comment by cantalupo555** [comment]
Leave your rtorrent.rc file the way I showed it in the previous image.

**Comment by psycholyzern** [comment]
@cantalupo555  yes I am leaving that commemted or it would produce error like in my original post.

Currently netstat shows
```
tcp6       0      0 :::11967                :::*                    LISTEN      16495/rtorrent
```

This is what it bounds to when I comment that option.

**Comment by psycholyzern** [comment]
@cantalupo555 I tried using actual ip address. rtorrent runs, but port forwarding won't work. To be honest, I even forgot why I want to bind to 0.0.0.0 because it has been a while since I opened this issue.

Port forwarding works fine with default binding (ipv6) even I disabled ipv6 on my server. But this issue should stay open because binding to 0.0.0.0 is not possible for me.

**Comment by Gosokan** [comment]
@psycholyzern I have similiar problem
rtorrent can't binding to 0.0.0.0 on Ubuntu 18.04 machine with dual stack ip, when compile using 0.9.7 feature-bind. Then I'm recompiling again with no feature-bind. 

Netstat still showing listen to ipv6 only. But when I check using canyouseeme.org, rtorrent is also responding on ipv4. So I'm sure it's actually binding to both ipv4 and ipv6 when bind = 0.0.0.0 is comment out in rtorrent.rc

Maybe netsat command not showing listen port properly when machine use dual stack ip, or maybe this netstat's behavior only occurs on Ubuntu 18.04 machine with dual stack ip. Netstat in my old machine (Ubuntu 14.04) show both ipv4 and ipv6 properly.

**netstat**
`# ► netstat -tulpn`
`tcp6       0      0 :::39079                :::*                    LISTEN      11499/rtorrent`

**ss** from iproute2 package
`# ► ss -ltp`
`LISTEN 0       128                     *:39079                 *:*      users:(("rtorrent main",pid=11499,fd=12))`

**Comment by rakshasa** [comment]
The latest feature-bind should automatically make 0.0.0.0 set the v4only flag.
