### ISSUE TITLE
Add a link to readthedocs / rtorrent-docs repo

### ISSUE THREAD

**Issue by pawamoy** [rakshasa/rtorrent#814]
If I type rtorrent on Duckduckgo, Google or GitHub itself, I end up on this repository, so I would consider this is the entry point for anyone who is looking for information about rtorrent.

I didn't even know there was a ReadTheDocs page before @pyroscope gave me the link on reddit :wink: 

So you should definitely add a link to the documentation on ReadTheDocs or to the rtorrent-community/rtorrent-docs repository in the README! Maybe even as the website field in the description of the GitHub repo.

**Comment by chros73** [comment]
- Wiki is editable by anyone, so you can add it there if it's not there already
- create a pull request for the rest with your suggestion :)

**Comment by pawamoy** [comment]
Added in the wiki home page.
