### ISSUE TITLE
User support query

### ISSUE THREAD

**Issue by PaulGWebster** [rakshasa/rtorrent#816]
How can I tell rtorrent that I want to allow it to use 100Megabytes per second, it can use the full 100 on upload or download but it should always preffer upload and neither should be static,.

So in effect Upload at 100MBps as priority 1 and download at whatever bandwidth is left as priority 2

**Comment by kannibalox** [comment]
1) is not possible in rtorrent, and I'm not sure why that'd be desirable in the first place.
2) Use a session directory.
