### ISSUE TITLE
Script to pass magnet link to rTorrent

### ISSUE THREAD

**Issue by mb720** [rakshasa/rtorrent#819]
Hi and thanks a lot for rTorrent!

In 2012, Max Gonzih published a [Bash script on his blog](https://blog.gonzih.me/blog/2012/02/17/how-to-use-magnet-links-with-rtorrent/) that passes magnet links to rTorrent.

That script is referenced on the [Arch Linux page](https://wiki.archlinux.org/index.php/RTorrent#Saving_magnet_links_as_torrent_files_in_watch_folder) for rTorrent, [this askubuntu.com question](https://askubuntu.com/questions/787100/how-to-open-magnet-torrent-links-from-firefox-in-rtorrent#796222), and still works for rTorrent 0.9.7.

Here's my adaption of the script that introduced some local variables and comments for clarity:

    #!/bin/bash
    torrent_file_or_magnet_link="$1"

    cd "$HOME/.rtorrent/watch/start/"

    # XT stands for "exact topic"
    # BTIH is the BitTorrent info hash:
    # https://en.wikipedia.org/wiki/Magnet_URI_scheme#BitTorrent_info_hash_(BTIH)
    # This is the hex-encoded SHA-1 hash of the torrent file info section
    magnet_regex="xt=urn:btih:([^&/]+)"
    if [[ "$torrent_file_or_magnet_link" =~ $magnet_regex ]]; then
      torrent_hash=${BASH_REMATCH[1]};
      magnet_link_length=${#torrent_file_or_magnet_link}
      # The number of characters of the magnet link must be part of
      # the torrent file, otherwise rTorrent can't read it.
      # Same for the "e" at the end.
      torrent_file_content="d10:magnet-uri${magnet_link_length}:${torrent_file_or_magnet_link}e"

      # Note that rTorrent will read this torrent file, start downloading
      # the file and then remove the torrent file
      echo "$torrent_file_content" > "$torrent_hash.torrent"
    else
      # We assume that the argument to the script is a regular .torrent file
      cp "$torrent_file_or_magnet_link" .
    fi

This all works fine; my question is why it works, specifically:

  * Why is the `d10:magnet-uri${magnet_link_length}` part necessary?
  * Why do we add `e` to the end of the magnet link?

By leaving those parts off, I saw that rTorrent won't be able to handle the download.

I've asked Max Gonzih those questions per mail but he can't remember the reason why the created torrent file has to be this way.

The only clue I've found is [this part](https://github.com/rakshasa/rtorrent/blob/f0207ce6548026853ec57ab26f2e57a872f223bb/src/core/download_factory.cc#L169) in the rTorrent code base (in `download_factory.cc`):

    *m_stream << "d10:magnet-uri" << m_uri.length() << ":" << m_uri << "e";

**Comment by kannibalox** [comment]
the `d10:magnet-uri${magnet_link_length}:` and `e` are part of the [bencode](https://en.wikipedia.org/wiki/Bencode) format that rTorrent uses to wrap magnet information (the code that actually parses it out is in [libtorrent](https://github.com/rakshasa/libtorrent/blob/master/src/download/download_constructor.cc#L85)).

**Comment by mb720** [comment]
Thanks @kannibalox for clearing that up!
