### ISSUE TITLE
rtorrent crashing (rock64 ubuntu bionic minimal armhf)

### ISSUE THREAD

**Issue by v9999** [rakshasa/rtorrent#821]
Hey guys, 

I'm trying to run rtorrent in a rock64 board running ubuntu bionic minimal 32bit (armhf).

> Linux rock64 4.4.132-1072-rockchip-ayufan-ga1d27dba5a2e #1 SMP Sat Jul 21 20:18:03 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

I've tried installing rtorrent with three methods: 1) sudo apt install rtorrent (this installs the older version); 2) rtinst; 3) this tutorial: https://npchk.info/ubuntu-bionic-install-rtorrent/ (building from source).

However, the result is always the same: rtorrent keeps crashing after a few minutes running.
Here's the error I receive:

```
Caught SIGBUS, dumping stack:Rate   0.6/426.4 KB] [Port: 34543]                                                                                                                     [U 1/65535] [D 5/65535] [H 0/32] [S 9/19/768] [F 128/128]
rtorrent(+0x1342a) [0xaaf2d42a]
/lib/arm-linux-gnueabihf/libc.so.6(+0x25760) [0xf6bc1760]
/usr/local/lib/libtorrent.so.20(+0x83a4a) [0xf6f42a4a]
/usr/local/lib/libtorrent.so.20(_ZN7torrent9PollEPoll7performEv+0x85) [0xf6ee7a06]
/usr/local/lib/libtorrent.so.20(_ZN7torrent9PollEPoll7do_pollExi+0x6b) [0xf6ee7b18]
/usr/local/lib/libtorrent.so.20(_ZN7torrent11thread_base10event_loopEPS0_+0x127) [0xf6f0d830]
rtorrent(+0x123aa) [0xaaf2c3aa]
/lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x99) [0xf6bb2fe6]

Error: Success
Signal code '1': Invalid address alignment.
Fault address: 0xabc30815
The fault address is not part of any chunk.
Aborted
```

Looks like a build/compilation error ? I have no idea. Didn't have any luck googling around.

So, what should I do to get rtorrent working in this system?
It's pretty annoying, since in my RaspberryPi I just had to go with rtinst and it would work perfectly.

**Comment by cantalupo555** [comment]
OVH(SoYouStart)?

**Comment by v9999** [comment]
Hello there, no, it's a single board computer. Rock64, running an Ubuntu bionic image.
