### ISSUE TITLE
Add Multiple Magnet Link.

### ISSUE THREAD

**Issue by cantalupo555** [rakshasa/rtorrent#822]
Would it be possible to add several Magnet Link at once?

**Comment by jw-redpanda** [comment]
Press ENTER, paste each magnet link plus one newline. e.g

magnet:?xt=urn:xxxxx

magnet:?xt=urn:xxxxx

magnet:?xt=urn:xxxxx

This will creates three torrent tasks

**Comment by chros73** [comment]
Or you can use one of the scripts mentioned [on this page](https://github.com/chros73/rtorrent-ps-ch_setup/wiki/Magnet-link-support).
