### ISSUE TITLE
Start in paused mode a torrent added with "radarr" label

### ISSUE THREAD

**Issue by jean-luc-56** [rakshasa/rtorrent#825]
Hello,

My English is not excellent, I hope you will understand me.

I would like that when a torrent is added via rutorrent by radarr with "radarr" as label, added in paused mode, so that I can start it manually if it suits me after.

I think that must be possible with .rtorrent.rc config file.

Thank you.

**Comment by pyroscope** [comment]
Wrong project, ask the Radarr people and close this. Unless they wok via a watch dir, then read the docs.
