### ISSUE TITLE
Start next stopped, a very basic queue

### ISSUE THREAD

**Issue by virtualghetto** [rakshasa/rtorrent#828]
Hello,

I have a small script that I would like to incorporate into my .rtorrent.rc file, but I don't know how.
The script checks the sessions folder for the number of started torrents. If it finds none, then it returns the hash of the first not started torrent.

```bash
#!/bin/sh
#

#Number of started torrents
RSTARTED=`grep -h state_counteri1 /mnt/rtorrent/session/*.rtorrent | wc -l`

#Check if we have 0 started torrents
if [ $RSTARTED -eq 0 ]
then
        #Get hash of first not started torrent
        grep -h state_counteri0 /mnt/rtorrent/session/*.rtorrent | head -n1 | grep -Eo "[A-Z0-9]{40}\.torrent" | sed 's/\.torrent//g'
fi
```

My idea is to run this script with schedule2 using execute2 I guess, and then d.start (maybe?) the torrent with the given hash. It shouldn't do anything if the above script doesn't return a hash string.

All of my torrents are already loaded into rtorrent but are closed.

Any advice would be greatly appreciated.

My first question is, if I have the hash of torrent, then how would I start it using Ctrl+x ?
I tried (Ctrl+x) d.start=HASHSTRING and that didn't work.

Thanks

**Comment by chros73** [comment]
> My first question is, if I have the hash of torrent, then how would I start it using Ctrl+x ?
> I tried (Ctrl+x) d.start=HASHSTRING and that didn't work.

You can't. It only works via xmlrpc commands, e.g. with pyrocore used in an external script.

What could work (in theory) inside rtorrent that you loop through all the downloads in a sorted/filtered view with `d.multicall2` command and only start the first one (using `branch` command for condition).
But if you need scripting then just go for the pyrocore way.

**Comment by pyroscope** [comment]
Or https://pyrocore.readthedocs.io/en/latest/advanced.html#rtorrent-queue-manager

**Comment by virtualghetto** [comment]
Thank you both for your replies and hints. I'll see if I can figure out how to do what I want using d.multicall2 and branch.
If anyone knows the rtorrent.rc syntax of how this can be done without the use of xmlrpc then please leave me a comment.
I'm closing this ticket for now.

**Comment by chros73** [comment]
Take a look at [this setup](https://github.com/chros73/rtorrent-ps-ch_setup/), maybe it's good for you as well. If not then do it as pyroscope suggested, you save yourself couple of grey hairs :)

**Comment by virtualghetto** [comment]
Based on the wiki (Send email for completed downloads) and a stripped down version of http://www.stabellini.net/rtorrent-howto.txt

Here is a very basic way of starting the next torrent once the currently downloading torrent completes download.

Maybe this or something similar should be added to the wiki.

```python
#!/usr/bin/env python

import glob
import stat
import os
import shutil
import time

watch = "~/rtorrent/watch/start"
queue = "~/rtorrent/watch/queue"

qfiles = glob.glob(queue + "/*.torrent")

oldesttime = 0
oldestfile = ""
time.sleep(60)
for i in qfiles :
        ftime = os.stat(i)[stat.ST_MTIME]
        if oldesttime == 0 or ftime < oldesttime :
                oldesttime = ftime
                oldestfile = i

if oldestfile != "" :
        shutil.move(oldestfile, watch)
```

```bash
#!/bin/sh
#

python ~/rtorrentmovequeue.py
```

```bash
## Create Queue directory
## Create instance directories
execute.throw = sh, -c, (cat,\
    "mkdir -p \"",(cfg.download),"\" ",\
    "\"",(cfg.logs),"\" ",\
    "\"",(cfg.session),"\" ",\
    "\"",(cfg.watch),"/queue\" ",\
    "\"",(cfg.watch),"/load\" ",\
    "\"",(cfg.watch),"/start\" ")

method.set_key = event.download.finished,queue_mv_me,"execute=~/rtorrent_queue_move.sh"
```
