### ISSUE TITLE
event.download.finished not working as torrent not finishing torrent

### ISSUE THREAD

**Issue by superm4n** [rakshasa/rtorrent#830]
Hi First post

i have tried adding the following code to the bottom of my .rtorrent.rc

`method.set_key=event.download.finished,filebot,"execute={/APPBOX_DATA/apps/rutorrent.witzend007.appboxes.co/torrents/config/rtorrent/rtorrent-postprocess.sh,$d.base_path=,$d.name=,$d.custom1=}"`

the code is supposed to call my rtorrent-postprocess script which then runs filbot which basically arranges the files and organises them for me.

however when i add that line into .rtorrent.rc the torrent downloaded doesn't ever show as finished in the history tab (on the Rutorrent GUI) if i comment it out then it does finish and shows that in the history tab im sure that that i have something wrong with the syntax that is preventing rtorrent from sending the event finished.

is there anybody that can either point me in the right direction to the answer as i have spent a while trying to sort this out or kindly lend a hand.

**Comment by chros73** [comment]
> Hi First post

Hi, first, search :)
https://github.com/rakshasa/rtorrent/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen+filebot
