### ISSUE TITLE
Mobile Magnet links not working

### ISSUE THREAD

**Issue by iDylanK** [rakshasa/rtorrent#832]
If i add any torrent magnet link using a particular mobile website, it won’t be able to retrieve the tracker (could not resolve hostname). So it gets stuck. If i Chang the website to a desktop Version, the same magnet link works.. Any ideas? I have had this problem for years and really like to fix it.

**Comment by kannibalox** [comment]
rtorrent doesn't care what site a magnet link came from. I'd recommend comparing the differences between the mobile and desktop magnet links, and reporting the difference to the as-yet unspecified particular mobile website.
