### ISSUE TITLE
This Bittorrent Client is a piece of shit. DONT Use it.

### ISSUE THREAD

**Issue by iamfreaky** [rakshasa/rtorrent#838]
Title Says Everything. Use Deluge or Transmission if you want a relaible software.

**Comment by Akito13** [comment]
> This Bittorrent Client is pice of shit. DONT Use it

Learn your spelling, son.

**Comment by chros73** [comment]
I think this issue can be closed, what do you think guys? :D

Issues like this are pretty sad, at least to say ...
It clearly means that the issuer doesn't have the slightest clue about how much free (!) work/time/energy needed to put into this project (or any other opensource one for that matter) throughout the years.
And clearly, he/she doesn't care either.

What saddens me further that today's opensource "world" arrived to this point, there are people who think githab/gitlab/etc. is a new form of twitter/facebook/etc.
Do you remember how was it 20-30 years ago? What kind of (!) people used those issue trackers back then and today?!

**Comment by pyroscope** [comment]
The kind of people able to quote paths with spaces in their watch schedules?

**Comment by rakshasa** [comment]
Some journalist a couple weeks ago wanted me to comment on that Tron crypto-currency monetizing thing that the mainline client is supposedly going to do. Haven't heard of it, didn't really care.

It did however seem like he wanted me to make some disparaging comments about crypto-currency corrupting the seed ratios, or something. And the players must choose what side of this next big battle they are on, and this is going to be very very big.

To be quite honest, those private tracker ratio-nazis and the crypto-currency globalists can battle it out.

Once I'm done with my first emacs mode, I'll be back,

**Comment by chros73** [comment]
> Tron crypto-currency monetizing thing that the mainline client is supposedly going to do. Haven't heard of it

Me neither, can you give us a link? Thanks

**Comment by rakshasa** [comment]
> > Tron crypto-currency monetizing thing that the mainline client is supposedly going to do. Haven't heard of it
> 
> Me neither, can you give us a link? Thanks

Looks like it's already released: https://www.bittorrent.com/btt/
