### ISSUE TITLE
[Question] Configure to use only in home network

### ISSUE THREAD

**Issue by vedant1811** [rakshasa/rtorrent#839]
Hello,
Not sure if it is possible, but can I configure rtorrent connect torrents only in a specific wifi SSID (or something else that will be unique enough to my home wifi)?

**Comment by chros73** [comment]
E.g. you can [bind it to the wifi interface](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#setting-bind-address).
