### ISSUE TITLE
help with moving a rtorrent session between two pc

### ISSUE THREAD

**Issue by rezad1393** [rakshasa/rtorrent#840]
I am trying to move my rotorrent seeing client from one pc my router.
rtorrent run fine but I am trying to not manually add all the torrent with changed path.
the old path was /media but the new path is /mnt (other part is the same)
so there is a folder called seeding with sub folders for different trackers.

can I edit HASH.torrent.rtorrent files to make rtorrent just seed them?
when I do this for one torrent and test it doesnt work.
rtorrent sees that as empty undowloaded torrent that is gonna be saved in the default download folder (not seeding folder)..

I think this is because the changed hash.torent.rtorrent is not the format it needs and doesnt respect that.

any idea how to edit the session files to make this migration happen?

**Comment by pyroscope** [comment]
Use a symlink.

Or https://pyrocore.readthedocs.io/en/latest/howto.html#move-data

**Comment by rezad1393** [comment]
did it manually. :)
