### ISSUE TITLE
add time custom value

### ISSUE THREAD

**Issue by tillkrischer** [rakshasa/rtorrent#842]
I want to set the custom value addtime when adding torrents.
I managed to produced this:

`method.set_key = event.download.inserted_new,addtime,(cat, "d.custom.set=addtime,", (system.time))`

But everything seems to get the same time.
How do I get delayed evaluation to work / is what I am trying to do even possible ?

**Comment by kannibalox** [comment]
See https://github.com/pyroscope/pyrocore/blob/master/src/pyrocore/data/config/rtorrent.d/timestamps.rc#L14 for an example of a working config. Note the `!` at the front of the event name to ensure it runs early, and the use of `d.save_resume=` to ensure the custom variable gets saved to the session file immediately.

**Comment by tillkrischer** [comment]
Awesome, thats exactly what I was looking for.
Thanks @kannibalox
