### ISSUE TITLE
DHT doesn't work

### ISSUE THREAD

**Issue by Gladuin** [rakshasa/rtorrent#848]
Hello,

When I load a torrent that uses DHT, it says `Tracker [0:0]: Connecting to dht:// [Searching: 8/21 nodes replied]`

After a while, the message disappears and nothing happens, the torrent doesnt start downloading and nothing happens. I know that this torrent works because it downloads fine in qBittorrent on my laptop

[My rtorrent.rc](https://p.teknik.io/Raw/NGSer)

**Comment by mhertz** [comment]
I'm guessing your port 50505 aren't forwarded/open. Trackerless torrents/magnets needs your main incoming port to be open even though e.g. deluge, qbittorrent, transmission and aria2 doesn't.

**Comment by Gladuin** [comment]
Yep that was the problem. 

I thought I had forwarded that port but I forwarded it for another computer on my network and not the one running rTorrent. 

Thanks for the help!
