### ISSUE TITLE
xml-rpc: ipv4 peer address in ipv6 format returned

### ISSUE THREAD

**Issue by sss123next** [rakshasa/rtorrent#849]
https://github.com/rakshasa/rtorrent/blob/master/src/command_peer.cc#L119

https://i.imgur.com/1pSEh1M.png

problem occurs only for incoming connections

**Comment by kannibalox** [comment]
Can you confirm that the issue isn't with how rutorrent displays them? That command works fine for me for both incoming and outgoing connections (the specific IPs have been munged for anonymity):
```
$ rtxmlrpc d.multicall complete p.multicall=,p.is_incoming=,p.address= | fgrep -v '[[]]'
[[[1, '89.13.267.218']]]
[[[1, '378.173.16.65']]]
[[[0, '378.173.16.65']]]
```

**Comment by sss123next** [comment]
can you explain how to test it please ?

i am not php programmer, so i prefer command line method if exists.

thx.,

**Comment by rakshasa** [comment]
This is being rewritten, reopen if it is still an issue after the feature-bind branch is done.
