### ISSUE TITLE
Moving torrents using Fast Resume deletes the torrent-data from disk.

### ISSUE THREAD

**Issue by smathev** [rakshasa/rtorrent#852]
Hi all.

I'm having a weird issue, which I don't know how to fix or even troubleshoot.

Using the latest rtorrent, it seems that if I move a completed (downloaded) torrent from one location to another (on the same disk) rTorrent deletes the downloaded file, and moves the download location, and then starts redownloading the file.

The torrent goes from 100% to 0% and starts downloading again. Searching for the data, I find that the data too is gone from the disk.

When I disable the Fast Resume option during a move, the file is moved without issue and the torrent stays at 100%.

It's irritating to say the least to have to remember to disable the option everytime I move a file, so if there simply was a way in the rtorrent.rc to disable the option as standard that would be great.

Thanks in advance.

**Comment by chros73** [comment]
> When I disable the Fast Resume option during a move

Do you use any frontend, e.g. ruTorrent? If so, I can't help you with it since I'm not. It'd be better to ask them.

**Comment by smathev** [comment]
Yep - using ruTorrent which exhibits the behavior, I've yet to try it using CLI - since I've never really used it. Guess I will try to move a torrent using it, but I'm unsure how to do it :/

**Comment by pyroscope** [comment]
https://pyrocore.readthedocs.io/en/latest/howto.html#move-data
