### ISSUE TITLE
XML-RPC with rtorrent & lighttpd

### ISSUE THREAD

**Issue by FlyingPersian** [rakshasa/rtorrent#855]
Hi
I'm trying to get XML-RPC to work with rtorrent and Lighttpd on FreeBSD (FreeNAS). I have xmlrpc-c installed and configured everything both in the .rtorrent.rc and lighttpd.conf as it is described in the wiki.

lighttpd.conf & .rtorrent.rc: https://pastebin.com/i1cWYCDj

When I try to access it via ip:port/RPC2, I get a 500 Internal Server Error. I have enabled "mod_scgi" in modules.conf of lighttpd as well. Using "xmlrpc" as a standalone command in the console gives me a "command not found", even though xmlrpc-c is installed (v1.43.08).

Lighttpd version: 1.4.53 
rtorrent version: 0.9.7_3

Edit: Here the debug error log: https://pastebin.com/0KPjE5t6

**Comment by chros73** [comment]
You can use [pyrocore](https://github.com/chros73/rtorrent-ps-ch_setup/wiki/Queue-Manager) utils instead (no webserver is required).

**Comment by loadletter** [comment]
I had the same issue on Gentoo after copying a working config from an old install.

Fortunately rutorrent seems to work just fine without RPC2 after setting the rpc socket at cgi_host in rutorrent/conf/config.php

**Comment by FlyingPersian** [comment]
> I had the same issue on Gentoo after copying a working config from an old install.
> 
> Fortunately rutorrent seems to work just fine without RPC2 after setting the rpc socket at cgi_host in rutorrent/conf/config.php

Sorry for the super late response. Any chance you can share all your configs? lighttpd + modules, rutorrent, rtorrent?
