### ISSUE TITLE
I'm having an issue with executing script on complete

### ISSUE THREAD

**Issue by PyR8zdl** [rakshasa/rtorrent#864]
I'm having an issue with executing script on complete.

I'm not 100% sure it's rtorrent but I just don't see anything wrong with my script.

So I have in rtorrent.rc the following...

`method.set_key = event.download.finished,chxpost,"execute=/home/owner/bin/chxpost.sh,$d.hash=,$d.custom1="`

The contents of chxpost.sh is...

> #!/bin/bash
> hash=$1
> label=$2
> 
> json=$(rtcontrol --json hash="$hash" | jq .[])
> fpath=$(echo $json | jq -r .path)
> 
> if ! [[ $label =~ CHX ]];
> then
>     echo "$fpath" >> /home/owner/bin/test.txt
>     /usr/bin/python /home/owner/bin/chxv1.7beta.packs.py "$fpath"
> fi

So my problem is this...
When chxv1.7beta.packs.py is ran, It is ran without the args of $fpath

But If I was to run chxpost.sh manually in shell like

/home/owner/bin/chxpost.sh <TORRENT HASH>

The python script is called with args passed.

Is there something happening when rtorrent executes a command that would stop this from working?

I really have no idea whats going on here.

**Comment by PyR8zdl** [comment]
I wonder if I could bypass the bash script and execute the python script directly from rtorrent.rc

Is there a way to execute a script only if the torrents label is Not X?

If not d.custom1 == CHX then execute /home/owner/bin/chxv1.7beta.packs.py "$var_for_torrent_data_dir"

Something like that would be best but not sure if it's something that can be done.

**Comment by PyR8zdl** [comment]
Ok I got it working by passing the d.datapath var from rtorrent.rc to script.

For some reason rtcontrol didn't pass the data path when executed so soon after torrent completed.

Everytime I manually ran script it worked fine so I think it was just a timing issue.


I am interested if there is a way to use IF VAR == Foo than logic in rtorrent.rc 

Otherwise this issue can be closed.

**Comment by maxonly1** [comment]
execute is a deprecated command. it's replaced by execute2.

maybe this would work:
method.set_key = event.download.finished,chxpost,"execute2=/home/owner/bin/chxpost.sh,$d.hash=,$d.custom1="

**Comment by chros73** [comment]
> I am interested if there is a way to use IF VAR == Foo than logic in rtorrent.rc

There's an `if` and a `branch` command for this. You can take a look at these projects for live examples about rtorrent scripting: [pimp-my-box](https://github.com/pyroscope/pimp-my-box/tree/master/roles/rtorrent-ps/templates/rtorrent), [rtorrent-ps-ch_setup](https://github.com/chros73/rtorrent-ps-ch_setup/tree/master/ubuntu-14.04/home/chros73)

**Comment by pyroscope** [comment]
the problem is calling back to xmlrpc from an *active* handler – boom, deadlock.
instead simply pass the data path to the handler script.
