### ISSUE TITLE
Please update the wiki

### ISSUE THREAD

**Issue by nabice** [rakshasa/rtorrent#867]
Or users would be confused.
https://github.com/rakshasa/rtorrent/blob/c62fa6a75649efe8cedb91c66d1b05b2b1be8872/src/ui/download.cc#L379-L395
https://github.com/rakshasa/rtorrent/wiki/User-Guide#download-view-keys

**Comment by chros73** [comment]
The WIKI is editable by anyone, so you can do it as well :) Thanks!

**Comment by nabice** [comment]
@chros73 I only modified the parts I can understand.
