### ISSUE TITLE
Why is my torrent in "finished" status

### ISSUE THREAD

**Issue by allifir** [rakshasa/rtorrent#869]
I'm using rtorrent (via ruTorrent) on a rented seedbox server.  I found that one of my torrents, which it was my intention to seed indefinitely, had stopped seeding and was showing as being in "finished" status.  I want to configure the system to never "finish" seeding anything at all; the whole point of using the software is to continue seeding.  But I can't find any corresponding setting and a search for the term "finished" in the documentation just finds references to torrents that have finished downloading.  Need help.

**Comment by Micdu70** [comment]
You can't change the number of active torrents if your seedbox offer doesn't have unlimited active torrents.
And it's not a rTorrent issue, please ask your seedbox provider...

**Comment by kannibalox** [comment]
Please refer to ruTorrent's support channels for ruTorrent support. If you believe it's an issue with rTorrent, please provide the status of the torrent as shown in rTorrent directly.
