### ISSUE TITLE
Inactive: Download registered as completed, but hash check returned unfinished chunks.

### ISSUE THREAD

**Issue by cppt** [rakshasa/rtorrent#871]
Verions:
ubuntu 18.04
rTorrent 0.9.6

I've been running rTorrent successfully within ubuntu for several weeks but am regularly greeted by the above upon restarting or starting post-restart.  I'll add that I've edited the .rtorrent.rc file to allow automatic loading of torrents from specified directories and DLing to corresponding directories.  I've included the content that I've modified within the .rc file below.  

Any torrents which had previously been downloaded successfully return the above error if I close and relaunch rTorrent.  The media itself hasn't moved or change and the directory location is the same.  The issue appears to be that rTorrent only recognizes active torrents for a single rTorrent session.  

Any ideas how to allow continued seeding of previously dled torrents after restarting rTorrent? 

Many thanks,
Chris

```
# Default directory to save the downloaded torrents.
#directory = /home/chris/rTorrent/newDLs

# Default session directory. Make sure you don't run multiple instance
# of rtorrent using the same session directory. Perhaps using a
# relative path?
session = /home/chris/rTorrent/session

#delete data when removed from rtorrent
#method.set_key = event.download.erased, remove_file,"execute={rm,-drf,--,$d.get_base_path=}"
#if necessesary
#on_erase = remove_file,"execute={rm,-drf,--,$d.get_base_path=}"

# Watch a directory for new torrents, and stop those that have been
# deleted.
schedule2 = watch_directory_1,5,5,"load.start_verbose=/home/chris/rTorrent/torrents/Music/*.torrent,d.set_directory=\"/media/E/1Music\""
schedule2 = watch_directory_2,5,5,"load.start_verbose=/home/chris/rTorrent/torrents/Videos/*.torrent,d.set_directory=\"/media/E/2Videos\""
```

**Comment by kannibalox** [comment]
Is it possible that rtorrent is starting up before the underlying storage is ready?

**Comment by cppt** [comment]
No, this happens whether I've recently restarted or I simply hadn't started
rTorrent post-startup (hence the system has been up for some time)

**Comment by rakshasa** [comment]
That error message is something that mainly happens when there are issues with the file system, the check was added as kernel-side mmap implementations were generally rather inadequate.

What filesystem/kernel are you using?

**Comment by cppt** [comment]
kernel details below.  I'm saving torrents to directories on /home formatted as ext4, and the resulting files on an external HD formatted as NTFS

```
chris@chris-X1C6:~$ uname -a
Linux chris-X1C6 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
chris@chris-X1C6:~$ df -hT | grep -v /dev/loop
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  7.7G     0  7.7G   0% /dev
tmpfs          tmpfs     1.6G  3.9M  1.6G   1% /run
/dev/nvme0n1p5 ext4       40G   28G  9.4G  75% /     // torrent save directory  
tmpfs          tmpfs     7.8G  311M  7.5G   4% /dev/shm
tmpfs          tmpfs     5.0M  4.0K  5.0M   1% /run/lock
tmpfs          tmpfs     7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/nvme0n1p4 fuseblk    50G  1.5G   49G   3% /media/Share
/dev/nvme0n1p1 vfat      256M   34M  223M  14% /boot/efi
tmpfs          tmpfs     1.6G   12K  1.6G   1% /run/user/121
tmpfs          tmpfs     1.6G  108K  1.6G   1% /run/user/1000
/dev/sdb2      fuseblk   4.6T  1.3T  3.3T  29% /media/E     // file save directory
```

**Comment by kannibalox** [comment]
given that the files are located on a fuse mount, i'd like to repeat my question, given that fuse mounts for remote storage can return "not found" more easily than "not available yet"

**Comment by rakshasa** [comment]
These kinds of errors are almost certainly caused by the FS layer, as it is showing up when there's a kernel bug in the memory mapping or file system layer.

In this case I'm assuming the FUSE layer is telling us that the pages we sync'ed, got a confirmation it was and unmapped, actually wasn't.
