### ISSUE TITLE
How to disable hash check?

### ISSUE THREAD

**Issue by USRGH** [rakshasa/rtorrent#872]
Hello,
using rTorrent 0.9.6/0.13.6 with ruTorrent 3.9.
I moved rTorrent to another server and now I want to add all torrents from previous server. If I add torrents, hash check starts. 
I will add torrent files to watch folder of rTorrent.

How can I disable checking?

**Comment by cantalupo555** [comment]
Add lines .rtorrent.rc file

`# Check hash for finished torrents. Might be usefull until the bug is
# fixed that causes lack of diskspace not to be properly reported.
check_hash = no
`

**Comment by USRGH** [comment]
Sorry forgot to write it. I already have check_hash = no in .rtorrent.rc
Added it but checking still works

**Comment by Eruurk** [comment]
Did you restart rtorrent after modify .rtorrent.rc?
.rtorrent.rc is only read on each start.

**Comment by USRGH** [comment]
Yes I restarted rtorrent.

**Comment by kannibalox** [comment]
I think `check_hash` may be misunderstood, see [here](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-pieces-hash-on-completion) for an explanation of how it works (`check_hash` is deprecated, `pieces.hash.on_completion` is the new syntax). As such, it depends entirely on how you're adding them. If you copy the session directory and all the data is in the same place, it should just start right up. If you try to add the via rutorrent manually, then of course it will try to hash check them individually. Fast resume is already an abused feature, disabling checking globally is an even worse idea.

**Comment by rakshasa** [comment]
You need to preserve the last modified time stamps of all files when you copy them, or you need to change the torrent's session files with the new modified time stamps.

The former should be the easiest solution.

**Comment by john-peterson** [comment]
Can I stop a running hash check without removing the torrent

**Comment by kannibalox** [comment]
> Can I stop a running hash check without removing the torrent

Simply close/stop the torrent.
