### ISSUE TITLE
Persistent labels

### ISSUE THREAD

**Issue by csjoh** [rakshasa/rtorrent#875]
Transitioning from uTorrent 2.2.1 to rTorrent and while rTorrent does nearly everything I need, I would like to see a possibility to define a persistent list of labels to avoid having to type them in for every torrent. This is useful for general downloading as well as for serials, where there's an episode released every week or so.

uTorrent 2.2.1 has a text box in the settings dialog under Advanced where a pipe separated list of persistent labels can be entered, like this:

Movies\Hollywood|TV series\Series 1\Season 1|Kids\Movies|Kids\Cartoons

and so on. I would love to see this in rTorrent (or implemented in a web GUI like ruTorrent; either works for me).

This is in Windows notation, and each backslash is thus a folder separator, meaning that a torrent downloaded and has one of the labels attached, would be moved to its right place in a file hierarchy. I.e., if the download base folder is E:\media, a torrent labeled with "TV series\Series 1\Season 1" would create the folder structure and place the downloaded torrent in "E:\media\TV series\Series 1\Season 1". For *nix systems, just replace the \ with / and it should behave the same.

I have seen much discussion about the use of d.set_custom1 for labels, but nothing explicit on whether that can be used to define persistent labels. If that variable covers this already I sorry for the noise, but would like to know how to use it for the above purpose.

**Comment by chros73** [comment]
Yep, there's nothing built-in exists, but it can be scripted (as you said):
- pyroscope implemented labels (and their corresponding views) in [PmB](https://github.com/pyroscope/pimp-my-box/tree/master/roles/rtorrent-ps/templates/rtorrent)
- I went on the [category](https://github.com/chros73/rtorrent-ps-ch_setup/) road (1 download can be only assigned to 1 category)

**Comment by rakshasa** [comment]
As said this is possible to do with what rtorrent already provides.
