### ISSUE TITLE
Feature request: Failsafe mode.

### ISSUE THREAD

**Issue by pthfdr-42** [rakshasa/rtorrent#876]
Sometimes a power failure could happen and the disk cannot sync, resulting in corrupted files.
I think that you should add a command option (`--failsafe`). When it is included in the command line, every torrent would be closed and all network activities are disabled until you manually start a torrent. This gives the user a chance to initiate a hash check.

**Comment by pyroscope** [comment]
DIY. `-o import=failsafe.rc` and add the few needed commands in there (0 up/down global, multicall with d.close).

**Comment by rakshasa** [comment]
Essentially this, and add it to the wiki.

It would even be possible to add the failsafe.rc block to the client as a command line option.
