### ISSUE TITLE
QUEUE

### ISSUE THREAD

**Issue by sirfom** [rakshasa/rtorrent#878]
After adding torrent it goes to QUEUE instead of Downloading or instead of checking.
Currently I have 25 active torrents and it goes to queue. If I stop some of the torrents then it starts checking or downloading. When it reaches 25-30 active torrents again problem starts. If I restart seedbox then all queued torrents stats seeding or downloading. Currently I am using seedboxes.cc and it has problem. I asked them from almost a month but they did not able to fix the issue and they told me to ask here about solution.

I never face this kind of issue on other seedbox provider.

**Comment by Micdu70** [comment]
What about the rtorrent config (`.rtorrent.rc` file)?
If using ruTorrent WebUI, try to check limitations (only if "connection" setting menu is not hidden by the seedbox provider...):
![rutorrent](https://user-images.githubusercontent.com/8136676/58784465-c888f500-85e3-11e9-88f1-5fb892be57de.JPG)

This provider gives very few info about their offers...

**Comment by kannibalox** [comment]
Please use ruTorrent support channels for questions about ruTorrent.
