### ISSUE TITLE
Pushbullet Notifications

### ISSUE THREAD

**Issue by jaffa374** [rakshasa/rtorrent#881]
So I'm new to rtorrent, so bear with me. 

I currently use RUTorrent and use pushbullet to notify on all events. This works fine. 

But when I add via schedule watch folder and rtorrent picks up the .torrent file, these notifications don't trigger. From reading up i'm guessing it needs adding to the rtorrent.rc file, as autotools must be handling it via the GUI. 

1. Is my logic correct that watch folder additions via rtorrent.rc file won't trigger RUTorrent's notifications?
2. If 1. is correct, then how do I set these up!

Cheers

**Comment by rakshasa** [comment]
Sounds like it's RUTorrent related, ask them.
