### ISSUE TITLE
Issue compiling

### ISSUE THREAD

**Issue by joydashy** [rakshasa/rtorrent#882]
I cloned the repo and ran autogen, configure and make, this errors:

> In file included from ./../globals.h:41:0,
>                  from manager.cc:64:
> ../../rak/priority_queue_default.h: In destructor ‘rak::priority_item::~priority_item()’:
> ../../rak/priority_queue_default.h:56:95: warning: throw will always call terminate() [-Wterminate]
>        throw torrent::internal_error("priority_item::~priority_item() called on a queued item.");
>                                                                                                ^
> ../../rak/priority_queue_default.h:56:95: note: in C++11 destructors default to noexcept
> manager.cc: In member function ‘void core::Manager::listen_open()’:
> manager.cc:209:70: error: no matching function for call to ‘torrent::ConnectionManager::listen_open(int&, int&)’
>      if (torrent::connection_manager()->listen_open(boundary, portLast) ||
>                                                                       ^
> In file included from manager.cc:52:0:
> /usr/local/include/torrent/connection_manager.h:147:23: note: candidate: bool torrent::ConnectionManager::listen_open()
>    bool                listen_open();
>                        ^~~~~~~~~~~
> /usr/local/include/torrent/connection_manager.h:147:23: note:   candidate expects 0 arguments, 2 provided
> manager.cc:210:71: error: no matching function for call to ‘torrent::ConnectionManager::listen_open(int&, int&)’
>          torrent::connection_manager()->listen_open(portFirst, boundary))
>                                                                        ^
> In file included from manager.cc:52:0:
> /usr/local/include/torrent/connection_manager.h:147:23: note: candidate: bool torrent::ConnectionManager::listen_open()
>    bool                listen_open();
>                        ^~~~~~~~~~~
> /usr/local/include/torrent/connection_manager.h:147:23: note:   candidate expects 0 arguments, 2 provided
> manager.cc:214:71: error: no matching function for call to ‘torrent::ConnectionManager::listen_open(int&, int&)’
>      if (torrent::connection_manager()->listen_open(portFirst, portLast))
>                                                                        ^
>

**Comment by kannibalox** [comment]
Having https://github.com/rakshasa/libtorrent installed is a hard dependency for rtorrent.

**Comment by joydashy** [comment]
Ok thanks, that helped!
