### ISSUE TITLE
Restart previously active torrents each time rTorrent is launched

### ISSUE THREAD

**Issue by c3td** [rakshasa/rtorrent#884]
This seems like it should have an easy answer, but I didn't find it looking through documentation/Wiki/assorted config files...is there a way for rTorrent to restart all previousl active torrents automatically with launch?  

At this point, launching rTorrent retrieves all previous torrents, but all are listed as [CLOSED], and I have to go through and manually reopen each.  

The load.start parameter I use as part of scheduling loads downloaded torrents automatically, but if I close rTorrent, it doesn't restart them.  Other versions don't seem likely to address my issue.  Is this a separate parameter or is there some other way to achieve this?

**Comment by pyroscope** [comment]
What you describe is the *default* behaviour, given a session is active. So find out what you did to break that.

**Comment by c3td** [comment]
Interesting.  Any thoughts what to look for to debug (does rTorrent save log files anywhere)?  I do get a handful of seemingly trivial messages at start up, they don't impact use and go away shortly thereafter.  

Settings are pretty standard.  I've added portions to my .rtorrent.rc file to set up watch directories for different file types.  Otherwise haven't changed much.
