### ISSUE TITLE
cannot get get value of variable $t.url in .rtorrent.rc

### ISSUE THREAD

**Issue by xyou365** [rakshasa/rtorrent#891]
When I add this line to .rtorrent.rc file, it is okay
method.set_key = `event.download.finished,notify_me,"execute2=python3,~/u.py,$d.name=,$d.size_bytes=,$d.custom1="`

But when I add this line to my code, it does not execute at all (think there is something error):
`event.download.finished,notify_me,"execute2=python3,~/u.py,$d.name=,$d.size_bytes=,$d.custom1=,$t.url"`

**Comment by chros73** [comment]
[`t.*` commands](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#t-commands) can't be used as `d.commands`!

**Comment by xyou365** [comment]
Thx. It is me do not know how to use it.

I know I should not ask about usage rather bug here, but could you tell me if it is possible to get the value of t.url directly in .rtorrent.rc or possible to show me a demo code?

**Comment by pyroscope** [comment]
https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-d-tracker-domain

And as it says, rT-PS only.
