### ISSUE TITLE
I can download from magnet and public torrents even with dht disbaled

### ISSUE THREAD

**Issue by rezad1393** [rakshasa/rtorrent#895]
I have set this in my confid but if I add a megnet to rtorrent it download the correct torrent and then later downloads the torrent.

dht.mode.set = disable
protocol.pex.set = no
trackers.use_udp.set = no

I thought this was supposed to be private mode of rtorrent?

it seems to disbale udp trackers and only use http public trackers (at least for the torrent I tested) so maybe the only bug is the dht that seems to be on and downloads the torrent.'

my rtorrent version is 0.9.6 (on openwrt so I cant install 0.9.7 right now).

**Comment by mhertz** [comment]
Those settings disable DHT and UDP-trackers, but the spec for magnets supports optionally specifying trackers so if the magnet includes a http-tracker then your settings wouldn't hinder it. BTW, all torrent clients disable DHT and PEX when the private flag is set in the torrent, so no need for a specific "private-mode" per-say.
