### ISSUE TITLE
Bumped API verson (9 -> 10) for rTorrent 0.9.8, why?

### ISSUE THREAD

**Issue by Micdu70** [rakshasa/rtorrent#896]
API version bumped to 10 for rTorrent 0.9.8, but is there changes in commands names or functionality from 0.9.7 release?

A weird thing => "feature-bind" branch = API version 10 with some commands names changed from "master" branch. And "master" branch has API version 10 now but without (same) changes...

Is it a mistake?

**Comment by rakshasa** [comment]
New commands were added in 0.9.8, so the number was bumped.

The feature-bind branch hasn't been merged yet, so the api version number is not guaranteed to be useful. I'll bump it to 11 however.

**Comment by Micdu70** [comment]
Okay... it's fine for ruTorrent if you don't bump the rtorrent version in "feature-bind" branch. ^^

Anyway, it would be cool to have a "beta" tag in version number for this branch... ;-)

**Comment by rakshasa** [comment]
The version number is an integer making it easy to check in code for stuff changing between releases.

Perhaps another command to see if it is master, or some other variant like the now long-lived feature-bind branch.

**Comment by Micdu70** [comment]
"Perhaps another command to see if it is master, or some other variant like the now long-lived feature-bind branch."

Nice idea! 👍 

I can close this issue, thanks for your answers. ;)

**Comment by pyroscope** [comment]
The answer to this is not yet another single number or flag, but https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-system-has
