### ISSUE TITLE
Rtorrent memory leak

### ISSUE THREAD

**Issue by badgv** [rakshasa/rtorrent#900]
Rtorrent consumes a lot of memory when downloading or uploading at high speed. The most important problem is that when the speed is lowered, or the rtorrent is directly closed, the occupied memory will not be released.

The system used is debian9 or debian10. The Linux kernel version number is higher than 4.9. Rtorrent runs in the docker environment or runs directly in the current system environment. This problem occurs.

In the case of high memory usage, the load on the CPU is greatly increased.

The same docker image in synology, there is no problem. Currently the core of Synology is 4.4.

It is not certain whether this is caused by libtorrent or by rtorrent.

Is there such a possibility, libtorrent or Rtorrent memory release code, is not compatible with the newer Linux kernel

Does anyone else have the same problem with me?

**Comment by chros73** [comment]
> Rtorrent consumes a lot of memory when downloading or uploading at high speed.

This is probably related to this issue: #443 (beware, huge amount of comments :) )

> when the speed is lowered, or the rtorrent is directly closed, the occupied memory will not be released.

Now that's new to me.
Which rtorrent/libtorrent version do you use?

> In the case of high memory usage, the load on the CPU is greatly increased.
> The same docker image in synology, there is no problem. Currently the core of Synology is 4.4.
> It is not certain whether this is caused by libtorrent or by rtorrent.

Or maybe an external library, like curl.

You can try out lastest [rtorrent-ps-ch](https://github.com/chros73/rtorrent-ps-ch) on Debian 9 to see if the issue still exists (it uses certain libraries), you [don't have to build it](https://github.com/chros73/rtorrent-ps-ch/blob/master/docs/DebianInstallFromTarballsPackages.rst) if you don't want.

**Comment by rakshasa** [comment]
If the memory isn't released after the rtorrent/libtorrent process has been killed, it means the kernel, or in this case virtualization, layer is at fault.

Had the same kinds of weird FS/paging issues a decade ago where rtorrent was exposing quite a few kernel bugs. Since we are now in the era of docker containers and all that fun stuff, I guess we're going to have some fun again.

Push this issue upstream, it's their responsibility.

**Comment by pyroscope** [comment]
also, "free -m" WITHOUT BUFFERS and after a sync.

**Comment by rakshasa** [comment]
Closing this as it seems like a kernel issue.
