### ISSUE TITLE
question : seeding newer before older

### ISSUE THREAD

**Issue by fuspu** [rakshasa/rtorrent#901]
How do i get rtorrent to seed newer downloads before older ones? I'll download something and just as it finishes it will stop seeding and go to an older download.

**Comment by chros73** [comment]
I don't think you can prioritise downloads while seeding (you can while downloading), but maybe I'm mistaken.
But rtorrent should handle everything automatically, if you set the [right config values](https://github.com/rakshasa/rtorrent/wiki/Performance-Tuning) (Peers and slots section) based on your connection speed.

**Comment by rakshasa** [comment]
Allocation of peer seed slots does not allow you to prioritize, however this is a possible future improvement we can do.
