### ISSUE TITLE
God, I hate systemd

### ISSUE THREAD

**Issue by weaselBuddha** [rakshasa/rtorrent#909]
Might want to make a note on the tuning wiki, systemd by default limits fids to 4096. That limit creates havoc when tuning rtorrent for a large footprint installs.

**Comment by rakshasa** [comment]
Since you've encountered the issue, could you update the wiki?

**Comment by Pheromon** [comment]
what do you mean with "fids"? File descriptors?

**Comment by weaselBuddha** [comment]
> Since you've encountered the issue, could you update the wiki?

Done.

> what do you mean with "fids"? File descriptors?

Ya, old school, File Identifier (FID). Where were you when I was ripping my hair out? Baldness sucks.

It can also be added systemd wide,  https://superuser.com/a/1322187

**Comment by rakshasa** [comment]
Thanks.
