### ISSUE TITLE
"info line" format (customise or cleanup)

### ISSUE THREAD

**Issue by sitaramc** [rakshasa/rtorrent#911]
Hi

Is there any way to clean up the "info line"?  Referring to the items in https://github.com/rakshasa/rtorrent/wiki/User-Guide#torrent-info-line-explanation for context, It would be nice to have the `[24%]` right after the numbers that it relates to (`161.6 / 617.2 MB`), and the `R: 0.03` be right after the `Uploaded: 5.1 MB`.

And while we're about it, can that also be made a percentage instead of a ratio, just to be consistent with the other one?  (Or change the other one to a ratio, that's consistent too).

I realise this is trifling matter, but at the same time it also seems relatively easy to do.  (Sadly my C programming days are decades behind me and I never learned C++, so I can't offer to send a PR)

**Comment by rakshasa** [comment]
Don't bother with libtorrent packages when making pull requests, use the git HEAD for both.

**Comment by sitaramc** [comment]
On 9/13/19 1:35 PM, Jari Sundell wrote:
> Don't bother with libtorrent packages when making pull requests, use the
> git HEAD for both.

I guess I could build libtorrent also, but I shouldn't *need to*.  Not
for such a trivial change (i.e., just a reordering of some printed output).

It's literally just swapping two paragraphs in display/utils.cc.  I
checked out 0.9.7, made the change, built, and tested it out on some
random torrent.  Seems to work fine.

I'll work something out this weekend or the next to do this on "master",
and then send in a PR.

**Comment by pyroscope** [comment]
Or define whatever you want in the config... https://rtorrent-ps.readthedocs.io/en/latest/customize.html#customizing-the-display-layout

**Comment by sitaramc** [comment]
On Sat, Sep 14, 2019 at 06:47:13PM -0700, PyroScope Project wrote:
> Or define whatever you want in the config... https://rtorrent-ps.readthedocs.io/en/latest/customize.html#customizing-the-display-layout

very pretty, but I use (any) torrent about once in a couple of
months, if that.

If I were using it more frequently I'd have gotten used to the
layout and probably would not have opened this issue :-)

**Comment by sitaramc** [comment]
I'm closing this because I could not make any headway in submitting a patch, having failed to even *compile* with a system installed libtorrent.  And I am not willing to go down the rabbit hole of compiling *that* as well (as suggested by the author) -- that does not seem like it should be necessary if the version numbers match.

As such, since I can't submit a patch, I don't feel it's right for me to leave the issue open.
