### ISSUE TITLE
Debug Logging

### ISSUE THREAD

**Issue by wheelerlaw** [rakshasa/rtorrent#916]
Debug logging is currently not showing a lot of information. 

I currently have `log.add_output = "debug", "log"` added in my rtorrent.rc, however I'm not seeing any evens for RPC calls. Can the RPC events be added to the debug group?

**Comment by rakshasa** [comment]
```
rpc_events
rpc_dump
```

Debug does not include rpc events.

**Comment by pyroscope** [comment]
https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#log-commands
