### ISSUE TITLE
Rtorrent not working

### ISSUE THREAD

**Issue by GhostValk** [rakshasa/rtorrent#918]
For some reason i'm not able to download anything with rtorrent; i think it's some kind of problem with the DHT tables. Any torrent i load, either via a magnet link or a torrent file gets stuck with a similar message to:

    Tracker[6:6]: Connecting to dht:// [Searching: 10/13 nodes replied]

The amount of nodes varies from torrent to torrent, but after sticking with that for a while, that message just disappears and it doesn't do anything else.

Any idea?

EDIT: It's not a port problem, i've tried with a lot different ports and other torrent clients work perfect with those ports, it isn't a torrent problem either, i've tested like 30 different torrents with a lot of seeds and nothing.

**Comment by chros73** [comment]
Take a look at this, hopefully it helps: [link](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#supporting-public-torrents-magnet-links-udp-trackers-dht)

**Comment by GhostValk** [comment]
It worked perfectly, thanks a lot!
