### ISSUE TITLE
pieces.hash.on_completion not staying set 0.9.7

### ISSUE THREAD

**Issue by weaselBuddha** [rakshasa/rtorrent#919]
Very odd behavior I'm seeing, freshly compiled rtorrent 0.9.7, ubuntu 18.04

**rtxmlrpc pieces.hash.on_completion**
**1**

with no mention of pieces.hash.on_completion in .rtorrent,rc, default is false, right? So it should be 0

Oddly, using rutorrent (3.8) to flip it off, it will stay off for awhile, and then it will flip back on

So, default issue I figure, lets be explicit. I put this at bottom of .rtorrent.rc

pieces.hash.on_completion.set = false

restart rtorrent. and as expected:

**rtxmlrpc pieces.hash.on_completion
0**

All good.

I reboot.

**rtxmlrpc pieces.hash.on_completion
1**

WTH?

What else influences pieces.hash.on_completion?  Anything that might cause the value to flip? Some other .rtorrent.rc value? Clock issues? Poettering fugg me again? Invasion of the hash check snatchers? I smoked too much hash when I was young and god thinks this is funny?

**Comment by pyroscope** [comment]
if in doubt, blame rutorrent. i.e. remove it from the rc and restart / reboot.

**Comment by rakshasa** [comment]
Let's blame it on rutorrent.
