### ISSUE TITLE
High memory Debian 10 buster rtorrent

### ISSUE THREAD

**Issue by guccifur** [rakshasa/rtorrent#920]
Hi!
I'm currently using debian 10 (buster)
The rtorrent version I'm using is 0.9.8.

My vps server is a KVM and has 2 gigs of ram.
The problem is when I download a torrent my ram gets saturated within a couple of seconds.
The ram also wont release after the torrent finished downloading.

I've seen similar issues but not a fix for this.
I hope someone can help me out 
Thanks in advance

**Comment by pyroscope** [comment]
what exactly is "ram" – there's endless ways to measure that.

**Comment by guccifur** [comment]
My random access memory.
According to the free -m command I only have 40 mb ram left of the 2 gigs.
It increases by 100 mb every few seconds until it reaches 1.88 gigs

This already happends when I add 1 torrent

**Comment by pyroscope** [comment]
Unless it is without buffers/cache, that's not relevant.

**Comment by guccifur** [comment]
Pardon?
My issue is that when ever I run rtorrent and I download a torrent. it uses all my memory I have and I cant add more than 3/4 torrents or my vps crashes.

after downloading my memory wont be released/cleared either.

**Comment by pyroscope** [comment]
https://g.co/kgs/T7g7ga

**Comment by guccifur** [comment]
Lol, thanks for that.
But thats not gonna help me.
I cant add more than 1 or 2 torrents or my rtorrent crashes. I only have issues on debian 10. Runs fine on centos 6.
If you not interested in helping ill search further. Thanks for trying tho.

**Comment by andrew-phi** [comment]
Thanks for the info, I was going to try rtorrent on Debian 10 in production mode. Now I'm holding back.

**Comment by rakshasa** [comment]
Closing this as probably not an issue with rtorrent itself.
