### ISSUE TITLE
Rtorrent doesnt start in Debian Buster

### ISSUE THREAD

**Issue by damionx7** [rakshasa/rtorrent#922]
rtorrent: error while loading shared libraries: libcppunit-1.13.so.0

OS : Debian buster 
rtorrent version : 0.9.7-1

<img width="903" alt="Screenshot 2019-10-04 at 5 36 05 PM" src="https://user-images.githubusercontent.com/6530843/66206436-be7c1d80-e6cd-11e9-9692-e0cfa73f0621.png">

**Comment by rakshasa** [comment]
Talk to the people who made the packages.

**Comment by Fronix** [comment]
Sorry for opening but I think it's important if someone else finds this issue. I've tried to contact the people in charge of the libcppunit package but not getting much from there.

The workaround for this (worked for me) is to add the stretch source mirror and simplyinstall the libcppunit package from stretch.

1. nano /etc/apt/sources.list
2. Add the following at the bottom:
``` 
deb http://ftp.debian.org/debian/ stretch main contrib non-free
deb-src http://ftp.debian.org/debian/ stretch main contrib non-free
```
3. run `apt update && apt install libcppunit-1.13-0v5`
4. After this you should comment out the stretch mirrors in your sources file and run `apt udpate` again.

A warning, don't take this as a solution.. It's a workaround and should be treated as such.

**Comment by kannibalox** [comment]
> Sorry for opening but I think it's important if someone else finds this issue. I've tried to contact the people in charge of the libcppunit package but not getting much from there.

Don't talk to them, talk to the people that compiled the rtorrent package, since an error about loading shared libraries generally means a program was compiled against packages that don't exist locally, and only the original compilers will know the full list of dependencies.

As an aside, I wouldn't recommend installing stretch packages on buster if that's indeed what's happening.

**Comment by Fronix** [comment]
> > Sorry for opening but I think it's important if someone else finds this issue. I've tried to contact the people in charge of the libcppunit package but not getting much from there.
> 
> Don't talk to them, talk to the people that compiled the rtorrent package, since an error about loading shared libraries generally means a program was compiled against packages that don't exist locally, and only the original compilers will know the full list of dependencies.
> 
> As an aside, I wouldn't recommend installing stretch packages on buster if that's indeed what's happening.

You are right, my mistake. As I said, my workaround is not a solution. Maybe someone can report it to the rtorrent package maintainer.
