### ISSUE TITLE
torrent stop at 99,.9%

### ISSUE THREAD

**Issue by TMTYD** [rakshasa/rtorrent#925]
Hi

I like it when I have a torrent in the download that it stops at 99.9% for hours, although peers are present.

If I stop the torrent and start it again, he pulls the rest at 0.1% and then jumps into the Seeden.

Why is that?

my [.rtorrent.rc](https://pastebin.com/en95MPL4)

**Comment by pyroscope** [comment]
The client typically crashes in those situations, so you're actually on the lucky side of things.

**Comment by TMTYD** [comment]
ok, but does not crash, depends again on 99.9%.  I have found that the priority is set to not load, what is that related to?  Can I put it somewhere?  Or what else can it be?

**Comment by TMTYD** [comment]
Hi

it is still a mystery to me why some torrents with different trackers remain at 99.9%, although there are peers. Any advice?

**Comment by TMTYD** [comment]
i found the problem, i have wrong dns

**Comment by dolohow** [comment]
I have the same problem.  Not sure what causes it, definitely not dns.
