### ISSUE TITLE
end of line (EOL), character when transferring torrent file

### ISSUE THREAD

**Issue by Timuridze1** [rakshasa/rtorrent#926]
Hi, I have been using rtorrent server on my home server for many years. Recently I updated my Ubuntu and rtorrent accordingly and faced with the fact that my config stopped working. Then I decided to make a new config, but ran into an problem.

I use the following construction
method.insert = d.get_loaded_basename, string|simple, "execute.capture=basename, $d.loaded_file="
method.insert = d.get_meta_path, simple, "cat=/home/server/rtorrent/RM/, $d.get_loaded_basename="
method.set_key = event.download.inserted_new, move_loaded, "execute2=mv,-u, $d.loaded_file=, $d.get_meta_path=; d.tied_to_file.set=$d.get_meta_path="

Variable $d.get_loaded_basename= 
The .torrent file is transferred as expected, but the line break character is put at the end of the file name, I think this is due to the fact that the linux "basename" command returns output with a line feed character (EOL or EOF), everything seems to work like that, but I not sure anyway it's not right. How can this problem be solved?

Maybe I kind of explained chaotically, English is not my native language, and this is my first isuse in my life, I registered on github just to describe this little problem of mine.

**Comment by rakshasa** [comment]
Try using '-z' argument for basename.

Might be a need for an execute capture that trims the last EOL from the output.

**Comment by Timuridze1** [comment]
Thank you very much for such a quick response. It was so simple, I read man but did not see this argument!

maybe someone will come in handy,
method.insert = d.get_loaded_basename, string|simple, "execute.capture=basename,-z, $d.loaded_file="

**Comment by pyroscope** [comment]
Generally, for any command, `echo -n "$(…)"`. Also https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-string-rstrip
