### ISSUE TITLE
Command on torrent creation failed: Missing value argument

### ISSUE THREAD

**Issue by sbh7600** [rakshasa/rtorrent#927]
Hello, im getting this error why ?

this is from rtorrent.rc
schedule2 = watch_directory_9,10,10,"load.start=/storage/watch/MP3/*.torrent,d.directory.set=/storage/db/MP3/,d.custom.set=Danish"

**Comment by pyroscope** [comment]
I guess the custom var feels pretty upset about being nameless.

**Comment by sbh7600** [comment]
Please explain ?

**Comment by sbh7600** [comment]
Got it working, removed the custom thingie!
