### ISSUE TITLE
Missing curl_openssl_3 (buster)

### ISSUE THREAD

**Issue by Fronix** [rakshasa/rtorrent#933]
Not sure exactly what happened but I updated my server to debian 10 (buster) a while ago and everything was working fine. Now all of a sudden rTorrent stops working and when trying to start it I get the following error

```/usr/bin/rtorrent: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/bin/rtorrent)```

Using buster doing `apt install libcurl3` and my googling hasn't led me to any working answers yet.

Any help is really appreciated

**Comment by rakshasa** [comment]
If you didn't restart rtorrent since the update it would have kept the library as long as rtorrent was running. Search for the file in the package repository, if it is no longer available update the client.

**Comment by Fronix** [comment]
Ended up solving it by installing rtorrent from packages
`apt install rtorrent`

**Comment by ormanya** [comment]
I also recently updated to Buster and get the same error:
/usr/local/bin/rtorrent: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/bin/rtorrent)
Updating the client with "apt install rtorrent" did not fix it (updated to 0.9.7-1).

**Comment by ormanya** [comment]
Ok, so I 'apt remove rtorrent', then manually delated the rtorrent executable. After that I reinstalled rtorrent via apt and now it works.
