### ISSUE TITLE
Auto-delete .torrent file on Inotify watch load

### ISSUE THREAD

**Issue by thirstyraven** [rakshasa/rtorrent#934]
After the .torrent file gets added from the watch directory, I want it to automatically get deleted immediately.

I [came across a snippet](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-d-delete-tied) that does exactly this if you're polling the watch directory, but when I ported it to over to Inotify, I can't get it to work.

```
method.insert = load_watch, simple|private, "load.start_verbose=$argument.0=; d.custom1.set=; d.delete_tied="
directory.watch.added = "/downloads/watch/", "load_watch"
```

Help?

**Comment by thirstyraven** [comment]
Never mind, I managed to make it work.

```
method.insert = load_watch, simple|private, "load.start_verbose=(argument.0), d.custom1.set=, d.delete_tied="
directory.watch.added = "/downloads/watch/", "load_watch"
```

I wish the documentation for the syntax was better 😕.

**Comment by kannibalox** [comment]
> I wish the documentation for the syntax was better 😕.

https://rtorrent-docs.readthedocs.io/en/latest/ is open source and ready for improvement.
