### ISSUE TITLE
How can i run and script on completion as a non root user? for example the user name is Xocai

### ISSUE THREAD

**Issue by JavascriptHiFi** [rakshasa/rtorrent#940]
How can i run and script on completion as a non root user? for example the user name is Xocai i have a script/program that only works as Xocai user and it's the rutorrent user and the rtorrent keeps running the script as root how can I make it run as Xocai instead? 

Thank You!

**Comment by rakshasa** [comment]
I'm slightly afraid to ask if you are running rtorrent as root, which means you need to to look into sudo and more.

**Comment by chros73** [comment]
You can run rtorrent [as a normal user](https://github.com/rakshasa/rtorrent/tree/master/doc/scripts/init).

**Comment by JavascriptHiFi** [comment]
sorry I was drunk when typed this and installed rtorrent/rutorrent with root
sorry lol

**Comment by pyroscope** [comment]
You have to be more specific, are you sorry to have installed as root, too? You should be. :>

**Comment by JavascriptHiFi** [comment]
hahaha, yeah I woke up and checked my email and I saw rakshasa reply and I noticed what have I done luckily it's fixed now and it's working GREAT!
