### ISSUE TITLE
Do not automatically start torrents when the user add it.

### ISSUE THREAD

**Issue by pthfdr-42** [rakshasa/rtorrent#945]
Sometimes I only need to download a part of a torrent.
However, currently rtorrent automatically creates all the files and start downloading.
So I think when the user adds a torrent it should be in closed state, allowing the user to go to the files list and pick which files to download, then start it with `^S`.

**Comment by chros73** [comment]
You can do this with another watch dir: use `load.normal` with that directory.

**Comment by pthfdr-42** [comment]
Maybe you should add an option in the config file to apply to all the tasks.

**Comment by pyroscope** [comment]
Or maybe just read the docs, about enter vs. backspace.
