### ISSUE TITLE
Torrents with subdirectories dont finish

### ISSUE THREAD

**Issue by lordvalium** [rakshasa/rtorrent#947]
### Behaviour
Torrents with subdirectories, do not finish the download. They either stop or go to paused state. 

#### Steps to reproduce this issue

1. Add torrent with subdirectories in it 
2. Torrents finish every file execpt the subdirectory
e.g. 
![image](https://user-images.githubusercontent.com/2970225/71718072-5945de80-2e1a-11ea-9f8d-ce7e9265df5c.png)

#### Expected behaviour

> Finish the download to 100%

#### Actual behaviour

> Stops at ~95 - 99% - dependend on the size of the torrent. 

#### add. info what i've tested and found on the net

- independent of the chunksize
- double checked with torrents without subdirectories in it
- checked if the user owner of the parent directory
- umask is 022 so create subdirectories should work?!
- This user seems to have the same problem [Link](http://forum.cheapseedboxes.com/threads/always-in-pause-state.720/post-3508)
- The user seems to have a simliar symptom (but that issue indicated to sonarr), but the last sentence is exactly my problem [Link to Github issue](https://github.com/Novik/ruTorrent/issues/1250#issuecomment-242839040)

### Configuration

* Docker version (type `docker --version`) : 18.09.0-0506
* Docker compose version if applicable (type `docker-compose --version`) : 
* Platform (Debian 9, Ubuntu 18.04, ...) :  Synology DSM 
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
sudo docker info
Password:
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.09.6
Storage Driver: btrfs
Logging Driver: db
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk                                                                                                              syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 0cf16177dbb234350dc27dd2bbd1d7cebd098108
runc version: 6cc9d3f2cd512eeb3d548e2f6b75bcdebc779d4d
init version: e01de58 (expected: fec3683)
Security Options:
 apparmor
Kernel Version: 4.4.59+
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.55GiB
Name: monster
ID: VBXU:TKSU:VHCL:TNTK:MXSQ:OU7Z:MXDH:ESL7:3UTR:MNBG:QNDG:D4AL
Docker Root Dir: /volume1/@docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

### Logs

```
1578046192 E F934DC88ED19C62A5B675FF922FBECFABF227089->file_list: Failed to prepare file '/Sample/sample.mkv': Could not open file: No such file or directory
1578046192 E Could not resume download: Could not open file: No such file or directory
```

**Comment by chros73** [comment]
> Torrents with subdirectories, do not finish the download.

Do you mean "with empty subdirectories"?

**Comment by lordvalium** [comment]
> > Torrents with subdirectories, do not finish the download.
> 
> Do you mean "with empty subdirectories"?

No, there was absolutely no subdirectories. 
Was playing a lot with, switched now to that one and it works flawless 
https://registry.hub.docker.com/r/linuxserver/qbittorrent
