### ISSUE TITLE
rutorrent can't connect to rtorrent after dist. upgrade (Debian 9->10)

### ISSUE THREAD

**Issue by tonyrulez** [rakshasa/rtorrent#950]
I've upgraded from Debian 9 to 10, and now neither ruTorrent nor Sonarr can reach rtorrent.

ruTorrent says the following: 

> No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

Checking if it runs, and it looks like it:
```
tonyrulez@brix:~$ ps -edf |grep rtorrent
root      4522   660  0 17:44 ?        00:00:00 sshd: rtorrent [priv]
rtorrent  4525     1  0 17:44 ?        00:00:00 /lib/systemd/systemd --user
rtorrent  4526  4525  0 17:44 ?        00:00:00 (sd-pam)
rtorrent  4541  4522  0 17:44 ?        00:00:00 sshd: rtorrent@pts/2
rtorrent  4542  4541  0 17:44 pts/2    00:00:00 -bash
rtorrent  4594     1  0 17:45 ?        00:00:00 /usr/bin/SCREEN -d -m -fa -S rtorrent /usr/bin/rtorrent
rtorrent  4595  4594 61 17:45 pts/0    00:00:06 /usr/bin/rtorrent
tonyrul+  4636   876  0 17:45 pts/1    00:00:00 grep rtorrent
```
I also checked on the tracker and yes, all my torrents are running, so rtorrent really works.

Here are all the configs where scgi is mentioned, and they are all set to 5000:

_/home/rtorrent/.rtorrent.rc_
```
directory.default.set = /opt/rtorrent/download
session.path.set = /opt/rtorrent/session
schedule2 = watch_directory,5,5,load.normal=/opt/rtorrent/watch/*.torrent
schedule2 = low_diskspace,5,60,close_low_diskspace=2000M
network.port_range.set = 6882-6892
throttle.global_up.max_rate.set_kb = 0
throttle.global_down.max_rate.set_kb = 0
trackers.use_udp.set = yes
throttle.max_uploads.set = 200
throttle.min_peers.normal.set=10
throttle.max_peers.normal.set=400
pieces.hash.on_completion.set = no
network.max_open_sockets.set = 100

# DHT
protocol.pex.set = yes
dht.port.set = 1026
dht.mode.set = auto

# Encryption
protocol.encryption.set = allow_incoming,try_outgoing,require,require_RC4,prefer_plaintext,enable_retry

# SCGI
network.scgi.open_port = localhost:5000
```
_/etc/apache2/sites-enabled/rtorrentscgi.conf_
```
#rTorrent SCGI Password Location
#===========================================================================
        <LocationMatch "/RPC2">
                AuthType        Basic
                AuthName        "rtorrentscgi"
                AuthUserFile    /etc/apache2/passwords-enabled/rtorrentscgi
                Require         valid-user
                BrowserMatch    "MSIE"  AuthDigestEnableQueryStringHack=On
                Require ip 127.0.0.1
        </LocationMatch>
#===========================================================================

# SCGI PORT
#===========================================================================

#LoadModule scgi_module /usr/lib/apache2/modules/mod_scgi.so
SCGIMount /RPC2 127.0.0.1:5000

#===========================================================================
```
There were several restarts of the server, I also tried changing the scgi port to 5001, but it still can't connect. What could be the problem?

**Comment by pyroscope** [comment]
https://github.com/pyroscope/pimp-my-box/blob/master/xmlrpctest.py

**Comment by tonyrulez** [comment]
```
root@brix:/opt/rtorrent/download/!barna# python xmlrpctest.py
Connecting to 'https://localhost/RPC2'...
<ServerProxy for localhost/RPC2>
ERROR: [Errno 111] Connection refused
```

**Comment by kannibalox** [comment]
rTorrent isn't running where you think it is, or apache isn't configured to point at where it is running.
`network.port_range.set = 6882-6892` Narrow this down to a single port to prevent confusion. `6882-6882` is entirely valid.
`/etc/apache2/sites-enabled/rtorrentscgi.conf` Provide the entire configuration next time, what you posted is clearly truncated.
`SCGIMount /RPC2 127.0.0.1:5000` How does your box turn port 5000 into the `6882-6892` range you posted previously?

**Comment by tonyrulez** [comment]
> Narrow this down to a single port to prevent confusion. 6882-6882 is entirely valid.

I changed the port to 6882-6882, however it still doesn't work after restarting `rtorrent.service`.
Isn't `network.port_range.set` the listening port for incoming peer traffic? So it's independent of the SCGI port?

> Provide the entire configuration next time, what you posted is clearly truncated.

`rtorrentscgi.conf` as posted **is** the entire config file, not truncated. I installed and configured rtorrent and rutorrent based on this guide a year ago, and it worked until the Debian 10 upgrade: https://terminal28.com/how-to-install-and-configure-rutorrent-rtorrent-debian-9-stretch/

> SCGIMount /RPC2 127.0.0.1:5000 How does your box turn port 5000 into the 6882-6892 range you posted previously?

As mentioned in the beginning, I don't think he scgi port and the listening port has anything common, or am I wrong? For the past year it worked with SCGI port set to 5000 and listening port set to the range of 6882-6892.

**Comment by neuroid** [comment]
You can check if/where rtorrent is listening with `ss -ltnp`. This will show all listening TCP sockets and processes using them.

**Comment by tonyrulez** [comment]
[Here is the output](https://pastebin.com/raw/ZuM1v0nc), however it doesn't show which process uses what.

**Comment by neuroid** [comment]
Try running that as root.

**Comment by tonyrulez** [comment]
Oh, yes, now it shows the processes. [Full output here](https://pastebin.com/raw/EgdHzugZ), but the relevant rows are:

```
LISTEN      0     128          *:6882           *:*        users:(("rtorrent main",pid=20247,fd=12))
LISTEN      0     100      [::1]:5000        [::]:*        users:(("rtorrent main",pid=20247,fd=13))
```
First one is peer traffic, second one is SCGI. So does this mean the SCGI port on 5000 works? Yet rutorrent and sonarr can't communicate with it.

**Comment by neuroid** [comment]
Looks like it's only listening on the IPv6 loopback address. On my system, `host localhost` returns:
localhost has address 127.0.0.1
localhost has IPv6 address ::1

**Comment by neuroid** [comment]
You could also try replacing `network.scgi.open_port = localhost:5000` with `network.scgi.open_port = 127.0.0.1:5000`.

**Comment by tonyrulez** [comment]
In hoping this would fix it, in `/etc/apache2/sites-enabled/rtorrentscgi.conf` I changed it to `SCGIMount /RPC2 ::1:5000`, and restarted rtorrent and apache2 services. Still not working.

Then I saw your edited comment, output is:
```
127.0.0.1       localhost
127.0.1.1       brix

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Then saw the new comment. Changed it to `network.scgi.open_port = 127.0.0.1:5000` and it TOTALLY WORKS, YOU ROCK! Thanks!

**Comment by neuroid** [comment]
Just to test this, I put `localhost` in `network.scgi.open_port` and indeed rtorrent only created an IPv6 socket. Perhaps this could be improved. Anyway, I'm glad things are working for you.
