### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by an0n666** [rakshasa/rtorrent#961]
1580253307 C Caught signal: 'Segmentation fault.
---DUMP---
Caught Segmentation fault, dumping stack:
/usr/bin/rtorrent(+0x1f442) [0x5613cfe55442]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f5f3654b890]
/usr/lib/libxmlrpc_util.so.4(xmlrpc_mem_pool_release+0) [0x7f5f3675ab40]
/usr/lib/libxmlrpc_util.so.4(xmlrpc_mem_block_free+0x15) [0x7f5f3675a8e5]
/usr/lib/libxmlrpc.so.3(xmlrpc_DECREF+0xcb) [0x7f5f36967e8b]
/usr/lib/libxmlrpc_server.so.3(xmlrpc_registry_process_call2+0x10d) [0x7f5f36b7eebd]
/usr/lib/libxmlrpc_server.so.3(xmlrpc_registry_process_call+0x25) [0x7f5f36b7f005]
/usr/bin/rtorrent(+0x133309) [0x5613cff69309]
/usr/bin/rtorrent(+0x131d9e) [0x5613cff67d9e]
/usr/bin/rtorrent(+0x1325c7) [0x5613cff685c7]
/usr/lib/libtorrent.so.21(_ZN7torrent9PollEPoll7performEv+0xe2) [0x7f5f36dbe1d2]
/usr/lib/libtorrent.so.21(_ZN7torrent9PollEPoll7do_pollEli+0x90) [0x7f5f36dbe330]
/usr/lib/libtorrent.so.21(_ZN7torrent11thread_base10event_loopEPS0_+0x110) [0x7f5f36df9700]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f5f365406db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f5f35cc888f]

---END---

rtorrent 0.9.8
libtorrent 0.13.8

**Comment by an0n666** [comment]
another one
1580247508 C Caught internal_error: 'DownloadWrapper::receive_hash_done(...) Was not expecting non-NULL hash.'.
---DUMP---
/usr/lib/libtorrent.so.21(_ZN7torrent14internal_error10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x231) [0x7f0e54de0771]
/usr/bin/rtorrent(_ZN7torrent14internal_errorC1EPKc+0xaf) [0x55d4d7bb2e2f]
/usr/lib/libtorrent.so.21(+0xb044b) [0x7f0e54e6344b]
/usr/lib/libtorrent.so.21(+0x7df1b) [0x7f0e54e30f1b]
/usr/lib/libtorrent.so.21(_ZN7torrent15signal_bitfield4workEv+0x61) [0x7f0e54e285d1]
/usr/lib/libtorrent.so.21(_ZN7torrent11thread_base10event_loopEPS0_+0x16f) [0x7f0e54e2875f]
/usr/bin/rtorrent(+0x1e194) [0x55d4d7b65194]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f0e53bf7b97]
/usr/bin/rtorrent(+0x1ec2a) [0x55d4d7b65c2a]

---END---

**Comment by funkypoly** [comment]
Here is another thread with random crashes : https://github.com/rakshasa/rtorrent/issues/944
