### ISSUE TITLE
TLS v1.3 Support

### ISSUE THREAD

**Issue by HDVinnie** [rakshasa/rtorrent#964]
It seems TLS v1.3 is not supported. SSL connection fails to trackers using TLS v1.3 only. Is there any plans to add support?

**Comment by pyroscope** [comment]
No versions → no diagnostics.

**Comment by HDVinnie** [comment]
rtorrent release version `0.9.6/0.13.6`

**Comment by pyroscope** [comment]
that only leaves OS, openssl, and curl a guessing game.

**Comment by shlandturtle** [comment]
OS:
Ubuntu 19.10
curl:
7.65.3-1ubuntu3
openssl:
1.1.1c-1ubuntu4

Using rtorrent 0.9.8 / libtorrent 0.13.8 fails to announce with a SSL Connect Error if tracker doesn't support TLSv1.2 or lower.

**Comment by HDVinnie** [comment]
Any update?

**Comment by rouggy** [comment]
same issue here, rtorrent will give SSL connect error, impossible to download torrents with Tls 1.3

**Comment by HDVinnie** [comment]
Guess it's never going to happen.

**Comment by Talanor** [comment]
Yeah, I haven't seen activity on this repo for a while. And it's not the only issue. It was a good client and thanks to its author for all the work. But I guess its time to pick another one.

**Comment by moodboom** [comment]
Why was this closed?  Is there a solution?

**Comment by HDVinnie** [comment]
There is no solution. A year passed without any movement toward a fix so I closed it.
