### ISSUE TITLE
Allow binding to multiple specific IP addresses

### ISSUE THREAD

**Issue by an0n666** [rakshasa/rtorrent#970]
rtorrent 0.9.8
libtorrent 0.13.8
ubuntu 18.04 LTS

Currently if you don't bind rtorrent to any specific IP, it listens on all. But I want it to listen on a specific IPv4 and specific/all IPv6 addresses. Is there any way to achieve this? Why doesn't rtorrent have support for multi homed peers yet?

**Comment by pyroscope** [comment]
Because network namespace and ``iproute2`` can do that job just fine.

**Comment by an0n666** [comment]
why can't rtorrent accept multiple IPs to bind to from config? If it can already listen on all IPs, it should be able to bind to multiple specific IPs.

**Comment by kannibalox** [comment]
> If it can already listen on all IPs, it should be able to bind to multiple specific IPs.

completely different problem spaces, shouldn't be hard if you want to implement it though.
