### ISSUE TITLE
rtorrent keeps doing hash check on a "random" set of torrents on startup

### ISSUE THREAD

**Issue by renox92** [rakshasa/rtorrent#976]
Whenever I quit rtorrent and start it again there are 15-ish torrents out of my 1000 that start doing hash recheck. Most of them are not finished, but 1 of them was completed weeks ago, it even says so in the Finished column during cheching, yet is starts as a 95% torrent (as if missing 1 chunk I guess) and is queued for a recheck. I have session save scheduled to happen every 12 hours, the system running it wasn't rebooted for at least 2 weeks, and I even did a manual session save request, still, same torrents are queued for recheck on start up. I am running 0.9.8/0.13.8. Any clue as to what might be going on here?

**Comment by rakshasa** [comment]
The mtime of some files did not match with what was saved in the session save file, triggering a check of those files.

**Comment by renox92** [comment]
I checked files in a completed folder against contents of libtorrent_resume, and modified timestamps did match, yet still performed a check. Single file torrents however either had some gibberish in them ("ÛÇÝwýÿÿÿ¾ýÿßë" where something like "filesld9:completedi2287e5:" usually goes) or 8 rows of 4digit blocks (not sure if it's supposed to be that way).

**Comment by pyroscope** [comment]
Do not manipulate the session if you do not know EXACTLY what is in those files.

**Comment by luv2dnce33** [comment]
Can we do anything about this? I have the same issue and I am trying to migrate just my files without the session data (lost the sessions) and when I use the torrent files to verify the files, they work fine but every reboot of the client triggers a rehash on over 1500+ torrents spanning 16Tb....

**Comment by pyroscope** [comment]
You need a new session. No session, no memory.

**Comment by luv2dnce33** [comment]
Is there any way to make a new session on a fresh rtorrent instance? I only have the raw files and the .torrent file. Loading the torrent file into rtorrent kicks off a hash check and seeds the file, but on reboot starts new hash checks for every file loaded. How can I make a new session with just the .torrent and the files?

**Comment by luv2dnce33** [comment]
For what its worth I tried session.save and it didnt help. Not sure how to fix using the torrent file I have with the exisiting files I migrated and their already defined mtime. Is there any way I can delete mtime on my files, import the .torrent, and have rtorrent define a new matching mtime? this should allow me to save the state of the session if possible. thanks for your help
