### ISSUE TITLE
killall failing

### ISSUE THREAD

**Issue by Commissar0617** [rakshasa/rtorrent#982]
>   Loaded: loaded (/etc/systemd/system/rtorrent.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Thu 2020-04-02 23:12:30 CDT; 1min 43s ago
>   Process: 504 ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/bin/rtorrent (code=exited, status=0/SUCCESS)
>   Process: 519 ExecStop=/usr/bin/killall -w -s 2 /usr/bin/rtorrent (code=exited, status=1/FAILURE)
>  Main PID: 511 (code=exited, status=0/SUCCESS)
> 
> Apr 02 23:12:30 Ruskidown systemd[1]: Starting rTorrent...
> Apr 02 23:12:30 Ruskidown systemd[1]: Started rTorrent.
> Apr 02 23:12:30 Ruskidown killall[519]: /usr/bin/rtorrent: no process found
> Apr 02 23:12:30 Ruskidown systemd[1]: rtorrent.service: Control process exited, code=exited, status=1/FAILURE
> Apr 02 23:12:30 Ruskidown systemd[1]: rtorrent.service: Failed with result 'exit-code'.
> ~
> 

not sure what is wrong here. was working-ish until recently. could add torrents thru xmlrpc, but they wouldn't download. now it doesn't even start
says /usr/bin/rtorrent: no process found

**Comment by piramiday** [comment]
first, you can try and run `rtorrent` outside of `screen`/`systemd`, and see whether it will run successfully (e.g. might have a typo in your `.rc` file).
then, you can take a look at whether the process to be killed actually exists (e.g. attach to it: `screen -r rtorrent`).
finally, you can take a look at a normal `killall` execution, outside of `systemd`.

**Comment by Commissar0617** [comment]
oh. i decommed that server because i couldn't get it to work and couldn't find any useful info to help. went and got me a seedbox.
