### ISSUE TITLE
throttle speed settings seem off

### ISSUE THREAD

**Issue by dvazriel** [rakshasa/rtorrent#989]
I have to use 

```
# Global upload and download rate in KiB, `0` for unlimited
throttle.global_down.max_rate.set = 35000000
throttle.global_up.max_rate.set = 1500000
```

Just to be able to get:

[Throttle 1464/34179 KB] 

Seems to be quite off. I dont remember having to set the numbers so high in the config before.

**Comment by pyroscope** [comment]
Because you did not use the set_kb variants.

**Comment by dvazriel** [comment]
Ahhhh, that was it.

Thank you
