### ISSUE TITLE
File exceedes the configured max file size.

### ISSUE THREAD

**Issue by chenerg** [rakshasa/rtorrent#994]
I met this issue
> A306397CCF9C2EAD27155983C254227C0FD938E2->file_list: Failed to prepare file '/ILSVRC2012_img_train.tar': File exceedes the configured max file size.

The torrent is in [imagenet-2012](https://academictorrents.com/collection/imagenet-2012). This torrent is not dead, but is 147.9GB.

**Comment by kannibalox** [comment]
Have you tried increasing the max file size? https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-d-max-file-size

**Comment by chenerg** [comment]
I will give a try next time.
