### ISSUE TITLE
Script that I execute causes rtorrent to crash.

### ISSUE THREAD

**Issue by varoOP** [rakshasa/rtorrent#997]
The script : 
```
#!/bin/bash
/home/user/bin/rtcontrol is_complete=yes is_open=yes is_private=no --stop
```
The line in .rtorrent.rc : 
`system.method.set_key = event.download.finished,stop_public_torrents,"execute=/home/user/bin/stopPUB.sh"
`

**Comment by pyroscope** [comment]
execute.throw.bg

**Comment by varoOP** [comment]
What should I ideally use ? I am completely new to all of this and a friend suggested using pyrocore for everything..
